"""
Shared enums for Societal Innovation & Smart Governance microservices.
Reused across auth-service, core-service, ai-service, routing-service, analytics-service.
"""

from enum import Enum


class IssueCategory(str, Enum):
    ROADS_AND_TRANSPORT = "ROADS_AND_TRANSPORT"
    WATER_AND_SEWAGE = "WATER_AND_SEWAGE"
    SOLID_WASTE_MANAGEMENT = "SOLID_WASTE_MANAGEMENT"
    ELECTRICITY_AND_POWER = "ELECTRICITY_AND_POWER"
    PUBLIC_HEALTH_AND_SANITATION = "PUBLIC_HEALTH_AND_SANITATION"
    ENVIRONMENT_AND_GREENERY = "ENVIRONMENT_AND_GREENERY"
    PUBLIC_SAFETY_AND_LAW = "PUBLIC_SAFETY_AND_LAW"
    EDUCATION_AND_INFRASTRUCTURE = "EDUCATION_AND_INFRASTRUCTURE"
    OTHER = "OTHER"


class SubCategory(str, Enum):
    # Roads & Transport
    POTHOLE = "POTHOLE"
    BROKEN_ROAD = "BROKEN_ROAD"
    TRAFFIC_SIGNAL_FAILURE = "TRAFFIC_SIGNAL_FAILURE"
    ROAD_BLOCKAGE = "ROAD_BLOCKAGE"
    DAMAGED_FOOTPATH = "DAMAGED_FOOTPATH"

    # Water & Sewage
    PIPELINE_LEAKAGE = "PIPELINE_LEAKAGE"
    SEWAGE_OVERFLOW = "SEWAGE_OVERFLOW"
    WATER_CONTAMINATION = "WATER_CONTAMINATION"
    WATER_SCARCITY = "WATER_SCARCITY"
    OPEN_MANHOLE = "OPEN_MANHOLE"

    # Solid Waste
    GARBAGE_DUMP = "GARBAGE_DUMP"
    UNCOLLECTED_WASTE = "UNCOLLECTED_WASTE"
    HAZARDOUS_WASTE = "HAZARDOUS_WASTE"
    DEAD_ANIMAL = "DEAD_ANIMAL"

    # Electricity & Power
    BROKEN_STREETLIGHT = "BROKEN_STREETLIGHT"
    DANGLING_WIRE = "DANGLING_WIRE"
    TRANSFORMER_FAILURE = "TRANSFORMER_FAILURE"
    POWER_OUTAGE = "POWER_OUTAGE"

    # Public Health & Sanitation
    OPEN_DRAIN = "OPEN_DRAIN"
    STAGNANT_WATER_MOSQUITO = "STAGNANT_WATER_MOSQUITO"
    DIRTY_PUBLIC_TOILET = "DIRTY_PUBLIC_TOILET"
    PUBLIC_HEALTH_HAZARD = "PUBLIC_HEALTH_HAZARD"

    # Environment & Greenery
    FALLEN_TREE = "FALLEN_TREE"
    ILLEGAL_TREE_CUTTING = "ILLEGAL_TREE_CUTTING"
    AIR_POLLUTION = "AIR_POLLUTION"
    WATER_BODY_POLLUTION = "WATER_BODY_POLLUTION"

    # Public Safety & Law
    DARK_ALLEY_UNLIT_AREA = "DARK_ALLEY_UNLIT_AREA"
    VANDALISM = "VANDALISM"
    UNSAFE_INFRASTRUCTURE = "UNSAFE_INFRASTRUCTURE"

    # Education & Infrastructure
    BROKEN_SCHOOL_FACILITY = "BROKEN_SCHOOL_FACILITY"
    UNSAFE_SCHOOL_BUILDING = "UNSAFE_SCHOOL_BUILDING"

    # General
    OTHER = "OTHER"


class PriorityLevel(str, Enum):
    CRITICAL = "CRITICAL"  # P1 - Immediate risk to life/severe disaster
    HIGH = "HIGH"          # P2 - Serious disruption / high health risk
    MEDIUM = "MEDIUM"      # P3 - Moderate public inconvenience
    LOW = "LOW"            # P4 - Minor / aesthetic / routine maintenance


class SeverityLevel(str, Enum):
    CATASTROPHIC = "CATASTROPHIC"
    SEVERE = "SEVERE"
    MODERATE = "MODERATE"
    MINOR = "MINOR"


class ResponsibleDepartment(str, Enum):
    MUNICIPAL_CORPORATION = "MUNICIPAL_CORPORATION"
    PUBLIC_WORKS_DEPARTMENT = "PUBLIC_WORKS_DEPARTMENT"  # PWD
    WATER_AND_SEWERAGE_BOARD = "WATER_AND_SEWERAGE_BOARD"
    ELECTRICITY_DISTRIBUTION_COMPANY = "ELECTRICITY_DISTRIBUTION_COMPANY"  # DISCOM
    PUBLIC_HEALTH_DEPARTMENT = "PUBLIC_HEALTH_DEPARTMENT"
    TRAFFIC_POLICE = "TRAFFIC_POLICE"
    POLICE_DEPARTMENT = "POLICE_DEPARTMENT"
    FOREST_AND_ENVIRONMENT_DEPT = "FOREST_AND_ENVIRONMENT_DEPT"
    EDUCATION_DEPARTMENT = "EDUCATION_DEPARTMENT"
    DISASTER_MANAGEMENT_AUTHORITY = "DISASTER_MANAGEMENT_AUTHORITY"
    GENERAL_ADMINISTRATION = "GENERAL_ADMINISTRATION"


class StakeholderRole(str, Enum):
    CITIZEN = "CITIZEN"
    GOVERNMENT_OFFICIAL = "GOVERNMENT_OFFICIAL"
    UNIVERSITY_RESEARCHER = "UNIVERSITY_RESEARCHER"
    STUDENT_INNOVATOR = "STUDENT_INNOVATOR"
    INDUSTRY_CSR_PARTNER = "INDUSTRY_CSR_PARTNER"
    TECH_STARTUP = "TECH_STARTUP"
    NGO = "NGO"
    VOLUNTEER_GROUP = "VOLUNTEER_GROUP"  # NSS, NCC, civic clubs
