# -*- coding: utf-8 -*-
"""Hindi (hi) translations dictionary for SOCIAL-X platform"""

def get_hi_dict():
    return {
        "nav": {
            "overview": "अवलोकन",
            "access_identity": "पहुंच एवं पहचान",
            "stakeholder_ecosystem": "हितधारक पारिस्थितिकी तंत्र",
            "operations_ai": "संचालन एवं एआई",
            "infra_observability": "इन्फ्रा एवं वेधशाला",
            "field_activities": "क्षेत्रीय गतिविधियाँ एवं राहत",
            "community_workforce": "समुदाय एवं कार्यबल",
            "governance_comms": "शासन एवं संचार",
            "csr_investment": "सीएसआर एवं पूंजी आवंटन",
            "collaboration_rd": "सहयोग एवं अनुसंधान",
            "student_portal": "छात्र पोर्टल",
            "faculty_portal": "संकाय पोर्टल",
            "dashboard": "डैशबोर्ड",
            "my_issues": "मेरी शिकायतें",
            "report_problem": "समस्या दर्ज करें",
            "track_issues": "निवारण ट्रैक करें",
            "notifications": "सूचनाएं",
            "profile": "प्रोफ़ाइल",
            "settings": "सेटिंग्स",
            "help": "सहायता एवं समर्थन",
            "logout": "लॉग आउट",
            "login": "लॉग इन",
            "analytics": "एनालिटिक्स एवं रिपोर्ट",
            "assigned_cases": "आवंटित मामले",
            "departments": "विभाग",
            "officers": "अधिकारी निर्देशिका",
            "ai_suggestions": "एआई सुझाव",
            "reports": "रिपोर्ट एवं ऑडिट",
            "projects": "उपलब्ध परियोजनाएं",
            "funding": "वित्तपोषण अवसर",
            "csr_analytics": "सीएसआर एनालिटिक्स",
            "mentorship": "मार्गदर्शन",
            "university_collaboration": "विश्वविद्यालय सहयोग",
            "research": "अनुसंधान पहल",
            "prototypes": "प्रोटोटाइप एवं डेमो",
            "volunteers": "स्वयंसेवक दस्ते",
            "field_log": "क्षेत्रीय साक्ष्य लॉग",
            "impact": "सामुदायिक प्रभाव",
            "certificates": "प्रमाणपत्र एवं बैज",
            "lab_tasks": "प्रयोगशाला कार्य",
            "upload_deliverables": "प्रस्तुति अपलोड करें",
            "milestone_timeline": "मील का पत्थर समयरेखा",
            "advisor_discussion": "सलाहकार चर्चा",
            "milestone_approvals": "मील का पत्थर स्वीकृतियां",
            "municipal_proposals": "नगर निगम प्रस्ताव",
            "teams": "टीमें एवं सूची",
            "credits": "शैक्षणिक क्रेडिट",
            "user_management": "उपयोगकर्ता प्रबंधन",
            "role_management": "भूमिका प्रबंधन",
            "government_management": "सरकारी प्रबंधन",
            "university_management": "विश्वविद्यालय प्रबंधन",
            "industry_management": "उद्योग प्रबंधन",
            "ngo_management": "एनजीओ प्रबंधन",
            "research_organizations": "अनुसंधान संगठन",
            "issue_management": "मुद्दा प्रबंधन",
            "ai_monitoring": "एआई टेलीमेट्री निगरानी",
            "workflow_monitoring": "कार्यप्रवाह निगरानी",
            "audit_logs": "अपरिवर्तनीय ऑडिट ट्रेल",
            "system_health": "सिस्टम स्वास्थ्य",
            "landing_features": "विशेषताएं",
            "landing_how_it_works": "यह कैसे काम करता है",
            "landing_about": "हमारे बारे में",
            "landing_faq": "सामान्य प्रश्न",
            "landing_contact": "संपर्क करें",
            "role_login": "भूमिका लॉगिन",
            "citizen_sign_up": "नागरिक पंजीकरण"
        },
        "common": {
            "buttons": {
                "browseFiles": "फ़ाइलें ब्राउज़ करें",
                "openCamera": "कैमरा खोलें",
                "startRecording": "रिकॉर्डिंग शुरू करें",
                "stopRecording": "रिकॉर्डिंग बंद करें",
                "submit": "जमा करें",
                "cancel": "रद्द करें",
                "save": "बदलाव सहेजें",
                "delete": "हटाएं",
                "search": "खोजें",
                "filter": "फ़िल्टर",
                "upload": "अपलोड करें",
                "confirm": "पुष्टि करें",
                "close": "बंद करें",
                "back": "वापस",
                "next": "आगे",
                "previous": "पिछला",
                "detectLocation": "वर्तमान स्थान का पता लगाएं",
                "useCurrentGps": "वर्तमान GPS का उपयोग करें",
                "resetForm": "फ़ॉर्म रीसेट करें",
                "submitIssue": "शिकायत दर्ज करें",
                "viewAll": "सभी देखें",
                "export": "डेटा निर्यात करें",
                "download": "डाउनलोड",
                "refresh": "रीफ्रेश करें",
                "login": "लॉग इन",
                "logout": "लॉग आउट",
                "modifyUploads": "मीडिया अपलोड संशोधित करें",
                "removeFile": "फ़ाइल हटाएं",
                "removeVoiceMemo": "वॉयस मेमो हटाएं",
                "edit": "संपादित करें",
                "view": "विवरण देखें",
                "add": "नया जोड़ें",
                "create": "बनाएं",
                "update": "अपडेट करें",
                "approve": "स्वीकृत करें",
                "reject": "अस्वीकार करें",
                "reassign": "पुनः सौंपें",
                "escalate": "वृद्धि ट्रिगर करें",
                "resolve": "मामला हल करें",
                "assign": "आवंटित करें",
                "verify": "सत्यापित करें",
                "downloadReport": "रिपोर्ट डाउनलोड करें",
                "syncTelemetry": "टेलीमेट्री सिंक करें",
                "applyFilters": "फ़िल्टर लागू करें",
                "clearFilters": "फ़िल्टर साफ़ करें",
                "viewDetails": "विवरण देखें",
                "sendNotification": "सूचना भेजें",
                "inviteMember": "सदस्य आमंत्रित करें",
                "print": "प्रिंट करें",
                "share": "साझा करें",
                "copyLink": "लिंक कॉपी करें",
                "proceed": "आगे बढ़ें",
                "retry": "पुनः प्रयास करें",
                "dismiss": "खारिज करें",
                "accept": "स्वीकार करें",
                "decline": "अस्वीकार करें"
            },
            "labels": {
                "dashboard": "डैशबोर्ड",
                "profile": "प्रोफ़ाइल",
                "settings": "सेटिंग्स",
                "notifications": "सूचनाएं",
                "help": "सहायता एवं समर्थन",
                "logout": "लॉग आउट",
                "login": "लॉग इन",
                "status": "स्थिति",
                "priority": "प्राथमिकता",
                "department": "विभाग",
                "category": "श्रेणी",
                "district": "ज़िला",
                "ward": "वार्ड",
                "address": "पता",
                "landmark": "सीमाचिह्न",
                "title": "शीर्षक",
                "description": "विवरण",
                "location": "स्थान",
                "latitude": "अक्षांश",
                "longitude": "देशांतर",
                "accuracy": "सटीकता",
                "date": "दिनांक",
                "action": "कार्रवाई",
                "actions": "कार्रवाइयां",
                "all": "सभी",
                "high": "उच्च",
                "medium": "मध्यम",
                "low": "कम",
                "critical": "गंभीर",
                "emergency": "आपातकालीन",
                "pending": "लंबित",
                "inProgress": "प्रगति पर है",
                "resolved": "हल किया गया",
                "closed": "बंद",
                "rejected": "अस्वीकृत",
                "verified": "सत्यापित",
                "assigned": "आवंटित",
                "recentActivity": "हाल की गतिविधि",
                "quickActions": "त्वरित कार्रवाइयां",
                "systemHealth": "सिस्टम स्वास्थ्य",
                "language": "भाषा",
                "selectLanguage": "भाषा चुनें",
                "searchLanguage": "भाषाएं खोजें...",
                "editable": "संपादन योग्य",
                "active": "सक्रिय",
                "inactive": "निष्क्रिय",
                "completed": "पूर्ण",
                "failed": "विफल",
                "total": "कुल",
                "count": "गिनती",
                "rate": "दर",
                "percentage": "प्रतिशत",
                "timeRemaining": "शेष समय",
                "dueDate": "नियत तारीख",
                "submittedBy": "द्वारा प्रस्तुत",
                "assignedTo": "आवंटित किया गया",
                "officerInCharge": "प्रभारी अधिकारी",
                "slaTimer": "एसएलए उलटी गिनती",
                "auditTimeline": "ऑडिट समयरेखा",
                "contactInfo": "संपर्क जानकारी",
                "phoneNumber": "फ़ोन नंबर",
                "emailAddress": "ईमेल पता",
                "fullName": "पूरा नाम",
                "role": "भूमिका",
                "organization": "संगठन",
                "institution": "संस्थान",
                "createdAt": "रिपोर्ट की तारीख",
                "updatedAt": "अद्यतन तिथि"
            },
            "status": {
                "open": "खुला",
                "submitted": "जमा किया गया",
                "verified": "एआई सत्यापित",
                "assigned": "आवंटित",
                "in_progress": "प्रगति पर है",
                "inProgress": "प्रगति पर है",
                "resolved": "हल किया गया",
                "closed": "बंद",
                "rejected": "अस्वीकृत",
                "under_review": "समीक्षाधीन",
                "under_government_review": "सरकारी समीक्षाधीन",
                "assigned_to_government": "सरकार को आवंटित",
                "assigned_to_industry": "उद्योग को आवंटित",
                "industry_review": "उद्योग समीक्षा",
                "assigned_to_university": "विश्वविद्यालय को आवंटित",
                "student_development": "छात्र विकास",
                "faculty_review": "संकाय समीक्षा",
                "industry_validation": "उद्योग सत्यापन",
                "inspection": "स्थल निरीक्षण",
                "feedback_pending": "प्रतिक्रिया लंबित",
                "escalated": "अग्रसारित",
                "active": "सक्रिय",
                "inactive": "निष्क्रिय",
                "completed": "पूर्ण",
                "approved": "स्वीकृत",
                "declined": "अस्वीकृत",
                "pending": "लंबित"
            },
            "priority": {
                "low": "कम प्राथमिकता",
                "medium": "मध्यम प्राथमिकता",
                "high": "उच्च प्राथमिकता",
                "critical": "गंभीर प्राथमिकता",
                "emergency": "आपातकालीन प्राथमिकता",
                "urgent": "अति आवश्यक"
            },
            "departments": {
                "waterSupply": "जल आपूर्ति एवं जल निकासी",
                "roadsTransport": "सड़क एवं परिवहन",
                "electricityPower": "विद्युत एवं पावर ग्रिड",
                "solidWaste": "ठोस अपशिष्ट एवं स्वच्छता",
                "publicHealth": "सार्वजनिक स्वास्थ्य एवं सुरक्षा",
                "urbanPlanning": "नगर नियोजन एवं शहरी अवसंरचना",
                "education": "शिक्षा एवं युवा मामले",
                "environmentForest": "पर्यावरण एवं वन विभाग",
                "policeSafety": "पुलिस एवं सार्वजनिक सुरक्षा",
                "disasterManagement": "आपदा प्रबंधन प्राधिकरण",
                "municipalAdmin": "नगर पालिका प्रशासन"
            },
            "categories": {
                "water": "जल आपूर्ति एवं जल निकासी",
                "roads": "सड़क एवं परिवहन",
                "electricity": "विद्युत एवं पावर ग्रिड",
                "waste": "ठोस अपशिष्ट एवं स्वच्छता",
                "health": "सार्वजनिक स्वास्थ्य एवं सुरक्षा",
                "sanitation": "स्वच्छता एवं सीवरेज",
                "infrastructure": "सार्वजनिक अवसंरचना",
                "streetlights": "स्ट्रीट लाइट एवं बिजली",
                "drainage": "जल निकासी एवं सीवरेज",
                "potholes": "गड्ढे एवं सड़क मरम्मत",
                "traffic": "यातायात एवं सड़क सुरक्षा",
                "pollution": "प्रदूषण एवं पर्यावरणीय खतरा"
            },
            "validation": {
                "requiredField": "यह फ़ील्ड आवश्यक है",
                "titleRequired": "शीर्षक आवश्यक है",
                "descriptionRequired": "विवरण आवश्यक है",
                "locationRequired": "घटना का भौगोलिक स्थान आवश्यक है",
                "invalidEmail": "कृपया एक मान्य ईमेल पता दर्ज करें",
                "invalidPassword": "पासवर्ड कम से कम 8 वर्णों का होना चाहिए",
                "passwordTooShort": "पासवर्ड बहुत छोटा है (न्यूनतम 8 वर्ण)",
                "passwordMismatch": "पासवर्ड मेल नहीं खाते",
                "unsupportedFile": "असमर्थित फ़ाइल प्रारूप। कृपया JPEG, PNG, MP4 या PDF अपलोड करें।",
                "maxFileSizeExceeded": "अधिकतम फ़ाइल आकार पार हो गया (25MB सीमा)",
                "micPermissionDenied": "माइक्रोफ़ोन अनुमति अस्वीकृत। कृपया माइक्रोफ़ोन पहुंच की अनुमति दें।",
                "cameraPermissionDenied": "कैमरा अनुमति अस्वीकृत। कृपया कैमरा पहुंच की अनुमति दें।",
                "minLength": "इनपुट न्यूनतम लंबाई से छोटा है",
                "maxLength": "इनपुट अधिकतम अनुमत लंबाई से अधिक है",
                "uploadFailed": "अपलोड विफल रहा। कृपया कनेक्शन जांचें और पुनः प्रयास करें।",
                "uploadSuccessful": "फ़ाइल सफलतापूर्वक अपलोड की गई।",
                "loginSuccessful": "सफलतापूर्वक साइन इन किया गया।",
                "registrationSuccessful": "पंजीकरण सफलतापूर्वक पूरा हुआ।",
                "fillRequiredFields": "कृपया जमा करने से पहले सभी अनिवार्य फ़ील्ड भरें।"
            },
            "emptyStates": {
                "noData": "कोई डेटा उपलब्ध नहीं है",
                "noResults": "आपकी खोज से मेल खाता कोई परिणाम नहीं मिला",
                "noNotifications": "कोई नई सूचना नहीं है",
                "noIssuesFound": "आपके मानदंडों से मेल खाती कोई शिकायत नहीं मिली",
                "noProjectsFound": "इस समय कोई सक्रिय परियोजना उपलब्ध नहीं है",
                "noOfficersFound": "खोज फ़िल्टर से मेल खाते कोई अधिकारी नहीं हैं",
                "noActivitiesFound": "अभी तक कोई क्षेत्रीय गतिविधि दर्ज नहीं की गई है"
            },
            "loading": {
                "loading": "लोड हो रहा है...",
                "pleaseWait": "कृपया प्रतीक्षा करें...",
                "fetchingData": "नवीनतम डेटा प्राप्त किया जा रहा है...",
                "processing": "आपके अनुरोध पर कार्रवाई की जा रही है...",
                "uploadingMedia": "मीडिया अपलोड किया जा रहा है...",
                "analyzingAi": "मल्टीमॉडल एआई के साथ विश्लेषण किया जा रहा है...",
                "savingChanges": "परिवर्तन सहेजे जा रहे हैं..."
            },
            "pagination": {
                "previous": "पिछला",
                "next": "आगे",
                "page": "पृष्ठ",
                "of": "का",
                "rowsPerPage": "पंक्तियाँ प्रति पृष्ठ",
                "showing": "दिखाया जा रहा है",
                "entries": "प्रविष्टियाँ",
                "totalRecords": "कुल रिकॉर्ड"
            },
            "search": {
                "searchPlaceholder": "शिकायतें, मामले, स्थान खोजें...",
                "searchGrievances": "शिकायतें खोजें...",
                "searchUsers": "उपयोगकर्ता खोजें...",
                "searchDepartments": "विभाग खोजें...",
                "searchProjects": "परियोजनाएं खोजें...",
                "searchOfficers": "अधिकारी खोजें...",
                "quickNavigator": "त्वरित नेविगेटर...",
                "searchAll": "प्लेटफ़ॉर्म पर सभी खोजें..."
            }
        },
        "ai": {
            "processing": "एआई प्रसंस्करण",
            "ocrResult": "ओसीआर पाठ निकाला गया",
            "speechResult": "स्थानीय भाषा भाषण प्रतिलेख",
            "speechTranscript": "भाषण प्रतिलेख",
            "confidenceScore": "एआई विश्वास स्कोर",
            "aiConfidence": "एआई विश्वास",
            "suggestedCategory": "सुझाई गई श्रेणी",
            "suggestedDepartment": "सुझाया गया विभाग",
            "recommendedDepartment": "अनुशंसित विभाग",
            "suggestedIndustry": "सुझाया गया उद्योग भागीदार",
            "duplicateDetection": "डुप्लिकेट शिकायत का पता लगाना",
            "aiVerification": "मल्टीमॉडल विज़न सत्यापन",
            "smartRouting": "बुद्धिमान विभागीय रूटिंग",
            "previewTitle": "मल्टीमॉडल एआई निष्कर्षण पूर्वावलोकन",
            "previewSubtitle": "हमारी कंप्यूटर विज़न और भाषण पाइपलाइनों ने निम्नलिखित डेटा निकाला है। प्रेषण से पहले सत्यापित और समायोजित करें।",
            "detectedHeadline": "पहचाना गया शिकायत शीर्षक",
            "classifiedCategory": "एआई वर्गीकृत श्रेणी",
            "dispatchedDept": "आवंटित नगर पालिका विभाग",
            "severityPriority": "गंभीरता एवं तात्कालिकता प्राथमिकता",
            "mappedLocation": "मानचित्रित घटना स्थल",
            "confirmSubmit": "पुष्टि करें एवं प्रेषित करें",
            "cancel": "रद्द करें",
            "ocrBadge": "FastAPI ओसीआर निकाला गया",
            "sttBadge": "स्थानीय बोली प्रतिलेखित",
            "verificationStep": "नागरिक सत्यापन चरण",
            "verificationStepHelp": "100% सटीकता सुनिश्चित करने के लिए आप अंतिम प्रेषण से पहले नीचे किसी भी फ़ील्ड को सीधे संपादित कर सकते हैं।",
            "ocrVision": "ओसीआर विज़न निष्कर्षण",
            "noOcrText": "साइनबोर्ड पर कोई पाठ नहीं मिला",
            "noAudioMemo": "कोई ऑडियो मेमो संलग्न नहीं है",
            "priorityScore": "गणना किया गया प्राथमिकता स्कोर",
            "estimatedCost": "अनुमानित नगर निगम लागत",
            "estimatedTime": "अनुमानित समाधान समय",
            "recommendation": "एआई शासन अनुशंसा",
            "confidenceHigh": "उच्च विश्वास (>90%)",
            "confidenceMedium": "मध्यम विश्वास (70-90%)",
            "confidenceLow": "कम विश्वास (<70%)",
            "duplicateFound": "संभावित डुप्लिकेट का पता चला",
            "duplicateScore": "समानता स्कोर"
        },
        "citizen": {
            "portalTitle": "नागरिक पोर्टल",
            "dashboard": {
                "welcomeBack": "वापसी पर स्वागत है",
                "totalReported": "कुल रिपोर्ट की गई",
                "inProgress": "प्रगति पर है",
                "resolved": "हल किया गया",
                "needsVerification": "सत्यापन की आवश्यकता है",
                "communityImpact": "सामुदायिक प्रभाव स्कोर",
                "avgResolution": "औसत समाधान समय",
                "recentGrievances": "हाल की शिकायतें",
                "reportNewIssue": "नई शिकायत दर्ज करें",
                "myIssues": "मेरी शिकायतें",
                "trackIssues": "निवारण ट्रैक करें",
                "liveIncidents": "लाइव नागरिक घटनाएं",
                "civicFeed": "नागरिक फ़ीड",
                "satisfactionScore": "नागरिक संतुष्टि रेटिंग",
                "activeCases": "सक्रिय शिकायतें",
                "resolvedCases": "हल की गई शिकायतें"
            },
            "report": {
                "title": "सामाजिक शिकायत दर्ज करें",
                "subtitle": "फ़ोटो, वीडियो, ऑडियो वॉयस नोट्स या दस्तावेज़ सबमिट करें। हमारा एआई इंजन ओसीआर के माध्यम से साइनबोर्ड निकालेगा और एआई पूर्वावलोकन उत्पन्न करेगा।",
                "multimodalBadge": "मल्टीमॉडल एआई अंतर्ग्रहण",
                "moduleBadge": "मॉड्यूल 1",
                "uploadEvidence": "फ़ोटोग्राफ़िक एवं दस्तावेज़ साक्ष्य",
                "uploadSubtitle": "दोष, टूटे हुए साइनबोर्ड या नगरपालिका दस्तावेज़ की छवि अपलोड करें",
                "dragDrop": "छवियां, वीडियो क्लिप या दस्तावेज़ खींचें और छोड़ें",
                "supportedFormats": "JPEG, PNG, MP4, और PDF (अधिकतम 25MB) का समर्थन करता है।",
                "browseFiles": "फ़ाइलें ब्राउज़ करें",
                "openCamera": "कैमरा खोलें",
                "uploadingProgress": "एआई के माध्यम से मीडिया अपलोड और संसाधित किया जा रहा है...",
                "attachedEvidence": "संलग्न साक्ष्य",
                "voiceGrievance": "वॉयस ऑडियो शिकायत",
                "optional": "वैकल्पिक",
                "voiceSubtitle": "बोला गया विवरण रिकॉर्ड करें। स्पीच-टू-टेक्स्ट द्वारा स्वचालित रूप से प्रतिलेखित।",
                "pressRecordHelp": "किसी भी भाषा में अपनी समस्या का वर्णन करने के लिए रिकॉर्ड दबाएं।",
                "startVoiceRecording": "वॉयस रिकॉर्डिंग शुरू करें",
                "stopRecording": "रिकॉर्डिंग बंद करें",
                "recording": "रिकॉर्डिंग हो रही है...",
                "speechProcessing": "भाषण प्रसंस्करण...",
                "speechConverted": "भाषण सफलतापूर्वक परिवर्तित हुआ",
                "incidentLocation": "घटना का भौगोलिक स्थान",
                "locationSubtitle": "नगर निगम कार्यकर्ता प्रेषण के लिए सटीक निर्देशांक इंगित करें",
                "useCurrentGps": "वर्तमान GPS का उपयोग करें",
                "streetAddress": "सड़क का पता / सीमाचिह्न",
                "addressPlaceholder": "उदा. 14वां मुख्य मार्ग, इंदिरा गांधी सर्कल के पास",
                "mapTip": "सुझाव: निर्देशांक समायोजित करने के लिए आप मानचित्र पर कहीं भी क्लिक कर सकते हैं।",
                "contextTitle": "समस्या का विवरण",
                "contextSubtitle": "संक्षिप्त संदर्भ प्रदान करें (एआई स्वचालित रूप से वर्गीकृत करेगा)",
                "headlineLabel": "संक्षिप्त शिकायत शीर्षक",
                "headlinePlaceholder": "उदा., भूमिगत पानी की पाइप फटना और सड़क जलभराव",
                "detailsLabel": "विस्तृत विवरण",
                "detailsPlaceholder": "सामाजिक प्रभाव, अवधि और सुरक्षा खतरों का वर्णन करें...",
                "categoryLabel": "नगर पालिका श्रेणी",
                "priorityLabel": "तात्कालिकता प्राथमिकता",
                "generateAiPreview": "एआई अंतर्ग्रहण पूर्वावलोकन उत्पन्न करें",
                "processingAi": "मल्टीमॉडल एआई प्रसंस्करण जारी...",
                "audioMemo": "ऑडियो शिकायत मेमो",
                "readyStt": "एसटीटी पार्सिंग के लिए तैयार",
                "incidentCoordinates": "शिकायत घटना निर्देशांक",
                "currentDetectedLocation": "वर्तमान पता लगाया गया स्थान"
            },
            "track": {
                "title": "शिकायत निवारण ट्रैक करें",
                "subtitle": "लाइव स्थिति परिवर्तन, नियुक्त विभागीय इंजीनियरों और एसएलए टाइमर की निगरानी करें।",
                "enterId": "शिकायत ट्रैकिंग आईडी दर्ज करें",
                "searchPlaceholder": "उदा. SOC-2026-8821",
                "currentStage": "वर्तमान चरण",
                "assignedTo": "आवंटित विभाग",
                "officerInCharge": "प्रभारी अधिकारी",
                "slaTimer": "एसएलए समाधान उलटी गिनती",
                "timeline": "ऑडिट समयरेखा",
                "trackingDetails": "ट्रैकिंग विवरण",
                "liveStatusTransitions": "लाइव स्थिति परिवर्तन"
            },
            "profile": {
                "title": "नागरिक प्रोफ़ाइल",
                "fullName": "पूरा नाम",
                "email": "ईमेल पता",
                "phone": "फ़ोन नंबर",
                "district": "आवासीय ज़िला",
                "address": "स्थायी पता",
                "saveProfile": "प्रोफ़ाइल सहेजें",
                "citizenBadge": "सत्यापित नागरिक",
                "verificationStatus": "पहचान सत्यापन स्थिति"
            },
            "settings": {
                "title": "प्राथमिकताएं एवं सेटिंग्स",
                "notifications": "शिकायत सूचनाएं",
                "emailAlerts": "ईमेल अलर्ट",
                "smsAlerts": "एसएमएस अलर्ट",
                "theme": "प्रदर्शन थीम",
                "language": "ऐप भाषा",
                "savePreferences": "प्राथमिकताएं सहेजें"
            }
        },
        "government": {
            "portalTitle": "नगर पालिका कमान एवं नियंत्रण",
            "dashboard": {
                "title": "सरकारी अधिकारी पोर्टल",
                "overview": "नगर पालिका अवलोकन",
                "assignedCases": "आवंटित शिकायतें",
                "liveCases": "सक्रिय मामले",
                "slaBreachRisk": "एसएलए उल्लंघन जोखिम",
                "avgTurnaround": "औसत समाधान समय",
                "citizenSatisfaction": "नागरिक संतुष्टि",
                "urgentDocket": "अत्यावश्यक प्रेषण डॉकेट",
                "viewQueue": "पूरी कतार देखें",
                "syncTelemetry": "टेलीमेट्री सिंक करें",
                "telemetryActive": "वास्तविक समय नागरिक टेलीमेट्री और स्वचालित प्रेषण स्ट्रीम सक्रिय है।",
                "monthlyTrends": "मासिक शिकायत रुझान",
                "resolutionBreakdown": "समाधान विवरण",
                "districtHeatmap": "ज़िला भू-प्रदर्शन",
                "departmentEfficiency": "विभागीय दक्षता रेटिंग",
                "docketOverview": "डॉकेट अवलोकन",
                "statutoryTarget": "24 घंटे के वैधानिक राज्य लक्ष्य के विरुद्ध"
            },
            "officers": {
                "title": "अधिकारी निर्देशिका",
                "directory": "क्षेत्रीय एवं नोडल अधिकारी",
                "addOfficer": "अधिकारी पंजीकृत करें",
                "officerName": "अधिकारी का नाम",
                "designation": "पदनाम",
                "department": "विभाग",
                "contact": "संपर्क",
                "assignedCount": "आवंटित मामले",
                "resolutionRate": "समाधान दर",
                "status": "ड्यूटी स्थिति",
                "actions": "कार्रवाइयां",
                "searchOfficers": "अधिकारियों को नाम, बैज या विभाग द्वारा खोजें..."
            },
            "departments": {
                "title": "नगर पालिका विभाग",
                "municipalDepartments": "शहर के परिचालन विभाग",
                "addDepartment": "विभाग जोड़ें",
                "deptName": "विभाग का नाम",
                "headOfDept": "विभागाध्यक्ष",
                "activePersonnel": "सक्रिय कर्मचारी",
                "budgetAllocated": "आवंटित बजट",
                "openGrievances": "खुली शिकायतें",
                "slaCompliance": "एसएलए अनुपालन",
                "efficiencyRating": "दक्षता रेटिंग",
                "searchDepartments": "विभाग खोजें..."
            },
            "assigned": {
                "title": "आवंटित शिकायतें",
                "caseId": "डॉकेट आईडी",
                "citizenName": "नागरिक का नाम",
                "category": "श्रेणी",
                "priority": "प्राथमिकता",
                "status": "स्थिति",
                "dateReported": "रिपोर्ट की तारीख",
                "targetResolution": "लक्ष्य समाधान",
                "reassign": "अधिकारी को पुनः सौंपें",
                "escalate": "वृद्धि ट्रिगर करें",
                "resolveCase": "हल के रूप में चिह्नित करें",
                "viewCase": "मामले का निरीक्षण करें",
                "filterPriority": "प्राथमिकता के अनुसार फ़िल्टर करें",
                "filterStatus": "स्थिति के अनुसार फ़िल्टर करें",
                "allCases": "सभी मामले"
            },
            "tracking": {
                "title": "शिकायत भू-ट्रैकिंग",
                "subtitle": "क्षेत्रीय अधिकारी टेलीमेट्री के साथ सक्रिय और लंबित मुद्दों को दिखाने वाला इंटरेक्टिव भौगोलिक मानचित्र।",
                "liveIncidentMap": "लाइव घटना मानचित्र",
                "filterByWard": "वार्ड के अनुसार फ़िल्टर करें",
                "filterBySeverity": "गंभीरता के अनुसार फ़िल्टर करें"
            },
            "aiSuggestions": {
                "title": "एआई शासन अंतर्दृष्टि",
                "smartRoutingTitle": "स्वचालित रूटिंग और वर्गीकरण सिफारिशें",
                "recommendedActions": "अनुशंसित कार्रवाइयां",
                "anomalyDetection": "विसंगति का पता लगाना",
                "duplicateClusters": "पहचाने गए डुप्लिकेट समूह",
                "autoTriage": "ऑटो-ट्राइएज नियम इंजन"
            },
            "reports": {
                "title": "शासन एनालिटिक्स एवं रिपोर्ट",
                "generateReport": "रिपोर्ट बनाएं",
                "downloadPdf": "पीडीएफ डाउनलोड करें",
                "downloadCsv": "सीएसवी निर्यात करें",
                "monthlyAudit": "मासिक नगरपालिका ऑडिट",
                "quarterlyPerformance": "त्रैमासिक प्रदर्शन समीक्षा",
                "exportAnalytics": "एनालिटिक्स निर्यात करें"
            },
            "settings": {
                "title": "पोर्टल प्रशासन सेटिंग्स",
                "slaThresholds": "एसएलए तात्कालिकता सीमाएं",
                "notificationRules": "चेतावनी एवं अधिसूचना नियम",
                "escalationMatrix": "वृद्धि मैट्रिक्स",
                "workingHours": "विभागीय कार्य के घंटे"
            }
        },
        "industry": {
            "portalTitle": "उद्योग एवं कॉर्पोरेट सीएसआर पोर्टल",
            "dashboard": {
                "title": "उद्योग सीएसआर डैशबोर्ड",
                "overview": "सीएसआर पूंजी एवं प्रभाव",
                "csrFunding": "सीएसआर पूंजी आवंटन",
                "capitalAllocation": "पूंजी आवंटन",
                "availableProjects": "जांची गई परियोजनाएं",
                "liveGrants": "सक्रिय अनुदान",
                "partnershipPact": "पीपीपी समझौते",
                "totalDisbursed": "कुल वितरित धन",
                "activeProjects": "सक्रिय वित्तपोषित परियोजनाएं",
                "impactScore": "सामाजिक प्रभाव स्कोर",
                "viewOpportunities": "अवसर देखें",
                "availableCsr": "उपलब्ध सीएसआर बजट",
                "corporatePartner": "कॉर्पोरेट भागीदार",
                "verifiedEntity": "सत्यापित सीएसआर इकाई"
            },
            "projects": {
                "title": "उपलब्ध सीएसआर परियोजनाएं",
                "projectCatalog": "परियोजना सूची",
                "fundingGoal": "लक्ष्य वित्तपोषण",
                "raisedAmount": "एकत्रित धन",
                "municipalSponsor": "नगर पालिका प्रायोजक",
                "sdgImpact": "एसडीजी प्रभाव श्रेणी",
                "applyFunding": "सीएसआर निधि प्रतिबद्ध करें",
                "exploreInitiatives": "नागरिक पहल का अन्वेषण करें",
                "searchProjects": "कीवर्ड, एसडीजी या शहर द्वारा सीएसआर परियोजनाएं खोजें..."
            },
            "funding": {
                "title": "वित्तपोषण एवं पूंजी आवंटन",
                "grantApplication": "अनुदान प्रस्ताव",
                "disbursementStatus": "वितरण स्थिति",
                "corporateDonation": "कॉर्पोरेट योगदान",
                "taxBenefit": "धारा 80G / 135 लाभ",
                "escrowStatus": "एस्क्रो खाता स्थिति",
                "fundMilestone": "मील का पत्थर किश्त जारी करें"
            },
            "csr": {
                "title": "सीएसआर प्रभाव एनालिटिक्स",
                "spendByCategory": "श्रेणी अनुसार सीएसआर खर्च",
                "geographicAllocation": "भौगोलिक आवंटन",
                "socialReturnOnInvestment": "निवेश पर सामाजिक लाभ (एसआरओआई)",
                "auditCompliance": "वैधानिक ऑडिट अनुपालन",
                "csrDistribution": "सीएसआर वितरण"
            },
            "mentorship": {
                "title": "उद्योग मार्गदर्शन कार्यक्रम",
                "expertGuidance": "विशेषज्ञ मार्गदर्शन प्रदान करें",
                "studentPrototypes": "छात्र प्रोटोटाइप",
                "industryAdvisors": "कॉर्पोरेट सलाहकार",
                "scheduleSession": "मार्गदर्शन सत्र निर्धारित करें"
            },
            "collaboration": {
                "title": "विश्वविद्यालय सहयोग केंद्र",
                "academicPacts": "शैक्षणिक गठबंधन",
                "joinConsortium": "कंसोर्टियम में शामिल हों",
                "jointResearch": "संयुक्त अनुसंधान उपक्रम",
                "mouSigned": "हस्ताक्षरित समझौता ज्ञापन"
            },
            "prototypes": {
                "title": "प्रौद्योगिकी प्रदर्शक एवं प्रोटोटाइप",
                "technologyDemonstrators": "नागरिक प्रोटोटाइप",
                "readyForDeployment": "पायलट परिनियोजन के लिए तैयार",
                "pilotTested": "क्षेत्रीय परीक्षण किया गया",
                "commercialize": "विस्तार एवं अंगीकार"
            },
            "tracking": {
                "title": "निधि एवं मील का पत्थर ट्रैकिंग",
                "milestoneProgress": "मील का पत्थर पूर्णता",
                "verificationCheck": "तृतीय-पक्ष ऑडिट जांच",
                "fundRelease": "किश्त जारी करना"
            },
            "profile": {
                "title": "संगठन प्रोफ़ाइल",
                "companyName": "कंपनी का नाम",
                "cinRegistration": "कॉर्पोरेट पहचान (CIN)",
                "csrBudget": "वार्षिक सीएसआर बजट",
                "contactPerson": "सीएसआर प्रमुख / संपर्क",
                "panNumber": "कॉर्पोरेट पैन"
            },
            "settings": {
                "title": "सीएसआर पोर्टल सेटिंग्स",
                "emailNotifications": "सीएसआर गतिविधि अलर्ट",
                "bankDetails": "एस्क्रो एवं बैंकिंग विवरण",
                "complianceDocs": "अनुपालन दस्तावेज़ीकरण"
            }
        },
        "ngo": {
            "portalTitle": "नागरिक समाज एवं स्वयंसेवक पोर्टल",
            "dashboard": {
                "title": "नागरिक समाज डैशबोर्ड",
                "overview": "क्षेत्रीय संचालन अवलोकन",
                "groundSquads": "सक्रिय स्वयंसेवक दस्ते",
                "activeVolunteers": "पंजीकृत स्वयंसेवक",
                "fieldInterventions": "क्षेत्रीय हस्तक्षेप",
                "reliefOperations": "राहत कार्य",
                "communityImpact": "सकारात्मक रूप से प्रभावित जीवन",
                "certsAwarded": "प्रदान किए गए प्रमाणपत्र",
                "urgentReliefCalls": "अत्यावश्यक नागरिक राहत कॉल",
                "groundTelemetryLive": "ग्राउंड टेलीमेट्री लाइव",
                "logFieldEvidence": "क्षेत्रीय साक्ष्य लॉग करें"
            },
            "projects": {
                "title": "सामुदायिक परियोजनाएं",
                "localGrievances": "नागरिक शिकायतें अपनाएं",
                "adoptIssue": "मुद्दे के लिए दस्ता जुटाएं",
                "publicWorks": "सामुदायिक कार्य अभियान",
                "grassrootInterventions": "जमीनी स्तर के हस्तक्षेप"
            },
            "assignedProjects": {
                "title": "आवंटित एनजीओ परियोजनाएं",
                "operationalSquads": "आवंटित दस्ते",
                "projectTimeline": "निष्पादन समयरेखा",
                "targetCompletion": "लक्ष्य पूर्णता तिथि",
                "submitProgressReport": "प्रगति रिपोर्ट जमा करें"
            },
            "fieldActivities": {
                "title": "क्षेत्रीय साक्ष्य लॉग",
                "liveReliefLog": "लाइव क्षेत्रीय लॉग",
                "geoTaggedPhotos": "जियो-टैग की गई तस्वीरें",
                "suppliesDistributed": "वितरित सामग्री / सहायता",
                "citizensAssisted": "सहायता प्राप्त नागरिक",
                "addLogEntry": "नया क्षेत्रीय लॉग सबमिट करें"
            },
            "volunteers": {
                "title": "स्वयंसेवक प्रबंधन",
                "registerVolunteer": "नए स्वयंसेवक को नामांकित करें",
                "skillsDirectory": "कौशल एवं विशेषज्ञता निर्देशिका",
                "assignWard": "नगर पालिका वार्ड को सौंपें",
                "volunteerSquads": "क्षेत्रीय दस्ते",
                "attendance": "उपस्थिति"
            },
            "impact": {
                "title": "सामुदायिक प्रभाव एनालिटिक्स",
                "livesImpacted": "प्रत्यक्ष रूप से लाभान्वित नागरिक",
                "wardsTransformed": "परिवर्तित नगरपालिका वार्ड",
                "satisfactionIndex": "जमीनी स्तर संतुष्टि सूचकांक",
                "volunteerHours": "कुल स्वयंसेवी घंटे लॉग किए गए"
            },
            "collaborations": {
                "title": "साझेदारी एवं गठबंधन",
                "municipalMoU": "नगर निगम सहयोग समझौते",
                "corporateSponsors": "कॉर्पोरेट सीएसआर भागीदार",
                "universityAlliances": "विश्वविद्यालय छात्र गठबंधन"
            },
            "certificates": {
                "title": "स्वयंसेवक प्रमाणपत्र एवं बैज",
                "awardCertificate": "प्रशस्ति पत्र जारी करें",
                "downloadBadge": "डिजिटल बैज डाउनलोड करें",
                "recognitionLetter": "नगर पालिका प्रशंसा पत्र"
            },
            "reports": {
                "title": "क्षेत्रीय ऑडिट एवं गतिविधि रिपोर्ट",
                "fieldAuditReports": "क्षेत्रीय सत्यापन रिपोर्ट",
                "monthlyActivitySummary": "मासिक गतिविधि सारांश",
                "incidentLogSheet": "घटना प्रतिक्रिया लॉग",
                "submitToGovernment": "सरकार को रिपोर्ट प्रेषित करें"
            },
            "settings": {
                "title": "एनजीओ प्रोफ़ाइल एवं सेटिंग्स",
                "registrationDetails": "ट्रस्ट / सोसायटी पंजीकरण",
                "ngoDarpanId": "नीति आयोग एनजीओ दर्पण आईडी",
                "focalPoints": "क्षेत्रीय समन्वयक"
            }
        },
        "university": {
            "portalTitle": "विश्वविद्यालय एवं शिक्षा जगत पोर्टल",
            "student": {
                "dashboard": {
                    "title": "छात्र नवाचार डैशबोर्ड",
                    "academicCredits": "अर्जित शैक्षणिक क्रेडिट",
                    "assignedTasks": "आवंटित प्रयोगशाला कार्य",
                    "labProjects": "नागरिक अनुसंधान परियोजनाएं",
                    "prototypeChallenges": "नवाचार चुनौतियाँ",
                    "submitMilestone": "परियोजना मील का पत्थर जमा करें"
                },
                "tasks": {
                    "title": "प्रयोगशाला कार्य एवं प्रस्तुतियाँ",
                    "pendingTasks": "लंबित कार्य",
                    "taskDescription": "कार्य निर्देश",
                    "dueDate": "प्रस्तुति अंतिम तिथि",
                    "submitDeliverable": "समाधान प्रस्तुति जमा करें",
                    "advisorNotes": "संकाय सलाहकार नोट्स",
                    "dueTasks": "जल्द देय कार्य"
                },
                "uploads": {
                    "title": "प्रस्तुति अपलोड करें",
                    "researchNotes": "अनुसंधान नोट्स एवं रिपोर्ट",
                    "projectCode": "स्रोत कोड भंडार",
                    "presentationSlides": "प्रस्तुति स्लाइड",
                    "submitForGrading": "शैक्षणिक समीक्षा के लिए जमा करें"
                },
                "timeline": {
                    "title": "मील का पत्थर समयरेखा",
                    "projectSchedule": "परियोजना अनुसूची",
                    "semesterDeadlines": "सेमेस्टर मील के पत्थर",
                    "facultyReviewDate": "निर्धारित संकाय समीक्षा"
                },
                "messages": {
                    "title": "सलाहकार चर्चा",
                    "chatWithMentor": "संकाय संरक्षक के साथ बातचीत करें",
                    "feedbackThread": "प्रतिक्रिया एवं सुधार",
                    "askQuestion": "प्रश्न पूछें"
                }
            },
            "faculty": {
                "dashboard": {
                    "title": "संकाय संरक्षक डैशबोर्ड",
                    "studentCohorts": "छात्र समूह",
                    "mentoredProjects": "निर्देशित परियोजनाएं",
                    "pendingApprovals": "लंबित स्वीकृतियां",
                    "researchPapers": "प्रकाशित शोध पत्र",
                    "innovationIndex": "समूह नवाचार सूचकांक"
                },
                "approvals": {
                    "title": "मील का पत्थर स्वीकृतियां",
                    "reviewSubmission": "छात्र प्रस्तुति की समीक्षा करें",
                    "approveMilestone": "मील का पत्थर स्वीकृत करें",
                    "rejectMilestone": "संशोधन का अनुरोध करें",
                    "provideFeedback": "प्रतिक्रिया एवं मूल्यांकन",
                    "gradeAwarded": "प्रदान किए गए शैक्षणिक क्रेडिट",
                    "pendingReviews": "लंबित समीक्षाएं"
                },
                "proposals": {
                    "title": "नगर निगम अनुसंधान प्रस्ताव",
                    "civicResearchTopics": "नागरिक समस्या विवरण",
                    "grantProposals": "संयुक्त अनुसंधान अनुदान",
                    "callForPapers": "समाधान के लिए आह्वान",
                    "openProposals": "खुले प्रस्ताव"
                },
                "teams": {
                    "title": "छात्र अनुसंधान दल",
                    "teamRoster": "टीम के सदस्य",
                    "assignLead": "छात्र नेता नियुक्त करें",
                    "performanceReview": "आवधिक मूल्यांकन",
                    "academicAdvising": "शैक्षणिक सलाह"
                },
                "reports": {
                    "title": "शैक्षणिक एनालिटिक्स एवं रिपोर्ट",
                    "cohortProgress": "समूह प्रगति ट्रैकर",
                    "publicationOutput": "शैक्षणिक आउटपुट",
                    "creditDistribution": "क्रेडिट वितरण"
                }
            },
            "shared": {
                "projects": {
                    "title": "शैक्षणिक अनुसंधान परियोजनाएं",
                    "studentResearch": "छात्र अनुसंधान पहल",
                    "capstoneProjects": "कैपस्टोन परियोजनाएं",
                    "interdisciplinaryTeams": "अंतःविषय टीमें"
                },
                "research": {
                    "title": "अनुसंधान केंद्र",
                    "publications": "श्वेतपत्र एवं प्रकाशन",
                    "datasets": "ओपन नागरिक डेटासेट",
                    "patentFiling": "पेटेंट एवं बौद्धिक संपदा",
                    "peerReview": "सहकर्मी समीक्षा निर्देशिका"
                },
                "innovation": {
                    "title": "नागरिक नवाचार प्रयोगशाला",
                    "innovationChallenges": "हैकाथॉन एवं चुनौतियाँ",
                    "hackathonDemos": "प्रोटोटाइप शोकेस",
                    "incubatorReady": "ऊष्मायन चरण",
                    "smartCityPrototypes": "स्मार्ट सिटी तकनीक डेमो"
                },
                "credits": {
                    "title": "शैक्षणिक क्रेडिट एवं मान्यता",
                    "creditsEarned": "अर्जित क्रेडिट",
                    "skillBadges": "कौशल बैज",
                    "hallOfFame": "हॉल ऑफ फेम",
                    "transcriptVerification": "सत्यापित डिजिटल प्रतिलेख"
                },
                "repository": {
                    "title": "शैक्षणिक भंडार",
                    "researchPapersArchive": "शोध पत्र पुरालेख",
                    "openDataVault": "ओपन डेटा वॉल्ट",
                    "citationIndex": "उद्धरण सूचकांक"
                },
                "settings": {
                    "title": "विश्वविद्यालय सेटिंग्स",
                    "facultyProfile": "संस्थागत प्रोफ़ाइल",
                    "departmentAffiliation": "विभागीय संबद्धता",
                    "orcidId": "ORCID / शोधकर्ता आईडी"
                }
            }
        },
        "admin": {
            "portalTitle": "केंद्रीय कमान एवं प्लेटफ़ॉर्म प्रशासन",
            "dashboard": {
                "title": "प्लेटफ़ॉर्म प्रशासन डैशबोर्ड",
                "totalSystemUsers": "कुल पंजीकृत उपयोगकर्ता",
                "activePortals": "सक्रिय पोर्टल",
                "aiModelStatus": "एआई मॉडल स्वास्थ्य",
                "databaseHealth": "डेटाबेस विलंबता",
                "unresolvedGrievances": "कुल खुली शिकायतें",
                "platformLoad": "सर्वर इन्फ्रास्ट्रक्चर लोड",
                "liveEventStream": "लाइव प्लेटफ़ॉर्म ऑडिट स्ट्रीम",
                "rootConsole": "रूट कंसोल",
                "cpuUsage": "सीपीयू उपयोग",
                "dbLatency": "डेटाबेस विलंबता",
                "uptime": "सिस्टम अपटाइम"
            },
            "users": {
                "title": "उपयोगकर्ता एवं भूमिका प्रबंधन",
                "allUsers": "सभी सिस्टम उपयोगकर्ता",
                "addUser": "उपयोगकर्ता जोड़ें",
                "editRole": "भूमिका एवं दायरा संशोधित करें",
                "suspendUser": "खाता निलंबित करें",
                "resetPassword": "पासवर्ड रीसेट करें",
                "roleFilter": "भूमिका के अनुसार फ़िल्टर करें",
                "searchUsers": "नाम, ईमेल या आईडी द्वारा खोजें..."
            },
            "roles": {
                "title": "भूमिका एवं अनुमति प्रबंधन",
                "permissionsMatrix": "अभिगम नियंत्रण मैट्रिक्स",
                "accessControl": "सुरक्षा नीतियां",
                "createRole": "कस्टम भूमिका परिभाषित करें",
                "customRoles": "कॉन्फ़िगर की गई भूमिकाएं"
            },
            "government": {
                "title": "नगर पालिका प्रशासन नियंत्रण",
                "municipalBOD": "नगर पालिका निकाय",
                "cityDistricts": "ज़िला क्षेत्राधिकार",
                "assignWardEngineers": "वार्ड इंजीनियर नियुक्त करें"
            },
            "universities": {
                "title": "विश्वविद्यालय प्रत्यायन प्रबंधन",
                "registeredCampuses": "संबद्ध विश्वविद्यालय",
                "accreditationVerify": "NAAC / UGC सत्यापन",
                "studentCap": "नामांकन कोटा"
            },
            "industry": {
                "title": "उद्योग एवं कॉर्पोरेट भागीदार निरीक्षण",
                "corporatePartners": "पंजीकृत सीएसआर भागीदार",
                "csrValidation": "धारा 135 पात्रता जांच",
                "escrowAudits": "एस्क्रो संवितरण सत्यापन"
            },
            "ngos": {
                "title": "एनजीओ एवं स्वयंसेवक निरीक्षण",
                "verifiedNgos": "मान्यता प्राप्त एनजीओ",
                "darpanCheck": "एनजीओ दर्पण सत्यापन",
                "groundClearance": "क्षेत्रीय संचालन मंजूरी"
            },
            "research": {
                "title": "अनुसंधान संस्थान निरीक्षण",
                "institutePartnerships": "अनुसंधान भागीदार",
                "ethicsClearance": "नैतिकता समीक्षा बोर्ड",
                "datasetAccess": "डेटा एक्सेस अनुमतियाँ"
            },
            "departments": {
                "title": "विभाग मास्टर विन्यास",
                "routingRules": "स्वचालित रूटिंग नियम",
                "autoAssignmentEngine": "एआई प्रेषण इंजन",
                "fallbackQueues": "फ़ॉलबैक कतारें"
            },
            "issues": {
                "title": "प्लेटफ़ॉर्म शिकायत मास्टर",
                "forceResolve": "प्रशासनिक समाधान",
                "reassignCluster": "मुद्दा क्लस्टर पुनः असाइन करें",
                "auditLog": "अपरिवर्तनीय एक्शन लॉग",
                "purgeTestData": "परीक्षण डेटा साफ़ करें"
            },
            "aiMonitoring": {
                "title": "एआई विज़न एवं टेलीमेट्री निगरानी",
                "geminiVisionUptime": "विज़न मॉडल अपटाइम",
                "fastApiOcrStatus": "FastAPI ओसीआर पाइपलाइन",
                "speechToTextLatency": "एसटीटी प्रतिलेखन विलंबता",
                "accuracyScore": "ट्राइएज सटीकता स्कोर",
                "confidenceDistribution": "विश्वास स्कोर वितरण",
                "modelLogs": "अनुमान विलंबता लॉग"
            },
            "workflowMonitoring": {
                "title": "कार्यप्रवाह इंजन एवं कतार टेलीमेट्री",
                "stateMachineInspect": "स्टेट मशीन संक्रमण",
                "queueDepth": "संदेश कतार गहराई",
                "deadLetterQueue": "डेड-लेटर कतार",
                "retryFailedTasks": "विफल कार्यों का पुनः प्रयास करें"
            },
            "analytics": {
                "title": "क्रॉस-प्लेटफ़ॉर्म मैक्रो एनालिटिक्स",
                "crossPortalActivity": "क्रॉस-पोर्टल उपयोग मेट्रिक्स",
                "municipalPerformanceIndex": "नगर पालिका प्रदर्शन सूचकांक",
                "peakUsageHours": "चरम गतिविधि के घंटे"
            },
            "systemHealth": {
                "title": "इन्फ्रास्ट्रक्चर एवं सिस्टम स्वास्थ्य",
                "databaseReplicas": "डेटाबेस प्रतिकृतियां",
                "redisCache": "रेडिस इन-मेमोरी स्थिति",
                "storageUsage": "ऑब्जेक्ट स्टोरेज वॉल्यूम",
                "apiGateways": "माइक्रोसर्विस स्वास्थ्य",
                "uptime99": "99.98% उच्च उपलब्धता",
                "online": "ऑनलाइन",
                "maintenance": "रखरखाव"
            },
            "settings": {
                "title": "प्लेटफ़ॉर्म सेटिंग्स",
                "maintenanceMode": "रखरखाव मोड",
                "apiRateLimits": "एपीआई दर सीमित करना",
                "backupSchedules": "स्वचालित बैकअप अनुसूची",
                "smtpConfig": "एसएमटीपी एवं ईमेल गेटवे"
            }
        },
        "toast": {
            "issueSubmitted": "शिकायत सफलतापूर्वक दर्ज की गई! संबंधित विभाग को भेजी गई।",
            "gpsCaptured": "जीपीएस निर्देशांक कैप्चर किए गए",
            "gpsCapturedDesc": "निर्देशांक शिकायत रिपोर्ट से जुड़े।",
            "locationDenied": "स्थान अनुमति अस्वीकृत या अनुपलब्ध। डिफ़ॉल्ट पिनपॉइंट का उपयोग किया जा रहा है।",
            "fileSizeExceeded": "फ़ाइल 25MB सीमा से अधिक है।",
            "audioNotSupported": "इस ब्राउज़र में ऑडियो रिकॉर्डिंग समर्थित नहीं है।",
            "micSimulation": "वॉयस शिकायत डेमो के लिए माइक्रोफ़ोन सिमुलेशन सक्रिय है।",
            "profileUpdated": "प्रोफ़ाइल सफलतापूर्वक अपडेट की गई।",
            "settingsSaved": "प्राथमिकताएं सफलतापूर्वक सहेजी गईं।",
            "deleteRequested": "खाता हटाने का अनुरोध प्रस्तुत किया गया।",
            "languageChanged": "भाषा सफलतापूर्वक बदल दी गई।",
            "errorOccurred": "एक त्रुटि उत्पन्न हुई। कृपया पुनः प्रयास करें।",
            "caseUpdated": "केस डॉकेट सफलतापूर्वक अपडेट किया गया।",
            "caseReassigned": "मामला नोडल अधिकारी को पुनः सौंपा गया।",
            "caseResolved": "शिकायत को हल के रूप में चिह्नित किया गया।",
            "volunteerAdded": "नया स्वयंसेवक सफलतापूर्वक पंजीकृत हुआ।",
            "grantApproved": "सीएसआर अनुदान आवंटन स्वीकृत।",
            "milestoneApproved": "शैक्षणिक मील का पत्थर स्वीकृत।",
            "deliverableUploaded": "प्रस्तुति समीक्षा के लिए अपलोड की गई।",
            "loginSuccess": "सफलतापूर्वक साइन इन किया गया। स्वागत है!",
            "logoutSuccess": "सफलतापूर्वक लॉग आउट किया गया।",
            "accessDenied": "पहुंच प्रतिबंधित। अपर्याप्त अनुमतियाँ।",
            "changesSaved": "सभी परिवर्तन सफलतापूर्वक सहेजे गए।",
            "reportExported": "रिपोर्ट उत्पन्न और डाउनलोड की गई।",
            "dataRefreshed": "टेलीमेट्री डेटा रीफ्रेश किया गया।"
        },
        "language": "भाषा",
        "dashboard": "डैशबोर्ड",
        "report_issue": "समस्या दर्ज करें",
        "report_problem": "समस्या दर्ज करें",
        "my_issues": "मेरी शिकायतें",
        "track_issues": "निवारण ट्रैक करें",
        "notifications": "सूचनाएं",
        "profile": "प्रोफ़ाइल",
        "settings": "सेटिंग्स",
        "help": "सहायता एवं समर्थन",
        "logout": "लॉग आउट",
        "login": "लॉग इन",
        "recent_grievances": "हाल की शिकायतें",
        "issue_id": "शिकायत आईडी",
        "citizen_portal": "नागरिक पोर्टल",
        "government_portal": "सरकारी पोर्टल",
        "university_portal": "विश्वविद्यालय पोर्टल",
        "industry_portal": "उद्योग पोर्टल",
        "ngo_portal": "एनजीओ पोर्टल",
        "admin_portal": "व्यवस्थापक पोर्टल",
        "ai_governance_insight": "एआई शासन अंतर्दृष्टि",
        "resolution": "समाधान",
        "report": "रिपोर्ट",
        "map": "घटना मानचित्र",
        "search": "खोजें",
        "search_placeholder": "शिकायतें, मामले, स्थान खोजें...",
        "filter": "फ़िल्टर",
        "save": "बदलाव सहेजें",
        "cancel": "रद्द करें",
        "delete": "हटाएं",
        "submit": "जमा करें",
        "upload": "अपलोड करें",
        "location": "स्थान",
        "description": "विवरण",
        "title": "शीर्षक",
        "category": "श्रेणी",
        "department": "विभाग",
        "created_at": "रिपोर्ट की तारीख",
        "action": "कार्रवाई",
        "actions": "कार्रवाइयां",
        "view": "देखें",
        "edit": "संपादित करें",
        "loading": "लोड हो रहा है...",
        "success": "सफलता",
        "error": "एक त्रुटि उत्पन्न हुई",
        "welcome_back": "वापसी पर स्वागत है",
        "total_issues": "कुल शिकायतें",
        "resolved_issues": "हल की गई शिकायतें",
        "in_progress_issues": "प्रगति पर शिकायतें",
        "pending_issues": "लंबित शिकायतें",
        "active_projects": "सक्रिय परियोजनाएं",
        "ai_accuracy": "एआई रूटिंग सटीकता",
        "sla_compliance": "एसएलए अनुपालन दर",
        "civic_engagement": "नागरिक जुड़ाव सूचकांक",
        "recent_activity": "हाल की गतिविधि",
        "quick_actions": "त्वरित कार्रवाइयां",
        "live_incidents": "लाइव नागरिक घटनाएं",
        "all": "सभी",
        "high": "उच्च",
        "medium": "मध्यम",
        "low": "कम",
        "critical": "गंभीर",
        "emergency": "आपातकालीन",
        "pending": "लंबित",
        "in_progress": "प्रगति पर है",
        "resolved": "हल किया गया",
        "closed": "बंद",
        "rejected": "अस्वीकृत",
        "approved": "स्वीकृत",
        "declined": "अस्वीकृत",
        "export": "डेटा निर्यात करें",
        "download": "डाउनलोड",
        "confirm": "पुष्टि करें",
        "close": "बंद करें",
        "back": "वापस",
        "next": "आगे",
        "previous": "पिछला",
        "no_results": "कोई परिणाम नहीं मिला",
        "view_all": "सभी देखें",
        "home": "होम",
        "feed": "नागरिक फ़ीड",
        "analytics": "एआई एनालिटिक्स",
        "optional": "वैकल्पिक",
        "faculty": "संकाय",
        "student": "छात्र",
        "projects": "परियोजनाएं",
        "research": "अनुसंधान",
        "innovation": "नवाचार",
        "teams": "टीमें",
        "credits": "शैक्षणिक क्रेडिट",
        "officers": "अधिकारी",
        "assigned": "आवंटित",
        "under_review": "समीक्षाधीन",
        "industry_assigned": "उद्योग को आवंटित",
        "industry_review": "उद्योग समीक्षा",
        "univ_assigned": "विश्वविद्यालय को आवंटित",
        "student_dev": "छात्र विकास",
        "faculty_review": "संकाय समीक्षा",
        "industry_val": "उद्योग सत्यापन",
        "inspection": "स्थल निरीक्षण",
        "feedback": "प्रतिक्रिया लंबित"
    }
