import {
  StudentProfileData,
  CreditScoreData,
  CreditActivity,
  StudentBadge,
  ProjectStatistics,
  LeaderboardEntry,
  StudentCertificate,
  CreditHistoryMonth,
} from '../types/student-contribution';

export const INITIAL_STUDENT_PROFILE: StudentProfileData = {
  id: 'usr-student-01',
  name: 'Alex Rivera',
  university: 'Stanford University',
  department: 'Department of Computer Science',
  yearOfStudy: '2nd Year M.S. (Graduate)',
  rollNumber: 'CS-2024-8902',
  email: 'alex.rivera@stanford.edu',
  mobileNumber: '+1 (650) 498-1002',
  nssMember: true,
  nssDetails: 'NSS Lead Volunteer • Environmental Conservation Cell',
  nccMember: true,
  nccDetails: 'NCC Senior Under Officer (SUO) • Technical Signals Unit',
  bio: 'Graduate researcher in low-power embedded AI, decentralized solar microgrids, and urban sensor networks.',
};

export const INITIAL_CREDIT_SCORE: CreditScoreData = {
  currentScore: 785,
  currentLevel: 'Platinum',
  nextLevel: 'Diamond',
  nextLevelThreshold: 1000,
  creditsRemaining: 215,
  percentileRank: 4, // Top 4%
  levelProgressPercentage: 78.5,
};

export const CREDIT_ACTIVITIES: CreditActivity[] = [
  {
    id: 'act-01',
    name: 'Reported Issues',
    category: 'Grievance & Verification',
    creditsEarned: 45,
    maxCredits: 50,
    completionPercentage: 90,
    completedCount: 9,
    iconName: 'AlertCircle',
  },
  {
    id: 'act-02',
    name: 'Successfully Verified Issues',
    category: 'Grievance & Verification',
    creditsEarned: 60,
    maxCredits: 60,
    completionPercentage: 100,
    completedCount: 12,
    iconName: 'CheckCircle2',
  },
  {
    id: 'act-03',
    name: 'Community Surveys',
    category: 'Community & NSS/NCC',
    creditsEarned: 50,
    maxCredits: 70,
    completionPercentage: 71,
    completedCount: 5,
    iconName: 'ClipboardList',
  },
  {
    id: 'act-04',
    name: 'University Projects Joined',
    category: 'Research & Innovation',
    creditsEarned: 70,
    maxCredits: 80,
    completionPercentage: 88,
    completedCount: 4,
    iconName: 'FolderGit2',
  },
  {
    id: 'act-05',
    name: 'Projects Successfully Completed',
    category: 'Research & Innovation',
    creditsEarned: 110,
    maxCredits: 120,
    completionPercentage: 92,
    completedCount: 3,
    iconName: 'Trophy',
  },
  {
    id: 'act-06',
    name: 'Prototype Submitted',
    category: 'Research & Innovation',
    creditsEarned: 85,
    maxCredits: 100,
    completionPercentage: 85,
    completedCount: 2,
    iconName: 'Cpu',
  },
  {
    id: 'act-07',
    name: 'Research Contribution',
    category: 'Research & Innovation',
    creditsEarned: 65,
    maxCredits: 75,
    completionPercentage: 87,
    completedCount: 3,
    iconName: 'BookOpen',
  },
  {
    id: 'act-08',
    name: 'Mentor Appreciation',
    category: 'Research & Innovation',
    creditsEarned: 40,
    maxCredits: 40,
    completionPercentage: 100,
    completedCount: 4,
    iconName: 'HeartHandshake',
  },
  {
    id: 'act-09',
    name: 'Government Appreciation',
    category: 'Grievance & Verification',
    creditsEarned: 50,
    maxCredits: 50,
    completionPercentage: 100,
    completedCount: 2,
    iconName: 'Building2',
  },
  {
    id: 'act-10',
    name: 'NSS Activities',
    category: 'Community & NSS/NCC',
    creditsEarned: 35,
    maxCredits: 40,
    completionPercentage: 88,
    completedCount: 7,
    iconName: 'Users',
  },
  {
    id: 'act-11',
    name: 'NCC Activities',
    category: 'Community & NSS/NCC',
    creditsEarned: 40,
    maxCredits: 40,
    completionPercentage: 100,
    completedCount: 8,
    iconName: 'Shield',
  },
  {
    id: 'act-12',
    name: 'Volunteer Hours',
    category: 'Community & NSS/NCC',
    creditsEarned: 30,
    maxCredits: 50,
    completionPercentage: 60,
    completedCount: 142, // hours
    iconName: 'Clock',
  },
  {
    id: 'act-13',
    name: 'Hackathons Participated',
    category: 'Competitions & Deployment',
    creditsEarned: 35,
    maxCredits: 40,
    completionPercentage: 88,
    completedCount: 3,
    iconName: 'Code2',
  },
  {
    id: 'act-14',
    name: 'Innovation Challenges',
    category: 'Competitions & Deployment',
    creditsEarned: 40,
    maxCredits: 50,
    completionPercentage: 80,
    completedCount: 2,
    iconName: 'Sparkles',
  },
  {
    id: 'act-15',
    name: 'Solution Deployment',
    category: 'Competitions & Deployment',
    creditsEarned: 45,
    maxCredits: 50,
    completionPercentage: 90,
    completedCount: 2,
    iconName: 'Rocket',
  },
  {
    id: 'act-16',
    name: 'Field Visits',
    category: 'Grievance & Verification',
    creditsEarned: 25,
    maxCredits: 30,
    completionPercentage: 83,
    completedCount: 6,
    iconName: 'MapPin',
  },
];

export const STUDENT_BADGES: StudentBadge[] = [
  {
    id: 'badge-01',
    name: 'Community Volunteer',
    description: 'Awarded for over 100 verified volunteer hours in civic and NSS sanitation drives.',
    tier: 'Diamond',
    earnedDate: 'August 14, 2026',
    iconName: 'Heart',
    unlocked: true,
    nextTierCriteria: 'Maximum tier unlocked! Recognized as Grand Community Fellow.',
  },
  {
    id: 'badge-02',
    name: 'Problem Solver',
    description: 'Diagnosed and verified 10+ municipal grievances with zero false telemetry.',
    tier: 'Platinum',
    earnedDate: 'July 28, 2026',
    iconName: 'CheckCheck',
    unlocked: true,
    nextTierCriteria: 'Verify 5 more municipal issues to unlock Diamond Problem Solver tier.',
  },
  {
    id: 'badge-03',
    name: 'Innovation Contributor',
    description: 'Designed and deployed functional hardware prototypes for clean energy challenges.',
    tier: 'Gold',
    earnedDate: 'June 19, 2026',
    iconName: 'Lightbulb',
    unlocked: true,
    nextTierCriteria: 'Deploy 1 more city-scale pilot to achieve Platinum rank.',
  },
  {
    id: 'badge-04',
    name: 'Research Assistant',
    description: 'Co-authored indexed peer-reviewed publications with faculty advisors.',
    tier: 'Gold',
    earnedDate: 'May 30, 2026',
    iconName: 'GraduationCap',
    unlocked: true,
    nextTierCriteria: 'Publish 1 more IEEE or ACM journal paper to unlock Platinum.',
  },
  {
    id: 'badge-05',
    name: 'Field Survey Expert',
    description: 'Conducted high-accuracy acoustic pipeline and GIS drainage mapping surveys.',
    tier: 'Silver',
    earnedDate: 'April 12, 2026',
    iconName: 'Map',
    unlocked: true,
    nextTierCriteria: 'Complete 3 additional ward acoustic telemetry audits for Gold.',
  },
  {
    id: 'badge-06',
    name: 'AI Contributor',
    description: 'Trained and optimized edge vision & anomaly models on low-power microcontrollers.',
    tier: 'Platinum',
    earnedDate: 'August 02, 2026',
    iconName: 'BrainCircuit',
    unlocked: true,
    nextTierCriteria: 'Contribute 1 open-source model weights dataset to reach Diamond.',
  },
  {
    id: 'badge-07',
    name: 'Prototype Builder',
    description: 'Assembled working PCB hardware prototypes under faculty supervision.',
    tier: 'Gold',
    earnedDate: 'July 05, 2026',
    iconName: 'Wrench',
    unlocked: true,
    nextTierCriteria: 'Fabricate 2 more municipal test rig benches to reach Platinum.',
  },
  {
    id: 'badge-08',
    name: 'Top Collaborator',
    description: 'Active peer reviewer, assisting fellow student fellows across lab disciplines.',
    tier: 'Silver',
    earnedDate: 'March 22, 2026',
    iconName: 'Users2',
    unlocked: true,
    nextTierCriteria: 'Conduct 4 more cross-departmental peer reviews for Gold.',
  },
];

export const PROJECT_STATISTICS: ProjectStatistics = {
  completedProjects: 4,
  ongoingProjects: 2,
  pendingAssignments: 3,
  hoursContributed: 142,
  communitiesServed: 8,
  certificatesEarned: 6,
  researchPapers: 2,
  patentsFiled: 1,
  innovationAwards: 3,
};

export const LEADERBOARD_ENTRIES: LeaderboardEntry[] = [
  {
    rank: 1,
    id: 'stu-01',
    name: 'Priya Narayanan',
    avatarText: 'PN',
    department: 'Computer Science',
    year: 'Final Year M.S.',
    university: 'Stanford University',
    creditScore: 920,
    tier: 'Diamond',
    badgesCount: 8,
  },
  {
    rank: 2,
    id: 'stu-02',
    name: 'Karthik Subramanian',
    avatarText: 'KS',
    department: 'Electrical Engineering',
    year: 'Final Year B.Tech',
    university: 'Stanford University',
    creditScore: 840,
    tier: 'Platinum',
    badgesCount: 7,
  },
  {
    rank: 3,
    id: 'usr-student-01',
    name: 'Alex Rivera',
    avatarText: 'AR',
    department: 'Computer Science',
    year: '2nd Year M.S.',
    university: 'Stanford University',
    creditScore: 785,
    tier: 'Platinum',
    badgesCount: 8,
    isCurrentUser: true,
  },
  {
    rank: 4,
    id: 'stu-04',
    name: 'Maya Chen',
    avatarText: 'MC',
    department: 'Civil & Environmental Engineering',
    year: '1st Year Ph.D.',
    university: 'Stanford University',
    creditScore: 750,
    tier: 'Platinum',
    badgesCount: 6,
  },
  {
    rank: 5,
    id: 'stu-05',
    name: 'Sarah Al-Hassan',
    avatarText: 'SA',
    department: 'Computer Science',
    year: '1st Year M.S.',
    university: 'Stanford University',
    creditScore: 690,
    tier: 'Gold',
    badgesCount: 5,
  },
  {
    rank: 6,
    id: 'stu-06',
    name: 'Rohan Varma',
    avatarText: 'RV',
    department: 'Civil & Environmental Engineering',
    year: '2nd Year Ph.D.',
    university: 'IISc Bangalore',
    creditScore: 675,
    tier: 'Gold',
    badgesCount: 6,
  },
  {
    rank: 7,
    id: 'stu-07',
    name: 'Ananya Iyer',
    avatarText: 'AI',
    department: 'Data Science',
    year: 'Final Year M.Tech',
    university: 'IISc Bangalore',
    creditScore: 640,
    tier: 'Gold',
    badgesCount: 5,
  },
  {
    rank: 8,
    id: 'stu-08',
    name: 'David Kim',
    avatarText: 'DK',
    department: 'Electrical Engineering',
    year: 'Senior Year B.S.',
    university: 'Stanford University',
    creditScore: 590,
    tier: 'Gold',
    badgesCount: 4,
  },
  {
    rank: 9,
    id: 'stu-09',
    name: 'Tanvi Deshmukh',
    avatarText: 'TD',
    department: 'Civil Engineering',
    year: '3rd Year B.Tech',
    university: 'IIT Bombay',
    creditScore: 510,
    tier: 'Gold',
    badgesCount: 4,
  },
  {
    rank: 10,
    id: 'stu-10',
    name: 'Liam Vance',
    avatarText: 'LV',
    department: 'Mechanical Engineering',
    year: '2nd Year M.S.',
    university: 'Stanford University',
    creditScore: 460,
    tier: 'Silver',
    badgesCount: 3,
  },
];

export const STUDENT_CERTIFICATES: StudentCertificate[] = [
  {
    id: 'cert-01',
    name: 'Excellence in Urban Solar Microgrid Telemetry',
    issuedBy: 'Stanford Energy Institute & City Innovation Council',
    issueDate: 'August 2026',
    credentialId: 'SOCX-CERT-2026-8812',
    category: 'Project Deployment',
  },
  {
    id: 'cert-02',
    name: 'National Service Scheme (NSS) - Community Leadership Award',
    issuedBy: 'Ministry of Youth Affairs & University NSS Cell',
    issueDate: 'July 2026',
    credentialId: 'NSS-HON-2026-4401',
    category: 'Social Service',
  },
  {
    id: 'cert-03',
    name: 'Municipal Sensor Benchmark & Telemetry Certification',
    issuedBy: 'Metropolitan Water Supply & Drainage Board',
    issueDate: 'June 2026',
    credentialId: 'BWSSB-ENG-2026-192',
    category: 'Government Verification',
  },
  {
    id: 'cert-04',
    name: 'National Cadet Corps (NCC) - SUO Technical Merit Certificate',
    issuedBy: 'Directorate General NCC & Signals Regiment',
    issueDate: 'May 2026',
    credentialId: 'NCC-MERIT-2026-902',
    category: 'NCC Honor',
  },
  {
    id: 'cert-05',
    name: 'Edge AI Anomaly Detection Hackathon - First Prize Winner',
    issuedBy: 'Global Societal Innovation Summit',
    issueDate: 'April 2026',
    credentialId: 'HACK-WIN-2026-042',
    category: 'Hackathon Award',
  },
  {
    id: 'cert-06',
    name: 'Faculty Advisory Research Fellow Fellowship Diploma',
    issuedBy: 'Department of Computer Science & Engineering',
    issueDate: 'March 2026',
    credentialId: 'STAN-FELLOW-2026-08',
    category: 'Academic Fellowship',
  },
];

export const CREDIT_MONTHLY_HISTORY: CreditHistoryMonth[] = [
  { month: 'Apr', credits: 110, cumulative: 220 },
  { month: 'May', credits: 135, cumulative: 355 },
  { month: 'Jun', credits: 120, cumulative: 475 },
  { month: 'Jul', credits: 150, cumulative: 625 },
  { month: 'Aug', credits: 160, cumulative: 785 },
];
