"""App prompts package."""

from app.prompts.civic_prompts import (
    CRITICAL_SAFETY_KEYWORDS,
    HIGH_URGENCY_KEYWORDS,
    CATEGORY_KEYWORD_TAXONOMY,
    SUBCATEGORY_MARKERS,
)

__all__ = [
    "CRITICAL_SAFETY_KEYWORDS",
    "HIGH_URGENCY_KEYWORDS",
    "CATEGORY_KEYWORD_TAXONOMY",
    "SUBCATEGORY_MARKERS",
]
