"""App schemas package."""

from app.schemas.ai_requests import (
    OCRExtractBase64Request,
    SpeechTranscribeBase64Request,
    VisionAnalyzeBase64Request,
    NLPAnalyzeRequest,
    TranslationRequest,
    ClassificationRequest,
    PriorityDetectionRequest,
    SummaryGenerationRequest,
    PipelineProcessJsonRequest,
)
from app.schemas.ai_responses import (
    BoundingBox,
    OCRExtractResponse,
    SpeechSegment,
    SpeechTranscribeResponse,
    VisionAnalyzeResponse,
    ExtractedEntity,
    NLPAnalyzeResponse,
    TranslationResponse,
    ClassificationResponse,
    PriorityDetectionResponse,
    SummaryGenerationResponse,
    PipelineProcessResponse,
)

__all__ = [
    "OCRExtractBase64Request",
    "SpeechTranscribeBase64Request",
    "VisionAnalyzeBase64Request",
    "NLPAnalyzeRequest",
    "TranslationRequest",
    "ClassificationRequest",
    "PriorityDetectionRequest",
    "SummaryGenerationRequest",
    "PipelineProcessJsonRequest",
    "BoundingBox",
    "OCRExtractResponse",
    "SpeechSegment",
    "SpeechTranscribeResponse",
    "VisionAnalyzeResponse",
    "ExtractedEntity",
    "NLPAnalyzeResponse",
    "TranslationResponse",
    "ClassificationResponse",
    "PriorityDetectionResponse",
    "SummaryGenerationResponse",
    "PipelineProcessResponse",
]
