# -*- coding: utf-8 -*-
"""
Builder for scripts/data_mr.py (Marathi)
Ensures 100% key parity with get_base_en().
"""

import sys, os, json
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from scripts.generate_all_translations import get_base_en

def generate_mr():
    # Load base en as key template
    base = get_base_en()
    
    # We will build mr_dict with exact keys
    mr = {
        "nav": {
            "overview": "आढावा",
            "access_identity": "प्रवेश आणि ओळख",
            "stakeholder_ecosystem": "भागधारक परिसंस्था",
            "operations_ai": "ऑपरेशन्स आणि एआय",
            "infra_observability": "पायाभूत सुविधा आणि वेधशाळा",
            "field_activities": "फील्ड उपक्रम आणि मदत",
            "community_workforce": "समुदाय आणि कार्यबल",
            "governance_comms": "प्रशासन आणि संप्रेषण",
            "csr_investment": "सीएसआर आणि भांडवल वाटप",
            "collaboration_rd": "सहकार्य आणि संशोधन",
            "student_portal": "विद्यार्थी पोर्टल",
            "faculty_portal": "प्राध्यापक पोर्टल",
            "dashboard": "डॅशबोर्ड",
            "my_issues": "माझ्या तक्रारी",
            "report_problem": "तक्रार नोंदवा",
            "track_issues": "निकालाचा मागोवा घ्या",
            "notifications": "सूचना",
            "profile": "प्रोफाइल",
            "settings": "सेटिंग्ज",
            "help": "मदत आणि सहाय्य",
            "logout": "लॉग आउट",
            "login": "लॉग इन",
            "analytics": "विश्लेषण आणि अहवाल",
            "assigned_cases": "सोपवलेली प्रकरणे",
            "departments": "विभाग",
            "officers": "अधिकारी निर्देशिका",
            "ai_suggestions": "एआय सूचना",
            "reports": "अहवाल आणि लेखापरीक्षण",
            "projects": "उपलब्ध प्रकल्प",
            "funding": "निधीच्या संधी",
            "csr_analytics": "सीएसआर विश्लेषण",
            "mentorship": "मार्गदर्शन",
            "university_collaboration": "विद्यापीठ सहकार्य",
            "research": "संशोधन उपक्रम",
            "prototypes": "प्रोटोटाइप आणि प्रात्यक्षिके",
            "volunteers": "स्वयंसेवक पथके",
            "field_log": "फील्ड पुरावा नोंद",
            "impact": "सामुदायिक प्रभाव",
            "certificates": "प्रमाणपत्रे आणि बॅज",
            "lab_tasks": "लॅब कार्ये",
            "upload_deliverables": "सादरणीय घटक अपलोड करा",
            "milestone_timeline": "टप्पा टाइमलाइन",
            "advisor_discussion": "सल्लागार चर्चा",
            "milestone_approvals": "टप्पा मंजुरी",
            "municipal_proposals": "महानगरपालिका प्रस्ताव",
            "teams": "संघ आणि रोस्टर",
            "credits": "शैक्षणिक क्रेडिट्स",
            "user_management": "वापरकर्ता व्यवस्थापन",
            "role_management": "भूमिका व्यवस्थापन",
            "government_management": "सरकारी व्यवस्थापन",
            "university_management": "विद्यापीठ व्यवस्थापन",
            "industry_management": "उद्योग व्यवस्थापन",
            "ngo_management": "एनजीओ व्यवस्थापन",
            "research_organizations": "संशोधन संस्था",
            "issue_management": "तक्रार व्यवस्थापन",
            "ai_monitoring": "एआय टेलिमेट्री देखरेख",
            "workflow_monitoring": "कार्यप्रवाह देखरेख",
            "audit_logs": "अपरिवर्तनीय ऑडिट ट्रेल",
            "system_health": "प्रणाली आरोग्य",
            "landing_features": "वैशिष्ट्ये",
            "landing_how_it_works": "हे कसे कार्य करते",
            "landing_about": "आमच्याबद्दल",
            "landing_faq": "नेहमी विचारले जाणारे प्रश्न",
            "landing_contact": "संपर्क",
            "role_login": "भूमिका लॉगिन",
            "citizen_sign_up": "नागरिक नोंदणी"
        },
        "common": {
            "buttons": {
                "browseFiles": "फायली ब्राउझ करा",
                "openCamera": "कॅमेरा उघडा",
                "startRecording": "रेकॉर्डिंग सुरू करा",
                "stopRecording": "रेकॉर्डिंग थांबवा",
                "submit": "सबमिट करा",
                "cancel": "रद्द करा",
                "save": "बदल जतन करा",
                "delete": "हटवा",
                "search": "शोधा",
                "filter": "फिल्टर",
                "upload": "अपलोड करा",
                "confirm": "पुष्टी करा",
                "close": "बंद करा",
                "back": "मागे",
                "next": "पुढे",
                "previous": "मागील",
                "detectLocation": "वर्तमान स्थान शोधा",
                "useCurrentGps": "वर्तमान GPS वापरा",
                "resetForm": "फॉर्म रीसेट करा",
                "submitIssue": "तक्रार नोंदवा",
                "viewAll": "सर्व पहा",
                "export": "डेटा निर्यात करा",
                "download": "डाउनलोड",
                "refresh": "रिफ्रेश करा",
                "login": "लॉग इन",
                "logout": "लॉग आउट",
                "modifyUploads": "अपलोड सुधारित करा",
                "removeFile": "फाइल काढा",
                "removeVoiceMemo": "व्हॉइस मेमो काढा",
                "edit": "संपादित करा",
                "view": "तपशील पहा",
                "add": "नवीन जोडा",
                "create": "तयार करा",
                "update": "अपडेट करा",
                "approve": "मंजूर करा",
                "reject": "नाकारा",
                "reassign": "पुन्हा सोपवा",
                "escalate": "प्रकरण वाढवा",
                "resolve": "प्रकरण सोडवा",
                "assign": "सोपवा",
                "verify": "पडताळणी करा",
                "downloadReport": "अहवाल डाउनलोड करा",
                "syncTelemetry": "टेलिमेट्री सिंक करा",
                "applyFilters": "फिल्टर लागू करा",
                "clearFilters": "फिल्टर साफ करा",
                "viewDetails": "तपशील पहा",
                "sendNotification": "सूचना पाठवा",
                "inviteMember": "सदस्याला आमंत्रित करा",
                "print": "प्रिंट करा",
                "share": "शेअर करा",
                "copyLink": "लिंक कॉपी करा",
                "proceed": "पुढे जा",
                "retry": "पुन्हा प्रयत्न करा",
                "dismiss": "काढून टाका",
                "accept": "स्वीकारा",
                "decline": "नाकारा"
            },
            "labels": {
                "dashboard": "डॅशबोर्ड",
                "profile": "प्रोफाइल",
                "settings": "सेटिंग्ज",
                "notifications": "सूचना",
                "help": "मदत आणि सहाय्य",
                "logout": "लॉग आउट",
                "login": "लॉग इन",
                "status": "स्थिती",
                "priority": "प्राधान्य",
                "department": "विभाग",
                "category": "वर्गवारी",
                "district": "जिल्हा",
                "ward": "प्रभाग",
                "address": "पत्ता",
                "landmark": "महत्त्वाचे ठिकाण",
                "title": "शीर्षक",
                "description": "वर्णन",
                "attachments": "संलग्न फाइल्स",
                "voiceMemo": "व्हॉइस मेमो",
                "date": "दिनांक",
                "time": "वेळ",
                "assignedTo": "सोपवले गेलेले",
                "reportedBy": "नोंदणीकर्ता",
                "contactNumber": "संपर्क क्रमांक",
                "email": "ईमेल पत्ता",
                "name": "पूर्ण नाव",
                "role": "भूमिका",
                "actions": "कृती",
                "search": "शोधा",
                "filter": "फिल्टर",
                "total": "एकूण",
                "active": "सक्रिय",
                "completed": "पूर्ण झालेले",
                "pending": "प्रलंबित",
                "resolved": "निराकरण झालेले",
                "rejected": "नाकारलेले",
                "approved": "मंजूर केलेले",
                "high": "उच्च",
                "medium": "मध्यम",
                "low": "कमी",
                "critical": "गंभीर",
                "emergency": "तातडीचे",
                "details": "तपशील",
                "timeline": "टाइमलाइन",
                "comments": "टिप्पण्या",
                "feedback": "अभिप्राय",
                "rating": "रेटिंग",
                "sla": "SLA मर्यादा",
                "resolutionTime": "निराकरण वेळ",
                "confidence": "एआय विश्वासार्हता",
                "similarity": "समानता निर्देशांक",
                "location": "स्थान",
                "coordinates": "GPS निर्देशांक",
                "wardNumber": "प्रभाग क्रमांक",
                "zone": "महानगरपालिका झोन",
                "createdAt": "नोंदणी दिनांक",
                "updatedAt": "अद्यतन दिनांक",
                "resolvedAt": "निराकरण दिनांक",
                "closedAt": "बंद दिनांक",
                "budget": "मंजूर अंदाजपत्रक",
                "expenditure": "झालेला खर्च",
                "milestone": "प्रकल्प टप्पा",
                "deliverable": "सादरणीय घटक",
                "team": "कार्य पथक",
                "members": "सदस्य संख्या",
                "organization": "संस्था",
                "institution": "शैक्षणिक संस्था"
            },
            "status": {
                "pending": "प्रलंबित",
                "submitted": "नोंदणी झाली",
                "acknowledged": "स्वीकारले",
                "in_progress": "प्रगतीपथावर",
                "under_review": "पुनरावलोकन सुरू",
                "assigned": "सोपवले",
                "assigned_to_dept": "विभागाला सोपवले",
                "assigned_to_officer": "अधिकाऱ्याला सोपवले",
                "assigned_to_industry": "उद्योगाला सोपवले",
                "assigned_to_university": "विद्यापीठाला सोपवले",
                "assigned_to_ngo": "एनजीओकडे सोपवले",
                "student_development": "विद्यार्थी विकास कार्य",
                "faculty_review": "प्राध्यापक पुनरावलोकन",
                "industry_validation": "उद्योग प्रमाणीकरण",
                "govt_inspection": "सरकारी स्थळ पाहणी",
                "resolved": "निराकरण झाले",
                "closed": "बंद केले",
                "rejected": "नाकारले",
                "escalated": "वरिष्ठांकडे पाठवले",
                "reopened": "पुन्हा उघडले",
                "verified": "पडताळणी झाली",
                "action_taken": "कारवाई पूर्ण",
                "citizen_feedback_pending": "नागरिक अभिप्राय प्रलंबित",
                "active": "सक्रिय",
                "completed": "पूर्ण झाले",
                "cancelled": "रद्द झाले",
                "on_hold": "स्थगित"
            },
            "priority": {
                "emergency": "तातडीचे / आणीबाणी",
                "critical": "गंभीर",
                "high": "उच्च प्राधान्य",
                "medium": "मध्यम प्राधान्य",
                "low": "कमी प्राधान्य",
                "routine": "नेहमीचे"
            },
            "departments": {
                "roads": "रस्ते आणि पायाभूत सुविधा",
                "sanitation": "घनकचरा आणि स्वच्छता",
                "water": "पाणी पुरवठा आणि जलनिस्सारण",
                "electricity": "विद्युत आणि पथदिवे",
                "health": "सार्वजनिक आरोग्य आणि पर्यावरण",
                "transport": "वाहतूक आणि नगर नियोजन",
                "education": "शिक्षण आणि कौशल्य",
                "police": "नागरी सुरक्षा आणि सुव्यवस्था",
                "fire": "अग्निशामक आणि आपत्ती व्यवस्थापन",
                "revenue": "महसूल आणि मालमत्ता कर",
                "general": "सामान्य प्रशासन"
            },
            "categories": {
                "pothole": "खड्डे आणि रस्ते दुरुस्ती",
                "garbage": "कचरा आणि घाणीचे साम्राज्य",
                "drainage": "तुंबलेली गटारे आणि सांडपाणी",
                "streetlight": "बंद पथदिवे आणि वीज पुरवठा",
                "water_leakage": "पाण्याची गळती आणि तुटवडा",
                "illegal_construction": "अनधिकृत बांधकाम",
                "tree_fall": "झाडांची पडझड आणि अडथळा",
                "stray_animals": "भटके प्राणी आणि उपद्रव",
                "air_pollution": "हवा आणि धूळ प्रदूषण",
                "noise_pollution": "ध्वनी प्रदूषण",
                "traffic_congestion": "वाहतूक कोंडी",
                "other": "इतर नागरी समस्या"
            },
            "validation": {
                "required": "हे फील्ड आवश्यक आहे",
                "minLength": "किमान आवश्यक लांबी पूर्ण करा",
                "maxLength": "कमाल अक्षरांची मर्यादा ओलांडली",
                "invalidEmail": "कृपया वैध ईमेल पत्ता प्रविष्ट करा",
                "invalidPhone": "कृपया १० अंकी वैध मोबाइल क्रमांक टाका",
                "invalidCoordinates": "अवैध भौगोलिक निर्देशांक",
                "fileTooLarge": "फाइलचा आकार २५MB पेक्षा जास्त असू नये",
                "unsupportedFormat": "फाइल फॉरमॅट समर्थित नाही",
                "passwordMismatch": "पासवर्ड जुळत नाहीत",
                "weakPassword": "पासवर्ड अधिक सुरक्षित असावा",
                "uploadFailed": "फाइल अपलोड अयशस्वी",
                "uploadSuccessful": "फाइल यशस्वीरित्या अपलोड केली",
                "loginSuccessful": "लॉग इन यशस्वी झाले",
                "registrationSuccessful": "नोंदणी यशस्वी झाली",
                "submissionFailed": "सबमिशन अयशस्वी झाले, पुन्हा प्रयत्न करा",
                "sessionExpired": "सत्र संपले आहे, कृपया पुन्हा लॉग इन करा",
                "accessDenied": "प्रवेश नाकारला",
                "networkError": "नेटवर्क त्रुटी, कृपया इंटरनेट तपासा",
                "serverError": "सर्व्हर त्रुटी आली, कृपया नंतर प्रयत्न करा"
            },
            "emptyStates": {
                "noIssues": "कोणतीही तक्रार आढळली नाही",
                "noNotifications": "कोणतीही नवीन सूचना नाही",
                "noProjects": "कोणतेही सक्रिय प्रकल्प उपलब्ध नाहीत",
                "noCases": "सोपवलेली प्रकरणे नाहीत",
                "noOfficers": "अधिकारी उपलब्ध नाहीत",
                "noResults": "शोध परिणामांमध्ये काहीही आढळले नाही",
                "noActivity": "कोणतीही अलीकडील हालचाल नोंदवली नाही"
            },
            "loading": {
                "default": "लोड होत आहे...",
                "submitting": "तक्रार सबमिट होत आहे...",
                "uploading": "फायली अपलोड होत आहेत...",
                "fetching": "माहिती मिळवत आहे...",
                "verifying": "एआय पडताळणी सुरू आहे...",
                "routing": "विभागाला प्रेषित करत आहे...",
                "saving": "बदल जतन केले जात आहेत..."
            },
            "pagination": {
                "previous": "मागील",
                "next": "पुढील",
                "first": "पहिले",
                "last": "शेवटचे",
                "page": "पृष्ठ",
                "of": "पैकी",
                "showing": "दर्शवित आहे",
                "results": "परिणाम"
            },
            "search": {
                "placeholder": "तक्रारी, विभाग किंवा स्थान शोधा...",
                "clear": "शोध साफ करा",
                "filterBy": "फिल्टर लावा",
                "sortBy": "क्रमवारी लावा",
                "newest": "नवीनतम",
                "oldest": "सर्वात जुने",
                "priority": "सर्वोच्च प्राधान्य",
                "status": "स्थितीनुसार"
            }
        },
        "ai": {
            "processing": "एआय विश्लेषण सुरू आहे",
            "ocrResult": "ओसीआर द्वारे काढलेला मजकूर",
            "speechResult": "स्थानिक व्हॉइस ट्रान्सक्रिप्ट",
            "speechTranscript": "ध्वनी ट्रान्सक्रिप्ट",
            "confidenceScore": "एआय विश्वासार्हता निर्देशांक",
            "aiConfidence": "एआय विश्वासार्हता",
            "suggestedCategory": "सुचवलेली वर्गवारी",
            "suggestedDepartment": "सुचवलेला विभाग",
            "recommendedDepartment": "शिफारस केलेला विभाग",
            "suggestedIndustry": "सुचवलेला उद्योग भागीदार",
            "duplicateDetection": "समान तक्रार तपासणी",
            "aiVerification": "मल्टीमॉडल व्हिजन पडताळणी",
            "smartRouting": "स्मार्ट विभागीय रूटिंग",
            "previewTitle": "मल्टीमॉडल एआय माहिती पूर्वावलोकन",
            "previewSubtitle": "संगणक दृष्टी आणि ध्वनी प्रणालीने खालील माहिती काढली आहे. सबमिट करण्यापूर्वी तपासा.",
            "detectedHeadline": "ओळखलेले तक्रार शीर्षक",
            "classifiedCategory": "एआय वर्गीकृत वर्गवारी",
            "dispatchedDept": "वाटप केलेला महानगरपालिका विभाग",
            "severityPriority": "तीव्रता आणि प्राधान्यक्रम",
            "mappedLocation": "नकाशावरील अचूक स्थान",
            "confirmSubmit": "तपासणी पुष्टी करा आणि तक्रार पाठवा",
            "cancel": "रद्द करा",
            "ocrBadge": "FastAPI ओसीआर निष्कर्ष",
            "sttBadge": "व्हॉइस ट्रान्सक्रिप्ट तयार",
            "verificationStep": "नागरिक पडताळणी टप्पा",
            "verificationStepHelp": "१००% अचूकतेसाठी आपण सबमिट करण्यापूर्वी खालील फील्ड्स संपादित करू शकता.",
            "ocrVision": "ओसीआर व्हिजन निष्कर्ष",
            "noOcrText": "पाटीवर कोणताही मजकूर आढळला नाही",
            "noAudioMemo": "कोणताही ऑडिओ मेमो जोडलेला नाही",
            "priorityScore": "गणित केलेले प्राधान्य गुण",
            "estimatedCost": "अंदाजे दुरुस्ती खर्च",
            "estimatedTime": "अंदाजे निराकरण वेळ",
            "recommendation": "एआय प्रशासन शिफारस",
            "confidenceHigh": "उच्च विश्वासार्हता (>९०%)",
            "confidenceMedium": "मध्यम विश्वासार्हता (७०-९०%)",
            "confidenceLow": "कमी विश्वासार्हता (<७०%)",
            "duplicateFound": "संभाव्य समान तक्रार आढळली",
            "duplicateScore": "समानता गुण"
        },
        "citizen": {
            "portalTitle": "नागरिक सेवा आणि तक्रार पोर्टल",
            "dashboard": {
                "title": "नागरिक डॅशबोर्ड",
                "welcome": "आपले स्वागत आहे",
                "quickReport": "तातडीची तक्रार नोंदवा",
                "trackGrievances": "तक्रारींचा मागोवा घ्या",
                "statsTotal": "एकूण नोंदवलेल्या तक्रारी",
                "statsResolved": "निराकरण झालेल्या तक्रारी",
                "statsPending": "सध्या प्रलंबित",
                "statsActive": "कारवाई सुरू असलेल्या",
                "recentGrievances": "माझ्या अलीकडील तक्रारी",
                "emergencyNotice": "तातडीच्या आपत्कालीन मदतीसाठी हेल्पलाइन १०१/१०८ वर संपर्क साधा.",
                "viewAll": "सर्व तक्रारी पहा",
                "filterStatus": "स्थितीनुसार फिल्टर",
                "exploreFeed": "नागरी समस्या फीड",
                "trendingIssues": "परिसरातील मुख्य समस्या",
                "communityImpact": "सामुदायिक प्रभाव",
                "civicScore": "नागरिक सहभाग गुण"
            },
            "report": {
                "title": "नवीन नागरी तक्रार नोंदवा",
                "subtitle": "फोटो, ऑडिओ आणि अचूक GPS सह समस्या नोंदवा. एआय प्रणाली तात्काळ योग्य विभागाकडे पाठवेल.",
                "stepMedia": "१. फोटो किंवा ऑडिओ पुरावा जोडा",
                "stepDetails": "२. समस्येचा तपशील",
                "stepLocation": "३. अचूक भौगोलिक स्थान",
                "stepReview": "४. एआय पडताळणी आणि सबमिशन",
                "mediaPrompt": "समस्येचा स्पष्ट फोटो अपलोड करा किंवा कॅमेऱ्याने थेट फोटो काढा",
                "voicePrompt": "किंवा आपली समस्या स्थानिक भाषेत बोलून रेकॉर्ड करा",
                "titleLabel": "तक्रारीचे संक्षिप्त शीर्षक",
                "titlePlaceholder": "उदा. मुख्य रस्त्यावर पडलेला मोठा धोकादायक खड्डा",
                "categoryLabel": "समस्येची वर्गवारी",
                "categorySelect": "वर्गवारी निवडा",
                "deptLabel": "संबंधित विभाग (पर्यायी - एआय स्वयं निवडेल)",
                "deptSelect": "विभाग निवडा",
                "descLabel": "सविस्तर वर्णन",
                "descPlaceholder": "समस्येचे अचूक स्वरूप, वाहतुकीस होणारा अडथळा व धोके विशद करा...",
                "landmarkLabel": "जवळचे महत्त्वाचे ठिकाण",
                "landmarkPlaceholder": "उदा. शासकीय रुग्णालयाजवळ, बस स्थानकासमोर",
                "addressLabel": "पत्ता किंवा रस्ता",
                "addressPlaceholder": "रस्त्याचे नाव, वॉर्ड क्रमांक...",
                "useGps": "माझे चालू GPS स्थान वापरा",
                "gpsLocked": "GPS स्थान निश्चित केले गेले",
                "dragPin": "नकाशावर अचूक पिन ठेवा",
                "aiNotice": "आमची प्रगत एआय प्रणाली फोटोतील बोर्ड्स वाचून आणि समस्येचे वर्गीकरण करून थेट संबंधित अधिकाऱ्याला पाठवते.",
                "submitBtn": "तक्रार अधिकृतपणे नोंदवा",
                "submitting": "तक्रार नोंदवली जात आहे...",
                "cancel": "रद्द करा",
                "retake": "पुन्हा फोटो काढा",
                "recordVoice": "व्हॉइस मेमो रेकॉर्ड करा",
                "stopVoice": "रेकॉर्डिंग पूर्ण करा",
                "voiceRecorded": "व्हॉइस मेमो यशस्वीरित्या रेकॉर्ड झाला",
                "uploadSuccess": "पुरावा यशस्वीरित्या जोडला",
                "maxFiles": "कमाल ३ फायली अपलोड केल्या जाऊ शकतात",
                "allowedTypes": "फक्त JPG, PNG, MP4, MP3 फॉरमॅट स्वीकारले जातील",
                "anonymous": "तक्रार निनावी म्हणून नोंदवा",
                "anonymousHelp": "आपली वैयक्तिक ओळख सार्वजनिकरीत्या प्रदर्शित केली जाणार नाही."
            },
            "track": {
                "title": "तक्रार निवारण ट्रॅकर",
                "subtitle": "नोंदवलेल्या तक्रारीची सद्यस्थिती, नियुक्त अधिकारी आणि कारवाईचा थेट मागोवा घ्या.",
                "timeline": "निराकरण टाइमलाइन",
                "currentStatus": "सद्यस्थिती",
                "assignedOfficer": "नियुक्त नोडल अधिकारी",
                "estimatedDate": "अंदाजे निराकरण दिनांक",
                "evidenceUploaded": "कारवाईचे छायाचित्र पुरावे",
                "feedbackPrompt": "समस्या सुटली असल्यास आपला अभिप्राय नोंदवा",
                "rateResolution": "निराकरणाची गुणवत्ता रेट करा",
                "reopenIssue": "समस्या न सुटल्यास पुन्हा उघडा",
                "escalateIssue": "विलंब झाल्यास वरिष्ठांकडे तक्रार वाढवा",
                "downloadDocket": "अधिकृत पावती डाउनलोड करा"
            },
            "profile": {
                "title": "नागरिक प्रोफाइल आणि ओळख",
                "name": "पूर्ण नाव",
                "phone": "नोंदणीकृत मोबाइल क्रमांक",
                "email": "ईमेल पत्ता",
                "ward": "माझा प्रभाग / वॉर्ड",
                "address": "निवासी पत्ता",
                "languagePreference": "पसंतीची भाषा",
                "saveChanges": "माहिती जतन करा",
                "notificationSettings": "सूचना प्राधान्ये"
            },
            "settings": {
                "title": "खाते आणि सुरक्षा सेटिंग्ज",
                "language": "अनुप्रयोग भाषा",
                "notifications": "एसएमएस आणि व्हॉट्सॲप सूचना",
                "privacy": "गोपनीयता नियंत्रणे",
                "darkMode": "गडद थीम (डार्क मोड)",
                "deleteAccount": "खाते हटवण्याची विनंती",
                "helpCenter": "नागरी मदत केंद्र"
            }
        },
        "government": {
            "portalTitle": "महानगरपालिका प्रशासन आणि नियंत्रण केंद्र",
            "dashboard": {
                "title": "प्रशासकीय नियंत्रण कक्ष",
                "liveCases": "थेट सक्रिय प्रकरणे",
                "criticalAlerts": "तातडीचे धोके आणि इशारे",
                "slaBreaches": "SLA मर्यादा ओलांडलेली प्रकरणे",
                "avgResolutionTime": "सरासरी निराकरण कालावधी",
                "departmentPerformance": "विभागीय कार्यक्षमता",
                "wardHeatmap": "प्रभागनिहाय तक्रार घनता नकाशा",
                "officerWorkload": "अधिकारी कार्यभार निर्देशांक",
                "aiTriagedToday": "आज एआय द्वारे प्रेषित प्रकरणे",
                "exportReports": "दैनिक अहवाल निर्यात",
                "filterByWard": "प्रभाग निवडा",
                "filterByDept": "विभाग निवडा",
                "recentDockets": "नवीनतम तक्रार डॉकेट्स",
                "citizenSatisfaction": "नागरिक समाधान निर्देशांक",
                "totalBudgetUsed": "खर्च झालेला नागरी निधी",
                "unassignedCases": "सोपवणे बाकी असलेली प्रकरणे",
                "actionCenter": "त्वरित कृती केंद्र"
            },
            "officers": {
                "title": "क्षेत्रीय अधिकारी निर्देशिका",
                "addOfficer": "नवीन अधिकारी जोडा",
                "name": "अधिकाऱ्याचे नाव",
                "designation": "पदनाम",
                "department": "विभाग",
                "assignedWard": "सोपवलेला प्रभाग",
                "activeCases": "सक्रिय प्रकरणांची संख्या",
                "solvedCases": "सोडवलेली प्रकरणे",
                "rating": "कार्यक्षमता रेटिंग",
                "contact": "संपर्क तपशील",
                "status": "उपलब्धता स्थिती",
                "reassignLoad": "कार्यभार पुनर्संतुलन"
            },
            "departments": {
                "title": "महानगरपालिका विभाग व्यवस्थापन",
                "name": "विभागाचे नाव",
                "head": "विभागीय प्रमुख",
                "slaTarget": "लक्ष्यित निराकरण वेळ",
                "activeStaff": "कार्यरत कर्मचारी",
                "budgetAllocated": "मंजूर वार्षिक तरतूद",
                "escalationMatrix": "वाढवण्याचा पदानुक्रम",
                "autoAssignRule": "स्वयंचलित वाटप नियम",
                "totalGrievances": "एकूण प्राप्त तक्रारी",
                "resolvedPercentage": "निराकरण टक्केवारी",
                "performanceScore": "एकूण गुणवत्ता गुण"
            },
            "assigned": {
                "title": "मला सोपवलेली नागरी प्रकरणे",
                "caseId": "डॉकेट क्रमांक",
                "reportedTime": "प्राप्त वेळ",
                "ward": "प्रभाग",
                "severity": "तीव्रता",
                "status": "स्थिती",
                "actionPlan": "कृती योजना",
                "updateStatus": "स्थिती बदला",
                "uploadResolutionProof": "स्थळ पाहणी व दुरुस्ती पुरावा जोडा",
                "dispatchWorkforce": "कर्मचारी पथक पाठवा",
                "requestBudget": "विशेष दुरुस्ती निधी मागणी",
                "forwardToIndustry": "उद्योगाला सहकार्यासाठी पाठवा",
                "forwardToUniversity": "तांत्रिक संशोधनासाठी पाठवा",
                "markResolved": "प्रकरण सोडवले म्हणून नोंदवा",
                "internalNotes": "विभागीय अंतर्गत नोंद"
            },
            "tracking": {
                "title": "शहरव्यापी प्रकरणांचा थेट मागोवा",
                "gisView": "भौगोलिक नकाशा दृश्य",
                "slaMonitor": "SLA उल्लंघन देखरेख",
                "citizenEscalations": "नागरिकांनी वाढवलेली प्रकरणे",
                "repeatIssues": "वारंवार उद्भवणाऱ्या समस्यांची क्लस्टर्स"
            },
            "aiSuggestions": {
                "title": "एआय प्रगत प्रशासकीय विश्लेषण आणि सूचना",
                "predictedHotspots": "संभाव्य समस्या प्रवण क्षेत्रे",
                "optimalRoute": "कचरा संकलन आणि दुरुस्तीचा सर्वोत्तम मार्ग",
                "costOptimization": "खर्च बचतीचे मार्ग",
                "contractorScore": "कंत्राटदार गुणवत्ता मूल्यांकन",
                "duplicateClusters": "एकत्रित करता येणाऱ्या तक्रारींचे गट"
            },
            "reports": {
                "title": "ऑडिट आणि कामगिरी अहवाल",
                "monthlyAudit": "मासिक नागरी सेवा ऑडिट",
                "wardComparison": "प्रभागनिहाय तुलनात्मक अहवाल",
                "budgetUtilization": "निधी विनियोग अहवाल",
                "slaComplianceReport": "SLA अनुपालन दर",
                "downloadPdf": "PDF स्वरूपात डाउनलोड करा",
                "downloadExcel": "Excel स्प्रेडशीट डाउनलोड करा"
            },
            "settings": {
                "title": "विभागीय नियंत्रण कक्ष सेटिंग्ज",
                "autoDispatch": "एआय थेट वाटप सक्रिय करा",
                "escalationThreshold": "SLA पूर्वसूचना कालावधी",
                "smsNotifications": "अधिकारी एसएमएस सूचना",
                "publicFeedModeration": "नागरी फीड मॉडरेशन नियंत्रणे"
            }
        },
        "industry": {
            "portalTitle": "उद्योग आणि कॉर्पोरेट सीएसआर पोर्टल",
            "dashboard": {
                "title": "उद्योग सीएसआर आणि नवोन्मेष डॅशबोर्ड",
                "fundedProjects": "निधी पुरवलेले प्रकल्प",
                "totalCsrCommitted": "एकूण वचनबद्ध सीएसआर निधी",
                "impactLives": "लाभार्थी नागरिकांची संख्या",
                "activeRnD": "सक्रिय संशोधन आणि विकास सहयोग",
                "pendingProposals": "मंजुरी प्रलंबित प्रस्ताव",
                "sustainabilityScore": "शाश्वतता आणि ESG गुण",
                "recentInitiatives": "अलीकडील सीएसआर उपक्रम",
                "universityPartnerships": "विद्यापीठ भागीदारी",
                "verifiedImpact": "पडताळलेला नागरी प्रभाव",
                "taxExemptionStatus": "कलम ८०जी कर सवलत प्रमाणपत्रे",
                "disbursedFunds": "वितरित झालेला निधी",
                "rfpOpen": "सध्या सुरू असलेल्या निविदा (RFP)",
                "kpiMetrics": "सीएसआर प्रभाव निर्देशांक"
            },
            "projects": {
                "title": "शाश्वत नागरी प्रकल्प",
                "adoptCivicIssue": "नागरी समस्या दत्तक घ्या",
                "projectScope": "प्रकल्पाची व्याप्ती आणि उद्दिष्ट",
                "estimatedBudget": "अंदाजे भांडवली खर्च",
                "partnerInstitutes": "सहभागी तांत्रिक संस्था",
                "targetCompletion": "पूर्णत्वाचे उद्दिष्ट",
                "status": "प्रकल्प प्रगती",
                "fundProject": "या प्रकल्पाला निधी द्या",
                "viewMilestones": "टप्पे आणि अहवाल पहा"
            },
            "funding": {
                "title": "सीएसआर अनुदान आणि वाटप व्यवस्थापन",
                "grantAllocation": "अनुदान वाटप",
                "disbursementSchedule": "टप्पानिहाय वितरण वेळापत्रक",
                "utilizationCertificates": "निधी विनियोग प्रमाणपत्रे",
                "bankDetails": "अधिकृत बँक खाते तपशील",
                "escrowAccount": "एस्क्रो सुरक्षा खाते",
                "auditTrail": "निधी विनियोग तपासणी",
                "approveDisbursement": "पुढील हप्ता वितरित करा"
            },
            "csr": {
                "title": "कंपनी सीएसआर धोरण आणि अनुपालन",
                "mcaReporting": "कंपनी व्यवहार मंत्रालय (MCA) अनुपालन",
                "annualBudget": "वार्षिक सीएसआर अंदाजपत्रक",
                "esgAlignment": "संयुक्त राष्ट्र शाश्वत विकास उद्दिष्टे (SDG)",
                "beneficiaryData": "लाभार्थ्यांची सांख्यिकी",
                "socialAudit": "थर्ड-पार्टी सामाजिक ऑडिट"
            },
            "mentorship": {
                "title": "उद्योग तज्ज्ञ आणि विद्यार्थी मार्गदर्शन",
                "mentorsList": "कंपनी तज्ज्ञ मार्गदर्शक",
                "studentTeams": "मार्गदर्शनाखालील विद्यार्थी गट",
                "hackathons": "नागरी समस्या हॅकाथॉन",
                "sessionSchedule": "मार्गदर्शन सत्रांचे वेळापत्रक",
                "evaluatePrototype": "विद्यार्थी प्रोटोटाइप मूल्यमापन"
            },
            "collaboration": {
                "title": "महानगरपालिका आणि शैक्षणिक सहकार्य",
                "mouAgreements": "सामंजस्य करार (MoU)",
                "jointLabs": "संयुक्त नवोन्मेष प्रयोगशाळा",
                "sharedPatents": "नागरी तंत्रज्ञान पेटंट",
                "publicPrivatePartnership": "पीपीपी मॉडेल प्रकल्प",
                "resourceSharing": "साधनसामग्री आणि डेटा देवाणघेवाण"
            },
            "prototypes": {
                "title": "विद्यार्थी प्रोटोटाइप आणि प्रात्यक्षिके",
                "innovations": "सादर केलेले नागरी नवोन्मेष",
                "technologyReadiness": "तंत्रज्ञान सज्जता स्तर (TRL)",
                "pilotTesting": "शहरातील प्रत्यक्ष चाचणी",
                "commercialization": "मोठ्या प्रमाणावर निर्मिती",
                "feedback": "तांत्रिक अभिप्राय नोंदवा"
            },
            "tracking": {
                "title": "सीएसआर प्रभाव थेट ट्रॅकिंग",
                "liveGpsProgress": "कामाची थेट प्रगती",
                "geoTaggedPhotos": "जिओ-टॅग केलेली प्रगती चित्रे",
                "independentVerification": "स्वतंत्र संस्थेची पडताळणी",
                "exportCertificate": "सीएसआर पूर्णत्व प्रमाणपत्र"
            },
            "profile": {
                "title": "कंपनी आणि उद्योग प्रोफाइल",
                "cinNumber": "कंपनी नोंदणी क्रमांक (CIN)",
                "csrRegistrationNumber": "सीएसआर नोंदणी क्रमांक (CSR-1)",
                "authorizedSignatory": "अधिकृत स्वाक्षरीकर्ता",
                "headquarters": "मुख्यालय पत्ता",
                "sector": "उद्योग क्षेत्र",
                "updateProfile": "माहिती अद्ययावत करा"
            },
            "settings": {
                "title": "उद्योग पोर्टल प्राधान्ये",
                "emailReports": "साप्ताहिक प्रभाव अहवाल",
                "proposalAlerts": "नवीन प्रस्तावांच्या त्वरित सूचना",
                "taxReceiptsAuto": "कर पावती स्वयंचलित निर्मिती",
                "twoFactorAuth": "दोन-टप्प्यांची सुरक्षा (2FA)"
            }
        },
        "ngo": {
            "portalTitle": "स्वयंसेवी संस्था आणि नागरिक सहभाग पोर्टल",
            "dashboard": {
                "title": "स्वयंसेवी संस्था कार्य नियंत्रण केंद्र",
                "activeCampaigns": "सक्रिय नागरी मोहिमा",
                "registeredVolunteers": "नोंदणीकृत स्वयंसेवक",
                "groundIssuesResolved": "प्रत्यक्ष सोडवलेल्या समस्या",
                "verifiedReports": "पडताळलेले क्षेत्रीय अहवाल",
                "reliefDistribution": "मदत आणि साहित्य वाटप",
                "communityMeetings": "नागरी प्रभाग बैठका",
                "csrGrantsReceived": "मिळालेले सीएसआर अनुदान",
                "awardsBadges": "मिळालेले गौरव आणि बॅज",
                "rapidResponseSquads": "तातडीचे प्रतिसाद पथक",
                "upcomingEvents": "आगामी स्वच्छता व मदत मोहिमा",
                "impactSummary": "एकूण सामाजिक प्रभाव"
            },
            "projects": {
                "title": "समुदाय सुधारणा प्रकल्प",
                "adoptNeighborhood": "वस्ती किंवा परिसर दत्तक घ्या",
                "projectDetails": "मोहिमेचा तपशील",
                "volunteersNeeded": "आवश्यक स्वयंसेवक संख्या",
                "joinProject": "या मोहिमेत सहभागी व्हा",
                "logHours": "स्वयंसेवक कामाचे तास नोंदवा"
            },
            "assignedProjects": {
                "title": "महानगरपालिकेने दिलेले संयुक्त प्रकल्प",
                "municipalOrder": "महानगरपालिका अधिकृत आदेश",
                "designatedArea": "नियुक्त नागरी क्षेत्र",
                "workforceAllocated": "तैनात स्वयंसेवक पथक",
                "submissionDeadline": "पूर्तता मुदत",
                "status": "कामाची स्थिती"
            },
            "fieldActivities": {
                "title": "क्षेत्रीय उपक्रम आणि पुरावा नोंद",
                "logEvidence": "नवीन क्षेत्रीय पुरावा नोंदवा",
                "gpsCoordinates": "अचूक GPS स्थान",
                "photosBeforeAfter": "कामापूर्वीचे आणि नंतरचे फोटो",
                "beneficiaryCount": "उपकृत नागरिकांची संख्या",
                "localFeedback": "स्थानिक नागरिकांचे म्हणणे",
                "submitLog": "क्षेत्रीय नोंद प्रमाणित करा"
            },
            "volunteers": {
                "title": "स्वयंसेवक व्यवस्थापन आणि संघ",
                "addVolunteer": "नवीन स्वयंसेवक नोंदणी",
                "volunteerList": "सक्रिय स्वयंसेवक यादी",
                "skills": "विशेष कौशल्ये (आपत्ती/आरोग्य/बांधकाम)",
                "hoursContributed": "एकूण दिलेले तास",
                "badgeLevel": "स्वयंसेवक सन्मान स्तर",
                "deployTeam": "तातडीच्या कार्यासाठी पथक पाठवा"
            },
            "impact": {
                "title": "नागरी प्रभाव आणि परिणाम मूल्यांकन",
                "tonsGarbageCleared": "संकलित केलेला कचरा (टन)",
                "potHolesFilled": "दुरुस्त केलेले खड्डे",
                "streetlightsFixed": "सुरू केलेले पथदिवे",
                "citizensEducated": "प्रशिक्षित नागरिक संख्या",
                "socialReturnOnInvestment": "सामाजिक परतावा निर्देशांक (SROI)"
            },
            "collaborations": {
                "title": "उद्योग आणि महानगरपालिका सहकार्य",
                "jointVentures": "संयुक्त भागीदारी",
                "csrPartners": "सीएसआर देणगीदार कंपन्या",
                "municipalLiaison": "महानगरपालिका संपर्क अधिकारी",
                "signedAgreements": "सहकार्य करार"
            },
            "certificates": {
                "title": "प्रमाणपत्रे आणि स्वयंसेवक गौरव",
                "generateCertificate": "सहभाग प्रमाणपत्र तयार करा",
                "volunteerName": "स्वयंसेवकाचे नाव",
                "contributionHours": "योगदान तास",
                "downloadPdf": "प्रमाणपत्र डाउनलोड करा"
            },
            "reports": {
                "title": "मासिक क्षेत्रीय कार्य अहवाल",
                "monthlyReport": "मासिक प्रगती अहवाल",
                "financialAudit": "लेखापरीक्षण अहवाल",
                "darpanVerification": "नीती आयोग एनजीओ दर्पण प्रमाणपत्र",
                "submitToGovt": "महानगरपालिकेकडे सादर करा",
                "downloadAudit": "ऑडिट प्रत डाउनलोड करा"
            },
            "settings": {
                "title": "संस्था प्रोफाइल आणि सेटिंग्ज",
                "ngoRegistration": "संस्था नोंदणी क्रमांक",
                "fcraNumber": "FCRA नोंदणी क्रमांक (असल्यास)",
                "darpanId": "एनजीओ दर्पण आयडी",
                "bankDetails": "अधिकृत बँक खाते"
            }
        },
        "university": {
            "portalTitle": "विद्यापीठ आणि शैक्षणिक नवोन्मेष पोर्टल",
            "student": {
                "title": "विद्यार्थी संशोधन आणि विकास कक्ष",
                "assignedProblems": "सोपवलेली नागरी समस्या",
                "myDeliverables": "माझे प्रकल्प सादरीकरण",
                "academicCredits": "मिळणारे शैक्षणिक क्रेडिट्स",
                "mentorFeedback": "प्राध्यापक मार्गदर्शकाचा अभिप्राय",
                "submitMilestone": "प्रकल्पाचा टप्पा सादर करा"
            },
            "faculty": {
                "title": "प्राध्यापक आणि मार्गदर्शक नियंत्रण कक्ष",
                "reviewSubmissions": "विद्यार्थी सादरीकरण तपासा",
                "approveCredits": "शैक्षणिक क्रेडिट्स मंजूर करा",
                "assignTeams": "समस्यांचे वाटप करा",
                "municipalLiaison": "महानगरपालिका अधिकारी संवाद",
                "researchPublications": "नागरी संशोधन प्रकाशने"
            },
            "shared": {
                "title": "शैक्षणिक सहयोग आणि प्रयोगशाळा",
                "labTasks": "प्रयोगशाळा चाचणी कार्ये",
                "timeline": "प्रकल्प वेळापत्रक आणि मुदती",
                "discussion": "तांत्रिक चर्चा मंच",
                "proposals": "महानगरपालिका तांत्रिक प्रस्ताव",
                "teams": "विद्यार्थी संशोधन पथके",
                "credits": "विद्यापीठ क्रेडिट प्रणाली"
            }
        },
        "admin": {
            "portalTitle": "मध्यवर्ती प्रणाली प्रशासन आणि नियंत्रण",
            "dashboard": {
                "title": "मध्यवर्ती प्रशासन डॅशबोर्ड",
                "totalUsers": "एकूण नोंदणीकृत वापरकर्ते",
                "activeIncidents": "शहरभरातील एकूण समस्या",
                "aiAccuracy": "एआय प्रेषण अचूकता",
                "systemHealth": "प्रणाली आरोग्य स्थिती",
                "databaseLoad": "डेटाबेस कार्यभार",
                "registeredEntities": "नोंदणीकृत संस्था",
                "crossPortalActivity": "क्रॉस-पोर्टल थेट वापर",
                "telemetryFeed": "थेट टेलिमेट्री फीड",
                "globalSecurity": "सुरक्षा आणि ऑडिट स्थिती",
                "backupStatus": "डेटा बॅकअप स्थिती",
                "quickActions": "प्रशासकीय कृती केंद्र"
            },
            "users": {
                "title": "प्लॅटफॉर्म वापरकर्ता व्यवस्थापन",
                "addUser": "नवीन वापरकर्ता जोडा",
                "userList": "वापरकर्त्यांची यादी",
                "role": "भूमिका",
                "status": "स्थिती",
                "lastLogin": "शेवटचा लॉगिन",
                "actions": "नियंत्रण कृती",
                "suspendUser": "वापरकर्ता निलंबित करा"
            },
            "roles": {
                "title": "भूमिका आणि अधिकार नियंत्रण (RBAC)",
                "manageRoles": "भूमिका व्यवस्थापन",
                "permissions": "अधिकार संच",
                "createRole": "नवीन भूमिका तयार करा",
                "auditAccess": "प्रवेश तपासणी लॉग"
            },
            "government": {
                "title": "महानगरपालिका संस्था व्यवस्थापन",
                "municipalities": "नोंदणीकृत महानगरपालिका",
                "commissionerDesk": "आयुक्त नियंत्रण कक्ष",
                "departmentHierarchy": "विभागीय पदानुक्रम"
            },
            "universities": {
                "title": "विद्यापीठ आणि शैक्षणिक संस्था",
                "accreditedUnis": "मान्यताप्राप्त विद्यापीठे",
                "aiCTECheck": "एआयसीटीई / यूजीसी पडताळणी",
                "studentRoster": "विद्यार्थी नोंदणी मास्टर"
            },
            "industry": {
                "title": "उद्योग आणि कॉर्पोरेट संस्था",
                "registeredCorporates": "नोंदणीकृत कंपन्या",
                "csrVerified": "सीएसआर मान्यता प्राप्त",
                "mcaSync": "कंपनी व्यवहार मंत्रालय सिंक"
            },
            "ngos": {
                "title": "स्वयंसेवी संस्था आणि ट्रस्ट",
                "verifiedNgos": "मान्यताप्राप्त स्वयंसेवी संस्था",
                "darpanCheck": "एनजीओ दर्पण पडताळणी",
                "groundClearance": "क्षेत्रीय कार्य परवानगी"
            },
            "research": {
                "title": "संशोधन संस्था आणि प्रयोगशाळा",
                "institutePartnerships": "संशोधन भागीदार संस्था",
                "ethicsClearance": "नैतिकता समिती मान्यता",
                "datasetAccess": "नागरी डेटा ॲक्सेस परवानग्या"
            },
            "departments": {
                "title": "विभाग मास्टर आणि रूटिंग नियम",
                "routingRules": "स्वयंचलित रूटिंग नियम",
                "autoAssignmentEngine": "एआय प्रेषण इंजिन",
                "fallbackQueues": "पर्यायी कतार"
            },
            "issues": {
                "title": "प्लॅटफॉर्म तक्रार मास्टर",
                "forceResolve": "प्रशासकीय निराकरण",
                "reassignCluster": "तक्रार गट पुन्हा सोपवा",
                "auditLog": "अपरिवर्तनीय कृती लॉग",
                "purgeTestData": "चाचणी डेटा काढून टाका"
            },
            "aiMonitoring": {
                "title": "एआय व्हिजन आणि टेलिमेट्री देखरेख",
                "geminiVisionUptime": "व्हिजन मॉडेल अपटाइम",
                "fastApiOcrStatus": "FastAPI ओसीआर पाइपलाइन",
                "speechToTextLatency": "ध्वनी ट्रान्सक्रिप्शन विलंबता",
                "accuracyScore": "वर्गीकरण अचूकता गुण",
                "confidenceDistribution": "विश्वासार्हता वितरण",
                "modelLogs": "अनुमान विलंबता लॉग"
            },
            "workflowMonitoring": {
                "title": "कार्यप्रवाह इंजिन आणि कतार टेलिमेट्री",
                "stateMachineInspect": "स्टेट मशीन संक्रमण",
                "queueDepth": "संदेश कतार खोली",
                "deadLetterQueue": "डेड-लेटर कतार",
                "retryFailedTasks": "अयशस्वी कार्ये पुन्हा सुरू करा"
            },
            "analytics": {
                "title": "क्रॉस-प्लॅटफॉर्म मॅक्रो विश्लेषण",
                "crossPortalActivity": "क्रॉस-पोर्टल वापर मेट्रिक्स",
                "municipalPerformanceIndex": "महानगरपालिका कामगिरी निर्देशांक",
                "peakUsageHours": "सर्वोच्च वापराचे तास"
            },
            "systemHealth": {
                "title": "पायाभूत सुविधा आणि प्रणाली आरोग्य",
                "databaseReplicas": "डेटाबेस प्रतिकृती",
                "redisCache": "रेडिस इन-मेमरी स्थिती",
                "storageUsage": "ऑब्जेक्ट स्टोरेज वापर",
                "apiGateways": "मायक्रोसर्व्हिस आरोग्य",
                "uptime99": "९९.९८% उच्च उपलब्धता",
                "online": "ऑनलाइन",
                "maintenance": "देखभाल सुरू"
            },
            "settings": {
                "title": "प्लॅटफॉर्म कॉन्फिगरेशन सेटिंग्ज",
                "maintenanceMode": "देखभाल मोड",
                "apiRateLimits": "एपीआई मर्यादा",
                "backupSchedules": "स्वयंचलित बॅकअप वेळापत्रक",
                "smtpConfig": "ईमेल आणि एसएमएस गेटवे"
            }
        },
        "toast": {
            "issueSubmitted": "तक्रार यशस्वीरित्या नोंदवली गेली! संबंधित विभागाकडे पाठवली आहे.",
            "gpsCaptured": "जीपीएस निर्देशांक मिळवले गेले",
            "gpsCapturedDesc": "निर्देशांक तक्रार अहवालाशी जोडले गेले.",
            "locationDenied": "स्थान परवानगी नाकारली किंवा अनुपलब्ध. डीफॉल्ट पिन वापरला जात आहे.",
            "fileSizeExceeded": "फाइलचा आकार २५MB पेक्षा जास्त आहे.",
            "audioNotSupported": "या ब्राउझरमध्ये ऑडिओ रेकॉर्डिंग समर्थित नाही.",
            "micSimulation": "व्हॉइस तक्रार डेमोसाठी मायक्रोफोन सिम्युलेशन सक्रिय आहे.",
            "profileUpdated": "प्रोफाइल यशस्वीरित्या अद्ययावत केली.",
            "settingsSaved": "प्राधान्ये यशस्वीरित्या जतन केली.",
            "deleteRequested": "खाते हटवण्याची विनंती सादर केली गेली.",
            "languageChanged": "भाषा यशस्वीरित्या बदलली गेली.",
            "errorOccurred": "एक त्रुटी आली. कृपया पुन्हा प्रयत्न करा.",
            "caseUpdated": "केस डॉकेट यशस्वीरित्या अद्ययावत केले.",
            "caseReassigned": "प्रकरण नोडल अधिकाऱ्याकडे पुन्हा सोपवले.",
            "caseResolved": "तक्रार सोडवली गेली म्हणून नोंदवली.",
            "volunteerAdded": "नवीन स्वयंसेवक यशस्वीरित्या नोंदवला गेला.",
            "grantApproved": "सीएसआर अनुदान वाटप मंजूर झाले.",
            "milestoneApproved": "शैक्षणिक टप्पा मंजूर केला.",
            "deliverableUploaded": "सादरीकरण तपासणीसाठी अपलोड केले.",
            "loginSuccess": "यशस्वीरित्या साइन इन झाले. आपले स्वागत आहे!",
            "logoutSuccess": "यशस्वीरित्या लॉग आउट झाले.",
            "accessDenied": "प्रवेश प्रतिबंधित. अपुरे अधिकार.",
            "changesSaved": "सर्व बदल यशस्वीरित्या जतन केले.",
            "reportExported": "अहवाल तयार केला आणि डाउनलोड झाला.",
            "dataRefreshed": "टेलिमेट्री डेटा रिफ्रेश केला."
        },
        "language": "भाषा",
        "dashboard": "डॅशबोर्ड",
        "report_issue": "तक्रार नोंदवा",
        "report_problem": "तक्रार नोंदवा",
        "my_issues": "माझ्या तक्रारी",
        "track_issues": "निकालाचा मागोवा घ्या",
        "notifications": "सूचना",
        "profile": "प्रोफाइल",
        "settings": "सेटिंग्ज",
        "help": "मदत आणि सहाय्य",
        "logout": "लॉग आउट",
        "login": "लॉग इन",
        "recent_grievances": "अलीकडील तक्रारी",
        "issue_id": "तक्रार क्रमांक (ID)",
        "citizen_portal": "नागरिक पोर्टल",
        "government_portal": "सरकारी पोर्टल",
        "university_portal": "विद्यापीठ पोर्टल",
        "industry_portal": "उद्योग पोर्टल",
        "ngo_portal": "स्वयंसेवी संस्था पोर्टल",
        "admin_portal": "प्रशासक पोर्टल",
        "ai_governance_insight": "एआय प्रशासन अंतर्दृष्टी",
        "resolution": "निराकरण",
        "report": "अहवाल",
        "map": "घटना नकाशा",
        "search": "शोधा",
        "search_placeholder": "तक्रारी, प्रकरणे, स्थान शोधा...",
        "filter": "फिल्टर",
        "save": "बदल जतन करा",
        "cancel": "रद्द करा",
        "delete": "हटवा",
        "submit": "सबमिट करा",
        "upload": "अपलोड करा",
        "location": "स्थान",
        "description": "वर्णन",
        "title": "शीर्षक",
        "category": "वर्गवारी",
        "department": "विभाग",
        "created_at": "नोंदणी दिनांक",
        "action": "कृती",
        "actions": "कृती",
        "view": "पहा",
        "edit": "संपादित करा",
        "loading": "लोड होत आहे...",
        "success": "यशस्वी",
        "error": "एक त्रुटी आली",
        "welcome_back": "पुन्हा स्वागत आहे",
        "total_issues": "एकूण तक्रारी",
        "resolved_issues": "सोडवलेल्या तक्रारी",
        "in_progress_issues": "प्रगतीपथावरील तक्रारी",
        "pending_issues": "प्रलंबित तक्रारी",
        "active_projects": "सक्रिय प्रकल्प",
        "ai_accuracy": "एआय रूटिंग अचूकता",
        "sla_compliance": "SLA अनुपालन दर",
        "civic_engagement": "नागरी सहभाग निर्देशांक",
        "recent_activity": "अलीकडील हालचाली",
        "quick_actions": "त्वरित कृती",
        "live_incidents": "थेट नागरी घटना",
        "all": "सर्व",
        "high": "उच्च प्राधान्य",
        "medium": "मध्यम प्राधान्य",
        "low": "कमी प्राधान्य",
        "critical": "गंभीर प्राधान्य",
        "emergency": "तातडीचे प्राधान्य",
        "pending": "प्रलंबित",
        "in_progress": "प्रगतीपथावर",
        "resolved": "निराकरण झाले",
        "closed": "बंद केले",
        "rejected": "नाकारले",
        "approved": "मंजूर केले",
        "declined": "नाकारले",
        "export": "डेटा निर्यात करा",
        "download": "डाउनलोड",
        "confirm": "पुष्टी करा",
        "close": "बंद करा",
        "back": "मागे",
        "next": "पुढे",
        "previous": "मागील",
        "no_results": "कोणतेही परिणाम आढळले नाहीत",
        "view_all": "सर्व पहा",
        "home": "मुख्यपृष्ठ",
        "feed": "नागरी फीड",
        "analytics": "एआय विश्लेषण",
        "optional": "पर्यायी",
        "faculty": "प्राध्यापक मार्गदर्शक",
        "student": "विद्यार्थी गट",
        "projects": "प्रकल्प",
        "research": "संशोधन केंद्र",
        "innovation": "नवोन्मेष आव्हाने",
        "teams": "पथके",
        "credits": "शैक्षणिक क्रेडिट्स",
        "officers": "अधिकारी निर्देशिका",
        "assigned": "सोपवलेली प्रकरणे",
        "under_review": "पुनरावलोकन सुरू",
        "industry_assigned": "उद्योगाला सोपवले",
        "industry_review": "उद्योग पुनरावलोकन",
        "univ_assigned": "विद्यापीठाला सोपवले",
        "student_dev": "विद्यार्थी विकास कार्य",
        "faculty_review": "प्राध्यापक पुनरावलोकन",
        "industry_val": "उद्योग प्रमाणीकरण",
        "inspection": "स्थळ पाहणी",
        "feedback": "अभिप्राय प्रलंबित"
    }

    # Verify keys
    def get_keys(d, p=""):
        res = []
        for k, v in d.items():
            curr = f"{p}.{k}" if p else k
            if isinstance(v, dict):
                res.extend(get_keys(v, curr))
            else:
                res.append(curr)
        return set(res)

    base_keys = get_keys(base)
    mr_keys = get_keys(mr)
    diff = base_keys.symmetric_difference(mr_keys)
    if diff:
        print(f"Error in MR keys! Symmetric diff: {diff}")
        sys.exit(1)
    
    print(f"MR verified successfully with {len(mr_keys)} keys (0 diff).")
    
    out_path = os.path.join(os.path.dirname(os.path.abspath(__file__)), "data_mr.py")
    with open(out_path, "w", encoding="utf-8") as f:
        f.write("# -*- coding: utf-8 -*-\n")
        f.write('"""Marathi (mr) translations dictionary for SOCIAL-X platform"""\n\n')
        f.write("def get_mr_dict():\n")
        f.write("    return " + json.dumps(mr, ensure_ascii=False, indent=4) + "\n")
    print(f"Wrote {out_path}")

if __name__ == "__main__":
    generate_mr()
