# -*- coding: utf-8 -*-
"""Tamil (ta) translations dictionary for SOCIAL-X platform"""

def get_ta_dict():
    return {
        "nav": {
            "overview": "கண்ணோட்டம்",
            "access_identity": "அணுகல் மற்றும் அடையாளம்",
            "stakeholder_ecosystem": "பங்குதாரர் சுற்றுச்சூழல்",
            "operations_ai": "செயல்பாடுகள் மற்றும் AI",
            "infra_observability": "உள்கட்டமைப்பு மற்றும் கண்காணிப்பு",
            "field_activities": "கள செயல்பாடுகள் மற்றும் நிவாரணம்",
            "community_workforce": "சமூகம் மற்றும் பணியாளர்கள்",
            "governance_comms": "நிர்வாகம் மற்றும் தொடர்புகள்",
            "csr_investment": "CSR மற்றும் மூலதன ஒதுக்கீடு",
            "collaboration_rd": "கூட்டுறவு மற்றும் ஆராய்ச்சி",
            "student_portal": "மாணவர் தளம்",
            "faculty_portal": "பேராசிரியர் தளம்",
            "dashboard": "முகப்பு பலகை",
            "my_issues": "என் புகார்கள்",
            "report_problem": "புகார் அளிக்கவும்",
            "track_issues": "தீர்வை கண்காணிக்கவும்",
            "notifications": "அறிவிப்புகள்",
            "profile": "சுயவிவரம்",
            "settings": "அமைப்புகள்",
            "help": "உதவி & ஆதரவு",
            "logout": "வெளியேறு",
            "login": "உள்நுழை",
            "analytics": "பகுப்பாய்வு மற்றும் அறிக்கைகள்",
            "assigned_cases": "ஒதுக்கப்பட்ட வழக்குகள்",
            "departments": "துறைகள்",
            "officers": "அதிகாரிகள் அடைவு",
            "ai_suggestions": "AI பரிந்துரைகள்",
            "reports": "அறிக்கைகள் மற்றும் தணிக்கை",
            "projects": "கிடைக்கும் திட்டங்கள்",
            "funding": "நிதி வாய்ப்புகள்",
            "csr_analytics": "CSR பகுப்பாய்வு",
            "mentorship": "வழிகாட்டல்",
            "university_collaboration": "பல்கலைக்கழக கூட்டுறவு",
            "research": "ஆராய்ச்சி முயற்சிகள்",
            "prototypes": "முன்மாதிரிகள் மற்றும் விளக்கங்கள்",
            "volunteers": "தன்னார்வலர் படைகள்",
            "field_log": "கள ஆதார பதிவு",
            "impact": "சமூக தாக்கம்",
            "certificates": "சான்றிதழ்கள் மற்றும் பேட்ஜ்கள்",
            "lab_tasks": "ஆய்வக பணிகள்",
            "upload_deliverables": "பணிகளை பதிவேற்றவும்",
            "milestone_timeline": "மைல்கல் காலவரிசை",
            "advisor_discussion": "ஆலோசகர் கலந்துரையாடல்",
            "milestone_approvals": "மைல்கல் ஒப்புதல்கள்",
            "municipal_proposals": "நகராட்சி முன்மொழிவுகள்",
            "teams": "குழுக்கள் மற்றும் பட்டியல்",
            "credits": "கல்வி வரவு புள்ளிகள்",
            "user_management": "பயனர் மேலாண்மை",
            "role_management": "பங்கு மேலாண்மை",
            "government_management": "அரசு மேலாண்மை",
            "university_management": "பல்கலைக்கழக மேலாண்மை",
            "industry_management": "தொழில்துறை மேலாண்மை",
            "ngo_management": "தன்னார்வ தொண்டு நிறுவன மேலாண்மை",
            "research_organizations": "ஆராய்ச்சி அமைப்புகள்",
            "issue_management": "பிரச்சினை மேலாண்மை",
            "ai_monitoring": "AI தொலை அளவியல் கண்காணிப்பு",
            "workflow_monitoring": "பணிப்பாய்வு கண்காணிப்பு",
            "audit_logs": "தணிக்கை பாதை",
            "system_health": "கணினி ஆரோக்கியம்",
            "landing_features": "அம்சங்கள்",
            "landing_how_it_works": "இது எவ்வாறு செயல்படுகிறது",
            "landing_about": "எங்களை பற்றி",
            "landing_faq": "அடிக்கடி கேட்கப்படும் கேள்விகள்",
            "landing_contact": "தொடர்பு கொள்ள",
            "role_login": "பங்கு உள்நுழைவு",
            "citizen_sign_up": "குடிமக்கள் பதிவு"
        },
        "common": {
            "buttons": {
                "browseFiles": "கோப்புகளை உலாவுக",
                "openCamera": "கேமராவை திறக்கவும்",
                "startRecording": "பதிவைத் தொடங்கவும்",
                "stopRecording": "பதிவை நிறுத்தவும்",
                "submit": "சமர்ப்பிக்கவும்",
                "cancel": "ரத்து செய்",
                "save": "மாற்றங்களைச் சேமி",
                "delete": "நீக்கு",
                "search": "தேடு",
                "filter": "வடிகட்டு",
                "upload": "பதிவேற்று",
                "confirm": "உறுதிப்படுத்து",
                "close": "மூடு",
                "back": "பின்செல்",
                "next": "அடுத்து",
                "previous": "முந்தைய",
                "detectLocation": "தற்போதைய இருப்பிடத்தை கண்டறி",
                "useCurrentGps": "தற்போதைய GPS ஐப் பயன்படுத்து",
                "resetForm": "படிவத்தை மீட்டமை",
                "submitIssue": "குறைதீர்ப்பு மனுவை சமர்ப்பி",
                "viewAll": "அனைத்தையும் காண்க",
                "export": "தரவை ஏற்றுமதி செய்",
                "download": "பதிவிறக்கு",
                "refresh": "புதுப்பி",
                "login": "உள்நுழை",
                "logout": "வெளியேறு",
                "modifyUploads": "ஊடக பதிவேற்றங்களை மாற்றவும்",
                "removeFile": "கோப்பை நீக்கு",
                "removeVoiceMemo": "குரல் குறிப்பை நீக்கு",
                "edit": "திருத்து",
                "view": "விவரங்களை காண்க",
                "add": "புதிதாக சேர்",
                "create": "உருவாக்கு",
                "update": "புதுப்பி",
                "approve": "ஒப்புதல் அளி",
                "reject": "நிராகரி",
                "reassign": "மறுஒதுக்கீடு செய்",
                "escalate": "மேலதிகாரிக்கு அனுப்பு",
                "resolve": "வழக்கை தீர்க்கவும்",
                "assign": "ஒதுக்கீடு செய்",
                "verify": "சரிபார்க்கவும்",
                "downloadReport": "அறிக்கையை பதிவிறக்கு",
                "syncTelemetry": "தொலை அளவியலை ஒத்திசைக்கவும்",
                "applyFilters": "வடிகட்டிகளைப் பயன்படுத்து",
                "clearFilters": "வடிகட்டிகளை அழிக்கவும்",
                "viewDetails": "விவரங்களை காண்க",
                "sendNotification": "அறிவிப்பை அனுப்பு",
                "inviteMember": "உறுப்பினரை அழைக்கவும்",
                "print": "அச்சிடு",
                "share": "பகிர்",
                "copyLink": "இணைப்பை நகலெடு",
                "proceed": "தொடரவும்",
                "retry": "மீண்டும் முயற்சி செய்",
                "dismiss": "நிராகரி",
                "accept": "ஏற்கவும்",
                "decline": "மறுக்கவும்"
            },
            "labels": {
                "dashboard": "முகப்பு பலகை",
                "profile": "சுயவிவரம்",
                "settings": "அமைப்புகள்",
                "notifications": "அறிவிப்புகள்",
                "help": "உதவி & ஆதரவு",
                "logout": "வெளியேறு",
                "login": "உள்நுழை",
                "status": "நிலை",
                "priority": "முன்னுரிமை",
                "department": "துறை",
                "category": "வகை",
                "district": "மாவட்டம்",
                "ward": "வார்டு",
                "address": "முகவரி",
                "landmark": "அடையாளக் குறி",
                "title": "தலைப்பு",
                "description": "விளக்கம்",
                "location": "இருப்பிடம்",
                "latitude": "அட்சரேகை",
                "longitude": "தீர்க்கரேகை",
                "accuracy": "துல்லியம்",
                "date": "தேதி",
                "action": "நடவடிக்கை",
                "actions": "நடவடிக்கைகள்",
                "all": "அனைத்தும்",
                "high": "உயர்",
                "medium": "நடுத்தர",
                "low": "குறைந்த",
                "critical": "முக்கியமானது",
                "emergency": "அவசரம்",
                "pending": "நிலுவையில் உள்ளது",
                "inProgress": "செயல்பாட்டில் உள்ளது",
                "resolved": "தீர்க்கப்பட்டது",
                "closed": "மூடப்பட்டது",
                "rejected": "நிராகரிக்கப்பட்டது",
                "verified": "சரிபார்க்கப்பட்டது",
                "assigned": "ஒதுக்கப்பட்டது",
                "recentActivity": "சமீபத்திய செயல்பாடு",
                "quickActions": "விரைவு நடவடிக்கைகள்",
                "systemHealth": "கணினி ஆரோக்கியம்",
                "language": "மொழி",
                "selectLanguage": "மொழியைத் தேர்ந்தெடுக்கவும்",
                "searchLanguage": "மொழிகளைத் தேடுங்கள்...",
                "editable": "திருத்தக்கூடியது",
                "active": "செயலில் உள்ளது",
                "inactive": "செயலற்றது",
                "completed": "முடிந்தது",
                "failed": "தோல்வியடைந்தது",
                "total": "மொத்தம்",
                "count": "எண்ணிக்கை",
                "rate": "விகிதம்",
                "percentage": "சதவீதம்",
                "timeRemaining": "மீதமுள்ள நேரம்",
                "dueDate": "கடைசி தேதி",
                "submittedBy": "சமர்ப்பித்தவர்",
                "assignedTo": "ஒதுக்கப்பட்டவர்",
                "officerInCharge": "பொறுப்பு அதிகாரி",
                "slaTimer": "SLA டைமர்",
                "auditTimeline": "தணிக்கை காலவரிசை",
                "contactInfo": "தொடர்பு தகவல்",
                "phoneNumber": "தொலைபேசி எண்",
                "emailAddress": "மின்னஞ்சல் முகவரி",
                "fullName": "முழுப் பெயர்",
                "role": "பங்கு",
                "organization": "அமைப்பு",
                "institution": "நிறுவனம்",
                "createdAt": "பதிவு செய்யப்பட்ட தேதி",
                "updatedAt": "புதுப்பிக்கப்பட்ட தேதி"
            },
            "status": {
                "open": "திறந்தது",
                "submitted": "சமர்ப்பிக்கப்பட்டது",
                "verified": "AI சரிபார்க்கப்பட்டது",
                "assigned": "ஒதுக்கப்பட்டது",
                "in_progress": "செயல்பாட்டில் உள்ளது",
                "inProgress": "செயல்பாட்டில் உள்ளது",
                "resolved": "தீர்க்கப்பட்டது",
                "closed": "மூடப்பட்டது",
                "rejected": "நிராகரிக்கப்பட்டது",
                "under_review": "மறுஆய்வில் உள்ளது",
                "under_government_review": "அரசு மறுஆய்வில் உள்ளது",
                "assigned_to_government": "அரசுக்கு ஒதுக்கப்பட்டது",
                "assigned_to_industry": "தொழில்துறைக்கு ஒதுக்கப்பட்டது",
                "industry_review": "தொழில்துறை மறுஆய்வு",
                "assigned_to_university": "பல்கலைக்கழகத்திற்கு ஒதுக்கப்பட்டது",
                "student_development": "மாணவர் மேம்பாடு",
                "faculty_review": "பேராசிரியர் மறுஆய்வு",
                "industry_validation": "தொழில்துறை சரிபார்ப்பு",
                "inspection": "தள ஆய்வு",
                "feedback_pending": "கருத்து நிலுவையில் உள்ளது",
                "escalated": "மேலனுப்பப்பட்டது",
                "active": "செயலில் உள்ளது",
                "inactive": "செயலற்றது",
                "completed": "முடிந்தது",
                "approved": "ஒப்புதல் அளிக்கப்பட்டது",
                "declined": "நிராகரிக்கப்பட்டது",
                "pending": "நிலுவையில் உள்ளது"
            },
            "priority": {
                "low": "குறைந்த முன்னுரிமை",
                "medium": "நடுத்தர முன்னுரிமை",
                "high": "உயர் முன்னுரிமை",
                "critical": "முக்கிய முன்னுரிமை",
                "emergency": "அவசர முன்னுரிமை",
                "urgent": "அவசரம்"
            },
            "departments": {
                "waterSupply": "குடிநீர் வழங்கல் மற்றும் வடிகால்",
                "roadsTransport": "சாலைகள் மற்றும் போக்குவரத்து",
                "electricityPower": "மின்சாரம் மற்றும் மின் கட்டமைப்பு",
                "solidWaste": "திடக்கழிவு மற்றும் சுகாதாரம்",
                "publicHealth": "பொது சுகாதாரம் மற்றும் பாதுகாப்பு",
                "urbanPlanning": "நகர திட்டமிடல் மற்றும் உள்கட்டமைப்பு",
                "education": "கல்வி மற்றும் இளைஞர் நலன்",
                "environmentForest": "சுற்றுச்சூழல் மற்றும் வனத்துறை",
                "policeSafety": "காவல்துறை மற்றும் பொது பாதுகாப்பு",
                "disasterManagement": "பேரிடர் மேலாண்மை ஆணையம்",
                "municipalAdmin": "நகராட்சி நிர்வாகம்"
            },
            "categories": {
                "water": "குடிநீர் வழங்கல் மற்றும் வடிகால்",
                "roads": "சாலைகள் மற்றும் போக்குவரத்து",
                "electricity": "மின்சாரம் மற்றும் மின் கட்டமைப்பு",
                "waste": "திடக்கழிவு மற்றும் சுகாதாரம்",
                "health": "பொது சுகாதாரம் மற்றும் பாதுகாப்பு",
                "sanitation": "சுகாதாரம் மற்றும் கழிவுநீர்",
                "infrastructure": "பொது உள்கட்டமைப்பு",
                "streetlights": "தெரு விளக்குகள் மற்றும் மின்சாரம்",
                "drainage": "வடிகால் மற்றும் பாதாள சாக்கடை",
                "potholes": "குழிகள் மற்றும் சாலை பழுது",
                "traffic": "போக்குவரத்து மற்றும் சாலை பாதுகாப்பு",
                "pollution": "மாசுபாடு மற்றும் சுற்றுச்சூழல் ஆபத்து"
            },
            "validation": {
                "requiredField": "இந்த புலம் அவசியமானது",
                "titleRequired": "தலைப்பு தேவை",
                "descriptionRequired": "விளக்கம் தேவை",
                "locationRequired": "சம்பவ புவியியல் இருப்பிடம் தேவை",
                "invalidEmail": "சரியான மின்னஞ்சல் முகவரியை உள்ளிடவும்",
                "invalidPassword": "கடவுச்சொல் குறைந்தபட்சம் 8 எழுத்துகளாக இருக்க வேண்டும்",
                "passwordTooShort": "கடவுச்சொல் மிகவும் சிறியது (குறைந்தது 8 எழுத்துக்கள்)",
                "passwordMismatch": "கடவுச்சொற்கள் பொருந்தவில்லை",
                "unsupportedFile": "ஆதரிக்கப்படாத கோப்பு வடிவம். JPEG, PNG, MP4 அல்லது PDF ஐ பதிவேற்றவும்.",
                "maxFileSizeExceeded": "அதிகபட்ச கோப்பு அளவு தாண்டியது (25MB வரம்பு)",
                "micPermissionDenied": "மைக்ரோஃபோன் அனுமதி மறுக்கப்பட்டது. தயவுசெய்து அணுகலை அனுமதிக்கவும்.",
                "cameraPermissionDenied": "கேமரா அனுமதி மறுக்கப்பட்டது. தயவுசெய்து கேமரா அணுகலை அனுமதிக்கவும்.",
                "minLength": "உள்ளீடு குறைந்தபட்ச நீளத்தை விட குறைவாக உள்ளது",
                "maxLength": "உள்ளீடு அனுமதிக்கப்பட்ட அதிகபட்ச நீளத்தை தாண்டியது",
                "uploadFailed": "பதிவேற்றம் தோல்வியடைந்தது. இணைப்பைச் சரிபார்த்து மீண்டும் முயற்சிக்கவும்.",
                "uploadSuccessful": "கோப்பு வெற்றிகரமாக பதிவேற்றப்பட்டது.",
                "loginSuccessful": "வெற்றிகரமாக உள்நுழைந்தீர்கள்.",
                "registrationSuccessful": "பதிவு வெற்றிகரமாக முடிந்தது.",
                "fillRequiredFields": "சமர்ப்பிக்கும் முன் அனைத்து கட்டாய புலங்களையும் நிரப்பவும்."
            },
            "emptyStates": {
                "noData": "தரவு எதுவும் கிடைக்கவில்லை",
                "noResults": "உங்கள் வினவலுக்கு ஏற்ப முடிவுகள் எதுவும் இல்லை",
                "noNotifications": "புதிய அறிவிப்புகள் எதுவும் இல்லை",
                "noIssuesFound": "உங்கள் நிபந்தனைகளுடன் பொருந்தும் புகார்கள் எதுவும் இல்லை",
                "noProjectsFound": "தற்போது செயலில் உள்ள திட்டங்கள் எதுவும் இல்லை",
                "noOfficersFound": "தேடல் வடிகட்டிகளுக்கு பொருந்தும் அதிகாரிகள் இல்லை",
                "noActivitiesFound": "கள செயல்பாடுகள் எதுவும் இன்னும் பதிவு செய்யப்படவில்லை"
            },
            "loading": {
                "loading": "ஏற்றுகிறது...",
                "pleaseWait": "தயவுசெய்து காத்திருக்கவும்...",
                "fetchingData": "சமீபத்திய தரவை பெறுகிறது...",
                "processing": "உங்கள் கோரிக்கை செயலாக்கப்படுகிறது...",
                "uploadingMedia": "ஊடகம் பதிவேற்றப்படுகிறது...",
                "analyzingAi": "Multimodal AI உடன் பகுப்பாய்வு செய்யப்படுகிறது...",
                "savingChanges": "மாற்றங்கள் சேமிக்கப்படுகின்றன..."
            },
            "pagination": {
                "previous": "முந்தைய",
                "next": "அடுத்து",
                "page": "பக்கம்",
                "of": "இல்",
                "rowsPerPage": "பக்கத்திற்கான வரிசைகள்",
                "showing": "காட்டப்படுகிறது",
                "entries": "பதிவுகள்",
                "totalRecords": "மொத்த பதிவுகள்"
            },
            "search": {
                "searchPlaceholder": "புகார்கள், வழக்குகள், இடங்களைத் தேடுங்கள்...",
                "searchGrievances": "புகார்களைத் தேடுங்கள்...",
                "searchUsers": "பயனர்களைத் தேடுங்கள்...",
                "searchDepartments": "துறைகளைத் தேடுங்கள்...",
                "searchProjects": "திட்டங்களைத் தேடுங்கள்...",
                "searchOfficers": "அதிகாரிகளைத் தேடுங்கள்...",
                "quickNavigator": "விரைவு வழிசெலுத்தி...",
                "searchAll": "தளம் முழுவதும் தேடுங்கள்..."
            }
        },
        "ai": {
            "processing": "AI செயலாக்கம்",
            "ocrResult": "OCR உரை பிரித்தெடுக்கப்பட்டது",
            "speechResult": "வட்டார பேச்சு உரை வடிவம்",
            "speechTranscript": "பேச்சு உரை வடிவம்",
            "confidenceScore": "AI நம்பிக்கை மதிப்பெண்",
            "aiConfidence": "AI நம்பிக்கை",
            "suggestedCategory": "பரிந்துரைக்கப்பட்ட வகை",
            "suggestedDepartment": "பரிந்துரைக்கப்பட்ட துறை",
            "recommendedDepartment": "பரிந்துரைக்கப்பட்ட துறை",
            "suggestedIndustry": "பரிந்துரைக்கப்பட்ட தொழில்துறை கூட்டாளி",
            "duplicateDetection": "போலி குறைதீர்ப்பு கண்டறிதல்",
            "aiVerification": "மல்டிமாடல் பார்வை சரிபார்ப்பு",
            "smartRouting": "அறிவார்ந்த துறைசார் ரூட்டிங்",
            "previewTitle": "மல்டிமாடல் AI பிரித்தெடுத்தல் முன்னோட்டம்",
            "previewSubtitle": "எங்கள் கணினி பார்வை மற்றும் பேச்சு பைப்லைன்கள் பின்வரும் தரவை பிரித்தெடுத்துள்ளன. அனுப்புவதற்கு முன் சரிபார்க்கவும்.",
            "detectedHeadline": "கண்டறியப்பட்ட புகார் தலைப்பு",
            "classifiedCategory": "AI வகைப்படுத்திய பிரிவு",
            "dispatchedDept": "ஒதுக்கப்பட்ட நகராட்சி துறை",
            "severityPriority": "தீவிரம் & முன்னுரிமை",
            "mappedLocation": "வரைபடமாக்கப்பட்ட சம்பவ இடம்",
            "confirmSubmit": "உறுதிப்படுத்தி புகார் அனுப்பவும்",
            "cancel": "ரத்து செய்",
            "ocrBadge": "FastAPI OCR பிரித்தெடுத்தது",
            "sttBadge": "வட்டார பேச்சு படியெடுக்கப்பட்டது",
            "verificationStep": "குடிமக்கள் சரிபார்ப்பு படி",
            "verificationStepHelp": "100% துல்லியத்தை உறுதிப்படுத்த அனுப்புவதற்கு முன் கீழே உள்ள எந்த புலத்தையும் நீங்கள் நேரடியாக திருத்தலாம்.",
            "ocrVision": "OCR பார்வை பிரித்தெடுத்தல்",
            "noOcrText": "பலகைகளில் உரை எதுவும் கண்டறியப்படவில்லை",
            "noAudioMemo": "ஆடியோ குறிப்பு எதுவும் இணைக்கப்படவில்லை",
            "priorityScore": "கணக்கிடப்பட்ட முன்னுரிமை மதிப்பெண்",
            "estimatedCost": "மதிப்பிடப்பட்ட நகராட்சி செலவு",
            "estimatedTime": "மதிப்பிடப்பட்ட தீர்வு நேரம்",
            "recommendation": "AI ஆட்சி பரிந்துரை",
            "confidenceHigh": "உயர் நம்பிக்கை (>90%)",
            "confidenceMedium": "நடுத்தர நம்பிக்கை (70-90%)",
            "confidenceLow": "குறைந்த நம்பிக்கை (<70%)",
            "duplicateFound": "சாத்தியமான போலி கண்டறியப்பட்டது",
            "duplicateScore": "ஒற்றுமை மதிப்பெண்"
        },
        "citizen": {
            "portalTitle": "குடிமக்கள் பொது தளம்",
            "dashboard": {
                "welcomeBack": "மீண்டும் வருக",
                "totalReported": "மொத்தம் பதிவு செய்யப்பட்டவை",
                "inProgress": "செயல்பாட்டில் உள்ளது",
                "resolved": "தீர்க்கப்பட்டது",
                "needsVerification": "சரிபார்ப்பு தேவை",
                "communityImpact": "சமூக தாக்க மதிப்பெண்",
                "avgResolution": "சராசரி தீர்வு நேரம்",
                "recentGrievances": "சமீபத்திய புகார்கள்",
                "reportNewIssue": "புதிய புகாரை பதிவு செய்",
                "myIssues": "என் புகார்கள்",
                "trackIssues": "தீர்வை கண்காணிக்கவும்",
                "liveIncidents": "நேரலை குடிமக்கள் நிகழ்வுகள்",
                "civicFeed": "குடிமக்கள் ஊட்டம்",
                "satisfactionScore": "குடிமக்கள் திருப்தி மதிப்பீடு",
                "activeCases": "செயலில் உள்ள புகார்கள்",
                "resolvedCases": "தீர்க்கப்பட்ட புகார்கள்"
            },
            "report": {
                "title": "சமூக குறையைப் புகாரளிக்கவும்",
                "subtitle": "புகைப்படங்கள், வீடியோ, ஆடியோ குரல் குறிப்புகள் அல்லது ஆவணங்களைச் சமர்ப்பிக்கவும். எங்கள் AI இயந்திரம் OCR மூலம் பலகைகளை பிரித்தெடுத்து முன்னோட்டத்தை உருவாக்கும்.",
                "multimodalBadge": "மல்டிமாடல் AI உட்கொள்ளல்",
                "moduleBadge": "தொகுதி 1",
                "uploadEvidence": "புகைப்பட மற்றும் ஆவண சான்றுகள்",
                "uploadSubtitle": "குறைபாடு, உடைந்த எச்சரிக்கை பலகை அல்லது நகராட்சி ஆவணத்தின் படத்தை பதிவேற்றவும்",
                "dragDrop": "படங்கள், வீடியோ கிளிப்புகள் அல்லது ஆவணங்களை இழுத்து விடவும்",
                "supportedFormats": "JPEG, PNG, MP4 மற்றும் PDF (அதிகபட்சம் 25MB) ஆதரிக்கிறது.",
                "browseFiles": "கோப்புகளை உலாவுக",
                "openCamera": "கேமராவை திறக்கவும்",
                "uploadingProgress": "AI மூலம் ஊடகம் பதிவேற்றப்பட்டு செயலாக்கப்படுகிறது...",
                "attachedEvidence": "இணைக்கப்பட்ட சான்றுகள்",
                "voiceGrievance": "குரல் ஆடியோ புகார்",
                "optional": "விருப்பத்திற்குரியது",
                "voiceSubtitle": "பேசும் விளக்கத்தை பதிவு செய்யவும். உரையிலிருந்து பேச்சாக தானாக படியெடுக்கப்படும்.",
                "pressRecordHelp": "எந்த மொழியிலும் உங்கள் பிரச்சினையை விவரிக்க பதிவை அழுத்தவும்.",
                "startVoiceRecording": "குரல் பதிவைத் தொடங்கவும்",
                "stopRecording": "பதிவை நிறுத்தவும்",
                "recording": "பதிவாகிறது...",
                "speechProcessing": "பேச்சு செயலாக்கம்...",
                "speechConverted": "பேச்சு வெற்றிகரமாக மாற்றப்பட்டது",
                "incidentLocation": "சம்பவ புவியியல் இருப்பிடம்",
                "locationSubtitle": "நகராட்சி களப் பணியாளர்களை அனுப்ப துல்லியமான ஆயங்களை சுட்டிக்காட்டவும்",
                "useCurrentGps": "தற்போதைய GPS ஐப் பயன்படுத்து",
                "streetAddress": "தெரு முகவரி / அடையாளக்குறி",
                "addressPlaceholder": "எ.கா. 14வது பிரதான சாலை, இந்திரா காந்தி வட்டம் அருகில்",
                "mapTip": "குறிப்பு: ஆயங்களை சரிசெய்ய நீங்கள் வரைபடத்தில் எங்கு வேண்டுமானாலும் கிளிக் செய்யலாம்.",
                "contextTitle": "பிரச்சினை விளக்கம்",
                "contextSubtitle": "சுருக்கமான சூழலை வழங்கவும் (AI தானாக விரிவுபடுத்தி வகைப்படுத்தும்)",
                "headlineLabel": "சுருக்கமான புகார் தலைப்பு",
                "headlinePlaceholder": "எ.கா. நிலத்தடி நீர் குழாய் உடைப்பு மற்றும் சாலை வெள்ளம்",
                "detailsLabel": "விரிவான விளக்கம்",
                "detailsPlaceholder": "சமூக தாக்கம், காலம் மற்றும் பாதுகாப்பு அபாயங்களை விவரிக்கவும்...",
                "categoryLabel": "நகராட்சி வகை",
                "priorityLabel": "அவசர முன்னுரிமை",
                "generateAiPreview": "AI முன்னோட்டத்தை உருவாக்கவும்",
                "processingAi": "AI செயலாக்கம் நடைபெறுகிறது...",
                "audioMemo": "ஆடியோ புகார் குறிப்பு",
                "readyStt": "STT பாகுபடுத்தலுக்கு தயார்",
                "incidentCoordinates": "சம்பவ ஆயத்தொலைவுகள்",
                "currentDetectedLocation": "கண்டறியப்பட்ட தற்போதைய இடம்"
            },
            "track": {
                "title": "குறைதீர்ப்பு தீர்வை கண்காணிக்கவும்",
                "subtitle": "நேரலை நிலை மாற்றங்கள், ஒதுக்கப்பட்ட துறைசார் பொறியாளர்கள் மற்றும் SLA டைமர்களைக் கண்காணிக்கவும்.",
                "enterId": "புகார் கண்காணிப்பு ஐடியை உள்ளிடவும்",
                "searchPlaceholder": "எ.கா. SOC-2026-8821",
                "currentStage": "தற்போதைய நிலை",
                "assignedTo": "ஒதுக்கப்பட்ட துறை",
                "officerInCharge": "பொறுப்பு அதிகாரி",
                "slaTimer": "SLA தீர்வு கவுண்டவுன்",
                "timeline": "தணிக்கை காலவரிசை",
                "trackingDetails": "கண்காணிப்பு விவரங்கள்",
                "liveStatusTransitions": "நேரலை நிலை மாற்றங்கள்"
            },
            "profile": {
                "title": "குடிமகன் சுயவிவரம்",
                "fullName": "முழுப் பெயர்",
                "email": "மின்னஞ்சல் முகவரி",
                "phone": "தொலைபேசி எண்",
                "district": "குடியிருப்பு மாவட்டம்",
                "address": "நிரந்தர முகவரி",
                "saveProfile": "சுயவிவரத்தை சேமி",
                "citizenBadge": "சரிபார்க்கப்பட்ட குடிமகன்",
                "verificationStatus": "அடையாள சரிபார்ப்பு நிலை"
            },
            "settings": {
                "title": "விருப்பத்தேர்வுகள் & அமைப்புகள்",
                "notifications": "புகார் அறிவிப்புகள்",
                "emailAlerts": "மின்னஞ்சல் எச்சரிக்கைகள்",
                "smsAlerts": "எஸ்எம்எஸ் எச்சரிக்கைகள்",
                "theme": "காட்சி தீம்",
                "language": "பயன்பாட்டு மொழி",
                "savePreferences": "விருப்பத்தேர்வுகளைச் சேமி"
            }
        },
        "government": {
            "portalTitle": "நகராட்சி கட்டளை மற்றும் கட்டுப்பாடு",
            "dashboard": {
                "title": "அரசு அதிகாரி தளம்",
                "overview": "நகராட்சி கண்ணோட்டம்",
                "assignedCases": "ஒதுக்கப்பட்ட புகார்கள்",
                "liveCases": "செயலில் உள்ள வழக்குகள்",
                "slaBreachRisk": "SLA மீறல் ஆபத்து",
                "avgTurnaround": "சராசரி தீர்வு நேரம்",
                "citizenSatisfaction": "குடிமக்கள் திருப்தி",
                "urgentDocket": "அவசர வழக்கு பட்டியல்",
                "viewQueue": "முழு வரிசையையும் காண்க",
                "syncTelemetry": "தொலை அளவியலை ஒத்திசைக்கவும்",
                "telemetryActive": "நிகழ்நேர குடிமக்கள் தொலை அளவியல் மற்றும் தானியங்கி அனுப்பல் செயல்படுகிறது.",
                "monthlyTrends": "மாதாந்திர புகார் போக்குகள்",
                "resolutionBreakdown": "தீர்வு விவரங்கள்",
                "districtHeatmap": "மாவட்ட செயல்திறன் வெப்ப வரைபடம்",
                "departmentEfficiency": "துறை செயல்திறன் மதிப்பீடுகள்",
                "docketOverview": "வழக்கு கண்ணோட்டம்",
                "statutoryTarget": "24 மணி நேர மாநில சட்டப்பூர்வ இலக்கிற்கு எதிராக"
            },
            "officers": {
                "title": "அதிகாரிகள் அடைவு",
                "directory": "கள மற்றும் நோடல் அதிகாரிகள்",
                "addOfficer": "அதிகாரியை பதிவு செய்",
                "officerName": "அதிகாரி பெயர்",
                "designation": "பதவி",
                "department": "துறை",
                "contact": "தொடர்பு",
                "assignedCount": "ஒதுக்கப்பட்ட வழக்குகள்",
                "resolutionRate": "தீர்வு விகிதம்",
                "status": "பணி நிலை",
                "actions": "நடவடிக்கைகள்",
                "searchOfficers": "பெயர், பேட்ஜ் அல்லது துறை மூலம் அதிகாரிகளைத் தேடுங்கள்..."
            },
            "departments": {
                "title": "நகராட்சி துறைகள்",
                "municipalDepartments": "நகர செயல்பாட்டுத் துறைகள்",
                "addDepartment": "துறையைச் சேர்",
                "deptName": "துறை பெயர்",
                "headOfDept": "துறைத் தலைவர்",
                "activePersonnel": "செயலில் உள்ள பணியாளர்கள்",
                "budgetAllocated": "ஒதுக்கப்பட்ட நிதி",
                "openGrievances": "நிலுவையில் உள்ள புகார்கள்",
                "slaCompliance": "SLA இணக்கம்",
                "efficiencyRating": "செயல்திறன் மதிப்பீடு",
                "searchDepartments": "துறைகளைத் தேடுங்கள்..."
            },
            "assigned": {
                "title": "ஒதுக்கப்பட்ட புகார்கள்",
                "caseId": "வழக்கு ஐடி",
                "citizenName": "குடிமகன் பெயர்",
                "category": "வகை",
                "priority": "முன்னுரிமை",
                "status": "நிலை",
                "dateReported": "பதிவு செய்யப்பட்ட தேதி",
                "targetResolution": "இலக்கு தீர்வு",
                "reassign": "மறுஒதுக்கீடு செய்",
                "escalate": "மேலனுப்பு",
                "resolveCase": "தீர்க்கப்பட்டதாகக் குறி",
                "viewCase": "வழக்கை ஆய்வு செய்",
                "filterPriority": "முன்னுரிமை அடிப்படையில் வடிகட்டு",
                "filterStatus": "நிலை அடிப்படையில் வடிகட்டு",
                "allCases": "அனைத்து வழக்குகள்"
            },
            "tracking": {
                "title": "புகார் புவி கண்காணிப்பு",
                "subtitle": "கள அதிகாரி தொலை அளவியலுடன் செயலில் உள்ள மற்றும் நிலுவையில் உள்ள சிக்கல்களைக் காட்டும் வரைபடம்.",
                "liveIncidentMap": "நேரலை சம்பவ வரைபடம்",
                "filterByWard": "வார்டு வாரியாக வடிகட்டு",
                "filterBySeverity": "தீவிரத்தன்மை அடிப்படையில் வடிகட்டு"
            },
            "aiSuggestions": {
                "title": "AI ஆட்சி நுண்ணறிவு",
                "smartRoutingTitle": "தானியங்கி ரூட்டிங் பரிந்துரைகள்",
                "recommendedActions": "பரிந்துரைக்கப்பட்ட நடவடிக்கைகள்",
                "anomalyDetection": "முரண்பாடு கண்டறிதல்",
                "duplicateClusters": "போலி கிளஸ்டர்கள் கண்டறியப்பட்டன",
                "autoTriage": "தானியங்கி விதி இயந்திரம்"
            },
            "reports": {
                "title": "நிர்வாக பகுப்பாய்வு மற்றும் அறிக்கைகள்",
                "generateReport": "அறிக்கையை உருவாக்கு",
                "downloadPdf": "PDF ஐப் பதிவிறக்கு",
                "downloadCsv": "CSV ஐ ஏற்றுமதி செய்",
                "monthlyAudit": "மாதாந்திர நகராட்சி தணிக்கை",
                "quarterlyPerformance": "காலாண்டு செயல்திறன் மறுஆய்வு",
                "exportAnalytics": "பகுப்பாய்வை ஏற்றுமதி செய்"
            },
            "settings": {
                "title": "தள நிர்வாக அமைப்புகள்",
                "slaThresholds": "SLA அவசர வரம்புகள்",
                "notificationRules": "எச்சரிக்கை மற்றும் அறிவிப்பு விதிகள்",
                "escalationMatrix": "மேலனுப்பும் கட்டமைப்பு",
                "workingHours": "துறை வேலை நேரம்"
            }
        },
        "industry": {
            "portalTitle": "தொழில்துறை மற்றும் கார்ப்பரேட் CSR தளம்",
            "dashboard": {
                "title": "தொழில்துறை CSR பலகை",
                "overview": "CSR மூலதனம் மற்றும் தாக்கம்",
                "csrFunding": "CSR மூலதன ஒதுக்கீடு",
                "capitalAllocation": "மூலதன ஒதுக்கீடு",
                "availableProjects": "சரிபார்க்கப்பட்ட திட்டங்கள்",
                "liveGrants": "செயலில் உள்ள மானியங்கள்",
                "partnershipPact": "PPP ஒப்பந்தங்கள்",
                "totalDisbursed": "வழங்கப்பட்ட மொத்த நிதி",
                "activeProjects": "செயலில் உள்ள திட்டங்கள்",
                "impactScore": "சமூக தாக்க மதிப்பெண்",
                "viewOpportunities": "வாய்ப்புகளைக் காண்க",
                "availableCsr": "கிடைக்கும் CSR நிதி",
                "corporatePartner": "கார்ப்பரேட் கூட்டாளி",
                "verifiedEntity": "சரிபார்க்கப்பட்ட CSR அமைப்பு"
            },
            "projects": {
                "title": "கிடைக்கும் CSR திட்டங்கள்",
                "projectCatalog": "திட்ட பட்டியல்",
                "fundingGoal": "இலக்கு நிதி",
                "raisedAmount": "திரட்டப்பட்ட நிதி",
                "municipalSponsor": "நகராட்சி ஆதரவாளர்",
                "sdgImpact": "SDG தாக்க பிரிவு",
                "applyFunding": "CSR நிதியை வழங்கு",
                "exploreInitiatives": "முயற்சிகளை ஆராயுங்கள்",
                "searchProjects": "முக்கிய வார்த்தை, SDG அல்லது நகரம் மூலம் தேடுங்கள்..."
            },
            "funding": {
                "title": "நிதி மற்றும் மூலதன ஒதுக்கீடு",
                "grantApplication": "மானிய முன்மொழிவு",
                "disbursementStatus": "நிதி வழங்கல் நிலை",
                "corporateDonation": "கார்ப்பரேட் பங்களிப்பு",
                "taxBenefit": "பிரிவு 80G / 135 சலுகை",
                "escrowStatus": "எஸ்க்ரோ கணக்கு நிலை",
                "fundMilestone": "மைல்கல் தவணையை வெளியிடு"
            },
            "csr": {
                "title": "CSR தாக்க பகுப்பாய்வு",
                "spendByCategory": "பிரிவு வாரியாக CSR செலவு",
                "geographicAllocation": "புவியியல் ஒதுக்கீடு",
                "socialReturnOnInvestment": "சமூக முதலீட்டு வருவாய் (SROI)",
                "auditCompliance": "சட்டப்பூர்வ தணிக்கை இணக்கம்",
                "csrDistribution": "CSR விநியோகம்"
            },
            "mentorship": {
                "title": "தொழில்துறை வழிகாட்டல் திட்டம்",
                "expertGuidance": "நிபுணர் வழிகாட்டுதல் வழங்கு",
                "studentPrototypes": "மாணவர் முன்மாதிரிகள்",
                "industryAdvisors": "கார்ப்பரேட் ஆலோசகர்கள்",
                "scheduleSession": "அமர்வை திட்டமிடுங்கள்"
            },
            "collaboration": {
                "title": "பல்கலைக்கழக கூட்டுறவு மையம்",
                "academicPacts": "கல்வி கூட்டணிகள்",
                "joinConsortium": "கூட்டமைப்பில் சேருங்கள்",
                "jointResearch": "கூட்டு ஆராய்ச்சி முயற்சிகள்",
                "mouSigned": "கையொப்பமிடப்பட்ட ஒப்பந்தங்கள்"
            },
            "prototypes": {
                "title": "தொழில்நுட்ப முன்மாதிரிகள்",
                "technologyDemonstrators": "குடிமக்கள் முன்மாதிரிகள்",
                "readyForDeployment": "பயன்பாட்டிற்கு தயார்",
                "pilotTested": "களத்தில் சோதிக்கப்பட்டது",
                "commercialize": "வணிகமயமாக்குங்கள்"
            },
            "tracking": {
                "title": "நிதி மற்றும் மைல்கல் கண்காணிப்பு",
                "milestoneProgress": "மைல்கல் நிறைவு",
                "verificationCheck": "மூன்றாம் தரப்பு தணிக்கை சரிபார்ப்பு",
                "fundRelease": "தவணை வெளியீடு"
            },
            "profile": {
                "title": "அமைப்பு சுயவிவரம்",
                "companyName": "நிறுவனத்தின் பெயர்",
                "cinRegistration": "கார்ப்பரேட் அடையாளம் (CIN)",
                "csrBudget": "ஆண்டு CSR நிதி",
                "contactPerson": "CSR தலைவர் / தொடர்பு",
                "panNumber": "நிறுவன பான் எண்"
            },
            "settings": {
                "title": "CSR அமைப்புகள்",
                "emailNotifications": "செயல்பாட்டு எச்சரிக்கைகள்",
                "bankDetails": "வங்கி விவரங்கள்",
                "complianceDocs": "இணக்க ஆவணங்கள்"
            }
        },
        "ngo": {
            "portalTitle": "சமூக அமைப்புகள் மற்றும் தன்னார்வலர் தளம்",
            "dashboard": {
                "title": "சமூக அமைப்புகள் முகப்பு",
                "overview": "கள செயல்பாடுகள் கண்ணோட்டம்",
                "groundSquads": "செயலில் உள்ள படைகள்",
                "activeVolunteers": "பதிவு செய்த தன்னார்வலர்கள்",
                "fieldInterventions": "கள தலையீடுகள்",
                "reliefOperations": "நிவாரண பணிகள்",
                "communityImpact": "பயனடைந்த குடிமக்கள்",
                "certsAwarded": "வழங்கப்பட்ட சான்றிதழ்கள்",
                "urgentReliefCalls": "அவசர நிவாரண அழைப்புகள்",
                "groundTelemetryLive": "கள தொலை அளவியல் நேரலை",
                "logFieldEvidence": "கள ஆதாரத்தை பதிவு செய்"
            },
            "projects": {
                "title": "சமூக திட்டங்கள்",
                "localGrievances": "குடிமக்கள் குறைகளை ஏற்கவும்",
                "adoptIssue": "படையை திரட்டுங்கள்",
                "publicWorks": "சமூக நல இயக்கங்கள்",
                "grassrootInterventions": "அடிமட்ட தலையீடுகள்"
            },
            "assignedProjects": {
                "title": "ஒதுக்கப்பட்ட NGO திட்டங்கள்",
                "operationalSquads": "செயல்பாட்டு படைகள்",
                "projectTimeline": "செயல்படுத்தல் காலவரிசை",
                "targetCompletion": "இலக்கு நிறைவு தேதி",
                "submitProgressReport": "முன்னேற்ற அறிக்கையை சமர்ப்பிக்கவும்"
            },
            "fieldActivities": {
                "title": "கள ஆதார பதிவு",
                "liveReliefLog": "நேரலை கள பதிவுகள்",
                "geoTaggedPhotos": "புவி-குறிக்கப்பட்ட புகைப்படங்கள்",
                "suppliesDistributed": "வழங்கப்பட்ட உதவிகள்",
                "citizensAssisted": "உதவி பெற்ற குடிமக்கள்",
                "addLogEntry": "புதிய பதிவைச் சமர்ப்பிக்கவும்"
            },
            "volunteers": {
                "title": "தன்னார்வலர் மேலாண்மை",
                "registerVolunteer": "புதிய தன்னார்வலரை பதிவு செய்",
                "skillsDirectory": "திறன்கள் அடைவு",
                "assignWard": "வார்டை ஒதுக்குங்கள்",
                "volunteerSquads": "களப் படைகள்",
                "attendance": "கள வருகை"
            },
            "impact": {
                "title": "சமூக தாக்க பகுப்பாய்வு",
                "livesImpacted": "பயனடைந்த குடிமக்கள்",
                "wardsTransformed": "மாற்றமடைந்த நகராட்சி வார்டுகள்",
                "satisfactionIndex": "திருப்தி குறியீடு",
                "volunteerHours": "மொத்த தன்னார்வ நேரம்"
            },
            "collaborations": {
                "title": "கூட்டாண்மைகள் மற்றும் கூட்டணிகள்",
                "municipalMoU": "நகராட்சி கூட்டு ஒப்பந்தங்கள்",
                "corporateSponsors": "கார்ப்பரேட் CSR பங்காளிகள்",
                "universityAlliances": "பல்கலைக்கழக மாணவர் கூட்டணிகள்"
            },
            "certificates": {
                "title": "சான்றிதழ்கள் மற்றும் பேட்ஜ்கள்",
                "awardCertificate": "பாராட்டு சான்றிதழ் வழங்கவும்",
                "downloadBadge": "டிஜிட்டல் பேட்ஜை பதிவிறக்கவும்",
                "recognitionLetter": "நகராட்சி பாராட்டு கடிதம்"
            },
            "reports": {
                "title": "கள தணிக்கை மற்றும் செயல்பாட்டு அறிக்கைகள்",
                "fieldAuditReports": "கள சரிபார்ப்பு அறிக்கைகள்",
                "monthlyActivitySummary": "மாதாந்திர செயல்பாட்டு சுருக்கம்",
                "incidentLogSheet": "சம்பவ பதில் பதிவு",
                "submitToGovernment": "அரசுக்கு அறிக்கை அனுப்பவும்"
            },
            "settings": {
                "title": "NGO சுயவிவரம் மற்றும் அமைப்புகள்",
                "registrationDetails": "அறக்கட்டளை பதிவு விவரங்கள்",
                "ngoDarpanId": "நிதி ஆயோக் தர்பன் ஐடி",
                "focalPoints": "கள ஒருங்கிணைப்பாளர்கள்"
            }
        },
        "university": {
            "portalTitle": "பல்கலைக்கழகம் மற்றும் கல்வி தளம்",
            "student": {
                "dashboard": {
                    "title": "மாணவர் கண்டுபிடிப்பு முகப்பு",
                    "academicCredits": "ஈட்டிய கல்வி வரவுகள்",
                    "assignedTasks": "ஒதுக்கப்பட்ட ஆய்வக பணிகள்",
                    "labProjects": "ஆராய்ச்சி திட்டங்கள்",
                    "prototypeChallenges": "புதுமை சவால்கள்",
                    "submitMilestone": "மைல்கல்லை சமர்ப்பிக்கவும்"
                },
                "tasks": {
                    "title": "ஆய்வக பணிகள்",
                    "pendingTasks": "நிலுவையில் உள்ள பணிகள்",
                    "taskDescription": "பணி வழிமுறைகள்",
                    "dueDate": "சமர்ப்பிக்கும் காலக்கெடு",
                    "submitDeliverable": "தீர்வை சமர்ப்பிக்கவும்",
                    "advisorNotes": "ஆலோசகர் குறிப்புகள்",
                    "dueTasks": "விரைவில் முடிக்க வேண்டிய பணிகள்"
                },
                "uploads": {
                    "title": "பணிகளை பதிவேற்றவும்",
                    "researchNotes": "ஆராய்ச்சி குறிப்புகள் மற்றும் அறிக்கைகள்",
                    "projectCode": "மூலக் குறியீடு களஞ்சியம்",
                    "presentationSlides": "விளக்கக்காட்சி ஸ்லைடுகள்",
                    "submitForGrading": "மதிப்பாய்வுக்கு சமர்ப்பிக்கவும்"
                },
                "timeline": {
                    "title": "மைல்கல் காலவரிசை",
                    "projectSchedule": "திட்ட அட்டவணை",
                    "semesterDeadlines": "பருவ காலக்கெடு",
                    "facultyReviewDate": "திட்டமிடப்பட்ட மறுஆய்வு"
                },
                "messages": {
                    "title": "ஆலோசகர் கலந்துரையாடல்",
                    "chatWithMentor": "வழிகாட்டியுடன் உரையாடவும்",
                    "feedbackThread": "கருத்து மற்றும் திருத்தங்கள்",
                    "askQuestion": "கேள்வி கேளுங்கள்"
                }
            },
            "faculty": {
                "dashboard": {
                    "title": "பேராசிரியர் வழிகாட்டி முகப்பு",
                    "studentCohorts": "மாணவர் குழுக்கள்",
                    "mentoredProjects": "வழிகாட்டப்பட்ட திட்டங்கள்",
                    "pendingApprovals": "நிலுவையில் உள்ள ஒப்புதல்கள்",
                    "researchPapers": "வெளியிடப்பட்ட ஆய்வுக் கட்டுரைகள்",
                    "innovationIndex": "புதுமை குறியீடு"
                },
                "approvals": {
                    "title": "மைல்கல் ஒப்புதல்கள்",
                    "reviewSubmission": "சமர்ப்பிப்பை மறுஆய்வு செய்",
                    "approveMilestone": "மைல்கல்லை அங்கீகரி",
                    "rejectMilestone": "திருத்தத்தைக் கோரு",
                    "provideFeedback": "கருத்து மற்றும் மதிப்பீடு",
                    "gradeAwarded": "வழங்கப்பட்ட கல்வி வரவு",
                    "pendingReviews": "நிலுவையில் உள்ள மறுஆய்வுகள்"
                },
                "proposals": {
                    "title": "நகராட்சி ஆராய்ச்சி முன்மொழிவுகள்",
                    "civicResearchTopics": "குடிமக்கள் பிரச்சினை அறிக்கைகள்",
                    "grantProposals": "கூட்டு ஆராய்ச்சி மானியங்கள்",
                    "callForPapers": "தீர்வுகளுக்கான அழைப்பு",
                    "openProposals": "திறந்த முன்மொழிவுகள்"
                },
                "teams": {
                    "title": "மாணவர் ஆராய்ச்சிக் குழுக்கள்",
                    "teamRoster": "குழு உறுப்பினர்கள்",
                    "assignLead": "தலைவரை நியமிக்கவும்",
                    "performanceReview": "அவ்வப்போதைய மதிப்பீடு",
                    "academicAdvising": "கல்வி வழிகாட்டல்"
                },
                "reports": {
                    "title": "கல்வி பகுப்பாய்வு மற்றும் அறிக்கைகள்",
                    "cohortProgress": "குழு முன்னேற்ற கண்காணிப்பான்",
                    "publicationOutput": "கல்வி வெளியீடு",
                    "creditDistribution": "வரவு விநியோகம்"
                }
            },
            "shared": {
                "projects": {
                    "title": "ஆராய்ச்சி திட்டங்கள்",
                    "studentResearch": "மாணவர் ஆராய்ச்சி முயற்சிகள்",
                    "capstoneProjects": "கேப்ஸ்டோன் திட்டங்கள்",
                    "interdisciplinaryTeams": "பல்துறை குழுக்கள்"
                },
                "research": {
                    "title": "ஆராய்ச்சி மையம்",
                    "publications": "வெளியீடுகள்",
                    "datasets": "பொது தரவுத்தொகுப்புகள்",
                    "patentFiling": "காப்புரிமை விண்ணப்பங்கள்",
                    "peerReview": "சக மதிப்பாய்வு அடைவு"
                },
                "innovation": {
                    "title": "புதுமை ஆய்வகம்",
                    "innovationChallenges": "ஹேக்கத்தான்கள் மற்றும் சவால்கள்",
                    "hackathonDemos": "முன்மாதிரி காட்சி",
                    "incubatorReady": "இன்குபேட்டர் நிலை",
                    "smartCityPrototypes": "ஸ்மார்ட் சிட்டி செய்முறைகள்"
                },
                "credits": {
                    "title": "கல்வி வரவுகள் மற்றும் அங்கீகாரம்",
                    "creditsEarned": "பெற்ற வரவுகள்",
                    "skillBadges": "திறன் பேட்ஜ்கள்",
                    "hallOfFame": "புகழ் அரங்கம்",
                    "transcriptVerification": "சரிபார்க்கப்பட்ட டிரான்ஸ்கிரிப்ட்"
                },
                "repository": {
                    "title": "கல்வி களஞ்சியம்",
                    "researchPapersArchive": "ஆய்வுக் கட்டுரைகள் காப்பகம்",
                    "openDataVault": "திறந்த தரவு பெட்டகம்",
                    "citationIndex": "மேற்கோள் குறியீடு"
                },
                "settings": {
                    "title": "பல்கலைக்கழக அமைப்புகள்",
                    "facultyProfile": "நிறுவன சுயவிவரம்",
                    "departmentAffiliation": "துறை தொடர்பு",
                    "orcidId": "ORCID / ஆராய்ச்சியாளர் ஐடி"
                }
            }
        },
        "admin": {
            "portalTitle": "மத்திய கட்டளை மற்றும் தள நிர்வாகம்",
            "dashboard": {
                "title": "தள நிர்வாக பலகை",
                "totalSystemUsers": "மொத்த பதிவு செய்த பயனர்கள்",
                "activePortals": "செயலில் உள்ள தளங்கள்",
                "aiModelStatus": "AI மாதிரி ஆரோக்கியம்",
                "databaseHealth": "தரவுத்தள தாமதம்",
                "unresolvedGrievances": "தீர்க்கப்படாத புகார்கள்",
                "platformLoad": "சர்வர் சுமை",
                "liveEventStream": "நேரலை தணிக்கை ஓட்டம்",
                "rootConsole": "ரூட் கன்சோல்",
                "cpuUsage": "CPU பயன்பாடு",
                "dbLatency": "தரவுத்தள வினவல் தாமதம்",
                "uptime": "கணினி இயக்க நேரம்"
            },
            "users": {
                "title": "பயனர் மற்றும் பங்கு மேலாண்மை",
                "allUsers": "அனைத்து பயனர்கள்",
                "addUser": "பயனரை சேர்",
                "editRole": "பங்கை மாற்றவும்",
                "suspendUser": "கணக்கை இடைநிறுத்து",
                "resetPassword": "கடவுச்சொல்லை மீட்டமை",
                "roleFilter": "பங்கு அடிப்படையில் வடிகட்டு",
                "searchUsers": "பெயர், மின்னஞ்சல் மூலம் தேடுங்கள்..."
            },
            "roles": {
                "title": "பங்கு மற்றும் அனுமதி மேலாண்மை",
                "permissionsMatrix": "அணுகல் கட்டுப்பாட்டு மேட்ரிக்ஸ்",
                "accessControl": "பாதுகாப்புக் கொள்கைகள்",
                "createRole": "புதிய பங்கை வரையறுக்கவும்",
                "customRoles": "கட்டமைக்கப்பட்ட பங்குகள்"
            },
            "government": {
                "title": "நகராட்சி நிர்வாக கட்டுப்பாடு",
                "municipalBOD": "நகராட்சி அமைப்புகள்",
                "cityDistricts": "மாவட்ட அதிகார வரம்புகள்",
                "assignWardEngineers": "வார்டு பொறியாளர்களை நியமிக்கவும்"
            },
            "universities": {
                "title": "பல்கலைக்கழக அங்கீகார மேலாண்மை",
                "registeredCampuses": "இணைந்த பல்கலைக்கழகங்கள்",
                "accreditationVerify": "NAAC / UGC சரிபார்ப்பு",
                "studentCap": "மாணவர் சேர்க்கை ஒதுக்கீடு"
            },
            "industry": {
                "title": "தொழில்துறை கூட்டாளர் மேற்பார்வை",
                "corporatePartners": "பதிவு செய்த CSR கூட்டாளர்கள்",
                "csrValidation": "பிரிவு 135 தகுதி சரிபார்ப்பு",
                "escrowAudits": "எஸ்க்ரோ வழங்கல் தணிக்கை"
            },
            "ngos": {
                "title": "தன்னார்வ அமைப்புகள் மேற்பார்வை",
                "verifiedNgos": "அங்கீகரிக்கப்பட்ட NGOக்கள்",
                "darpanCheck": "NGO தர்பன் சரிபார்ப்பு",
                "groundClearance": "கள அனுமதி சான்றிதழ்கள்"
            },
            "research": {
                "title": "ஆராய்ச்சி நிறுவனங்கள் மேற்பார்வை",
                "institutePartnerships": "ஆராய்ச்சி கூட்டாளர்கள்",
                "ethicsClearance": "நெறிமுறைகள் மறுஆய்வு வாரியம்",
                "datasetAccess": "தரவு அணுகல் அனுமதிகள்"
            },
            "departments": {
                "title": "துறை முதன்மை கட்டமைப்பு",
                "routingRules": "தானியங்கி ரூட்டிங் விதிகள்",
                "autoAssignmentEngine": "AI ஒதுக்கீட்டு இயந்திரம்",
                "fallbackQueues": "மாற்று வரிசைகள்"
            },
            "issues": {
                "title": "தள புகார் மேலாண்மை",
                "forceResolve": "நிர்வாக தீர்வு",
                "reassignCluster": "கிளஸ்டரை மறுஒதுக்கீடு செய்",
                "auditLog": "செயல் பதிவு",
                "purgeTestData": "சோதனை தரவை நீக்கு"
            },
            "aiMonitoring": {
                "title": "AI பார்வை மற்றும் தொலை அளவியல் கண்காணிப்பு",
                "geminiVisionUptime": "விஷன் மாதிரி இயக்க நேரம்",
                "fastApiOcrStatus": "FastAPI OCR பைப்லைன்",
                "speechToTextLatency": "STT தாமதம்",
                "accuracyScore": "துல்லிய மதிப்பெண்",
                "confidenceDistribution": "நம்பிக்கை விநியோகம்",
                "modelLogs": "தாமத பதிவுகள்"
            },
            "workflowMonitoring": {
                "title": "பணிப்பாய்வு இயந்திரம் மற்றும் வரிசை கண்காணிப்பு",
                "stateMachineInspect": "நிலை மாற்றங்கள்",
                "queueDepth": "செய்தி வரிசை ஆழம்",
                "deadLetterQueue": "தோல்வியடைந்த வரிசை",
                "retryFailedTasks": "தோல்வியடைந்த பணிகளை மீண்டும் முயற்சிக்கவும்"
            },
            "analytics": {
                "title": "தள மேக்ரோ பகுப்பாய்வு",
                "crossPortalActivity": "தள பயன்பாட்டு அளவீடுகள்",
                "municipalPerformanceIndex": "நகராட்சி செயல்திறன் குறியீடு",
                "peakUsageHours": "அதிக பயன்பாட்டு நேரம்"
            },
            "systemHealth": {
                "title": "உள்கட்டமைப்பு மற்றும் கணினி ஆரோக்கியம்",
                "databaseReplicas": "தரவுத்தள பிரதிகள்",
                "redisCache": "ரெடிஸ் நினைவகம்",
                "storageUsage": "சேமிப்பக அளவு",
                "apiGateways": "மைக்ரோசர்வீஸ் ஆரோக்கியம்",
                "uptime99": "99.98% உயர் கிடைக்கும் தன்மை",
                "online": "இணைப்பில்",
                "maintenance": "பராமரிப்பு"
            },
            "settings": {
                "title": "தள அமைப்புகள்",
                "maintenanceMode": "பராமரிப்பு முறை",
                "apiRateLimits": "API வரம்புகள்",
                "backupSchedules": "தானியங்கி காப்புப்பிரதி அட்டவணை",
                "smtpConfig": "SMTP மற்றும் மின்னஞ்சல் நுழைவாயில்கள்"
            }
        },
        "toast": {
            "issueSubmitted": "குறைதீர்ப்பு வெற்றிகரமாக சமர்ப்பிக்கப்பட்டது! பொறுப்பான துறைக்கு அனுப்பப்பட்டது.",
            "gpsCaptured": "GPS ஆயத்தொலைவுகள் பிடிக்கப்பட்டன",
            "gpsCapturedDesc": "ஆயத்தொலைவுகள் புகார் அறிக்கையுடன் இணைக்கப்பட்டுள்ளன.",
            "locationDenied": "இருப்பிட அனுமதி மறுக்கப்பட்டது. இயல்புநிலை இருப்பிடம் பயன்படுத்தப்படுகிறது.",
            "fileSizeExceeded": "கோப்பு 25MB வரம்பை தாண்டியது.",
            "audioNotSupported": "இந்த உலாவியில் ஆடியோ பதிவு ஆதரிக்கப்படவில்லை.",
            "micSimulation": "குரல் புகாருக்கான மைக்ரோஃபோன் உருவகப்படுத்துதல் செயலில் உள்ளது.",
            "profileUpdated": "சுயவிவரம் வெற்றிகரமாக புதுப்பிக்கப்பட்டது.",
            "settingsSaved": "விருப்பத்தேர்வுகள் வெற்றிகரமாக சேமிக்கப்பட்டன.",
            "deleteRequested": "கணக்கு நீக்குதல் கோரிக்கை சமர்ப்பிக்கப்பட்டது.",
            "languageChanged": "மொழி வெற்றிகரமாக மாற்றப்பட்டது.",
            "errorOccurred": "ஒரு பிழை ஏற்பட்டது. தயவுசெய்து மீண்டும் முயற்சிக்கவும்.",
            "caseUpdated": "வழக்கு வெற்றிகரமாக புதுப்பிக்கப்பட்டது.",
            "caseReassigned": "வழக்கு நோடல் அதிகாரிக்கு மறுஒதுக்கீடு செய்யப்பட்டது.",
            "caseResolved": "குறைதீர்ப்பு தீர்க்கப்பட்டதாகக் குறிக்கப்பட்டது.",
            "volunteerAdded": "புதிய தன்னார்வலர் வெற்றிகரமாக பதிவு செய்யப்பட்டார்.",
            "grantApproved": "CSR மானிய ஒதுக்கீடு அங்கீகரிக்கப்பட்டது.",
            "milestoneApproved": "கல்வி மைல்கல் அங்கீகரிக்கப்பட்டது.",
            "deliverableUploaded": "ஆய்வக பணி வெற்றிகரமாக பதிவேற்றப்பட்டது.",
            "loginSuccess": "வெற்றிகரமாக உள்நுழைந்தீர்கள். நல்வரவு!",
            "logoutSuccess": "வெற்றிகரமாக வெளியேறினீர்கள்.",
            "accessDenied": "அணுகல் மறுக்கப்பட்டது. போதிய அனுமதி இல்லை.",
            "changesSaved": "அனைத்து மாற்றங்களும் வெற்றிகரமாக சேமிக்கப்பட்டன.",
            "reportExported": "அறிக்கை உருவாக்கப்பட்டு பதிவிறக்கப்பட்டது.",
            "dataRefreshed": "தொலை அளவியல் தரவு புதுப்பிக்கப்பட்டது."
        },
        "language": "மொழி",
        "dashboard": "முகப்பு பலகை",
        "report_issue": "புகார் அளிக்கவும்",
        "report_problem": "புகார் அளிக்கவும்",
        "my_issues": "என் புகார்கள்",
        "track_issues": "தீர்வை கண்காணிக்கவும்",
        "notifications": "அறிவிப்புகள்",
        "profile": "சுயவிவரம்",
        "settings": "அமைப்புகள்",
        "help": "உதவி & ஆதரவு",
        "logout": "வெளியேறு",
        "login": "உள்நுழை",
        "recent_grievances": "சமீபத்திய புகார்கள்",
        "issue_id": "புகார் ஐடி",
        "citizen_portal": "குடிமக்கள் தளம்",
        "government_portal": "அரசு தளம்",
        "university_portal": "பல்கலைக்கழக தளம்",
        "industry_portal": "தொழில்துறை தளம்",
        "ngo_portal": "தன்னார்வ அமைப்பு தளம்",
        "admin_portal": "நிர்வாக தளம்",
        "ai_governance_insight": "AI ஆட்சி நுண்ணறிவு",
        "resolution": "தீர்வு",
        "report": "அறிக்கைகள்",
        "map": "சம்பவ வரைபடம்",
        "search": "தேடு",
        "search_placeholder": "புகார்கள், வழக்குகள், இடங்களைத் தேடுங்கள்...",
        "filter": "வடிகட்டு",
        "save": "சேமி",
        "cancel": "ரத்து செய்",
        "delete": "நீக்கு",
        "submit": "சமர்ப்பி",
        "upload": "பதிவேற்று",
        "location": "இருப்பிடம்",
        "description": "விளக்கம்",
        "title": "தலைப்பு",
        "category": "வகை",
        "department": "துறை",
        "created_at": "பதிவு செய்யப்பட்ட தேதி",
        "action": "நடவடிக்கை",
        "actions": "நடவடிக்கைகள்",
        "view": "காண்க",
        "edit": "திருத்து",
        "loading": "ஏற்றுகிறது...",
        "success": "வெற்றி",
        "error": "ஒரு பிழை ஏற்பட்டது",
        "welcome_back": "மீண்டும் வருக",
        "total_issues": "மொத்த புகார்கள்",
        "resolved_issues": "தீர்க்கப்பட்ட புகார்கள்",
        "in_progress_issues": "செயல்பாட்டில் உள்ள புகார்கள்",
        "pending_issues": "நிலுவையில் உள்ள புகார்கள்",
        "active_projects": "செயலில் உள்ள திட்டங்கள்",
        "ai_accuracy": "AI ரூட்டிங் துல்லியம்",
        "sla_compliance": "SLA இணக்க விகிதம்",
        "civic_engagement": "குடிமக்கள் ஈடுபாடு குறியீடு",
        "recent_activity": "சமீபத்திய செயல்பாடு",
        "quick_actions": "விரைவு நடவடிக்கைகள்",
        "live_incidents": "நேரலை குடிமக்கள் நிகழ்வுகள்",
        "all": "அனைத்தும்",
        "high": "உயர் முன்னுரிமை",
        "medium": "நடுத்தர முன்னுரிமை",
        "low": "குறைந்த முன்னுரிமை",
        "critical": "முக்கிய முன்னுரிமை",
        "emergency": "அவசர முன்னுரிமை",
        "pending": "நிலுவையில் உள்ளது",
        "in_progress": "செயல்பாட்டில் உள்ளது",
        "resolved": "தீர்க்கப்பட்டது",
        "closed": "மூடப்பட்டது",
        "rejected": "நிராகரிக்கப்பட்டது",
        "approved": "ஒப்புதல் அளிக்கப்பட்டது",
        "declined": "நிராகரிக்கப்பட்டது",
        "export": "ஏற்றுமதி செய்",
        "download": "பதிவிறக்கு",
        "confirm": "உறுதிப்படுத்து",
        "close": "மூடு",
        "back": "பின்செல்",
        "next": "அடுத்து",
        "previous": "முந்தைய",
        "no_results": "முடிவுகள் எதுவும் இல்லை",
        "view_all": "அனைத்தையும் காண்க",
        "home": "முகப்பு",
        "feed": "குடிமக்கள் ஊட்டம்",
        "analytics": "AI பகுப்பாய்வு",
        "optional": "விருப்பத்திற்குரியது",
        "faculty": "பேராசிரியர்",
        "student": "மாணவர்",
        "projects": "திட்டங்கள்",
        "research": "ஆராய்ச்சி மையம்",
        "innovation": "புதுமை சவால்கள்",
        "teams": "குழுக்கள்",
        "credits": "கல்வி வரவுகள்",
        "officers": "அதிகாரிகள்",
        "assigned": "ஒதுக்கப்பட்டவை",
        "under_review": "மறுஆய்வில் உள்ளது",
        "industry_assigned": "தொழில்துறைக்கு ஒதுக்கப்பட்டது",
        "industry_review": "தொழில்துறை மறுஆய்வு",
        "univ_assigned": "பல்கலைக்கழகத்திற்கு ஒதுக்கப்பட்டது",
        "student_dev": "மாணவர் மேம்பாடு",
        "faculty_review": "பேராசிரியர் மறுஆய்வு",
        "industry_val": "தொழில்துறை சரிபார்ப்பு",
        "inspection": "தள ஆய்வு",
        "feedback": "கருத்து நிலுவையில் உள்ளது"
    }
