# -*- coding: utf-8 -*-
"""Malayalam (ml) translations dictionary for SOCIAL-X platform"""

def get_ml_dict():
    return {
    "nav": {
        "overview": "അവലോകനം",
        "access_identity": "പ്രവേശനവും ഐഡന്റിറ്റിയും",
        "stakeholder_ecosystem": "പങ്കാളിത്ത ഇക്കോസിസ്റ്റം",
        "operations_ai": "പ്രവർത്തനങ്ങളും AI-യും",
        "infra_observability": "അടിസ്ഥാന സൗകര്യങ്ങളും നിരീക്ഷണവും",
        "field_activities": "ഫീൽഡ് പ്രവർത്തനങ്ങളും ദുരിതാശ്വാസവും",
        "community_workforce": "കമ്മ്യൂണിറ്റിയും തൊഴിൽ ശക്തിയും",
        "governance_comms": "ഭരണവും ആശയവിനിമയവും",
        "csr_investment": "CSR & മൂലധന വിഹിതം",
        "collaboration_rd": "സഹകരണവും ഗവേഷണവും",
        "student_portal": "വിദ്യാർത്ഥി പോർട്ടൽ",
        "faculty_portal": "അധ്യാപക പോർട്ടൽ",
        "dashboard": "ഡാഷ്‌ബോർഡ്",
        "my_issues": "എന്റെ പരാതികൾ",
        "report_problem": "പരാതി രജിസ്റ്റർ ചെയ്യുക",
        "track_issues": "പരിഹാരം ട്രാക്ക് ചെയ്യുക",
        "notifications": "അറിയിപ്പുകൾ",
        "profile": "പ്രൊഫൈൽ",
        "settings": "ക്രമീകരണങ്ങൾ",
        "help": "സഹായവും പിന്തുണയും",
        "logout": "ലോഗ് ഔട്ട്",
        "login": "ലോഗിൻ",
        "analytics": "അനലിറ്റിക്സും റിപ്പോർട്ടുകളും",
        "assigned_cases": "നിയോഗിച്ച കേസുകൾ",
        "departments": "വകുപ്പുകൾ",
        "officers": "ഉദ്യോഗസ്ഥരുടെ ഡയറക്ടറി",
        "ai_suggestions": "AI നിർദ്ദേശങ്ങൾ",
        "reports": "റിപ്പോർട്ടുകളും ഓഡിറ്റുകളും",
        "projects": "ലഭ്യമായ പ്രോജക്റ്റുകൾ",
        "funding": "ഫണ്ടിംഗ് അവസരങ്ങൾ",
        "csr_analytics": "CSR അനലിറ്റിക്സ്",
        "mentorship": "മെന്റർഷിപ്പ്",
        "university_collaboration": "സർവ്വകലാശാല സഹകരണം",
        "research": "ഗവേഷണ സംരംഭങ്ങൾ",
        "prototypes": "പ്രോട്ടോടൈപ്പുകളും ഡെമോകളും",
        "volunteers": "സന്നദ്ധപ്രവർത്തക സംഘങ്ങൾ",
        "field_log": "ഫീൽഡ് തെളിവ് രേഖ",
        "impact": "കമ്മ്യൂണിറ്റി സ്വാധീനം",
        "certificates": "സർട്ടിഫിക്കറ്റുകളും ബാഡ്ജുകളും",
        "lab_tasks": "ലാബ് ടാസ്കുകൾ",
        "upload_deliverables": "റിപ്പോർട്ടുകൾ അപ്‌ലോഡ് ചെയ്യുക",
        "milestone_timeline": "മൈൽസ്റ്റോൺ ടൈംലൈൻ",
        "advisor_discussion": "ഉപദേശക ചർച്ച",
        "milestone_approvals": "മൈൽസ്റ്റോൺ അംഗീകാരങ്ങൾ",
        "municipal_proposals": "മുനിസിപ്പൽ നിർദ്ദേശങ്ങൾ",
        "teams": "ടീമുകളും അംഗങ്ങളും",
        "credits": "അക്കാദമിക് ക്രെഡിറ്റുകൾ",
        "user_management": "ഉപയോക്തൃ മാനേജ്മെന്റ്",
        "role_management": "റോൾ മാനേജ്മെന്റ്",
        "government_management": "സർക്കാർ മാനേജ്മെന്റ്",
        "university_management": "സർവ്വകലാശാല മാനേജ്മെന്റ്",
        "industry_management": "വ്യവസായ മാനേജ്മെന്റ്",
        "ngo_management": "എൻ‌ജി‌ഒ മാനേജ്മെന്റ്",
        "research_organizations": "ഗവേഷണ സ്ഥാപനങ്ങൾ",
        "issue_management": "പരാതി പരിഹാര മാനേജ്മെന്റ്",
        "ai_monitoring": "AI ടെലിമെട്രി നിരീക്ഷണം",
        "workflow_monitoring": "വർക്ക്ഫ്ലോ നിരീക്ഷണം",
        "audit_logs": "ഓഡിറ്റ് രേഖകൾ",
        "system_health": "സിസ്റ്റം ആരോഗ്യം",
        "landing_features": "സവിശേഷതകൾ",
        "landing_how_it_works": "ഇത് എങ്ങനെ പ്രവർത്തിക്കുന്നു",
        "landing_about": "ഞങ്ങളെക്കുറിച്ച്",
        "landing_faq": "പതിവ് ചോദ്യങ്ങൾ (FAQ)",
        "landing_contact": "ബന്ധപ്പെടുക",
        "role_login": "റോൾ ലോഗിൻ",
        "citizen_sign_up": "പൗര രജിസ്ട്രേഷൻ"
    },
    "common": {
        "buttons": {
            "browseFiles": "ഫയലുകൾ ബ്രൗസ് ചെയ്യുക",
            "openCamera": "ക്യാമറ തുറക്കുക",
            "startRecording": "റെക്കോർഡിംഗ് ആരംഭിക്കുക",
            "stopRecording": "റെക്കോർഡിംഗ് നിർത്തുക",
            "submit": "സമർപ്പിക്കുക",
            "cancel": "റദ്ദാക്കുക",
            "save": "മാറ്റങ്ങൾ സേവ് ചെയ്യുക",
            "delete": "ഡിലീറ്റ് ചെയ്യുക",
            "search": "തിരയുക",
            "filter": "ഫിൽട്ടർ ചെയ്യുക",
            "upload": "അപ്‌ലോഡ് ചെയ്യുക",
            "confirm": "സ്ഥിരീകരിക്കുക",
            "close": "അടയ്ക്കുക",
            "back": "പുറകിലേക്ക്",
            "next": "അടുത്തത്",
            "previous": "മുമ്പത്തെ",
            "detectLocation": "നിലവിലെ ലൊക്കേഷൻ കണ്ടെത്തുക",
            "useCurrentGps": "നിലവിലെ GPS ഉപയോഗിക്കുക",
            "resetForm": "ഫോം റീസെറ്റ് ചെയ്യുക",
            "submitIssue": "പരാതി സമർപ്പിക്കുക",
            "viewAll": "എല്ലാം കാണുക",
            "export": "ഡാറ്റ കയറ്റുമതി ചെയ്യുക",
            "download": "ഡൗൺലോഡ്",
            "refresh": "പുതുക്കുക",
            "login": "ലോഗിൻ",
            "logout": "ലോഗ് ഔട്ട്",
            "modifyUploads": "അപ്‌ലോഡുകൾ മാറ്റുക",
            "removeFile": "ഫയൽ നീക്കം ചെയ്യുക",
            "removeVoiceMemo": "വോയ്‌സ് മെമ്മോ നീക്കം ചെയ്യുക",
            "edit": "എഡിറ്റ് ചെയ്യുക",
            "view": "വിശദാംശങ്ങൾ കാണുക",
            "add": "പുതിയത് ചേർക്കുക",
            "create": "സൃഷ്ടിക്കുക",
            "update": "അപ്ഡേറ്റ് ചെയ്യുക",
            "approve": "അംഗീകരിക്കുക",
            "reject": "നിരസിക്കുക",
            "reassign": "പുനർനിയമിക്കുക",
            "escalate": "മേലധികാരിക്ക് അയക്കുക",
            "resolve": "പരിഹരിക്കുക",
            "assign": "നിയോഗിക്കുക",
            "verify": "സ്ഥിരീകരിക്കുക",
            "downloadReport": "റിപ്പോർട്ട് ഡൗൺലോഡ് ചെയ്യുക",
            "syncTelemetry": "ടെലിമെട്രി സമന്വയിപ്പിക്കുക",
            "applyFilters": "ഫിൽട്ടറുകൾ പ്രയോഗിക്കുക",
            "clearFilters": "ഫിൽട്ടറുകൾ നീക്കുക",
            "viewDetails": "വിശദാംശങ്ങൾ കാണുക",
            "sendNotification": "അറിയിപ്പ് അയക്കുക",
            "inviteMember": "അംഗത്തെ ക്ഷണിക്കുക",
            "print": "പ്രിന്റ് ചെയ്യുക",
            "share": "പങ്കിടുക",
            "copyLink": "ലിങ്ക് പകർത്തുക",
            "proceed": "തുടരുക",
            "retry": "വീണ്ടും ശ്രമിക്കുക",
            "dismiss": "തള്ളിക്കളയുക",
            "accept": "സ്വീകരിക്കുക",
            "decline": "നിരസിക്കുക"
        },
        "labels": {
            "dashboard": "ഡാഷ്‌ബോർഡ്",
            "profile": "പ്രൊഫൈൽ",
            "settings": "ക്രമീകരണങ്ങൾ",
            "notifications": "അറിയിപ്പുകൾ",
            "help": "സഹായവും പിന്തുണയും",
            "logout": "ലോഗ് ഔട്ട്",
            "login": "ലോഗിൻ",
            "status": "നില",
            "priority": "മുൻഗണന",
            "department": "വകുപ്പ്",
            "category": "വിഭാഗം",
            "district": "ജില്ല",
            "ward": "വാർഡ്",
            "address": "വിലാസം",
            "landmark": "പ്രധാന അടയാളം",
            "title": "ശീർഷകം",
            "description": "വിവരണം",
            "location": "ലൊക്കേഷൻ",
            "latitude": "അക്ഷാംശം",
            "longitude": "രേഖാംശം",
            "accuracy": "കൃത്യത",
            "date": "തീയതി",
            "action": "നടപടി",
            "actions": "നടപടികൾ",
            "all": "എല്ലാം",
            "high": "ഉയർന്ന",
            "medium": "ഇടത്തരം",
            "low": "കുറഞ്ഞ",
            "critical": "ഗുരുതരമായ",
            "emergency": "അടിയന്തിരം",
            "pending": "തീർപ്പുകൽപ്പിച്ചിട്ടില്ല",
            "inProgress": "പുരോഗതിയിൽ",
            "resolved": "പരിഹരിച്ചു",
            "closed": "അടച്ചു",
            "rejected": "നിരസിച്ചു",
            "verified": "പരിശോധിച്ചുറപ്പിച്ചു",
            "assigned": "നിയോഗിച്ചു",
            "recentActivity": "സമീപകാല പ്രവർത്തനങ്ങൾ",
            "quickActions": "ദ്രുത നടപടികൾ",
            "systemHealth": "സിസ്റ്റം ആരോഗ്യം",
            "language": "ഭാഷ",
            "selectLanguage": "ഭാഷ തിരഞ്ഞെടുക്കുക",
            "searchLanguage": "ഭാഷ തിരയുക...",
            "editable": "എഡിറ്റ് ചെയ്യാവുന്നത്",
            "active": "സജീവം",
            "inactive": "നിഷ്ക്രിയം",
            "completed": "പൂർത്തിയായി",
            "failed": "പരാജയപ്പെട്ടു",
            "total": "ആകെ",
            "count": "എണ്ണം",
            "rate": "നിരക്ക്",
            "percentage": "ശതമാനം",
            "timeRemaining": "ശേഷിക്കുന്ന സമയം",
            "dueDate": "അവസാന തീയതി",
            "submittedBy": "സമർപ്പിച്ചത്",
            "assignedTo": "നിയോഗിക്കപ്പെട്ട വ്യക്തി",
            "officerInCharge": "ചുമതലയുള്ള ഉദ്യോഗസ്ഥൻ",
            "slaTimer": "SLA ടൈമർ",
            "auditTimeline": "ഓഡിറ്റ് ടൈംലൈൻ",
            "contactInfo": "ബന്ധപ്പെടാനുള്ള വിവരങ്ങൾ",
            "phoneNumber": "ഫോൺ നമ്പർ",
            "emailAddress": "ഇമെയിൽ വിലാസം",
            "fullName": "പൂർണ്ണമായ പേര്",
            "role": "റോൾ",
            "organization": "സ്ഥാപനം",
            "institution": "വിദ്യാഭ്യാസ സ്ഥാപനം",
            "createdAt": "സൃഷ്ടിച്ച തീയതി",
            "updatedAt": "പുതുക്കിയ തീയതി"
        },
        "status": {
            "open": "തുറന്നത്",
            "submitted": "സമർപ്പിച്ചു",
            "verified": "പരിശോധിച്ചുറപ്പിച്ചു",
            "assigned": "നിയോഗിച്ചു",
            "in_progress": "പുരോഗതിയിൽ",
            "inProgress": "പുരോഗതിയിൽ",
            "resolved": "പരിഹരിച്ചു",
            "closed": "അടച്ചു",
            "rejected": "നിരസിച്ചു",
            "under_review": "പരിശോധനയിലാണ്",
            "under_government_review": "സർക്കാർ പരിശോധനയിലാണ്",
            "assigned_to_government": "സർക്കാരിലേക്ക് നൽകി",
            "assigned_to_industry": "വ്യവസായ പങ്കാളിക്ക് നൽകി",
            "industry_review": "വ്യവസായ പരിശോധന",
            "assigned_to_university": "സർവ്വകലാശാലയിലേക്ക് നൽകി",
            "student_development": "വിദ്യാർത്ഥി വികസനം",
            "faculty_review": "അധ്യാപക പരിശോധന",
            "industry_validation": "വ്യവസായ സാധൂകരണം",
            "inspection": "പരിശോധന",
            "feedback_pending": "ഫീഡ്‌ബാക്ക് കാത്തിരിക്കുന്നു",
            "escalated": "മേലധികാരിക്ക് കൈമാറി",
            "active": "സജീവം",
            "inactive": "നിഷ്ക്രിയം",
            "completed": "പൂർത്തിയായി",
            "approved": "അംഗീകരിച്ചു",
            "declined": "നിരസിച്ചു",
            "pending": "തീർപ്പുകൽപ്പിച്ചിട്ടില്ല"
        },
        "priority": {
            "low": "കുറഞ്ഞ മുൻഗണന",
            "medium": "ഇടത്തരം മുൻഗണന",
            "high": "ഉയർന്ന മുൻഗണന",
            "critical": "ഗുരുതരമായ മുൻഗണന",
            "emergency": "അടിയന്തിര മുൻഗണന",
            "urgent": "അടിയന്തിരം"
        },
        "departments": {
            "waterSupply": "ജലവിതരണവും ഡ്രെയിനേജും",
            "roadsTransport": "റോഡുകളും ഗതാഗതവും",
            "electricityPower": "വൈദ്യുതിയും പവർ ഗ്രിഡും",
            "solidWaste": "ഖരമാലിന്യ സംസ്കരണം",
            "publicHealth": "പൊതുജനാരോഗ്യവും ശുചിത്വവും",
            "urbanPlanning": "നഗരാസൂത്രണവും വികസനവും",
            "education": "വിദ്യാഭ്യാസവും നൈപുണ്യവും",
            "environmentForest": "പരിസ്ഥിതിയും വനങ്ങളും",
            "policeSafety": "പോലീസും പൊതു സുരക്ഷയും",
            "disasterManagement": "ദുരന്ത നിവാരണവും ഫയർ ഫോഴ്സും",
            "municipalAdmin": "പൊതു മുനിസിപ്പൽ ഭരണം"
        },
        "categories": {
            "water": "കുടിവെള്ള വിതരണവും ചോർച്ചയും",
            "roads": "റോഡുകളും കുഴികളും",
            "electricity": "വൈദ്യുതിയും തെരുവ് വിളക്കുകളും",
            "waste": "മാലിന്യവും ശുചിത്വവും",
            "health": "പൊതുജനാരോഗ്യവും പരിസര ശുചിത്വവും",
            "sanitation": "ഡ്രെയിനേജ് മലിനജലം",
            "infrastructure": "പൊതു അടിസ്ഥാന സൗകര്യങ്ങൾ",
            "streetlights": "തെരുവ് വിളക്കുകൾ",
            "drainage": "ഓടകളും മലിനജലവും",
            "potholes": "റോഡിലെ കുഴികൾ",
            "traffic": "ഗതാഗതക്കുരുക്ക്",
            "pollution": "മലിനീകരണം"
        },
        "validation": {
            "requiredField": "ഈ ഫീൽഡ് നിർബന്ധമാണ്",
            "titleRequired": "പരാതിയുടെ ശീർഷകം ആവശ്യമാണ്",
            "descriptionRequired": "വിശദമായ വിവരണം ആവശ്യമാണ്",
            "locationRequired": "ലൊക്കേഷൻ ആവശ്യമാണ്",
            "invalidEmail": "ശരിയായ ഇമെയിൽ വിലാസം നൽകുക",
            "invalidPassword": "ശരിയായ പാസ്‌വേഡ് നൽകുക",
            "passwordTooShort": "പാസ്‌വേഡിന് കുറഞ്ഞത് 8 അക്ഷരങ്ങൾ വേണം",
            "passwordMismatch": "പാസ്‌വേഡുകൾ പൊരുത്തപ്പെടുന്നില്ല",
            "unsupportedFile": "ഈ ഫയൽ ഫോർമാറ്റ് പിന്തുണയ്ക്കുന്നില്ല",
            "maxFileSizeExceeded": "ഫയൽ വലുപ്പം 25MB-യിൽ കൂടരുത്",
            "micPermissionDenied": "മൈക്രോഫോൺ അനുമതി നിരസിച്ചു",
            "cameraPermissionDenied": "ക്യാമറ അനുമതി നിരസിച്ചു",
            "minLength": "കുറഞ്ഞ അക്ഷര പരിധി തികയ്ക്കുക",
            "maxLength": "പരമാവധി അക്ഷര പരിധി കവിഞ്ഞു",
            "uploadFailed": "അപ്‌ലോഡ് പരാജയപ്പെട്ടു",
            "uploadSuccessful": "അപ്‌ലോഡ് വിജയകരമായി പൂർത്തിയായി",
            "loginSuccessful": "ലോഗിൻ വിജയകരമായി",
            "registrationSuccessful": "രജിസ്ട്രേഷൻ വിജയകരമായി",
            "fillRequiredFields": "എല്ലാ നിർബന്ധിത ഫീൽഡുകളും പൂരിപ്പിക്കുക"
        },
        "emptyStates": {
            "noData": "ഡാറ്റ ലഭ്യമല്ല",
            "noResults": "തിരച്ചിൽ ഫലങ്ങളൊന്നും കണ്ടെത്തിയില്ല",
            "noNotifications": "പുതിയ അറിയിപ്പുകളൊന്നുമില്ല",
            "noIssuesFound": "പരാതികളൊന്നും കണ്ടെത്തിയില്ല",
            "noProjectsFound": "പ്രോജക്റ്റുകളൊന്നും കണ്ടെത്തിയില്ല",
            "noOfficersFound": "ഉദ്യോഗസ്ഥരെയൊന്നും കണ്ടെത്തിയില്ല",
            "noActivitiesFound": "സമീപകാല പ്രവർത്തനങ്ങളൊന്നുമില്ല"
        },
        "loading": {
            "loading": "ലോഡ് ചെയ്യുന്നു...",
            "pleaseWait": "ദയവായി കാത്തിരിക്കുക...",
            "fetchingData": "ഡാറ്റ എടുക്കുന്നു...",
            "processing": "പ്രോസസ്സ് ചെയ്യുന്നു...",
            "uploadingMedia": "മീഡിയ അപ്‌ലോഡ് ചെയ്യുന്നു...",
            "analyzingAi": "AI വിശകലനം ചെയ്യുന്നു...",
            "savingChanges": "മാറ്റങ്ങൾ സേവ് ചെയ്യുന്നു..."
        },
        "pagination": {
            "previous": "മുമ്പത്തെ",
            "next": "അടുത്തത്",
            "page": "പേജ്",
            "of": "ൽ",
            "rowsPerPage": "ഒരു പേജിലെ വരികൾ",
            "showing": "കാണിക്കുന്നത്",
            "entries": "എൻട്രികൾ",
            "totalRecords": "ആകെ രേഖകൾ"
        },
        "search": {
            "searchPlaceholder": "പരാതികൾ, കേസുകൾ, ലൊക്കേഷൻ തിരയുക...",
            "searchGrievances": "പരാതികൾ തിരയുക...",
            "searchUsers": "ഉപയോക്താക്കളെ തിരയുക...",
            "searchDepartments": "വകുപ്പുകൾ തിരയുക...",
            "searchProjects": "പ്രോജക്റ്റുകൾ തിരയുക...",
            "searchOfficers": "ഉദ്യോഗസ്ഥരെ തിരയുക...",
            "quickNavigator": "ദ്രുത നാവിഗേറ്റർ...",
            "searchAll": "പ്ലാറ്റ്‌ഫോമിൽ എല്ലാം തിരയുക..."
        }
    },
    "ai": {
        "processing": "AI പ്രോസസ്സിംഗ്",
        "ocrResult": "OCR ടെക്സ്റ്റ് വേർതിരിച്ചെടുത്തു",
        "speechResult": "വോയ്‌സ് ട്രാൻസ്ക്രിപ്റ്റ് തയ്യാറായി",
        "speechTranscript": "ശബ്ദ രേഖ",
        "confidenceScore": "AI കോൺഫിഡൻസ് സ്കോർ",
        "aiConfidence": "AI കോൺഫിഡൻസ്",
        "suggestedCategory": "നിർദ്ദേശിച്ച വിഭാഗം",
        "suggestedDepartment": "നിർദ്ദേശിച്ച വകുപ്പ്",
        "recommendedDepartment": "ശുപാർശ ചെയ്ത വകുപ്പ്",
        "suggestedIndustry": "നിർദ്ദേശിച്ച വ്യവസായ പങ്കാളി",
        "duplicateDetection": "സമാന പരാതി കണ്ടെത്തൽ",
        "aiVerification": "വിഷൻ വെരിഫിക്കേഷൻ",
        "smartRouting": "സ്മാർട്ട് ഡിപ്പാർട്ട്മെന്റ് റൂട്ടിംഗ്",
        "previewTitle": "AI വിവരങ്ങളുടെ പ്രിവ്യൂ",
        "previewSubtitle": "കമ്പ്യൂട്ടർ വിഷനും സ്പീച്ച് പൈപ്പ്‌ലൈനുകളും താഴെ പറയുന്ന ഡാറ്റ കണ്ടെത്തി. സമർപ്പിക്കുന്നതിന് മുമ്പ് പരിശോധിക്കുക.",
        "detectedHeadline": "കണ്ടെത്തിയ പരാതി ശീർഷകം",
        "classifiedCategory": "വർഗ്ഗീകരിച്ച വിഭാഗം",
        "dispatchedDept": "അനുവദിച്ച മുനിസിപ്പൽ വകുപ്പ്",
        "severityPriority": "തീവ്രതയും മുൻഗണനയും",
        "mappedLocation": "മാപ്പ് ചെയ്ത ലൊക്കേഷൻ",
        "confirmSubmit": "സ്ഥിരീകരിച്ച് പരാതി അയക്കുക",
        "cancel": "റദ്ദാക്കുക",
        "ocrBadge": "FastAPI OCR പ്രോസസ്സിംഗ്",
        "sttBadge": "സംഭാഷണം ടെക്സ്റ്റാക്കി",
        "verificationStep": "പൗര പരിശോധനാ ഘട്ടം",
        "verificationStepHelp": "കൃത്യത ഉറപ്പാക്കാൻ അന്തിമ സമർപ്പണത്തിന് മുമ്പ് നിങ്ങൾക്ക് മാറ്റങ്ങൾ വരുത്താം.",
        "ocrVision": "OCR വിഷൻ എക്സ്ട്രാക്ഷൻ",
        "noOcrText": "ബോർഡിൽ എഴുത്തുകളൊന്നും കണ്ടെത്തിയില്ല",
        "noAudioMemo": "ഓഡിയോ മെമ്മോ ചേർത്തിട്ടില്ല",
        "priorityScore": "കണക്കാക്കിയ മുൻഗണനാ സ്കോർ",
        "estimatedCost": "കണക്കാക്കിയ മുനിസിപ്പൽ ചെലവ്",
        "estimatedTime": "പ്രതീക്ഷിക്കുന്ന പരിഹാര സമയം",
        "recommendation": "AI ഭരണ ശുപാർശ",
        "confidenceHigh": "ഉയർന്ന കോൺഫിഡൻസ് (>90%)",
        "confidenceMedium": "ഇടത്തരം കോൺഫിഡൻസ് (70-90%)",
        "confidenceLow": "കുറഞ്ഞ കോൺഫിഡൻസ് (<70%)",
        "duplicateFound": "സമാനമായ പരാതി കണ്ടെത്തി",
        "duplicateScore": "സാമ്യ സ്കോർ"
    },
    "citizen": {
        "portalTitle": "പൗര സേവന പോർട്ടൽ",
        "dashboard": {
            "welcomeBack": "സ്വാഗതം",
            "totalReported": "ആകെ സമർപ്പിച്ച പരാതികൾ",
            "inProgress": "നടപടിക്രമത്തിലുള്ളവ",
            "resolved": "പരിഹരിച്ച പരാതികൾ",
            "needsVerification": "പരിശോധന ആവശ്യമുള്ളവ",
            "communityImpact": "കമ്മ്യൂണിറ്റി സ്വാധീനം",
            "avgResolution": "ശരാശരി പരിഹാര സമയം",
            "recentGrievances": "എന്റെ സമീപകാല പരാതികൾ",
            "reportNewIssue": "പുതിയ പരാതി നൽകുക",
            "myIssues": "എന്റെ പരാതികൾ",
            "trackIssues": "പരിഹാരം ട്രാക്ക് ചെയ്യുക",
            "liveIncidents": "തത്സമയ മുനിസിപ്പൽ സംഭവങ്ങൾ",
            "civicFeed": "പൗര ഫീഡ്",
            "satisfactionScore": "പൗര സംതൃപ്തി സ്കോർ",
            "activeCases": "സജീവ കേസുകൾ",
            "resolvedCases": "പരിഹരിച്ച കേസുകൾ"
        },
        "report": {
            "title": "പുതിയ പരാതി രജിസ്റ്റർ ചെയ്യുക",
            "subtitle": "ഫോട്ടോ, ഓഡിയോ, കൃത്യമായ GPS എന്നിവ ഉപയോഗിച്ച് പ്രശ്നം റിപ്പോർട്ട് ചെയ്യുക. AI സിസ്റ്റം ഉടൻ ബന്ധപ്പെട്ട വകുപ്പിലേക്ക് അയക്കും.",
            "multimodalBadge": "മൾട്ടിമോഡൽ AI സജീവം",
            "moduleBadge": "സ്മാർട്ട് പൗര പരാതി മൊഡ്യൂൾ",
            "uploadEvidence": "ഫോട്ടോ അല്ലെങ്കിൽ വീഡിയോ തെളിവ് അപ്‌ലോഡ് ചെയ്യുക",
            "uploadSubtitle": "വ്യക്തമായ ചിത്രങ്ങൾ വേഗത്തിലുള്ള പരിഹാരത്തിന് സഹായിക്കുന്നു",
            "dragDrop": "ഫയലുകൾ ഇവിടെ വലിച്ചിടുക അല്ലെങ്കിൽ",
            "supportedFormats": "PNG, JPG, MP4, MP3 (പരമാവധി 25MB)",
            "browseFiles": "ഫയലുകൾ ബ്രൗസ് ചെയ്യുക",
            "openCamera": "ക്യാമറ തുറക്കുക",
            "uploadingProgress": "അപ്‌ലോഡ് ചെയ്യുന്നു...",
            "attachedEvidence": "ചേർത്ത തെളിവുകൾ",
            "voiceGrievance": "ശബ്ദ പരാതി റെക്കോർഡ് ചെയ്യുക",
            "optional": "ഓപ്ഷണൽ",
            "voiceSubtitle": "നിങ്ങളുടെ പ്രശ്നം സ്വന്തം ഭാഷയിൽ സംസാരിച്ച് റെക്കോർഡ് ചെയ്യാം",
            "pressRecordHelp": "സംസാരിക്കാൻ മൈക്രോഫോൺ അമർത്തുക",
            "startVoiceRecording": "വോയ്‌സ് റെക്കോർഡിംഗ് ആരംഭിക്കുക",
            "stopRecording": "റെക്കോർഡിംഗ് നിർത്തുക",
            "recording": "റെക്കോർഡ് ചെയ്യുന്നു...",
            "speechProcessing": "സംഭാഷണം ടെക്സ്റ്റാക്കി മാറ്റുന്നു...",
            "speechConverted": "സംഭാഷണം ടെക്സ്റ്റാക്കി മാറ്റി",
            "incidentLocation": "സംഭവം നടന്ന സ്ഥലം",
            "locationSubtitle": "മാപ്പിൽ അടയാളപ്പെടുത്തുക അല്ലെങ്കിൽ GPS ഉപയോഗിക്കുക",
            "useCurrentGps": "നിലവിലെ GPS ലൊക്കേഷൻ ഉപയോഗിക്കുക",
            "streetAddress": "റോഡ് / പ്രദേശം",
            "addressPlaceholder": "റോഡിന്റെ പേര്, വാർഡ് നമ്പർ...",
            "mapTip": "കൃത്യമായ സ്ഥലത്തിനായി പിൻ നീക്കുക",
            "contextTitle": "പ്രശ്നത്തിന്റെ പശ്ചാത്തലവും വിവരങ്ങളും",
            "contextSubtitle": "ഉദ്യോഗസ്ഥർക്ക് മനസ്സിലാകുന്നതിനായി കൃത്യമായ വിവരങ്ങൾ നൽകുക",
            "headlineLabel": "പരാതിയുടെ തലക്കെട്ട്",
            "headlinePlaceholder": "ഉദാഹരണത്തിന്: പ്രധാന റോഡിലെ വലിയ കുഴി",
            "detailsLabel": "വിശദമായ വിവരണം",
            "detailsPlaceholder": "പ്രശ്നത്തിന്റെ സ്വഭാവം, ഗതാഗത തടസ്സം, അപകട സാധ്യതകൾ എന്നിവ വിവരിക്കുക...",
            "categoryLabel": "പ്രശ്ന വിഭാഗം",
            "priorityLabel": "അടിയന്തിര മുൻഗണന",
            "generateAiPreview": "AI പ്രിവ്യൂ കാണുക",
            "processingAi": "AI സിസ്റ്റം വിവരങ്ങൾ പരിശോധിക്കുന്നു...",
            "audioMemo": "ഓഡിയോ മെമ്മോ ചേർത്തു",
            "readyStt": "ട്രാൻസ്ക്രിപ്റ്റ് തയ്യാറാണ്",
            "incidentCoordinates": "സംഭവ സ്ഥല കോർഡിനേറ്റുകൾ",
            "currentDetectedLocation": "കണ്ടെത്തിയ നിലവിലെ സ്ഥലം"
        },
        "track": {
            "title": "പരാതി പരിഹാര ട്രാക്കർ",
            "subtitle": "പരാതിയുടെ നിലവിലെ അവസ്ഥയും ചുമതലയുള്ള ഉദ്യോഗസ്ഥനെയും നേരിട്ട് ട്രാക്ക് ചെയ്യുക.",
            "enterId": "പരാതി ഐഡി (ID) നൽകുക",
            "searchPlaceholder": "ഉദാ: GRV-2026-8942",
            "currentStage": "നിലവിലെ ഘട്ടം",
            "assignedTo": "ചുമതലപ്പെടുത്തിയത്",
            "officerInCharge": "നോഡൽ ഓഫീസർ",
            "slaTimer": "പരിഹാര സമയപരിധി (SLA)",
            "timeline": "പരിഹാര ടൈംലൈൻ",
            "trackingDetails": "ട്രാക്കിംഗ് വിവരങ്ങൾ",
            "liveStatusTransitions": "തത്സമയ അവസ്ഥ മാറ്റങ്ങൾ"
        },
        "profile": {
            "title": "പൗര പ്രൊഫൈലും തിരിച്ചറിയലും",
            "fullName": "പൂർണ്ണമായ പേര്",
            "email": "ഇമെയിൽ വിലാസം",
            "phone": "രജിസ്റ്റർ ചെയ്ത മൊബൈൽ നമ്പർ",
            "district": "ജില്ല",
            "address": "മേൽവിലാസം",
            "saveProfile": "പ്രൊഫൈൽ സേവ് ചെയ്യുക",
            "citizenBadge": "സ്ഥിരീകരിച്ച പൗര ബാഡ്ജ്",
            "verificationStatus": "തിരിച്ചറിയൽ പരിശോധനാ നില"
        },
        "settings": {
            "title": "അക്കൗണ്ട് & സുരക്ഷാ ക്രമീകരണങ്ങൾ",
            "notifications": "അറിയിപ്പ് ക്രമീകരണങ്ങൾ",
            "emailAlerts": "ഇമെയിൽ അറിയിപ്പുകൾ",
            "smsAlerts": "SMS അറിയിപ്പുകൾ",
            "theme": "തീം (ഡാർക്ക് / ലൈറ്റ് മോഡ്)",
            "language": "ആപ്പ് ഭാഷ",
            "savePreferences": "മാറ്റങ്ങൾ സേവ് ചെയ്യുക"
        }
    },
    "government": {
        "portalTitle": "മുനിസിപ്പൽ അഡ്മിനിസ്ട്രേഷൻ & കൺട്രോൾ സെന്റർ",
        "dashboard": {
            "title": "ഭരണ നിയന്ത്രണ മുറി",
            "overview": "പൊതു അവലോകനം",
            "assignedCases": "നിയോഗിച്ച കേസുകൾ",
            "liveCases": "സജീവ കേസുകൾ",
            "slaBreachRisk": "SLA ലംഘന സാധ്യതയുള്ളവ",
            "avgTurnaround": "ശരാശരി പരിഹാര സമയം",
            "citizenSatisfaction": "പൗര സംതൃപ്തി സൂചിക",
            "urgentDocket": "അടിയന്തിര കേസുകൾ",
            "viewQueue": "കേസ് നിര കാണുക",
            "syncTelemetry": "ടെലിമെട്രി സമന്വയിപ്പിക്കുക",
            "telemetryActive": "തത്സമയ ടെലിമെട്രി സജീവം",
            "monthlyTrends": "പ്രതിമാസ ട്രെൻഡുകൾ",
            "resolutionBreakdown": "പരിഹാര വർഗ്ഗീകരണം",
            "districtHeatmap": "ജില്ലാ പരാതി സാന്ദ്രത മാപ്പ്",
            "departmentEfficiency": "വകുപ്പ് കാര്യക്ഷമത",
            "docketOverview": "കേസ് അവലോകനം",
            "statutoryTarget": "നിയമപരമായ ലക്ഷ്യം"
        },
        "officers": {
            "title": "ഫീൽഡ് ഓഫീസർമാരുടെ ഡയറക്ടറി",
            "directory": "ഉദ്യോഗസ്ഥ പട്ടിക",
            "addOfficer": "പുതിയ ഉദ്യോഗസ്ഥനെ ചേർക്കുക",
            "officerName": "ഉദ്യോഗസ്ഥന്റെ പേര്",
            "designation": "തസ്തിക",
            "department": "വകുപ്പ്",
            "contact": "ബന്ധപ്പെടാനുള്ള നമ്പർ",
            "assignedCount": "നിയോഗിച്ച കേസുകൾ",
            "resolutionRate": "പരിഹാര നിരക്ക്",
            "status": "ലഭ്യത നില",
            "actions": "നടപടികൾ",
            "searchOfficers": "ഉദ്യോഗസ്ഥരെ തിരയുക..."
        },
        "departments": {
            "title": "മുനിസിപ്പൽ വകുപ്പ് മാനേജ്മെന്റ്",
            "municipalDepartments": "എല്ലാ മുനിസിപ്പൽ വകുപ്പുകളും",
            "addDepartment": "പുതിയ വകുപ്പ് ചേർക്കുക",
            "deptName": "വകുപ്പിന്റെ പേര്",
            "headOfDept": "വകുപ്പ് മേധാവി",
            "activePersonnel": "ജീവനക്കാരുടെ എണ്ണം",
            "budgetAllocated": "അനുവദിച്ച വാർഷിക ഫണ്ട്",
            "openGrievances": "തീർപ്പാക്കാത്ത പരാതികൾ",
            "slaCompliance": "SLA പാലിക്കൽ നിരക്ക്",
            "efficiencyRating": "കാര്യക്ഷമതാ റേറ്റിംഗ്",
            "searchDepartments": "വകുപ്പുകൾ തിരയുക..."
        },
        "assigned": {
            "title": "എനിക്ക് ലഭിച്ച പരാതി കേസുകൾ",
            "caseId": "കേസ് ഐഡി",
            "citizenName": "പൗരന്റെ പേര്",
            "category": "വിഭാഗം",
            "priority": "മുൻഗണന",
            "status": "നില",
            "dateReported": "റിപ്പോർട്ട് ചെയ്ത തീയതി",
            "targetResolution": "പരിഹരിക്കേണ്ട തീയതി",
            "reassign": "പുനർനിയമിക്കുക",
            "escalate": "മേലധികാരിക്ക് അയക്കുക",
            "resolveCase": "കേസ് പരിഹരിക്കുക",
            "viewCase": "വിശദാംശങ്ങൾ കാണുക",
            "filterPriority": "മുൻഗണന പ്രകാരം ഫിൽട്ടർ ചെയ്യുക",
            "filterStatus": "നില പ്രകാരം ഫിൽട്ടർ ചെയ്യുക",
            "allCases": "എല്ലാ കേസുകളും"
        },
        "tracking": {
            "title": "നഗരവ്യാപക ലൈവ് ട്രാക്കിംഗ്",
            "subtitle": "മാപ്പിൽ എല്ലാ പരാതികളും സംഭവങ്ങളും തത്സമയം നിരീക്ഷിക്കുക",
            "liveIncidentMap": "തത്സമയ സംഭവ മാപ്പ്",
            "filterByWard": "വാർഡ് പ്രകാരം ഫിൽട്ടർ ചെയ്യുക",
            "filterBySeverity": "തീവ്രത പ്രകാരം ഫിൽട്ടർ ചെയ്യുക"
        },
        "aiSuggestions": {
            "title": "AI ഭരണ വിശകലനവും നിർദ്ദേശങ്ങളും",
            "smartRoutingTitle": "സ്മാർട്ട് റൂട്ടിംഗ് നിർദ്ദേശങ്ങൾ",
            "recommendedActions": "ശുപാർശ ചെയ്ത നടപടികൾ",
            "anomalyDetection": "അപാകത കണ്ടെത്തൽ",
            "duplicateClusters": "സമാന പരാതികളുടെ ക്ലസ്റ്ററുകൾ",
            "autoTriage": "ഓട്ടോ ട്രയാജ്"
        },
        "reports": {
            "title": "ഓഡിറ്റ് & പ്രകടന റിപ്പോർട്ടുകൾ",
            "generateReport": "റിപ്പോർട്ട് തയ്യാറാക്കുക",
            "downloadPdf": "PDF ഡൗൺലോഡ് ചെയ്യുക",
            "downloadCsv": "CSV ഡൗൺലോഡ് ചെയ്യുക",
            "monthlyAudit": "പ്രതിമാസ ഓഡിറ്റ് റിപ്പോർട്ട്",
            "quarterlyPerformance": "പാദവാർഷിക പ്രകടനം",
            "exportAnalytics": "അനലിറ്റിക്സ് എക്സ്പോർട്ട് ചെയ്യുക"
        },
        "settings": {
            "title": "നിയന്ത്രണ മുറി ക്രമീകരണങ്ങൾ",
            "slaThresholds": "SLA സമയപരിധി",
            "notificationRules": "അറിയിപ്പ് നിയമങ്ങൾ",
            "escalationMatrix": "എസ്കലേഷൻ മാട്രിക്സ്",
            "workingHours": "പ്രവൃത്തി സമയം"
        }
    },
    "industry": {
        "portalTitle": "വ്യവസായ & കോർപ്പറേറ്റ് CSR പോർട്ടൽ",
        "dashboard": {
            "title": "വ്യവസായ CSR & ഇന്നൊവേഷൻ ഡാഷ്‌ബോർഡ്",
            "overview": "CSR അവലോകനം",
            "csrFunding": "CSR ഫണ്ടിംഗ്",
            "capitalAllocation": "മൂലധന വിഹിതം",
            "availableProjects": "ലഭ്യമായ പ്രോജക്റ്റുകൾ",
            "liveGrants": "സജീവ ഗ്രാന്റുകൾ",
            "partnershipPact": "പങ്കാളിത്ത കരാർ",
            "totalDisbursed": "ആകെ വിതരണം ചെയ്ത ഫണ്ട്",
            "activeProjects": "സജീവ പ്രോജക്റ്റുകൾ",
            "impactScore": "സാമൂഹിക സ്വാധീന സ്കോർ",
            "viewOpportunities": "അവസരങ്ങൾ കാണുക",
            "availableCsr": "ലഭ്യമായ CSR ഫണ്ട്",
            "corporatePartner": "കോർപ്പറേറ്റ് പങ്കാളി",
            "verifiedEntity": "സ്ഥിരീകരിച്ച സ്ഥാപനം"
        },
        "projects": {
            "title": "സുസ്ഥിര നഗര പ്രോജക്റ്റുകൾ",
            "projectCatalog": "പ്രോജക്റ്റ് കാറ്റലോഗ്",
            "fundingGoal": "ഫണ്ടിംഗ് ലക്ഷ്യം",
            "raisedAmount": "സമാഹരിച്ച തുക",
            "municipalSponsor": "മുനിസിപ്പൽ സ്പോൺസർ",
            "sdgImpact": "സുസ്ഥിര വികസന ലക്ഷ്യങ്ങൾ (SDG)",
            "applyFunding": "ഫണ്ടിംഗിനായി അപേക്ഷിക്കുക",
            "exploreInitiatives": "സംരംഭങ്ങൾ കണ്ടെത്തുക",
            "searchProjects": "പ്രോജക്റ്റുകൾ തിരയുക..."
        },
        "funding": {
            "title": "CSR ഗ്രാന്റുകളും ഫണ്ട് മാനേജ്മെന്റും",
            "grantApplication": "ഗ്രാന്റ് അപേക്ഷ",
            "disbursementStatus": "വിതരണ നില",
            "corporateDonation": "കോർപ്പറേറ്റ് സംഭാവന",
            "taxBenefit": "നികുതി ആനുകൂല്യം (80G)",
            "escrowStatus": "എസ്ക്രോ അക്കൗണ്ട് നില",
            "fundMilestone": "ഘട്ടങ്ങൾക്ക് ഫണ്ട് നൽകുക"
        },
        "csr": {
            "title": "കമ്പനി CSR നയവും പാലിക്കലും",
            "spendByCategory": "വിഭാഗം തിരിച്ചുള്ള ചെലവ്",
            "geographicAllocation": "ഭൂമിശാസ്ത്രപരമായ വിഹിതം",
            "socialReturnOnInvestment": "സാമൂഹിക നിക്ഷേപ വരുമാനം (SROI)",
            "auditCompliance": "ഓഡിറ്റ് പാലിക്കൽ",
            "csrDistribution": "CSR വിതരണം"
        },
        "mentorship": {
            "title": "വിദഗ്ദ്ധ നിർദ്ദേശങ്ങളും വിദ്യാർത്ഥി മെന്റർഷിപ്പും",
            "expertGuidance": "വിദഗ്ദ്ധ മാർഗ്ഗനിർദ്ദേശം",
            "studentPrototypes": "വിദ്യാർത്ഥി പ്രോട്ടോടൈപ്പുകൾ",
            "industryAdvisors": "വ്യവസായ ഉപദേശകർ",
            "scheduleSession": "സെഷൻ ഷെഡ്യൂൾ ചെയ്യുക"
        },
        "collaboration": {
            "title": "മുനിസിപ്പൽ - അക്കാദമിക് സഹകരണം",
            "academicPacts": "അക്കാദമിക് കരാറുകൾ",
            "joinConsortium": "കൺസോർഷ്യത്തിൽ ചേരുക",
            "jointResearch": "സംയുക്ത ഗവേഷണം",
            "mouSigned": "ഒപ്പിട്ട ധാരണാപത്രങ്ങൾ"
        },
        "prototypes": {
            "title": "വിദ്യാർത്ഥി പ്രോട്ടോടൈപ്പുകളും ഇന്നൊവേഷനും",
            "technologyDemonstrators": "സാങ്കേതിക ഡെമോകൾ",
            "readyForDeployment": "ഉപയോഗത്തിന് സജ്ജം",
            "pilotTested": "പൈലറ്റ് പരീക്ഷണം പൂർത്തിയായി",
            "commercialize": "വാണിജ്യവൽക്കരിക്കുക"
        },
        "tracking": {
            "title": "CSR സ്വാധീനം തത്സമയം നിരീക്ഷിക്കുക",
            "milestoneProgress": "മൈൽസ്റ്റോൺ പുരോഗതി",
            "verificationCheck": "പരിശോധന പരിശോധന",
            "fundRelease": "ഫണ്ട് റിലീസ്"
        },
        "profile": {
            "title": "കമ്പനി പ്രൊഫൈൽ",
            "companyName": "കമ്പനിയുടെ പേര്",
            "cinRegistration": "CIN രജിസ്ട്രേഷൻ നമ്പർ",
            "csrBudget": "വാർഷിക CSR ബജറ്റ്",
            "contactPerson": "ബന്ധപ്പെടേണ്ട വ്യക്തി",
            "panNumber": "PAN നമ്പർ"
        },
        "settings": {
            "title": "വ്യവസായ പോർട്ടൽ മുൻഗണനകൾ",
            "emailNotifications": "ഇമെയിൽ അറിയിപ്പുകൾ",
            "bankDetails": "ബാങ്ക് അക്കൗണ്ട് വിവരങ്ങൾ",
            "complianceDocs": "നിയമപരമായ രേഖകൾ"
        }
    },
    "ngo": {
        "portalTitle": "സന്നദ്ധ സംഘടന & ജനകീയ പങ്കാളിത്ത പോർട്ടൽ",
        "dashboard": {
            "title": "എൻ‌ജി‌ഒ പ്രവർത്തന നിയന്ത്രണ കേന്ദ്രം",
            "overview": "പ്രവർത്തന അവലോകനം",
            "groundSquads": "സന്നദ്ധപ്രവർത്തക സംഘങ്ങൾ",
            "activeVolunteers": "സജീവ സന്നദ്ധപ്രവർത്തകർ",
            "fieldInterventions": "ഫീൽഡ് ഇടപെടലുകൾ",
            "reliefOperations": "ദുരിതാശ്വാസ പ്രവർത്തനങ്ങൾ",
            "communityImpact": "കമ്മ്യൂണിറ്റി സ്വാധീനം",
            "certsAwarded": "നൽകിയ സർട്ടിഫിക്കറ്റുകൾ",
            "urgentReliefCalls": "അടിയന്തിര ദുരിതാശ്വാസ കോളുകൾ",
            "groundTelemetryLive": "തത്സമയ ഫീൽഡ് ടെലിമെട്രി",
            "logFieldEvidence": "ഫീൽഡ് തെളിവുകൾ രേഖപ്പെടുത്തുക"
        },
        "projects": {
            "title": "കമ്മ്യൂണിറ്റി വികസന പ്രോജക്റ്റുകൾ",
            "localGrievances": "പ്രാദേശിക പരാതികൾ",
            "adoptIssue": "പ്രശ്നം ഏറ്റെടുക്കുക",
            "publicWorks": "പൊതുമരാമത്ത് പ്രവർത്തനങ്ങൾ",
            "grassrootInterventions": "ഗ്രാസ്റൂട്ട് ഇടപെടലുകൾ"
        },
        "assignedProjects": {
            "title": "മുനിസിപ്പൽ സംയുക്ത പദ്ധതികൾ",
            "operationalSquads": "കർമ്മനിരതരായ സംഘങ്ങൾ",
            "projectTimeline": "പ്രോജക്റ്റ് ടൈംലൈൻ",
            "targetCompletion": "പൂർത്തിയാക്കേണ്ട ലക്ഷ്യം",
            "submitProgressReport": "പുരോഗതി റിപ്പോർട്ട് സമർപ്പിക്കുക"
        },
        "fieldActivities": {
            "title": "ഫീൽഡ് പ്രവർത്തനങ്ങളും തെളിവ് രേഖകളും",
            "liveReliefLog": "തത്സമയ ദുരിതാശ്വാസ രേഖ",
            "geoTaggedPhotos": "ജിയോ-ടാഗ് ചെയ്ത ഫോട്ടോകൾ",
            "suppliesDistributed": "വിതരണം ചെയ്ത സാധനങ്ങൾ",
            "citizensAssisted": "സഹായം ലഭിച്ച പൗരന്മാർ",
            "addLogEntry": "പുതിയ എൻട്രി ചേർക്കുക"
        },
        "volunteers": {
            "title": "സന്നദ്ധപ്രവർത്തക മാനേജ്മെന്റും ടീമുകളും",
            "registerVolunteer": "പുതിയ സന്നദ്ധപ്രവർത്തക രജിസ്ട്രേഷൻ",
            "skillsDirectory": "നൈപുണ്യ ഡയറക്ടറി",
            "assignWard": "വാർഡ് നൽകുക",
            "volunteerSquads": "സന്നദ്ധ സംഘങ്ങൾ",
            "attendance": "ഹാജർ നില"
        },
        "impact": {
            "title": "സാമൂഹിക സ്വാധീന വിലയിരുത്തൽ",
            "livesImpacted": "സഹായം ലഭിച്ച ആളുകൾ",
            "wardsTransformed": "മെച്ചപ്പെട്ട വാർഡുകൾ",
            "satisfactionIndex": "സംതൃപ്തി സൂചിക",
            "volunteerHours": "ആകെ സന്നദ്ധപ്രവർത്തന മണിക്കൂറുകൾ"
        },
        "collaborations": {
            "title": "വ്യവസായ - മുനിസിപ്പൽ സഹകരണം",
            "municipalMoU": "മുനിസിപ്പൽ ധാരണാപത്രം",
            "corporateSponsors": "കോർപ്പറേറ്റ് സ്പോൺസർമാർ",
            "universityAlliances": "സർവ്വകലാശാലാ സഖ്യങ്ങൾ"
        },
        "certificates": {
            "title": "സർട്ടിഫിക്കറ്റുകളും അംഗീകാരങ്ങളും",
            "awardCertificate": "സർട്ടിഫിക്കറ്റ് നൽകുക",
            "downloadBadge": "ബാഡ്ജ് ഡൗൺലോഡ് ചെയ്യുക",
            "recognitionLetter": "അഭിനന്ദന കത്ത്"
        },
        "reports": {
            "title": "പ്രതിമാസ ഫീൽഡ് പ്രവർത്തന റിപ്പോർട്ട്",
            "fieldAuditReports": "ഫീൽഡ് ഓഡിറ്റ് റിപ്പോർട്ട്",
            "monthlyActivitySummary": "പ്രതിമാസ പ്രവർത്തന സംഗ്രഹം",
            "incidentLogSheet": "സംഭവ രേഖ ഷീറ്റ്",
            "submitToGovernment": "സർക്കാരിലേക്ക് സമർപ്പിക്കുക"
        },
        "settings": {
            "title": "സ്ഥാപന പ്രൊഫൈൽ ക്രമീകരണങ്ങൾ",
            "registrationDetails": "രജിസ്ട്രേഷൻ വിവരങ്ങൾ",
            "ngoDarpanId": "NGO ദർപ്പൺ ഐഡി",
            "focalPoints": "പ്രധാന ബന്ധപ്പെടൽ കേന്ദ്രങ്ങൾ"
        }
    },
    "university": {
        "portalTitle": "സർവ്വകലാശാല & ഇന്നൊവേഷൻ പോർട്ടൽ",
        "student": {
            "dashboard": {
                "title": "വിദ്യാർത്ഥി ഡാഷ്‌ബോർഡ്",
                "academicCredits": "അക്കാദമിക് ക്രെഡിറ്റുകൾ",
                "assignedTasks": "നിയോഗിച്ച ചുമതലകൾ",
                "labProjects": "ലാബ് പ്രോജക്റ്റുകൾ",
                "prototypeChallenges": "പ്രോട്ടോടൈപ്പ് വെല്ലുവിളികൾ",
                "submitMilestone": "ഘട്ടം സമർപ്പിക്കുക"
            },
            "tasks": {
                "title": "ലാബ് ടാസ്കുകൾ",
                "pendingTasks": "തീർപ്പാക്കാത്ത ചുമതലകൾ",
                "taskDescription": "ചുമതല വിവരണം",
                "dueDate": "അവസാന തീയതി",
                "submitDeliverable": "റിപ്പോർട്ട് അപ്‌ലോഡ് ചെയ്യുക",
                "advisorNotes": "ഉപദേശകന്റെ കുറിപ്പുകൾ",
                "dueTasks": "പൂർത്തിയാക്കാനുള്ള ചുമതലകൾ"
            },
            "uploads": {
                "title": "റിപ്പോർട്ടുകൾ അപ്‌ലോഡ് ചെയ്യുക",
                "researchNotes": "ഗവേഷണ കുറിപ്പുകൾ",
                "projectCode": "പ്രോജക്റ്റ് കോഡ്",
                "presentationSlides": "പ്രസന്റേഷൻ സ്ലൈഡുകൾ",
                "submitForGrading": "മൂല്യനിർണ്ണയത്തിനായി സമർപ്പിക്കുക"
            },
            "timeline": {
                "title": "പ്രോജക്റ്റ് ടൈംലൈൻ",
                "projectSchedule": "പ്രോജക്റ്റ് ഷെഡ്യൂൾ",
                "semesterDeadlines": "സെമസ്റ്റർ അവസാന തീയതികൾ",
                "facultyReviewDate": "അധ്യാപക പരിശോധനാ തീയതി"
            },
            "messages": {
                "title": "ഉപദേശക ചർച്ച",
                "chatWithMentor": "മെന്ററുമായി സംസാരിക്കുക",
                "feedbackThread": "ഫീഡ്‌ബാക്ക് ത്രെഡ്",
                "askQuestion": "സംശയം ചോദിക്കുക"
            }
        },
        "faculty": {
            "dashboard": {
                "title": "അധ്യാപക ഡാഷ്‌ബോർഡ്",
                "studentCohorts": "വിദ്യാർത്ഥി സംഘങ്ങൾ",
                "mentoredProjects": "മാർഗ്ഗനിർദ്ദേശം നൽകിയ പ്രോജക്റ്റുകൾ",
                "pendingApprovals": "തീർപ്പുകൽപ്പിക്കാത്ത അംഗീകാരങ്ങൾ",
                "researchPapers": "ഗവേഷണ പ്രബന്ധങ്ങൾ",
                "innovationIndex": "ഇന്നൊവേഷൻ സൂചിക"
            },
            "approvals": {
                "title": "മൈൽസ്റ്റോൺ അംഗീകാരങ്ങൾ",
                "reviewSubmission": "സമർപ്പിച്ചവ പരിശോധിക്കുക",
                "approveMilestone": "മൈൽസ്റ്റോൺ അംഗീകരിക്കുക",
                "rejectMilestone": "മൈൽസ്റ്റോൺ നിരസിക്കുക",
                "provideFeedback": "ഫീഡ്‌ബാക്ക് നൽകുക",
                "gradeAwarded": "നൽകിയ ഗ്രേഡ്",
                "pendingReviews": "തീർപ്പാക്കാത്ത അവലോകനങ്ങൾ"
            },
            "proposals": {
                "title": "മുനിസിപ്പൽ പ്രൊപ്പോസലുകൾ",
                "civicResearchTopics": "നഗര ഗവേഷണ വിഷയങ്ങൾ",
                "grantProposals": "ഗ്രാന്റ് പ്രൊപ്പോസലുകൾ",
                "callForPapers": "പ്രബന്ധ ക്ഷണം",
                "openProposals": "ലഭ്യമായ പ്രൊപ്പോസലുകൾ"
            },
            "teams": {
                "title": "ഗവേഷണ ടീമുകൾ",
                "teamRoster": "ടീം ലിസ്റ്റ്",
                "assignLead": "ടീം ലീഡറെ നിയമിക്കുക",
                "performanceReview": "പ്രകടന വിലയിരുത്തൽ",
                "academicAdvising": "അക്കാദമിക് ഉപദേശം"
            },
            "reports": {
                "title": "അക്കാദമിക് റിപ്പോർട്ടുകൾ",
                "cohortProgress": "സംഘ പുരോഗതി റിപ്പോർട്ട്",
                "publicationOutput": "പ്രസിദ്ധീകരണങ്ങൾ",
                "creditDistribution": "ക്രെഡിറ്റ് വിതരണം"
            }
        },
        "shared": {
            "projects": {
                "title": "സർവ്വകലാശാലാ പ്രോജക്റ്റുകൾ",
                "studentResearch": "വിദ്യാർത്ഥി ഗവേഷണം",
                "capstoneProjects": "ക്യാപ്സ്റ്റോൺ പ്രോജക്റ്റുകൾ",
                "interdisciplinaryTeams": "വിവിധ വിഷയ ടീമുകൾ"
            },
            "research": {
                "title": "ഗവേഷണ കേന്ദ്രം",
                "publications": "ഗവേഷണ പ്രസിദ്ധീകരണങ്ങൾ",
                "datasets": "നഗര ഡാറ്റാസെറ്റുകൾ",
                "patentFiling": "പേറ്റന്റ് ഫയലിംഗ്",
                "peerReview": "പിയർ റിവ്യൂ"
            },
            "innovation": {
                "title": "ഇന്നൊവേഷൻ വെല്ലുവിളികൾ",
                "innovationChallenges": "സ്മാർട്ട് സിറ്റി ചലഞ്ചുകൾ",
                "hackathonDemos": "ഹാക്കത്തോൺ ഡെമോകൾ",
                "incubatorReady": "ഇൻകുബേറ്റർ സജ്ജം",
                "smartCityPrototypes": "സ്മാർട്ട് സിറ്റി പ്രോട്ടോടൈപ്പുകൾ"
            },
            "credits": {
                "title": "അക്കാദമിക് ക്രെഡിറ്റുകൾ",
                "creditsEarned": "നേടിയ ക്രെഡിറ്റുകൾ",
                "skillBadges": "നൈപുണ്യ ബാഡ്ജുകൾ",
                "hallOfFame": "ഹാൾ ഓഫ് ഫെയിം",
                "transcriptVerification": "മാർക്ക് ലിസ്റ്റ് സ്ഥിരീകരണം"
            },
            "repository": {
                "title": "വിജ്ഞാന ശേഖരം",
                "researchPapersArchive": "പ്രബന്ധ ശേഖരം",
                "openDataVault": "ഓപ്പൺ ഡാറ്റാ ശേഖരം",
                "citationIndex": "സൈറ്റേഷൻ സൂചിക"
            },
            "settings": {
                "title": "അക്കാദമിക് പ്രൊഫൈൽ ക്രമീകരണങ്ങൾ",
                "facultyProfile": "അധ്യാപക പ്രൊഫൈൽ",
                "departmentAffiliation": "വകുപ്പ് വിവരങ്ങൾ",
                "orcidId": "ORCID ഐഡി"
            }
        }
    },
    "admin": {
        "portalTitle": "കേന്ദ്ര ഭരണ നിയന്ത്രണ കേന്ദ്രം",
        "dashboard": {
            "title": "കേന്ദ്ര അഡ്മിൻ ഡാഷ്‌ബോർഡ്",
            "totalSystemUsers": "ആകെ ഉപയോക്താക്കൾ",
            "activePortals": "സജീവ പോർട്ടലുകൾ",
            "aiModelStatus": "AI മോഡൽ അവസ്ഥ",
            "databaseHealth": "ഡാറ്റാബേസ് ആരോഗ്യം",
            "unresolvedGrievances": "പരിഹരിക്കാത്ത പരാതികൾ",
            "platformLoad": "പ്ലാറ്റ്‌ഫോം ലോഡ്",
            "liveEventStream": "തത്സമയ ഇവന്റ് സ്ട്രീം",
            "rootConsole": "റൂട്ട് കൺസോൾ",
            "cpuUsage": "CPU ഉപയോഗം",
            "dbLatency": "ഡാറ്റാബേസ് ലേറ്റൻസി",
            "uptime": "സിസ്റ്റം പ്രവർത്തന സമയം"
        },
        "users": {
            "title": "ഉപയോക്തൃ മാനേജ്മെന്റ്",
            "allUsers": "എല്ലാ ഉപയോക്താക്കളും",
            "addUser": "ഉപയോക്താവിനെ ചേർക്കുക",
            "editRole": "റോൾ മാറ്റുക",
            "suspendUser": "ഉപയോക്താവിനെ സസ്പെൻഡ് ചെയ്യുക",
            "resetPassword": "പാസ്‌വേഡ് റീസെറ്റ് ചെയ്യുക",
            "roleFilter": "റോൾ ഫിൽട്ടർ",
            "searchUsers": "ഉപയോക്താക്കളെ തിരയുക..."
        },
        "roles": {
            "title": "റോൾ & അനുമതി മാനേജ്മെന്റ് (RBAC)",
            "permissionsMatrix": "അനുമതി മാട്രിക്സ്",
            "accessControl": "പ്രവേശന നിയന്ത്രണം",
            "createRole": "പുതിയ റോൾ സൃഷ്ടിക്കുക",
            "customRoles": "കസ്റ്റം റോളുകൾ"
        },
        "government": {
            "title": "മുനിസിപ്പൽ അഡ്മിനിസ്ട്രേഷൻ മാനേജ്മെന്റ്",
            "municipalBOD": "മുനിസിപ്പൽ ബോർഡ്",
            "cityDistricts": "നഗര ജില്ലകളും സോണുകളും",
            "assignWardEngineers": "വാർഡ് എഞ്ചിനീയർമാരെ നിയമിക്കുക"
        },
        "universities": {
            "title": "സർവ്വകലാശാലകളും സ്ഥാപനങ്ങളും",
            "registeredCampuses": "രജിസ്റ്റർ ചെയ്ത സർവ്വകലാശാലകൾ",
            "accreditationVerify": "അക്രഡിറ്റേഷൻ പരിശോധന",
            "studentCap": "വിദ്യാർത്ഥി പരിധി"
        },
        "industry": {
            "title": "വ്യവസായ & കോർപ്പറേറ്റ് പങ്കാളികൾ",
            "corporatePartners": "കോർപ്പറേറ്റ് പങ്കാളികൾ",
            "csrValidation": "CSR സാധൂകരണം",
            "escrowAudits": "എസ്ക്രോ ഓഡിറ്റുകൾ"
        },
        "ngos": {
            "title": "സന്നദ്ധ സംഘടനകളും ട്രസ്റ്റുകളും",
            "verifiedNgos": "സ്ഥിരീകരിച്ച എൻ‌ജി‌ഒകൾ",
            "darpanCheck": "NGO ദർപ്പൺ പരിശോധന",
            "groundClearance": "ഫീൽഡ് അനുമതി"
        },
        "research": {
            "title": "ഗവേഷണ സ്ഥാപനങ്ങളും ലാബുകളും",
            "institutePartnerships": "പങ്കാളിത്ത സ്ഥാപനങ്ങൾ",
            "ethicsClearance": "എത്തിക്സ് അനുമതി",
            "datasetAccess": "ഡാറ്റാസെറ്റ് പ്രവേശനം"
        },
        "departments": {
            "title": "വകുപ്പ് മാസ്റ്ററും റൂട്ടിംഗ് നിയമങ്ങളും",
            "routingRules": "ഓട്ടോ റൂട്ടിംഗ് നിയമങ്ങൾ",
            "autoAssignmentEngine": "AI ഡിസ്പാച്ച് എഞ്ചിൻ",
            "fallbackQueues": "ഫാൾബാക്ക് ക്യൂകൾ"
        },
        "issues": {
            "title": "പ്ലാറ്റ്‌ഫോം പരാതി മാസ്റ്റർ",
            "forceResolve": "അഡ്മിൻ പരിഹാരം",
            "reassignCluster": "ക്ലസ്റ്റർ പുനർനിയമിക്കുക",
            "auditLog": "മാറ്റാനാവാത്ത ആക്ഷൻ ലോഗ്",
            "purgeTestData": "ടെസ്റ്റ് ഡാറ്റ നീക്കം ചെയ്യുക"
        },
        "aiMonitoring": {
            "title": "AI വിഷൻ & ടെലിമെട്രി നിരീക്ഷണം",
            "geminiVisionUptime": "വിഷൻ മോഡൽ പ്രവർത്തന സമയം",
            "fastApiOcrStatus": "FastAPI OCR പൈപ്പ്‌ലൈൻ",
            "speechToTextLatency": "ശബ്ദ പരിവർത്തന ലേറ്റൻസി",
            "accuracyScore": "വർഗ്ഗീകരണ കൃത്യതാ സ്കോർ",
            "confidenceDistribution": "കോൺഫിഡൻസ് വിതരണം",
            "modelLogs": "മോഡൽ ലോഗുകൾ"
        },
        "workflowMonitoring": {
            "title": "വർക്ക്ഫ്ലോ എഞ്ചിൻ & ക്യൂ ടെലിമെട്രി",
            "stateMachineInspect": "സ്റ്റേറ്റ് മെഷീൻ മാറ്റങ്ങൾ",
            "queueDepth": "മെസ്സേജ് ക്യൂ ആഴം",
            "deadLetterQueue": "ഡെഡ് ലെറ്റർ ക്യൂ",
            "retryFailedTasks": "പരാജയപ്പെട്ടവ വീണ്ടും ശ്രമിക്കുക"
        },
        "analytics": {
            "title": "മാക്രോ അനലിറ്റിക്സ്",
            "crossPortalActivity": "ക്രോസ്-പോർട്ടൽ പ്രവർത്തനങ്ങൾ",
            "municipalPerformanceIndex": "മുനിസിപ്പൽ പ്രകടന സൂചിക",
            "peakUsageHours": "ഉയർന്ന ഉപയോഗ സമയം"
        },
        "systemHealth": {
            "title": "അടിസ്ഥാന സൗകര്യങ്ങളും സിസ്റ്റം ആരോഗ്യവും",
            "databaseReplicas": "ഡാറ്റാബേസ് റെപ്ലിക്കകൾ",
            "redisCache": "റെഡിസ് കാഷെ നില",
            "storageUsage": "സ്റ്റോറേജ് ഉപയോഗം",
            "apiGateways": "മൈക്രോസർവീസ് ആരോഗ്യം",
            "uptime99": "99.98% ലഭ്യത",
            "online": "ഓൺലൈൻ",
            "maintenance": "മെയിന്റനൻസ് നടക്കുന്നു"
        },
        "settings": {
            "title": "പ്ലാറ്റ്‌ഫോം കോൺഫിഗറേഷൻ ക്രമീകരണങ്ങൾ",
            "maintenanceMode": "മെയിന്റനൻസ് മോഡ്",
            "apiRateLimits": "API പരിധികൾ",
            "backupSchedules": "ഓട്ടോ ബാക്കപ്പ് ഷെഡ്യൂളുകൾ",
            "smtpConfig": "ഇമെയിൽ & SMS ഗേറ്റ്‌വേ"
        }
    },
    "toast": {
        "issueSubmitted": "പരാതി വിജയകരമായി സമർപ്പിച്ചു! ബന്ധപ്പെട്ട വകുപ്പിലേക്ക് അയച്ചു.",
        "gpsCaptured": "GPS ലൊക്കേഷൻ കണ്ടെത്തി",
        "gpsCapturedDesc": "ലൊക്കേഷൻ പരാതി റിപ്പോർട്ടുമായി ബന്ധിപ്പിച്ചു.",
        "locationDenied": "ലൊക്കേഷൻ അനുമതി നിരസിച്ചു അല്ലെങ്കിൽ ലഭ്യമല്ല. ഡിഫോൾട്ട് ലൊക്കേഷൻ ഉപയോഗിക്കുന്നു.",
        "fileSizeExceeded": "ഫയൽ വലുപ്പം 25MB-യിൽ കൂടുതലാണ്.",
        "audioNotSupported": "ഈ ബ്രൗസറിൽ ഓഡിയോ റെക്കോർഡിംഗ് പിന്തുണയ്ക്കുന്നില്ല.",
        "micSimulation": "വോയ്‌സ് പരാതി ഡെമോയ്ക്കായി മൈക്രോഫോൺ സിമുലേഷൻ സജീവമാണ്.",
        "profileUpdated": "പ്രൊഫൈൽ വിജയകരമായി അപ്ഡേറ്റ് ചെയ്തു.",
        "settingsSaved": "മാറ്റങ്ങൾ വിജയകരമായി സേവ് ചെയ്തു.",
        "deleteRequested": "അക്കൗണ്ട് ഡിലീറ്റ് ചെയ്യാനുള്ള അഭ്യർത്ഥന സമർപ്പിച്ചു.",
        "languageChanged": "ഭാഷ വിജയകരമായി മാറ്റി.",
        "errorOccurred": "ഒരു പിശക് സംഭവിച്ചു. ദയവായി വീണ്ടും ശ്രമിക്കുക.",
        "caseUpdated": "കേസ് വിജയകരമായി അപ്ഡേറ്റ് ചെയ്തു.",
        "caseReassigned": "കേസ് നോഡൽ ഓഫീസർക്ക് വീണ്ടും നൽകി.",
        "caseResolved": "പരാതി പരിഹരിച്ചതായി അടയാളപ്പെടുത്തി.",
        "volunteerAdded": "പുതിയ സന്നദ്ധപ്രവർത്തകനെ ചേർത്തു.",
        "grantApproved": "CSR ഗ്രാന്റ് വിഹിതം അംഗീകരിച്ചു.",
        "milestoneApproved": "അക്കാദമിക് മൈൽസ്റ്റോൺ അംഗീകരിച്ചു.",
        "deliverableUploaded": "റിപ്പോർട്ട് പരിശോധനയ്ക്കായി അപ്‌ലോഡ് ചെയ്തു.",
        "loginSuccess": "വിജയകരമായി സൈൻ ഇൻ ചെയ്തു. സ്വാഗതം!",
        "logoutSuccess": "വിജയകരമായി ലോഗ് ഔട്ട് ചെയ്തു.",
        "accessDenied": "പ്രവേശനം പരിമിതപ്പെടുത്തിയിരിക്കുന്നു.",
        "changesSaved": "എല്ലാ മാറ്റങ്ങളും വിജയകരമായി സേവ് ചെയ്തു.",
        "reportExported": "റിപ്പോർട്ട് തയ്യാറാക്കി ഡൗൺലോഡ് ചെയ്തു.",
        "dataRefreshed": "ടെലിമെട്രി ഡാറ്റ പുതുക്കി."
    },
    "language": "ഭാഷ",
    "dashboard": "ഡാഷ്‌ബോർഡ്",
    "report_issue": "പരാതി നൽകുക",
    "report_problem": "പരാതി രജിസ്റ്റർ ചെയ്യുക",
    "my_issues": "എന്റെ പരാതികൾ",
    "track_issues": "പരിഹാരം ട്രാക്ക് ചെയ്യുക",
    "notifications": "അറിയിപ്പുകൾ",
    "profile": "പ്രൊഫൈൽ",
    "settings": "ക്രമീകരണങ്ങൾ",
    "help": "സഹായവും പിന്തുണയും",
    "logout": "ലോഗ് ഔട്ട്",
    "login": "ലോഗിൻ",
    "recent_grievances": "സമീപകാല പരാതികൾ",
    "issue_id": "പരാതി ഐഡി (ID)",
    "citizen_portal": "പൗര പോർട്ടൽ",
    "government_portal": "സർക്കാർ പോർട്ടൽ",
    "university_portal": "സർവ്വകലാശാല പോർട്ടൽ",
    "industry_portal": "വ്യവസായ പോർട്ടൽ",
    "ngo_portal": "സന്നദ്ധ സംഘടന പോർട്ടൽ",
    "admin_portal": "അഡ്മിൻ പോർട്ടൽ",
    "ai_governance_insight": "AI ഭരണ ഉൾക്കാഴ്ചകൾ",
    "resolution": "പരിഹാരം",
    "report": "റിപ്പോർട്ടുകൾ",
    "map": "സംഭവ മാപ്പ്",
    "search": "തിരയുക",
    "search_placeholder": "പരാതികൾ, കേസുകൾ, ലൊക്കേഷൻ തിരയുക...",
    "filter": "ഫിൽട്ടർ",
    "save": "മാറ്റങ്ങൾ സേവ് ചെയ്യുക",
    "cancel": "റദ്ദാക്കുക",
    "delete": "ഡിലീറ്റ് ചെയ്യുക",
    "submit": "സമർപ്പിക്കുക",
    "upload": "അപ്‌ലോഡ് ചെയ്യുക",
    "location": "ലൊക്കേഷൻ",
    "description": "വിവരണം",
    "title": "ശീർഷകം",
    "category": "വിഭാഗം",
    "department": "വകുപ്പ്",
    "created_at": "റിപ്പോർട്ട് ചെയ്ത തീയതി",
    "action": "നടപടി",
    "actions": "നടപടികൾ",
    "view": "കാണുക",
    "edit": "എഡിറ്റ് ചെയ്യുക",
    "loading": "ലോഡ് ചെയ്യുന്നു...",
    "success": "വിജയം",
    "error": "ഒരു പിശക് സംഭവിച്ചു",
    "welcome_back": "സ്വാഗതം",
    "total_issues": "ആകെ പരാതികൾ",
    "resolved_issues": "പരിഹരിച്ച പരാതികൾ",
    "in_progress_issues": "പുരോഗതിയിലുള്ള പരാതികൾ",
    "pending_issues": "തീർപ്പാക്കാത്ത പരാതികൾ",
    "active_projects": "സജീവ പ്രോജക്റ്റുകൾ",
    "ai_accuracy": "AI റൂട്ടിംഗ് കൃത്യത",
    "sla_compliance": "SLA പാലിക്കൽ നിരക്ക്",
    "civic_engagement": "പൗര പങ്കാളിത്ത സൂചിക",
    "recent_activity": "സമീപകാല പ്രവർത്തനങ്ങൾ",
    "quick_actions": "ദ്രുത നടപടികൾ",
    "live_incidents": "തത്സമയ സംഭവങ്ങൾ",
    "all": "എല്ലാം",
    "high": "ഉയർന്ന മുൻഗണന",
    "medium": "ഇടത്തരം മുൻഗണന",
    "low": "കുറഞ്ഞ മുൻഗണന",
    "critical": "ഗുരുതരമായ മുൻഗണന",
    "emergency": "അടിയന്തിര മുൻഗണന",
    "pending": "തീർപ്പുകൽപ്പിച്ചിട്ടില്ല",
    "in_progress": "പുരോഗതിയിൽ",
    "resolved": "പരിഹരിച്ചു",
    "closed": "അടച്ചു",
    "rejected": "നിരസിച്ചു",
    "approved": "അംഗീകരിച്ചു",
    "declined": "നിരസിച്ചു",
    "export": "ഡാറ്റ എക്സ്പോർട്ട് ചെയ്യുക",
    "download": "ഡൗൺലോഡ്",
    "confirm": "സ്ഥിരീകരിക്കുക",
    "close": "അടയ്ക്കുക",
    "back": "പുറകിലേക്ക്",
    "next": "അടുത്തത്",
    "previous": "മുമ്പത്തെ",
    "no_results": "ഫലങ്ങളൊന്നും കണ്ടെത്തിയില്ല",
    "view_all": "എല്ലാം കാണുക",
    "home": "ഹോം",
    "feed": "പൗര ഫീഡ്",
    "analytics": "AI അനലിറ്റിക്സ്",
    "optional": "ഓപ്ഷണൽ",
    "faculty": "അധ്യാപക ഉപദേശകൻ",
    "student": "വിദ്യാർത്ഥി സംഘം",
    "projects": "പ്രോജക്റ്റുകൾ",
    "research": "ഗവേഷണ കേന്ദ്രം",
    "innovation": "ഇന്നൊവേഷൻ വെല്ലുവിളികൾ",
    "teams": "ടീമുകൾ",
    "credits": "അക്കാദമിക് ക്രെഡിറ്റുകൾ",
    "officers": "ഉദ്യോഗസ്ഥരുടെ ഡയറക്ടറി",
    "assigned": "നിയോഗിച്ച കേസുകൾ",
    "under_review": "പരിശോധനയിലാണ്",
    "industry_assigned": "വ്യവസായ പങ്കാളിക്ക് നൽകി",
    "industry_review": "വ്യവസായ പരിശോധന",
    "univ_assigned": "സർവ്വകലാശാലയിലേക്ക് നൽകി",
    "student_dev": "വിദ്യാർത്ഥി വികസനം",
    "faculty_review": "അധ്യാപക പരിശോധന",
    "industry_val": "വ്യവസായ സാധൂകരണം",
    "inspection": "പരിശോധന",
    "feedback": "ഫീഡ്‌ബാക്ക് കാത്തിരിക്കുന്നു"
}
