# -*- coding: utf-8 -*-
"""Telugu (te) translations dictionary for SOCIAL-X platform"""

def get_te_dict():
    return {
        "nav": {
            "overview": "అవలోకనం",
            "access_identity": "యాక్సెస్ మరియు గుర్తింపు",
            "stakeholder_ecosystem": "భాగస్వామ్య పర్యావరణ వ్యవస్థ",
            "operations_ai": "కార్యకలాపాలు మరియు AI",
            "infra_observability": "మౌలిక సదుపాయాలు మరియు పరిశీలన",
            "field_activities": "క్షేత్ర కార్యకలాపాలు మరియు ఉపశమనం",
            "community_workforce": "కమ్యూనిటీ మరియు వర్క్‌ఫోర్స్",
            "governance_comms": "పాలన మరియు సమాచార మార్పిడి",
            "csr_investment": "CSR మరియు మూలధన కేటాయింపు",
            "collaboration_rd": "సహకారం మరియు పరిశోధన",
            "student_portal": "విద్యార్థి పోర్టల్",
            "faculty_portal": "ఫ్యాకల్టీ పోర్టల్",
            "dashboard": "డ్యాష్‌బోర్డ్",
            "my_issues": "నా ఫిర్యాదులు",
            "report_problem": "సమస్యను నివేదించండి",
            "track_issues": "పరిష్కారాన్ని ట్రాక్ చేయండి",
            "notifications": "నోటిఫికేషన్‌లు",
            "profile": "ప్రొఫైల్",
            "settings": "సెట్టింగ్‌లు",
            "help": "సహాయం & మద్దతు",
            "logout": "లాగ్ అవుట్",
            "login": "లాగిన్",
            "analytics": "విశ్లేషణలు మరియు నివేదికలు",
            "assigned_cases": "కేటాయించిన కేసులు",
            "departments": "విభాగాలు",
            "officers": "అధికారుల డైరెక్టరీ",
            "ai_suggestions": "AI సూచనలు",
            "reports": "నివేదికలు మరియు ఆడిట్‌లు",
            "projects": "అందుబాటులో ఉన్న ప్రాజెక్ట్‌లు",
            "funding": "నిధుల అవకాశాలు",
            "csr_analytics": "CSR విశ్లేషణలు",
            "mentorship": "మార్గదర్శకత్వం",
            "university_collaboration": "విశ్వవిద్యాలయ సహకారం",
            "research": "పరిశోధన కార్యక్రమాలు",
            "prototypes": "నమూనాలు మరియు ప్రదర్శనలు",
            "volunteers": "వాలంటీర్ బృందాలు",
            "field_log": "క్షేత్ర ఆధారాల లాగ్",
            "impact": "కమ్యూనిటీ ప్రభావం",
            "certificates": "సర్టిఫికెట్లు మరియు బ్యాడ్జ్‌లు",
            "lab_tasks": "ల్యాబ్ పనులు",
            "upload_deliverables": "ఫలితాలను అప్‌లోడ్ చేయండి",
            "milestone_timeline": "మైలురాయి కాలక్రమం",
            "advisor_discussion": "సలహాదారు చర్చ",
            "milestone_approvals": "మైలురాయి ఆమోదాలు",
            "municipal_proposals": "మున్సిపల్ ప్రతిపాదనలు",
            "teams": "జట్లు మరియు జాబితా",
            "credits": "విద్యా క్రెడిట్‌లు",
            "user_management": "వినియోగదారు నిర్వహణ",
            "role_management": "పాత్ర నిర్వహణ",
            "government_management": "ప్రభుత్వ నిర్వహణ",
            "university_management": "విశ్వవిద్యాలయ నిర్వహణ",
            "industry_management": "పరిశ్రమ నిర్వహణ",
            "ngo_management": "ఎన్జీఓ నిర్వహణ",
            "research_organizations": "పరిశోధనా సంస్థలు",
            "issue_management": "సమస్యల నిర్వహణ",
            "ai_monitoring": "AI టెలిమెట్రీ పర్యవేక్షణ",
            "workflow_monitoring": "వర్క్‌ఫ్లో పర్యవేక్షణ",
            "audit_logs": "ఆడిట్ ట్రయల్",
            "system_health": "సిస్టమ్ ఆరోగ్యం",
            "landing_features": "ఫీచర్లు",
            "landing_how_it_works": "ఇది ఎలా పనిచేస్తుంది",
            "landing_about": "మా గురించి",
            "landing_faq": "తరచుగా అడిగే ప్రశ్నలు",
            "landing_contact": "సంప్రదించండి",
            "role_login": "పాత్ర లాగిన్",
            "citizen_sign_up": "పౌర నమోదు"
        },
        "common": {
            "buttons": {
                "browseFiles": "ఫైళ్ళను బ్రౌజ్ చేయండి",
                "openCamera": "కెమెరాను తెరవండి",
                "startRecording": "రికార్డింగ్ ప్రారంభించండి",
                "stopRecording": "రికార్డింగ్ ఆపండి",
                "submit": "సమర్పించండి",
                "cancel": "రద్దు చేయండి",
                "save": "మార్పులను సేవ్ చేయండి",
                "delete": "తొలగించండి",
                "search": "శోధించండి",
                "filter": "ఫిల్టర్",
                "upload": "అప్‌లోడ్ చేయండి",
                "confirm": "నిర్ధారించండి",
                "close": "మూసివేయండి",
                "back": "వెనుకకు",
                "next": "తదుపరి",
                "previous": "మునుపటి",
                "detectLocation": "ప్రస్తుత స్థానాన్ని గుర్తించండి",
                "useCurrentGps": "ప్రస్తుత GPSని ఉపయోగించండి",
                "resetForm": "ఫారమ్‌ను రీసెట్ చేయండి",
                "submitIssue": "ఫిర్యాదును సమర్పించండి",
                "viewAll": "అన్నీ చూడండి",
                "export": "డేటాను ఎగుమతి చేయండి",
                "download": "డౌన్‌లోడ్",
                "refresh": "రిఫ్రెష్ చేయండి",
                "login": "లాగిన్",
                "logout": "లాగ్ అవుట్",
                "modifyUploads": "మీడియా అప్‌లోడ్‌లను సవరించండి",
                "removeFile": "ఫైల్‌ను తొలగించండి",
                "removeVoiceMemo": "వాయిస్ మెమోను తీసివేయండి",
                "edit": "సవరించండి",
                "view": "వివరాలను వీక్షించండి",
                "add": "కొత్తది జోడించండి",
                "create": "సృష్టించండి",
                "update": "నవీకరించండి",
                "approve": "ఆమోదించండి",
                "reject": "తిరస్కరించండి",
                "reassign": "తిరిగి కేటాయించండి",
                "escalate": "ఎస్కలేట్ చేయండి",
                "resolve": "కేసును పరిష్కరించండి",
                "assign": "కేటాయించండి",
                "verify": "ధృవీకరించండి",
                "downloadReport": "నివేదికను డౌన్‌లోడ్ చేయండి",
                "syncTelemetry": "టెలిమెట్రీని సమకాలీకరించండి",
                "applyFilters": "ఫిల్టర్‌లను వర్తింపజేయండి",
                "clearFilters": "ఫిల్టర్‌లను క్లియర్ చేయండి",
                "viewDetails": "వివరాలు చూడండి",
                "sendNotification": "నోటిఫికేషన్ పంపండి",
                "inviteMember": "సభ్యుడిని ఆహ్వానించండి",
                "print": "ప్రింట్",
                "share": "భాగస్వామ్యం చేయండి",
                "copyLink": "లింక్‌ను కాపీ చేయండి",
                "proceed": "కొనసాగించండి",
                "retry": "మళ్ళీ ప్రయత్నించండి",
                "dismiss": "రద్దు చేయండి",
                "accept": "అంగీకరించండి",
                "decline": "తిరస్కరించండి"
            },
            "labels": {
                "dashboard": "డ్యాష్‌బోర్డ్",
                "profile": "ప్రొఫైల్",
                "settings": "సెట్టింగ్‌లు",
                "notifications": "నోటిఫికేషన్‌లు",
                "help": "సహాయం & మద్దతు",
                "logout": "లాగ్ అవుట్",
                "login": "లాగిన్",
                "status": "స్థితి",
                "priority": "ప్రాధాన్యత",
                "department": "విభాగం",
                "category": "వర్గం",
                "district": "జిల్లా",
                "ward": "వార్డు",
                "address": "చిరునామా",
                "landmark": "ల్యాండ్‌మార్క్",
                "title": "శీర్షిక",
                "description": "వివరణ",
                "location": "స్థానం",
                "latitude": "అక్షాంశం",
                "longitude": "రేఖాంశం",
                "accuracy": "ఖచ్చితత్వం",
                "date": "తేదీ",
                "action": "చర్య",
                "actions": "చర్యలు",
                "all": "అన్నీ",
                "high": "అధిక",
                "medium": "మధ్యస్థ",
                "low": "తక్కువ",
                "critical": "క్లిష్టమైనది",
                "emergency": "అత్యవసరం",
                "pending": "పెండింగ్‌లో ఉంది",
                "inProgress": "పురోగతిలో ఉంది",
                "resolved": "పరిష్కరించబడింది",
                "closed": "మూసివేయబడింది",
                "rejected": "తిరస్కరించబడింది",
                "verified": "ధృవీకరించబడింది",
                "assigned": "కేటాయించబడింది",
                "recentActivity": "ఇటీవలి కార్యాచరణ",
                "quickActions": "త్వరిత చర్యలు",
                "systemHealth": "సిస్టమ్ ఆరోగ్యం",
                "language": "భాష",
                "selectLanguage": "భాషను ఎంచుకోండి",
                "searchLanguage": "భాషలను శోధించండి...",
                "editable": "సవరించదగినది",
                "active": "క్రియాశీల",
                "inactive": "నిష్క్రియ",
                "completed": "పూర్తయింది",
                "failed": "విఫలమైంది",
                "total": "మొత్తం",
                "count": "సంఖ్య",
                "rate": "రేటు",
                "percentage": "శాతం",
                "timeRemaining": "మిగిలిన సమయం",
                "dueDate": "గడువు తేదీ",
                "submittedBy": "సమర్పించిన వారు",
                "assignedTo": "కేటాయించబడిన వారు",
                "officerInCharge": "ఇన్చార్జ్ అధికారి",
                "slaTimer": "SLA టైమర్",
                "auditTimeline": "ఆడిట్ కాలక్రమం",
                "contactInfo": "సంప్రదింపు సమాచారం",
                "phoneNumber": "ఫోన్ నంబర్",
                "emailAddress": "ఇమెయిల్ చిరునామా",
                "fullName": "పూర్తి పేరు",
                "role": "పాత్ర",
                "organization": "సంస్థ",
                "institution": "విద్యా సంస్థ",
                "createdAt": "నివేదించబడిన తేదీ",
                "updatedAt": "నవీకరించబడిన తేదీ"
            },
            "status": {
                "open": "ఓపెన్",
                "submitted": "సమర్పించబడింది",
                "verified": "AI ధృవీకరించబడింది",
                "assigned": "కేటాయించబడింది",
                "in_progress": "పురోగతిలో ఉంది",
                "inProgress": "పురోగతిలో ఉంది",
                "resolved": "పరిష్కరించబడింది",
                "closed": "మూసివేయబడింది",
                "rejected": "తిరస్కరించబడింది",
                "under_review": "సమీక్షలో ఉంది",
                "under_government_review": "ప్రభుత్వ సమీక్షలో ఉంది",
                "assigned_to_government": "ప్రభుత్వానికి కేటాయించబడింది",
                "assigned_to_industry": "పరిశ్రమకు కేటాయించబడింది",
                "industry_review": "పరిశ్రమ సమీక్ష",
                "assigned_to_university": "విశ్వవిద్యాలయానికి కేటాయించబడింది",
                "student_development": "విద్యార్థి అభివృద్ధి",
                "faculty_review": "ఫ్యాకల్టీ సమీక్ష",
                "industry_validation": "పరిశ్రమ ధృవీకరణ",
                "inspection": "క్షేత్ర తనిఖీ",
                "feedback_pending": "అభిప్రాయం పెండింగ్‌లో ఉంది",
                "escalated": "ఎస్కలేట్ చేయబడింది",
                "active": "క్రియాశీల",
                "inactive": "నిష్క్రియ",
                "completed": "పూర్తయింది",
                "approved": "ఆమోదించబడింది",
                "declined": "తిరస్కరించబడింది",
                "pending": "పెండింగ్‌లో ఉంది"
            },
            "priority": {
                "low": "తక్కువ ప్రాధాన్యత",
                "medium": "మధ్యస్థ ప్రాధాన్యత",
                "high": "అధిక ప్రాధాన్యత",
                "critical": "క్లిష్టమైన ప్రాధాన్యత",
                "emergency": "అత్యవసర ప్రాధాన్యత",
                "urgent": "అత్యవసరం"
            },
            "departments": {
                "waterSupply": "నీటి సరఫరా మరియు డ్రైనేజీ",
                "roadsTransport": "రహదారులు మరియు రవాణా",
                "electricityPower": "విద్యుత్ మరియు పవర్ గ్రిడ్",
                "solidWaste": "ఘన వ్యర్థాలు మరియు పారిశుధ్యం",
                "publicHealth": "ప్రజా ఆరోగ్యం మరియు భద్రత",
                "urbanPlanning": "పట్టణ ప్రణాళిక మరియు మౌలిక సదుపాయాలు",
                "education": "విద్య మరియు యువజన వ్యవహారాలు",
                "environmentForest": "పర్యావరణం మరియు అటవీ శాఖ",
                "policeSafety": "పోలీస్ మరియు ప్రజా భద్రత",
                "disasterManagement": "విపత్తు నిర్వహణ అథారిటీ",
                "municipalAdmin": "మున్సిపల్ పరిపాలన"
            },
            "categories": {
                "water": "నీటి సరఫరా మరియు డ్రైనేజీ",
                "roads": "రహదారులు మరియు రవాణా",
                "electricity": "విద్యుత్ మరియు పవర్ గ్రిడ్",
                "waste": "ఘన వ్యర్థాలు మరియు పారిశుధ్యం",
                "health": "ప్రజా ఆరోగ్యం మరియు భద్రత",
                "sanitation": "పారిశుధ్యం మరియు మురుగునీరు",
                "infrastructure": "ప్రజా మౌలిక సదుపాయాలు",
                "streetlights": "వీధి దీపాలు మరియు విద్యుత్",
                "drainage": "డ్రైనేజీ మరియు మురుగు కాలువలు",
                "potholes": "గుంతలు మరియు రోడ్డు మరమ్మతులు",
                "traffic": "ట్రాఫిక్ మరియు రహదారి భద్రత",
                "pollution": "కాలుష్యం మరియు పర్యావరణ ముప్పు"
            },
            "validation": {
                "requiredField": "ఈ ఫీల్డ్ అవసరం",
                "titleRequired": "శీర్షిక అవసరం",
                "descriptionRequired": "వివరణ అవసరం",
                "locationRequired": "సంఘటన స్థానం అవసరం",
                "invalidEmail": "దయచేసి సరైన ఇమెయిల్ చిరునామాను నమోదు చేయండి",
                "invalidPassword": "పాస్‌వర్డ్ కనీసం 8 అక్షరాలు ఉండాలి",
                "passwordTooShort": "పాస్‌వర్డ్ చాలా చిన్నది (కనీసం 8 అక్షరాలు)",
                "passwordMismatch": "పాస్‌వర్డ్‌లు సరిపోలడం లేదు",
                "unsupportedFile": "మద్దతు లేని ఫైల్ ఫార్మాట్. దయచేసి JPEG, PNG, MP4 లేదా PDFని అప్‌లోడ్ చేయండి.",
                "maxFileSizeExceeded": "గరిష్ట ఫైల్ పరిమాణం మించిపోయింది (25MB పరిమితి)",
                "micPermissionDenied": "మైక్రోఫోన్ అనుమతి నిరాకరించబడింది. దయచేసి అనుమతించండి.",
                "cameraPermissionDenied": "కెమెరా అనుమతి నిరాకరించబడింది. దయచేసి అనుమతించండి.",
                "minLength": "ఇన్‌పుట్ కనీస పొడవు కంటే తక్కువగా ఉంది",
                "maxLength": "ఇన్‌పుట్ గరిష్ట పొడవును మించిపోయింది",
                "uploadFailed": "అప్‌లోడ్ విఫలమైంది. దయచేసి మళ్ళీ ప్రయత్నించండి.",
                "uploadSuccessful": "ఫైల్ విజయవంతంగా అప్‌లోడ్ చేయబడింది.",
                "loginSuccessful": "విజయవంతంగా సైన్ ఇన్ అయ్యారు.",
                "registrationSuccessful": "నమోదు విజయవంతంగా పూర్తయింది.",
                "fillRequiredFields": "సమర్పించే ముందు అన్ని తప్పనిసరి ఫీల్డ్‌లను పూరించండి."
            },
            "emptyStates": {
                "noData": "డేటా అందుబాటులో లేదు",
                "noResults": "శోధనకు సరిపోలే ఫలితాలు ఏవీ కనుగొనబడలేదు",
                "noNotifications": "కొత్త నోటిఫికేషన్‌లు ఏవీ లేవు",
                "noIssuesFound": "మీ ప్రమాణాలకు సరిపోలే ఫిర్యాదులు ఏవీ లేవు",
                "noProjectsFound": "ప్రస్తుతం క్రియాశీల ప్రాజెక్ట్‌లు ఏవీ లేవు",
                "noOfficersFound": "శోధన ఫిల్టర్‌లకు సరిపోలే అధికారులు లేరు",
                "noActivitiesFound": "ఇంతవరకు ఎటువంటి క్షేత్ర కార్యకలాపాలు నమోదు కాలేదు"
            },
            "loading": {
                "loading": "లోడ్ అవుతోంది...",
                "pleaseWait": "దయచేసి వేచి ఉండండి...",
                "fetchingData": "తాజా డేటాను పొందుతోంది...",
                "processing": "మీ అభ్యర్థన ప్రాసెస్ చేయబడుతోంది...",
                "uploadingMedia": "మీడియా అప్‌లోడ్ అవుతోంది...",
                "analyzingAi": "AIతో విశ్లేషించబడుతోంది...",
                "savingChanges": "మార్పులు సేవ్ అవుతున్నాయి..."
            },
            "pagination": {
                "previous": "మునుపటి",
                "next": "తదుపరి",
                "page": "పేజీ",
                "of": "యొక్క",
                "rowsPerPage": "పేజీకి అడ్డువరుసలు",
                "showing": "చూపిస్తోంది",
                "entries": "ఎంట్రీలు",
                "totalRecords": "మొత్తం రికార్డులు"
            },
            "search": {
                "searchPlaceholder": "ఫిర్యాదులు, కేసులు, స్థానాలను శోధించండి...",
                "searchGrievances": "ఫిర్యాదులను శోధించండి...",
                "searchUsers": "వినియోగదారులను శోధించండి...",
                "searchDepartments": "విభాగాలను శోధించండి...",
                "searchProjects": "ప్రాజెక్ట్‌లను శోధించండి...",
                "searchOfficers": "అధికారులను శోధించండి...",
                "quickNavigator": "శీఘ్ర నావిగేటర్...",
                "searchAll": "ప్లాట్‌ఫారమ్ అంతటా శోధించండి..."
            }
        },
        "ai": {
            "processing": "AI ప్రాసెసింగ్",
            "ocrResult": "OCR వచనం సంగ్రహించబడింది",
            "speechResult": "వ్యావహారిక ప్రసంగ లిప్యంతరీకరణ",
            "speechTranscript": "ప్రసంగ లిప్యంతరీకరణ",
            "confidenceScore": "AI విశ్వాస స్కోరు",
            "aiConfidence": "AI విశ్వాసం",
            "suggestedCategory": "సూచించిన వర్గం",
            "suggestedDepartment": "సూచించిన విభాగం",
            "recommendedDepartment": "సిఫార్సు చేయబడిన విభాగం",
            "suggestedIndustry": "సూచించిన పరిశ్రమ భాగస్వామి",
            "duplicateDetection": "నకిలీ ఫిర్యాదుల గుర్తింపు",
            "aiVerification": "మల్టీమోడల్ విజన్ ధృవీకరణ",
            "smartRouting": "ఇంటెలిజెంట్ డిపార్ట్‌మెంటల్ రూటింగ్",
            "previewTitle": "మల్టీమోడల్ AI సంగ్రహణ ప్రివ్యూ",
            "previewSubtitle": "కంప్యూటర్ విజన్ మరియు స్పీచ్ పైప్‌లైన్‌లు కింది డేటాను సేకరించాయి. పంపే ముందు సరిచూసుకోండి.",
            "detectedHeadline": "గుర్తించిన ఫిర్యాదు శీర్షిక",
            "classifiedCategory": "AI వర్గీకరించిన విభాగం",
            "dispatchedDept": "కేటాయించిన మున్సిపల్ విభాగం",
            "severityPriority": "తీవ్రత & ప్రాధాన్యత",
            "mappedLocation": "మ్యాప్ చేయబడిన సంఘటన స్థానం",
            "confirmSubmit": "ధృవీకరించి ఫిర్యాదును పంపండి",
            "cancel": "రద్దు చేయండి",
            "ocrBadge": "FastAPI OCR సంగ్రహించబడింది",
            "sttBadge": "వ్యావహారిక ప్రసంగం లిప్యంతరీకరించబడింది",
            "verificationStep": "పౌర ధృవీకరణ దశ",
            "verificationStepHelp": "100% ఖచ్చితత్వాన్ని నిర్ధారించడానికి మీరు పంపే ముందు దిగువ ఫీల్డ్‌లను నేరుగా సవరించవచ్చు.",
            "ocrVision": "OCR విజన్ సంగ్రహణ",
            "noOcrText": "సైన్‌బోర్డులపై వచనం ఏదీ గుర్తించబడలేదు",
            "noAudioMemo": "ఆడియో మెమో జతచేయబడలేదు",
            "priorityScore": "గణించబడిన ప్రాధాన్యత స్కోరు",
            "estimatedCost": "అంచనా వేసిన మున్సిపల్ ఖర్చు",
            "estimatedTime": "అంచనా వేసిన పరిష్కార సమయం",
            "recommendation": "AI పాలన సిఫార్సు",
            "confidenceHigh": "అధిక విశ్వాసం (>90%)",
            "confidenceMedium": "మధ్యస్థ విశ్వాసం (70-90%)",
            "confidenceLow": "తక్కువ విశ్వాసం (<70%)",
            "duplicateFound": "నకిలీ ఫిర్యాదు గుర్తించబడింది",
            "duplicateScore": "సారూప్యత స్కోరు"
        },
        "citizen": {
            "portalTitle": "పౌర పోర్టల్",
            "dashboard": {
                "welcomeBack": "తిరిగి స్వాగతం",
                "totalReported": "మొత్తం నివేదించినవి",
                "inProgress": "పురోగతిలో ఉంది",
                "resolved": "పరిష్కరించబడింది",
                "needsVerification": "ధృవీకరణ అవసరం",
                "communityImpact": "కమ్యూనిటీ ప్రభావ స్కోరు",
                "avgResolution": "సగటు పరిష్కార సమయం",
                "recentGrievances": "ఇటీవలి ఫిర్యాదులు",
                "reportNewIssue": "కొత్త ఫిర్యాదును నివేదించండి",
                "myIssues": "నా ఫిర్యాదులు",
                "trackIssues": "పరిష్కారాన్ని ట్రాక్ చేయండి",
                "liveIncidents": "లైవ్ పౌర సంఘటనలు",
                "civicFeed": "పౌర ఫీడ్",
                "satisfactionScore": "పౌర సంతృప్తి రేటింగ్",
                "activeCases": "క్రియాశీల ఫిర్యాదులు",
                "resolvedCases": "పరిష్కరించబడిన ఫిర్యాదులు"
            },
            "report": {
                "title": "సామాజిక ఫిర్యాదును నివేదించండి",
                "subtitle": "ఫోటోలు, వీడియో, ఆడియో వాయిస్ నోట్స్ లేదా పత్రాలను సమర్పించండి. మా AI ఇంజిన్ OCR ద్వారా సైన్‌బోర్డ్‌లను సేకరించి ప్రివ్యూని రూపొందిస్తుంది.",
                "multimodalBadge": "మల్టీమోడల్ AI ఇంజెషన్",
                "moduleBadge": "మాడ్యూల్ 1",
                "uploadEvidence": "ఫోటోగ్రాఫిక్ & డాక్యుమెంట్ ఆధారాలు",
                "uploadSubtitle": "లోపం, విరిగిన సైన్‌బోర్డ్ లేదా మున్సిపల్ పత్రం యొక్క చిత్రాన్ని అప్‌లోడ్ చేయండి",
                "dragDrop": "చిత్రాలు, వీడియో క్లిప్‌లు లేదా పత్రాలను లాగి వదలండి",
                "supportedFormats": "JPEG, PNG, MP4 మరియు PDF (గరిష్టంగా 25MB) మద్దతు ఇస్తుంది.",
                "browseFiles": "ఫైళ్ళను బ్రౌజ్ చేయండి",
                "openCamera": "కెమెరాను తెరవండి",
                "uploadingProgress": "AI ద్వారా మీడియా అప్‌లోడ్ మరియు ప్రాసెస్ అవుతోంది...",
                "attachedEvidence": "జతచేయబడిన ఆధారాలు",
                "voiceGrievance": "వాయిస్ ఆడియో ఫిర్యాదు",
                "optional": "ఐచ్ఛికం",
                "voiceSubtitle": "మాట్లాడిన వివరణను రికార్డ్ చేయండి. స్పీచ్-టు-టెక్స్ట్ ద్వారా స్వయంచాలకంగా లిప్యంతరీకరించబడుతుంది.",
                "pressRecordHelp": "ఏదైనా భాషలో మీ సమస్యను వివరించడానికి రికార్డ్‌ను నొక్కండి.",
                "startVoiceRecording": "వాయిస్ రికార్డింగ్ ప్రారంభించండి",
                "stopRecording": "రికార్డింగ్ ఆపండి",
                "recording": "రికార్డింగ్ అవుతోంది...",
                "speechProcessing": "స్పీచ్ ప్రాసెసింగ్...",
                "speechConverted": "వాయిస్ విజయవంతంగా మార్చబడింది",
                "incidentLocation": "సంఘటన స్థానం",
                "locationSubtitle": "ఫీల్డ్ వర్కర్ డిస్పాచ్ కోసం ఖచ్చితమైన కోఆర్డినేట్‌లను గుర్తించండి",
                "useCurrentGps": "ప్రస్తుత GPSని ఉపయోగించండి",
                "streetAddress": "వీధి చిరునామా / ల్యాండ్‌మార్క్",
                "addressPlaceholder": "ఉదా. 14వ మెయిన్ రోడ్, ఇందిరా గాంధీ సర్కిల్ దగ్గర",
                "mapTip": "చిట్కా: కోఆర్డినేట్‌లను సర్దుబాటు చేయడానికి మీరు మ్యాప్‌లో ఎక్కడైనా క్లిక్ చేయవచ్చు.",
                "contextTitle": "సమస్య వివరణ",
                "contextSubtitle": "సంక్షిప్త సందర్భాన్ని అందించండి (AI స్వయంచాలకంగా వర్గీకరిస్తుంది)",
                "headlineLabel": "సంక్షిప్త ఫిర్యాదు శీర్షిక",
                "headlinePlaceholder": "ఉదా., భూగర్భ నీటి పైపు పగిలి రోడ్డుపై నీరు చేరడం",
                "detailsLabel": "వివరణాత్మక వివరణ",
                "detailsPlaceholder": "సామాజిక ప్రభావం, వ్యవధి మరియు భద్రతా ప్రమాదాలను వివరించండి...",
                "categoryLabel": "మున్సిపల్ వర్గం",
                "priorityLabel": "అత్యవసర ప్రాధాన్యత",
                "generateAiPreview": "AI ప్రివ్యూను రూపొందించండి",
                "processingAi": "AI ప్రాసెసింగ్ కొనసాగుతోంది...",
                "audioMemo": "ఆడియో ఫిర్యాదు మెమో",
                "readyStt": "STT పార్సింగ్ కోసం సిద్ధంగా ఉంది",
                "incidentCoordinates": "సంఘటన కోఆర్డినేట్‌లు",
                "currentDetectedLocation": "గుర్తించిన ప్రస్తుత స్థానం"
            },
            "track": {
                "title": "ఫిర్యాదు పరిష్కారాన్ని ట్రాక్ చేయండి",
                "subtitle": "లైవ్ స్థితి మార్పులు, కేటాయించిన ఇంజనీర్లు మరియు SLA టైమర్‌లను పర్యవేక్షించండి.",
                "enterId": "ట్రాకింగ్ IDని నమోదు చేయండి",
                "searchPlaceholder": "ఉదా. SOC-2026-8821",
                "currentStage": "ప్రస్తుత దశ",
                "assignedTo": "కేటాయించిన విభాగం",
                "officerInCharge": "ఇన్చార్జ్ అధికారి",
                "slaTimer": "SLA పరిష్కార కౌంట్‌డౌన్",
                "timeline": "ఆడిట్ కాలక్రమం",
                "trackingDetails": "ట్రాకింగ్ వివరాలు",
                "liveStatusTransitions": "లైవ్ స్థితి మార్పులు"
            },
            "profile": {
                "title": "పౌర ప్రొఫైల్",
                "fullName": "పూర్తి పేరు",
                "email": "ఇమెయిల్ చిరునామా",
                "phone": "ఫోన్ నంబర్",
                "district": "నివాస జిల్లా",
                "address": "శాశ్వత చిరునామా",
                "saveProfile": "ప్రొఫైల్‌ను సేవ్ చేయండి",
                "citizenBadge": "ధృవీకరించబడిన పౌరుడు",
                "verificationStatus": "గుర్తింపు ధృవీకరణ స్థితి"
            },
            "settings": {
                "title": "ప్రాధాన్యతలు & సెట్టింగ్‌లు",
                "notifications": "ఫిర్యాదు నోటిఫికేషన్‌లు",
                "emailAlerts": "ఇమెయిల్ హెచ్చరికలు",
                "smsAlerts": "SMS హెచ్చరికలు",
                "theme": "డిస్‌ప్లే థీమ్",
                "language": "యాప్ భాష",
                "savePreferences": "ప్రాధాన్యతలను సేవ్ చేయండి"
            }
        },
        "government": {
            "portalTitle": "మున్సిపల్ కమాండ్ & కంట్రోల్",
            "dashboard": {
                "title": "ప్రభుత్వ అధికారిక పోర్టల్",
                "overview": "మున్సిపల్ అవలోకనం",
                "assignedCases": "కేటాయించిన ఫిర్యాదులు",
                "liveCases": "క్రియాశీల కేసులు",
                "slaBreachRisk": "SLA ఉల్లంఘన ప్రమాదం",
                "avgTurnaround": "సగటు పరిష్కార సమయం",
                "citizenSatisfaction": "పౌర సంతృప్తి",
                "urgentDocket": "అత్యవసర కేసుల జాబితా",
                "viewQueue": "పూర్తి జాబితాను వీక్షించండి",
                "syncTelemetry": "టెలిమెట్రీని సమకాలీకరించండి",
                "telemetryActive": "నిజ-సమయ పౌర టెలిమెట్రీ మరియు స్వయంచాలక డిస్పాచ్ సక్రియంగా ఉన్నాయి.",
                "monthlyTrends": "నెలవారీ ఫిర్యాదుల పోకడలు",
                "resolutionBreakdown": "పరిష్కార వివరాలు",
                "districtHeatmap": "జిల్లా పనితీరు హీట్‌మ్యాప్",
                "departmentEfficiency": "విభాగ సామర్థ్య రేటింగ్‌లు",
                "docketOverview": "కేసుల అవలోకనం",
                "statutoryTarget": "24 గంటల చట్టబద్ధమైన రాష్ట్ర లక్ష్యానికి వ్యతిరేకంగా"
            },
            "officers": {
                "title": "అధికారుల డైరెక్టరీ",
                "directory": "క్షేత్ర మరియు నోడల్ అధికారులు",
                "addOfficer": "అధికారిని నమోదు చేయండి",
                "officerName": "అధికారి పేరు",
                "designation": "హోదా",
                "department": "విభాగం",
                "contact": "సంప్రదించండి",
                "assignedCount": "కేటాయించిన కేసులు",
                "resolutionRate": "పరిష్కార రేటు",
                "status": "డ్యూటీ స్థితి",
                "actions": "చర్యలు",
                "searchOfficers": "పేరు, బ్యాడ్జ్ లేదా విభాగం ద్వారా అధికారులను శోధించండి..."
            },
            "departments": {
                "title": "మున్సిపల్ విభాగాలు",
                "municipalDepartments": "నగర కార్యాచరణ విభాగాలు",
                "addDepartment": "విభాగాన్ని జోడించండి",
                "deptName": "విభాగం పేరు",
                "headOfDept": "విభాగాధిపతి",
                "activePersonnel": "క్రియాశీల సిబ్బంది",
                "budgetAllocated": "కేటాయించిన బడ్జెట్",
                "openGrievances": "పరిష్కారం కాని ఫిర్యాదులు",
                "slaCompliance": "SLA సమ్మతి",
                "efficiencyRating": "సామర్థ్య రేటింగ్",
                "searchDepartments": "విభాగాలను శోధించండి..."
            },
            "assigned": {
                "title": "కేటాయించిన ఫిర్యాదులు",
                "caseId": "కేసు ID",
                "citizenName": "పౌరుడి పేరు",
                "category": "వర్గం",
                "priority": "ప్రాధాన్యత",
                "status": "స్థితి",
                "dateReported": "నివేదించిన తేదీ",
                "targetResolution": "లక్ష్య పరిష్కారం",
                "reassign": "అధికారిని తిరిగి కేటాయించండి",
                "escalate": "ఎస్కలేట్ చేయండి",
                "resolveCase": "పరిష్కరించినట్లు గుర్తించండి",
                "viewCase": "కేసును పరిశీలించండి",
                "filterPriority": "ప్రాధాన్యత ఆధారంగా ఫిల్టర్ చేయండి",
                "filterStatus": "స్థితి ఆధారంగా ఫిల్టర్ చేయండి",
                "allCases": "అన్ని కేసులు"
            },
            "tracking": {
                "title": "ఫిర్యాదుల జియో ట్రాకింగ్",
                "subtitle": "క్షేత్ర అధికారి టెలిమెట్రీతో సమస్యలను చూపే ఇంటరాక్టివ్ భౌగోళిక మ్యాప్.",
                "liveIncidentMap": "లైవ్ సంఘటన మ్యాప్",
                "filterByWard": "వార్డు వారీగా ఫిల్టర్ చేయండి",
                "filterBySeverity": "తీవ్రత ఆధారంగా ఫిల్టర్ చేయండి"
            },
            "aiSuggestions": {
                "title": "AI పాలన అంతర్దృష్టులు",
                "smartRoutingTitle": "స్వయంచాలక రూటింగ్ సిఫార్సులు",
                "recommendedActions": "సిఫార్సు చేసిన చర్యలు",
                "anomalyDetection": "అసాధారణతల గుర్తింపు",
                "duplicateClusters": "నకిలీ సమూహాలు గుర్తించబడ్డాయి",
                "autoTriage": "ఆటో-ట్రయాజ్ నిబంధనల ఇంజిన్"
            },
            "reports": {
                "title": "పాలన విశ్లేషణలు మరియు నివేదికలు",
                "generateReport": "నివేదికను రూపొందించండి",
                "downloadPdf": "PDFని డౌన్‌లోడ్ చేయండి",
                "downloadCsv": "CSVని ఎగుమతి చేయండి",
                "monthlyAudit": "నెలవారీ మున్సిపల్ ఆడిట్",
                "quarterlyPerformance": "త్రైమాసిక పనితీరు సమీక్ష",
                "exportAnalytics": "విశ్లేషణలను ఎగుమతి చేయండి"
            },
            "settings": {
                "title": "పోర్టల్ పరిపాలన సెట్టింగ్‌లు",
                "slaThresholds": "SLA అత్యవసర పరిమితులు",
                "notificationRules": "హెచ్చరిక మరియు నోటిఫికేషన్ నియమాలు",
                "escalationMatrix": "ఎస్కలేషన్ మ్యాట్రిక్స్",
                "workingHours": "విభాగ పని గంటలు"
            }
        },
        "industry": {
            "portalTitle": "పరిశ్రమ మరియు కార్పొరేట్ CSR పోర్టల్",
            "dashboard": {
                "title": "పరిశ్రమ CSR డ్యాష్‌బోర్డ్",
                "overview": "CSR మూలధనం మరియు ప్రభావం",
                "csrFunding": "CSR నిధుల కేటాయింపు",
                "capitalAllocation": "మూలధన కేటాయింపు",
                "availableProjects": "ధృవీకరించబడిన ప్రాజెక్ట్‌లు",
                "liveGrants": "క్రియాశీల గ్రాంట్లు",
                "partnershipPact": "PPP ఒప్పందాలు",
                "totalDisbursed": "మొత్తం పంపిణీ చేసిన నిధులు",
                "activeProjects": "క్రియాశీల నిధుల ప్రాజెక్ట్‌లు",
                "impactScore": "సామాజిక ప్రభావ స్కోరు",
                "viewOpportunities": "అవకాశాలను చూడండి",
                "availableCsr": "అందుబాటులో ఉన్న CSR బడ్జెట్",
                "corporatePartner": "కార్పొరేట్ భాగస్వామి",
                "verifiedEntity": "ధృవీకరించబడిన CSR సంస్థ"
            },
            "projects": {
                "title": "అందుబాటులో ఉన్న CSR ప్రాజెక్ట్‌లు",
                "projectCatalog": "ప్రాజెక్ట్ కేటలాగ్",
                "fundingGoal": "లక్ష్య నిధులు",
                "raisedAmount": "సమకూరిన నిధులు",
                "municipalSponsor": "మున్సిపల్ స్పాన్సర్",
                "sdgImpact": "SDG ప్రభావ వర్గం",
                "applyFunding": "CSR నిధులను అందించండి",
                "exploreInitiatives": "కార్యక్రమాలను అన్వేషించండి",
                "searchProjects": "కీవర్డ్, SDG లేదా నగరం ద్వారా శోధించండి..."
            },
            "funding": {
                "title": "నిధులు మరియు మూలధన కేటాయింపు",
                "grantApplication": "గ్రాంట్ ప్రతిపాదన",
                "disbursementStatus": "పంపిణీ స్థితి",
                "corporateDonation": "కార్పొరేట్ సహకారం",
                "taxBenefit": "సెక్షన్ 80G / 135 ప్రయోజనం",
                "escrowStatus": "ఎస్క్రో ఖాతా స్థితి",
                "fundMilestone": "విడత నిధులను విడుదల చేయండి"
            },
            "csr": {
                "title": "CSR ప్రభావ విశ్లేషణలు",
                "spendByCategory": "వర్గం వారీగా ఖర్చు",
                "geographicAllocation": "భౌగోళిక కేటాయింపు",
                "socialReturnOnInvestment": "సామాజిక రాబడి (SROI)",
                "auditCompliance": "చట్టబద్ధమైన ఆడిట్ సమ్మతి",
                "csrDistribution": "CSR పంపిణీ"
            },
            "mentorship": {
                "title": "పరిశ్రమ మార్గదర్శకత్వ కార్యక్రమం",
                "expertGuidance": "నిపుణుల మార్గదర్శకత్వం అందించండి",
                "studentPrototypes": "విద్యార్థి నమూనాలు",
                "industryAdvisors": "కార్పొరేట్ సలహాదారులు",
                "scheduleSession": "సెషన్‌ను షెడ్యూల్ చేయండి"
            },
            "collaboration": {
                "title": "విశ్వవిద్యాలయ సహకార కేంద్రం",
                "academicPacts": "విద్యా కూటములు",
                "joinConsortium": "కన్సార్టియంలో చేరండి",
                "jointResearch": "ఉమ్మడి పరిశోధనలు",
                "mouSigned": "సంతకం చేసిన అవగాహన ఒప్పందాలు"
            },
            "prototypes": {
                "title": "సాంకేతిక నమూనాలు",
                "technologyDemonstrators": "పౌర నమూనాలు",
                "readyForDeployment": "పైలట్ విస్తరణకు సిద్ధంగా ఉంది",
                "pilotTested": "క్షేత్రస్థాయిలో పరీక్షించబడింది",
                "commercialize": "వాణిజ్యీకరించండి"
            },
            "tracking": {
                "title": "నిధులు మరియు మైలురాళ్ల ట్రాకింగ్",
                "milestoneProgress": "మైలురాయి పురోగతి",
                "verificationCheck": "థర్డ్-పార్టీ ఆడిట్ తనిఖీ",
                "fundRelease": "విడత విడుదల"
            },
            "profile": {
                "title": "సంస్థ ప్రొఫైల్",
                "companyName": "కంపెనీ పేరు",
                "cinRegistration": "కార్పొరేట్ గుర్తింపు (CIN)",
                "csrBudget": "వార్షిక CSR బడ్జెట్",
                "contactPerson": "CSR హెడ్ / సంప్రదించండి",
                "panNumber": "కార్పొరేట్ పాన్"
            },
            "settings": {
                "title": "CSR సెట్టింగ్‌లు",
                "emailNotifications": "కార్యాచరణ హెచ్చరికలు",
                "bankDetails": "బ్యాంకింగ్ వివరాలు",
                "complianceDocs": "సమ్మతి పత్రాలు"
            }
        },
        "ngo": {
            "portalTitle": "పౌర సమాజం మరియు వాలంటీర్ పోర్టల్",
            "dashboard": {
                "title": "పౌర సమాజ డ్యాష్‌బోర్డ్",
                "overview": "క్షేత్ర కార్యకలాపాల అవలోకనం",
                "groundSquads": "క్రియాశీల వాలంటీర్ బృందాలు",
                "activeVolunteers": "నమోదిత వాలంటీర్లు",
                "fieldInterventions": "క్షేత్ర జోక్యాలు",
                "reliefOperations": "సహాయక చర్యలు",
                "communityImpact": "లబ్ధి పొందిన పౌరులు",
                "certsAwarded": "అందించిన సర్టిఫికెట్లు",
                "urgentReliefCalls": "అత్యవసర సహాయ కాల్స్",
                "groundTelemetryLive": "క్షేత్ర టెలిమెట్రీ లైవ్",
                "logFieldEvidence": "క్షేత్ర ఆధారాలను నమోదు చేయండి"
            },
            "projects": {
                "title": "కమ్యూనిటీ ప్రాజెక్ట్‌లు",
                "localGrievances": "పౌర సమస్యలను స్వీకరించండి",
                "adoptIssue": "బృందాన్ని సమీకరించండి",
                "publicWorks": "కమ్యూనిటీ కార్యక్రమాలు",
                "grassrootInterventions": "క్షేత్రస్థాయి జోక్యాలు"
            },
            "assignedProjects": {
                "title": "కేటాయించిన NGO ప్రాజెక్ట్‌లు",
                "operationalSquads": "కేటాయించిన బృందాలు",
                "projectTimeline": "అమలు కాలక్రమం",
                "targetCompletion": "లక్ష్య పూర్తి తేదీ",
                "submitProgressReport": "పురోగతి నివేదికను సమర్పించండి"
            },
            "fieldActivities": {
                "title": "క్షేత్ర ఆధారాల లాగ్",
                "liveReliefLog": "లైవ్ క్షేత్ర లాగ్‌లు",
                "geoTaggedPhotos": "జియో-ట్యాగ్ చేయబడిన ఫోటోలు",
                "suppliesDistributed": "పంపిణీ చేసిన సహాయం",
                "citizensAssisted": "సహాయం పొందిన పౌరులు",
                "addLogEntry": "కొత్త లాగ్‌ను సమర్పించండి"
            },
            "volunteers": {
                "title": "వాలంటీర్ల నిర్వహణ",
                "registerVolunteer": "కొత్త వాలంటీర్‌ను చేర్చుకోండి",
                "skillsDirectory": "నైపుణ్యాల డైరెక్టరీ",
                "assignWard": "వార్డును కేటాయించండి",
                "volunteerSquads": "క్షేత్ర బృందాలు",
                "attendance": "హాజరు"
            },
            "impact": {
                "title": "కమ్యూనిటీ ప్రభావ విశ్లేషణలు",
                "livesImpacted": "ప్రయోజనం పొందిన పౌరులు",
                "wardsTransformed": "మార్పు చెందిన మున్సిపల్ వార్డులు",
                "satisfactionIndex": "సంతృప్తి సూచిక",
                "volunteerHours": "మొత్తం వాలంటీర్ గంటలు"
            },
            "collaborations": {
                "title": "భాగస్వామ్యాలు మరియు కూటములు",
                "municipalMoU": "మున్సిపల్ సహకార ఒప్పందాలు",
                "corporateSponsors": "కార్పొరేట్ CSR భాగస్వాములు",
                "universityAlliances": "విశ్వవిద్యాలయ విద్యార్థి కూటములు"
            },
            "certificates": {
                "title": "సర్టిఫికెట్లు మరియు బ్యాడ్జ్‌లు",
                "awardCertificate": "ప్రశంసా పత్రం జారీ చేయండి",
                "downloadBadge": "డిజిటల్ బ్యాడ్జ్‌ని డౌన్‌లోడ్ చేయండి",
                "recognitionLetter": "మున్సిపల్ ప్రశంసా లేఖ"
            },
            "reports": {
                "title": "క్షేత్ర ఆడిట్ మరియు కార్యాచరణ నివేదికలు",
                "fieldAuditReports": "క్షేత్ర ధృవీకరణ నివేదికలు",
                "monthlyActivitySummary": "నెలవారీ కార్యాచరణ సారాంశం",
                "incidentLogSheet": "సంఘటన ప్రతిస్పందన లాగ్",
                "submitToGovernment": "ప్రభుత్వానికి నివేదికను పంపండి"
            },
            "settings": {
                "title": "NGO ప్రొఫైల్ మరియు సెట్టింగ్‌లు",
                "registrationDetails": "రిజిస్ట్రేషన్ వివరాలు",
                "ngoDarpanId": "నీతి ఆయోగ్ దర్పణ్ ID",
                "focalPoints": "క్షేత్ర సమన్వయకర్తలు"
            }
        },
        "university": {
            "portalTitle": "విశ్వవిద్యాలయం మరియు విద్యా పోర్టల్",
            "student": {
                "dashboard": {
                    "title": "విద్యార్థి ఆవిష్కరణ డ్యాష్‌బోర్డ్",
                    "academicCredits": "పొందిన అకడమిక్ క్రెడిట్‌లు",
                    "assignedTasks": "కేటాయించిన ల్యాబ్ పనులు",
                    "labProjects": "పరిశోధన ప్రాజెక్ట్‌లు",
                    "prototypeChallenges": "ఆవిష్కరణ సవాళ్లు",
                    "submitMilestone": "మైలురాయిని సమర్పించండి"
                },
                "tasks": {
                    "title": "ల్యాబ్ పనులు",
                    "pendingTasks": "పెండింగ్ పనులు",
                    "taskDescription": "పని సూచనలు",
                    "dueDate": "సమర్పణ గడువు",
                    "submitDeliverable": "పరిష్కారాన్ని సమర్పించండి",
                    "advisorNotes": "సలహాదారు నోట్స్",
                    "dueTasks": "త్వరలో పూర్తి చేయవలసిన పనులు"
                },
                "uploads": {
                    "title": "ఫలితాలను అప్‌లోడ్ చేయండి",
                    "researchNotes": "పరిశోధనా నోట్స్ మరియు నివేదికలు",
                    "projectCode": "సోర్స్ కోడ్ రిపోజిటరీ",
                    "presentationSlides": "ప్రెజెంటేషన్ స్లైడ్‌లు",
                    "submitForGrading": "సమీక్ష కోసం సమర్పించండి"
                },
                "timeline": {
                    "title": "మైలురాయి కాలక్రమం",
                    "projectSchedule": "ప్రాజెక్ట్ షెడ్యూల్",
                    "semesterDeadlines": "సెమిస్టర్ మైలురాళ్ళు",
                    "facultyReviewDate": "షెడ్యూల్ చేసిన సమీక్ష"
                },
                "messages": {
                    "title": "సలహాదారు చర్చ",
                    "chatWithMentor": "మెంటార్‌తో చాట్ చేయండి",
                    "feedbackThread": "అభిప్రాయం మరియు దిద్దుబాట్లు",
                    "askQuestion": "ప్రశ్న అడగండి"
                }
            },
            "faculty": {
                "dashboard": {
                    "title": "ఫ్యాకల్టీ మెంటార్ డ్యాష్‌బోర్డ్",
                    "studentCohorts": "విద్యార్థి బృందాలు",
                    "mentoredProjects": "మార్గదర్శక ప్రాజెక్ట్‌లు",
                    "pendingApprovals": "పెండింగ్‌లో ఉన్న ఆమోదాలు",
                    "researchPapers": "ప్రచురించిన పరిశోధనా పత్రాలు",
                    "innovationIndex": "ఆవిష్కరణ సూచిక"
                },
                "approvals": {
                    "title": "మైలురాయి ఆమోదాలు",
                    "reviewSubmission": "సమర్పణను సమీక్షించండి",
                    "approveMilestone": "మైలురాయిని ఆమోదించండి",
                    "rejectMilestone": "సవరణను అభ్యర్థించండి",
                    "provideFeedback": "అభిప్రాయం మరియు మూల్యాంకనం",
                    "gradeAwarded": "అందించిన క్రెడిట్‌లు",
                    "pendingReviews": "పెండింగ్‌లో ఉన్న సమీక్షలు"
                },
                "proposals": {
                    "title": "మున్సిపల్ పరిశోధన ప్రతిపాదనలు",
                    "civicResearchTopics": "పౌర సమస్య ప్రకటనలు",
                    "grantProposals": "ఉమ్మడి పరిశోధన గ్రాంట్లు",
                    "callForPapers": "పరిష్కారాల కోసం ఆహ్వానం",
                    "openProposals": "ఓపెన్ ప్రతిపాదనలు"
                },
                "teams": {
                    "title": "విద్యార్థి పరిశోధన బృందాలు",
                    "teamRoster": "బృంద సభ్యులు",
                    "assignLead": "టీమ్ లీడ్‌ను నియమించండి",
                    "performanceReview": "నియత మూల్యాంకనం",
                    "academicAdvising": "విద్యా సలహా"
                },
                "reports": {
                    "title": "విద్యా విశ్లేషణలు మరియు నివేదికలు",
                    "cohortProgress": "పురోగతి ట్రాకర్",
                    "publicationOutput": "విద్యా అవుట్‌పుట్",
                    "creditDistribution": "క్రెడిట్ పంపిణీ"
                }
            },
            "shared": {
                "projects": {
                    "title": "పరిశోధన ప్రాజెక్ట్‌లు",
                    "studentResearch": "విద్యార్థి పరిశోధనా కార్యక్రమాలు",
                    "capstoneProjects": "క్యాప్‌స్టోన్ ప్రాజెక్ట్‌లు",
                    "interdisciplinaryTeams": "అంతర్విభాగ బృందాలు"
                },
                "research": {
                    "title": "పరిశోధన కేంద్రం",
                    "publications": "ప్రచురణలు",
                    "datasets": "ఓపెన్ డేటాసెట్‌లు",
                    "patentFiling": "పేటెంట్ దరఖాస్తులు",
                    "peerReview": "పీర్ రివ్యూ డైరెక్టరీ"
                },
                "innovation": {
                    "title": "ఆవిష్కరణ ప్రయోగశాల",
                    "innovationChallenges": "హ్యాకథాన్‌లు మరియు సవాళ్లు",
                    "hackathonDemos": "నమూనాల ప్రదర్శన",
                    "incubatorReady": "ఇంక్యుబేషన్ దశ",
                    "smartCityPrototypes": "స్మార్ట్ సిటీ డెమోలు"
                },
                "credits": {
                    "title": "క్రెడిట్‌లు మరియు గుర్తింపు",
                    "creditsEarned": "పొందిన క్రెడిట్‌లు",
                    "skillBadges": "నైపుణ్య బ్యాడ్జ్‌లు",
                    "hallOfFame": "హాల్ ఆఫ్ ఫేమ్",
                    "transcriptVerification": "ధృవీకరించబడిన ట్రాన్స్‌క్రిప్ట్"
                },
                "repository": {
                    "title": "విద్యా రిపోజిటరీ",
                    "researchPapersArchive": "పరిశోధనా పత్రాల ఆర్కైవ్",
                    "openDataVault": "ఓపెన్ డేటా వాల్ట్",
                    "citationIndex": "సైటేషన్ ఇండెక్స్"
                },
                "settings": {
                    "title": "విశ్వవిద్యాలయ సెట్టింగ్‌లు",
                    "facultyProfile": "సంస్థాగత ప్రొఫైల్",
                    "departmentAffiliation": "విభాగ అనుబంధం",
                    "orcidId": "ORCID / పరిశోధకుడి ID"
                }
            }
        },
        "admin": {
            "portalTitle": "కేంద్ర కమాండ్ మరియు ప్లాట్‌ఫారమ్ పరిపాలన",
            "dashboard": {
                "title": "ప్లాట్‌ఫారమ్ అడ్మినిస్ట్రేషన్ డ్యాష్‌బోర్డ్",
                "totalSystemUsers": "మొత్తం నమోదిత వినియోగదారులు",
                "activePortals": "క్రియాశీల పోర్టల్‌లు",
                "aiModelStatus": "AI మోడల్ ఆరోగ్యం",
                "databaseHealth": "డేటాబేస్ జాప్యం",
                "unresolvedGrievances": "పరిష్కారం కాని ఫిర్యాదులు",
                "platformLoad": "సర్వర్ లోడ్",
                "liveEventStream": "లైవ్ ఆడిట్ స్ట్రీమ్",
                "rootConsole": "రూట్ కన్సోల్",
                "cpuUsage": "CPU వినియోగం",
                "dbLatency": "డేటాబేస్ జాప్యం",
                "uptime": "సిస్టమ్ అప్‌టైమ్"
            },
            "users": {
                "title": "వినియోగదారు మరియు పాత్ర నిర్వహణ",
                "allUsers": "వినియోగదారులందరూ",
                "addUser": "వినియోగదారుని జోడించండి",
                "editRole": "పాత్రను సవరించండి",
                "suspendUser": "ఖాతాను నిలిపివేయండి",
                "resetPassword": "పాస్‌వర్డ్‌ను రీసెట్ చేయండి",
                "roleFilter": "పాత్ర ఆధారంగా ఫిల్టర్ చేయండి",
                "searchUsers": "పేరు, ఇమెయిల్ ద్వారా శోధించండి..."
            },
            "roles": {
                "title": "పాత్ర మరియు అనుమతుల నిర్వహణ",
                "permissionsMatrix": "యాక్సెస్ కంట్రోల్ మ్యాట్రిక్స్",
                "accessControl": "భద్రతా విధానాలు",
                "createRole": "కొత్త పాత్రను సృష్టించండి",
                "customRoles": "అనుకూల పాత్రలు"
            },
            "government": {
                "title": "మున్సిపల్ పరిపాలన నియంత్రణ",
                "municipalBOD": "మున్సిపల్ సంస్థలు",
                "cityDistricts": "జిల్లా అధికార పరిధులు",
                "assignWardEngineers": "వార్డు ఇంజనీర్లను నియమించండి"
            },
            "universities": {
                "title": "విశ్వవిద్యాలయ గుర్తింపు నిర్వహణ",
                "registeredCampuses": "అనుబంధ విశ్వవిద్యాలయాలు",
                "accreditationVerify": "NAAC / UGC ధృవీకరణ",
                "studentCap": "నమోదు కోటా"
            },
            "industry": {
                "title": "పరిశ్రమ భాగస్వాముల పర్యవేక్షణ",
                "corporatePartners": "నమోదిత CSR భాగస్వాములు",
                "csrValidation": "సెక్షన్ 135 అర్హత తనిఖీ",
                "escrowAudits": "ఎస్క్రో ఆడిట్ తనిఖీ"
            },
            "ngos": {
                "title": "ఎన్జీఓల పర్యవేక్షణ",
                "verifiedNgos": "గుర్తింపు పొందిన ఎన్జీఓలు",
                "darpanCheck": "ఎన్జీఓ దర్పణ్ ధృవీకరణ",
                "groundClearance": "క్షేత్ర అనుమతులు"
            },
            "research": {
                "title": "పరిశోధనా సంస్థల పర్యవేక్షణ",
                "institutePartnerships": "పరిశోధనా భాగస్వాములు",
                "ethicsClearance": "ఎథిక్స్ రివ్యూ బోర్డ్",
                "datasetAccess": "డేటా యాక్సెస్ అనుమతులు"
            },
            "departments": {
                "title": "డిపార్ట్‌మెంట్ మాస్టర్ కాన్ఫిగరేషన్",
                "routingRules": "స్వయంచాలక రూటింగ్ నియమాలు",
                "autoAssignmentEngine": "AI డిస్పాచ్ ఇంజిన్",
                "fallbackQueues": "ఫాల్‌బ్యాక్ క్యూలు"
            },
            "issues": {
                "title": "ప్లాట్‌ఫారమ్ ఫిర్యాదుల నిర్వహణ",
                "forceResolve": "పరిపాలనా పరిష్కారం",
                "reassignCluster": "సమస్య క్లస్టర్‌ను తిరిగి కేటాయించండి",
                "auditLog": "చర్య లాగ్",
                "purgeTestData": "పరీక్ష డేటాను క్లియర్ చేయండి"
            },
            "aiMonitoring": {
                "title": "AI విజన్ మరియు టెలిమెట్రీ పర్యవేక్షణ",
                "geminiVisionUptime": "విజన్ మోడల్ అప్‌టైమ్",
                "fastApiOcrStatus": "FastAPI OCR పైప్‌లైన్",
                "speechToTextLatency": "STT జాప్యం",
                "accuracyScore": "ఖచ్చితత్వ స్కోరు",
                "confidenceDistribution": "విశ్వాస పంపిణీ",
                "modelLogs": "జాప్యం లాగ్‌లు"
            },
            "workflowMonitoring": {
                "title": "వర్క్‌ఫ్లో మరియు క్యూ టెలిమెట్రీ",
                "stateMachineInspect": "స్థితి మార్పులు",
                "queueDepth": "సందేశాల క్యూ లోతు",
                "deadLetterQueue": "డెడ్-లెటర్ క్యూ",
                "retryFailedTasks": "విఫలమైన పనులను మళ్ళీ ప్రయత్నించండి"
            },
            "analytics": {
                "title": "ప్లాట్‌ఫారమ్ విశ్లేషణలు",
                "crossPortalActivity": "వినియోగ కొలమానాలు",
                "municipalPerformanceIndex": "మున్సిపల్ పనితీరు సూచిక",
                "peakUsageHours": "గరిష్ట వినియోగ గంటలు"
            },
            "systemHealth": {
                "title": "మౌలిక సదుపాయాలు మరియు ఆరోగ్యం",
                "databaseReplicas": "డేటాబేస్ రెప్లికాలు",
                "redisCache": "రెడిస్ మెమరీ స్థితి",
                "storageUsage": "నిల్వ పరిమాణం",
                "apiGateways": "మైక్రోసర్వీస్ ఆరోగ్యం",
                "uptime99": "99.98% లభ్యత",
                "online": "ఆన్‌లైన్",
                "maintenance": "నిర్వహణ"
            },
            "settings": {
                "title": "ప్లాట్‌ఫారమ్ సెట్టింగ్‌లు",
                "maintenanceMode": "నిర్వహణ మోడ్",
                "apiRateLimits": "API పరిమితులు",
                "backupSchedules": "బ్యాకప్ షెడ్యూల్",
                "smtpConfig": "SMTP మరియు ఇమెయిల్ గేట్‌వేలు"
            }
        },
        "toast": {
            "issueSubmitted": "ఫిర్యాదు విజయవంతంగా సమర్పించబడింది! బాధ్యతాయుతమైన విభాగానికి పంపబడింది.",
            "gpsCaptured": "GPS కోఆర్డినేట్‌లు సేకరించబడ్డాయి",
            "gpsCapturedDesc": "కోఆర్డినేట్‌లు ఫిర్యాదు నివేదికతో లింక్ చేయబడ్డాయి.",
            "locationDenied": "స్థాన అనుమతి నిరాకరించబడింది. డిఫాల్ట్ స్థానం ఉపయోగించబడుతోంది.",
            "fileSizeExceeded": "ఫైల్ పరిమాణం 25MB పరిమితిని మించిపోయింది.",
            "audioNotSupported": "ఈ బ్రౌజర్‌లో ఆడియో రికార్డింగ్ మద్దతు లేదు.",
            "micSimulation": "వాయిస్ ఫిర్యాదు డెమో కోసం మైక్రోఫోన్ సిమ్యులేషన్ సక్రియంగా ఉంది.",
            "profileUpdated": "ప్రొఫైల్ విజయవంతంగా నవీకరించబడింది.",
            "settingsSaved": "ప్రాధాన్యతలు విజయవంతంగా సేవ్ చేయబడ్డాయి.",
            "deleteRequested": "ఖాతా తొలగింపు అభ్యర్థన సమర్పించబడింది.",
            "languageChanged": "భాష విజయవంతంగా మార్చబడింది.",
            "errorOccurred": "ఒక లోపం సంభవించింది. దయచేసి మళ్ళీ ప్రయత్నించండి.",
            "caseUpdated": "కేసు వివరాలు నవీకరించబడ్డాయి.",
            "caseReassigned": "కేసు నోడల్ అధికారికి తిరిగి కేటాయించబడింది.",
            "caseResolved": "ఫిర్యాదు పరిష్కరించబడినట్లు గుర్తించబడింది.",
            "volunteerAdded": "కొత్త వాలంటీర్ విజయవంతంగా నమోదు చేయబడ్డారు.",
            "grantApproved": "CSR గ్రాంట్ కేటాయింపు ఆమోదించబడింది.",
            "milestoneApproved": "విద్యా మైలురాయి ఆమోదించబడింది.",
            "deliverableUploaded": "పని సమీక్ష కోసం అప్‌లోడ్ చేయబడింది.",
            "loginSuccess": "విజయవంతంగా సైన్ ఇన్ అయ్యారు. స్వాగతం!",
            "logoutSuccess": "విజయవంతంగా లాగ్ అవుట్ అయ్యారు.",
            "accessDenied": "యాక్సెస్ పరిమితం చేయబడింది. అనుమతులు లేవు.",
            "changesSaved": "అన్ని మార్పులు విజయవంతంగా సేవ్ చేయబడ్డాయి.",
            "reportExported": "నివేదిక రూపొందించబడింది మరియు డౌన్‌లోడ్ చేయబడింది.",
            "dataRefreshed": "టెలిమెట్రీ డేటా రిఫ్రెష్ చేయబడింది."
        },
        "language": "భాష",
        "dashboard": "డ్యాష్‌బోర్డ్",
        "report_issue": "సమస్యను నివేదించండి",
        "report_problem": "సమస్యను నివేదించండి",
        "my_issues": "నా ఫిర్యాదులు",
        "track_issues": "పరిష్కారాన్ని ట్రాక్ చేయండి",
        "notifications": "నోటిఫికేషన్‌లు",
        "profile": "ప్రొఫైల్",
        "settings": "సెట్టింగ్‌లు",
        "help": "సహాయం & మద్దతు",
        "logout": "లాగ్ అవుట్",
        "login": "లాగిన్",
        "recent_grievances": "ఇటీవలి ఫిర్యాదులు",
        "issue_id": "ఫిర్యాదు ID",
        "citizen_portal": "పౌర పోర్టల్",
        "government_portal": "ప్రభుత్వ పోర్టల్",
        "university_portal": "విశ్వవిద్యాలయ పోర్టల్",
        "industry_portal": "పరిశ్రమ పోర్టల్",
        "ngo_portal": "ఎన్జీఓ పోర్టల్",
        "admin_portal": "అడ్మిన్ పోర్టల్",
        "ai_governance_insight": "AI పాలన అంతర్దృష్టి",
        "resolution": "పరిష్కారం",
        "report": "నివేదికలు",
        "map": "సంఘటన మ్యాప్",
        "search": "శోధించండి",
        "search_placeholder": "ఫిర్యాదులు, కేసులు, స్థానాలను శోధించండి...",
        "filter": "ఫిల్టర్",
        "save": "సేవ్ చేయండి",
        "cancel": "రద్దు చేయండి",
        "delete": "తొలగించండి",
        "submit": "సమర్పించండి",
        "upload": "అప్‌లోడ్ చేయండి",
        "location": "స్థానం",
        "description": "వివరణ",
        "title": "శీర్షిక",
        "category": "వర్గం",
        "department": "విభాగం",
        "created_at": "నివేదించిన తేదీ",
        "action": "చర్య",
        "actions": "చర్యలు",
        "view": "వీక్షించండి",
        "edit": "సవరించండి",
        "loading": "లోడ్ అవుతోంది...",
        "success": "విజయం",
        "error": "ఒక లోపం సంభవించింది",
        "welcome_back": "తిరిగి స్వాగతం",
        "total_issues": "మొత్తం ఫిర్యాదులు",
        "resolved_issues": "పరిష్కరించబడిన ఫిర్యాదులు",
        "in_progress_issues": "పురోగతిలో ఉన్న ఫిర్యాదులు",
        "pending_issues": "పెండింగ్‌లో ఉన్న ఫిర్యాదులు",
        "active_projects": "క్రియాశీల ప్రాజెక్ట్‌లు",
        "ai_accuracy": "AI రూటింగ్ ఖచ్చితత్వం",
        "sla_compliance": "SLA సమ్మతి రేటు",
        "civic_engagement": "పౌర భాగస్వామ్య సూచిక",
        "recent_activity": "ఇటీవలి కార్యాచరణ",
        "quick_actions": "త్వరిత చర్యలు",
        "live_incidents": "లైవ్ పౌర సంఘటనలు",
        "all": "అన్నీ",
        "high": "అధిక ప్రాధాన్యత",
        "medium": "మధ్యస్థ ప్రాధాన్యత",
        "low": "తక్కువ ప్రాధాన్యత",
        "critical": "క్లిష్టమైన ప్రాధాన్యత",
        "emergency": "అత్యవసర ప్రాధాన్యత",
        "pending": "పెండింగ్‌లో ఉంది",
        "in_progress": "పురోగతిలో ఉంది",
        "resolved": "పరిష్కరించబడింది",
        "closed": "మూసివేయబడింది",
        "rejected": "తిరస్కరించబడింది",
        "approved": "ఆమోదించబడింది",
        "declined": "తిరస్కరించబడింది",
        "export": "డేటాను ఎగుమతి చేయండి",
        "download": "డౌన్‌లోడ్",
        "confirm": "నిర్ధారించండి",
        "close": "మూసివేయండి",
        "back": "వెనుకకు",
        "next": "తదుపరి",
        "previous": "మునుపటి",
        "no_results": "ఫలితాలు ఏవీ కనుగొనబడలేదు",
        "view_all": "అన్నీ చూడండి",
        "home": "హోమ్",
        "feed": "పౌర ఫీడ్",
        "analytics": "AI విశ్లేషణలు",
        "optional": "ఐచ్ఛికం",
        "faculty": "ఫ్యాకల్టీ",
        "student": "విద్యార్థి",
        "projects": "ప్రాజెక్ట్‌లు",
        "research": "పరిశోధన కేంద్రం",
        "innovation": "ఆవిష్కరణ సవాళ్లు",
        "teams": "జట్లు",
        "credits": "అకడమిక్ క్రెడిట్‌లు",
        "officers": "అధికారులు",
        "assigned": "కేటాయించినవి",
        "under_review": "సమీక్షలో ఉంది",
        "industry_assigned": "పరిశ్రమకు కేటాయించబడింది",
        "industry_review": "పరిశ్రమ సమీక్ష",
        "univ_assigned": "విశ్వవిద్యాలయానికి కేటాయించబడింది",
        "student_dev": "విద్యార్థి అభివృద్ధి",
        "faculty_review": "ఫ్యాకల్టీ సమీక్ష",
        "industry_val": "పరిశ్రమ ధృవీకరణ",
        "inspection": "క్షేత్ర తనిఖీ",
        "feedback": "అభిప్రాయం పెండింగ్‌లో ఉంది"
    }
