# -*- coding: utf-8 -*-
"""Kannada (kn) translations dictionary for SOCIAL-X platform"""

def get_kn_dict():
    return {
        "nav": {
            "overview": "ಅವಲೋಕನ",
            "access_identity": "ಪ್ರವೇಶ ಮತ್ತು ಗುರುತು",
            "stakeholder_ecosystem": "ಪಾಲುದಾರರ ಪರಿಸರ ವ್ಯವಸ್ಥೆ",
            "operations_ai": "ಕಾರ್ಯಾಚರಣೆಗಳು ಮತ್ತು AI",
            "infra_observability": "ಮೂಲಸೌಕರ್ಯ ಮತ್ತು ವೀಕ್ಷಣೆ",
            "field_activities": "ಕ್ಷೇತ್ರ ಚಟುವಟಿಕೆಗಳು ಮತ್ತು ಪರಿಹಾರ",
            "community_workforce": "ಸಮುದಾಯ ಮತ್ತು ಕಾರ್ಯಪಡೆ",
            "governance_comms": "ಆಡಳಿತ ಮತ್ತು ಸಂವಹನ",
            "csr_investment": "CSR ಮತ್ತು ಬಂಡವಾಳ ಹಂಚಿಕೆ",
            "collaboration_rd": "ಸಹಯೋಗ ಮತ್ತು ಸಂಶೋಧನೆ",
            "student_portal": "ವಿದ್ಯಾರ್ಥಿ ಪೋರ್ಟಲ್",
            "faculty_portal": "ಅಧ್ಯಾಪಕರ ಪೋರ್ಟಲ್",
            "dashboard": "ಡ್ಯಾಶ್‌ಬೋರ್ಡ್",
            "my_issues": "ನನ್ನ ದೂರುಗಳು",
            "report_problem": "ಸಮಸ್ಯೆಯನ್ನು ವರದಿ ಮಾಡಿ",
            "track_issues": "ಪರಿಹಾರವನ್ನು ಟ್ರ್ಯಾಕ್ ಮಾಡಿ",
            "notifications": "ಅಧಿಸೂಚನೆಗಳು",
            "profile": "ಪ್ರೊಫೈಲ್",
            "settings": "ಸಂಯೋಜನೆಗಳು",
            "help": "ಸಹಾಯ ಮತ್ತು ಬೆಂಬಲ",
            "logout": "ಲಾಗ್ ಔಟ್",
            "login": "ಲಾಗ್ ಇನ್",
            "analytics": "ವಿಶ್ಲೇಷಣೆ ಮತ್ತು ವರದಿಗಳು",
            "assigned_cases": "ನಿಯೋಜಿಸಲಾದ ಪ್ರಕರಣಗಳು",
            "departments": "ಇಲಾಖೆಗಳು",
            "officers": "ಅಧಿಕಾರಿಗಳ ಡೈರೆಕ್ಟರಿ",
            "ai_suggestions": "AI ಸಲಹೆಗಳು",
            "reports": "ವರದಿಗಳು ಮತ್ತು ಲೆಕ್ಕಪರಿಶೋಧನೆ",
            "projects": "ಲಭ್ಯವಿರುವ ಯೋಜನೆಗಳು",
            "funding": "ನಿಧಿಯ ಅವಕಾಶಗಳು",
            "csr_analytics": "CSR ವಿಶ್ಲೇಷಣೆ",
            "mentorship": "ಮಾರ್ಗದರ್ಶನ",
            "university_collaboration": "ವಿಶ್ವವಿದ್ಯಾಲಯ ಸಹಯೋಗ",
            "research": "ಸಂಶೋಧನಾ ಉಪಕ್ರಮಗಳು",
            "prototypes": "ಮಾದರಿಗಳು ಮತ್ತು ಡೆಮೊಗಳು",
            "volunteers": "ಸ್ವಯಂಸೇವಕ ತಂಡಗಳು",
            "field_log": "ಕ್ಷೇತ್ರ ಪುರಾವೆ ಲಾಗ್",
            "impact": "ಸಮುದಾಯದ ಪ್ರಭಾವ",
            "certificates": "ಪ್ರಮಾಣಪತ್ರಗಳು ಮತ್ತು ಬ್ಯಾಡ್ಜ್‌ಗಳು",
            "lab_tasks": "ಪ್ರಯೋಗಾಲಯದ ಕಾರ್ಯಗಳು",
            "upload_deliverables": "ಫಲಿತಾಂಶಗಳನ್ನು ಅಪ್‌ಲೋಡ್ ಮಾಡಿ",
            "milestone_timeline": "ಮೈಲಿಗಲ್ಲು ಕಾಲಮಿತಿ",
            "advisor_discussion": "ಸಲಹೆಗಾರರ ಚರ್ಚೆ",
            "milestone_approvals": "ಮೈಲಿಗಲ್ಲು ಅನುಮೋದನೆಗಳು",
            "municipal_proposals": "ಪುರಸಭೆಯ ಪ್ರಸ್ತಾಪಗಳು",
            "teams": "ತಂಡಗಳು ಮತ್ತು ಪಟ್ಟಿ",
            "credits": "ಶೈಕ್ಷಣಿಕ ಕ್ರೆಡಿಟ್‌ಗಳು",
            "user_management": "ಬಳಕೆದಾರರ ನಿರ್ವಹಣೆ",
            "role_management": "ಪಾತ್ರ ನಿರ್ವಹಣೆ",
            "government_management": "ಸರ್ಕಾರಿ ನಿರ್ವಹಣೆ",
            "university_management": "ವಿಶ್ವವಿದ್ಯಾಲಯ ನಿರ್ವಹಣೆ",
            "industry_management": "ಉದ್ಯಮ ನಿರ್ವಹಣೆ",
            "ngo_management": "ಎನ್‌ಜಿಒ ನಿರ್ವಹಣೆ",
            "research_organizations": "ಸಂಶೋಧನಾ ಸಂಸ್ಥೆಗಳು",
            "issue_management": "ಸಮಸ್ಯೆ ನಿರ್ವಹಣೆ",
            "ai_monitoring": "AI ಟೆಲಿಮೆಟ್ರಿ ಮೇಲ್ವಿಚಾರಣೆ",
            "workflow_monitoring": "ಕೆಲಸದ ಹರಿವಿನ ಮೇಲ್ವಿಚಾರಣೆ",
            "audit_logs": "ಆಡಿಟ್ ಹಾದಿ",
            "system_health": "ವ್ಯವಸ್ಥೆಯ ಆರೋಗ್ಯ",
            "landing_features": "ವೈಶಿಷ್ಟ್ಯಗಳು",
            "landing_how_it_works": "ಇದು ಹೇಗೆ ಕಾರ್ಯನಿರ್ವಹಿಸುತ್ತದೆ",
            "landing_about": "ನಮ್ಮ ಬಗ್ಗೆ",
            "landing_faq": "ಪದೇ ಪದೇ ಕೇಳಲಾಗುವ ಪ್ರಶ್ನೆಗಳು",
            "landing_contact": "ಸಂಪರ್ಕಿಸಿ",
            "role_login": "ಪಾತ್ರ ಲಾಗಿನ್",
            "citizen_sign_up": "ನಾಗರಿಕ ನೋಂದಣಿ"
        },
        "common": {
            "buttons": {
                "browseFiles": "ಫೈಲ್‌ಗಳನ್ನು ಬ್ರೌಸ್ ಮಾಡಿ",
                "openCamera": "ಕ್ಯಾಮೆರಾ ತೆರೆಯಿರಿ",
                "startRecording": "ರೆಕಾರ್ಡಿಂಗ್ ಪ್ರಾರಂಭಿಸಿ",
                "stopRecording": "ರೆಕಾರ್ಡಿಂಗ್ ನಿಲ್ಲಿಸಿ",
                "submit": "ಸಲ್ಲಿಸಿ",
                "cancel": "ರದ್ದುಮಾಡಿ",
                "save": "ಬದಲಾವಣೆಗಳನ್ನು ಉಳಿಸಿ",
                "delete": "ಅಳಿಸಿ",
                "search": "ಹುಡುಕಿ",
                "filter": "ಫಿಲ್ಟರ್",
                "upload": "ಅಪ್‌ಲೋಡ್ ಮಾಡಿ",
                "confirm": "ದೃಢೀಕರಿಸಿ",
                "close": "ಮುಚ್ಚಿ",
                "back": "ಹಿಂದಕ್ಕೆ",
                "next": "ಮುಂದೆ",
                "previous": "ಹಿಂದಿನ",
                "detectLocation": "ಪ್ರಸ್ತುತ ಸ್ಥಳವನ್ನು ಪತ್ತೆಹಚ್ಚಿ",
                "useCurrentGps": "ಪ್ರಸ್ತುತ GPS ಬಳಸಿ",
                "resetForm": "ಫಾರ್ಮ್ ಮರುಹೊಂದಿಸಿ",
                "submitIssue": "ದೂರನ್ನು ಸಲ್ಲಿಸಿ",
                "viewAll": "ಎಲ್ಲವನ್ನೂ ವೀಕ್ಷಿಸಿ",
                "export": "ಡೇಟಾ ರಫ್ತು ಮಾಡಿ",
                "download": "ಡೌನ್‌ಲೋಡ್",
                "refresh": "ರಿಫ್ರೆಶ್ ಮಾಡಿ",
                "login": "ಲಾಗಿನ್",
                "logout": "ಲಾಗ್ ಔಟ್",
                "modifyUploads": "ಅಪ್‌ಲೋಡ್‌ಗಳನ್ನು ಮಾರ್ಪಡಿಸಿ",
                "removeFile": "ಫೈಲ್ ತೆಗೆದುಹಾಕಿ",
                "removeVoiceMemo": "ಧ್ವನಿ ಮೆಮೊ ತೆಗೆದುಹಾಕಿ",
                "edit": "ತಿದ್ದು",
                "view": "ವಿವರಗಳನ್ನು ವೀಕ್ಷಿಸಿ",
                "add": "ಹೊಸದನ್ನು ಸೇರಿಸಿ",
                "create": "ರಚಿಸಿ",
                "update": "ನವೀಕರಿಸಿ",
                "approve": "ಅನುಮೋದಿಸಿ",
                "reject": "ತಿರಸ್ಕರಿಸಿ",
                "reassign": "ಮರುನಿಯೋಜಿಸಿ",
                "escalate": "ಮೇಲಧಿಕಾರಿಗೆ ಕಳುಹಿಸಿ",
                "resolve": "ಪ್ರಕರಣವನ್ನು ಪರಿಹರಿಸಿ",
                "assign": "ನಿಯೋಜಿಸಿ",
                "verify": "ಪರಿಶೀಲಿಸಿ",
                "downloadReport": "ವರದಿಯನ್ನು ಡೌನ್‌ಲೋಡ್ ಮಾಡಿ",
                "syncTelemetry": "ಟೆಲಿಮೆಟ್ರಿ ಸಿಂಕ್ ಮಾಡಿ",
                "applyFilters": "ಫಿಲ್ಟರ್‌ಗಳನ್ನು ಅನ್ವಯಿಸಿ",
                "clearFilters": "ಫಿಲ್ಟರ್‌ಗಳನ್ನು ತೆರವುಗೊಳಿಸಿ",
                "viewDetails": "ವಿವರಗಳನ್ನು ನೋಡಿ",
                "sendNotification": "ಅಧಿಸೂಚನೆ ಕಳುಹಿಸಿ",
                "inviteMember": "ಸದಸ್ಯರನ್ನು ಆಹ್ವಾನಿಸಿ",
                "print": "ಮುದ್ರಿಸಿ",
                "share": "ಹಂಚಿಕೊಳ್ಳಿ",
                "copyLink": "ಲಿಂಕ್ ನಕಲಿಸಿ",
                "proceed": "ಮುಂದುವರಿಯಿರಿ",
                "retry": "ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ",
                "dismiss": "ವಜಾಗೊಳಿಸಿ",
                "accept": "ಸ್ವೀಕರಿಸಿ",
                "decline": "ನಿರಾಕರಿಸಿ"
            },
            "labels": {
                "dashboard": "ಡ್ಯಾಶ್‌ಬೋರ್ಡ್",
                "profile": "ಪ್ರೊಫೈಲ್",
                "settings": "ಸಂಯೋಜನೆಗಳು",
                "notifications": "ಅಧಿಸೂಚನೆಗಳು",
                "help": "ಸಹಾಯ ಮತ್ತು ಬೆಂಬಲ",
                "logout": "ಲಾಗ್ ಔಟ್",
                "login": "ಲಾಗ್ ಇನ್",
                "status": "ಸ್ಥಿತಿ",
                "priority": "ಆದ್ಯತೆ",
                "department": "ಇಲಾಖೆ",
                "category": "ವರ್ಗ",
                "district": "ಜಿಲ್ಲೆ",
                "ward": "ವಾರ್ಡ್",
                "address": "ವಿಳಾಸ",
                "landmark": "ಗುರುತು",
                "title": "ಶೀರ್ಷಿಕೆ",
                "description": "ವಿವರಣೆ",
                "location": "ಸ್ಥಳ",
                "latitude": "ಅಕ್ಷಾಂಶ",
                "longitude": "ರೇಖಾಂಶ",
                "accuracy": "ನಿಖರತೆ",
                "date": "ದಿನಾಂಕ",
                "action": "ಕ್ರಿಯೆ",
                "actions": "ಕ್ರಿಯೆಗಳು",
                "all": "ಎಲ್ಲವೂ",
                "high": "ಹೆಚ್ಚು",
                "medium": "ಮಧ್ಯಮ",
                "low": "ಕಡಿಮೆ",
                "critical": "ನಿರ್ಣಾಯಕ",
                "emergency": "ತುರ್ತು",
                "pending": "ಬಾಕಿ ಉಳಿದಿದೆ",
                "inProgress": "ಪ್ರಗತಿಯಲ್ಲಿದೆ",
                "resolved": "ಪರಿಹರಿಸಲಾಗಿದೆ",
                "closed": "ಮುಚ್ಚಲಾಗಿದೆ",
                "rejected": "ತಿರಸ್ಕರಿಸಲಾಗಿದೆ",
                "verified": "ಪರಿಶೀಲಿಸಲಾಗಿದೆ",
                "assigned": "ನಿಯೋಜಿಸಲಾಗಿದೆ",
                "recentActivity": "ಇತ್ತೀಚಿನ ಚಟುವಟಿಕೆ",
                "quickActions": "ತ್ವರಿತ ಕ್ರಿಯೆಗಳು",
                "systemHealth": "ವ್ಯವಸ್ಥೆಯ ಆರೋಗ್ಯ",
                "language": "ಭಾಷೆ",
                "selectLanguage": "ಭಾಷೆಯನ್ನು ಆಯ್ಕೆಮಾಡಿ",
                "searchLanguage": "ಭಾಷೆಗಳನ್ನು ಹುಡುಕಿ...",
                "editable": "ಸಂಪಾದಿಸಬಹುದಾದ",
                "active": "ಸಕ್ರಿಯ",
                "inactive": "ನಿಷ್ಕ್ರಿಯ",
                "completed": "ಪೂರ್ಣಗೊಂಡಿದೆ",
                "failed": "ವಿಫಲವಾಗಿದೆ",
                "total": "ಒಟ್ಟು",
                "count": "ಎಣಿಕೆ",
                "rate": "ದರ",
                "percentage": "ಶೇಕಡಾವಾರು",
                "timeRemaining": "ಉಳಿದ ಸಮಯ",
                "dueDate": "ಅಂತಿಮ ದಿನಾಂಕ",
                "submittedBy": "ಸಲ್ಲಿಸಿದವರು",
                "assignedTo": "ನಿಯೋಜಿಸಲಾದವರು",
                "officerInCharge": "ಪ್ರಭಾರ ಅಧಿಕಾರಿ",
                "slaTimer": "SLA ಟೈಮರ್",
                "auditTimeline": "ಆಡಿಟ್ ಕಾಲಮಿತಿ",
                "contactInfo": "ಸಂಪರ್ಕ ಮಾಹಿತಿ",
                "phoneNumber": "ದೂರವಾಣಿ ಸಂಖ್ಯೆ",
                "emailAddress": "ಇಮೇಲ್ ವಿಳಾಸ",
                "fullName": "ಪೂರ್ಣ ಹೆಸರು",
                "role": "ಪಾತ್ರ",
                "organization": "ಸಂಸ್ಥೆ",
                "institution": "ಶೈಕ್ಷಣಿಕ ಸಂಸ್ಥೆ",
                "createdAt": "ವರದಿ ಮಾಡಿದ ದಿನಾಂಕ",
                "updatedAt": "ನವೀಕರಿಸಿದ ದಿನಾಂಕ"
            },
            "status": {
                "open": "ತೆರೆದಿದೆ",
                "submitted": "ಸಲ್ಲಿಸಲಾಗಿದೆ",
                "verified": "AI ಪರಿಶೀಲಿಸಿದೆ",
                "assigned": "ನಿಯೋಜಿಸಲಾಗಿದೆ",
                "in_progress": "ಪ್ರಗತಿಯಲ್ಲಿದೆ",
                "inProgress": "ಪ್ರಗತಿಯಲ್ಲಿದೆ",
                "resolved": "ಪರಿಹರಿಸಲಾಗಿದೆ",
                "closed": "ಮುಚ್ಚಲಾಗಿದೆ",
                "rejected": "ತಿರಸ್ಕರಿಸಲಾಗಿದೆ",
                "under_review": "ಪರಿಶೀಲನೆಯಲ್ಲಿದೆ",
                "under_government_review": "ಸರ್ಕಾರದ ಪರಿಶೀಲನೆಯಲ್ಲಿದೆ",
                "assigned_to_government": "ಸರ್ಕಾರಕ್ಕೆ ನಿಯೋಜಿಸಲಾಗಿದೆ",
                "assigned_to_industry": "ಉದ್ಯಮಕ್ಕೆ ನಿಯೋಜಿಸಲಾಗಿದೆ",
                "industry_review": "ಉದ್ಯಮ ಪರಿಶೀಲನೆ",
                "assigned_to_university": "ವಿಶ್ವವಿದ್ಯಾಲಯಕ್ಕೆ ನಿಯೋಜಿಸಲಾಗಿದೆ",
                "student_development": "ವಿದ್ಯಾರ್ಥಿ ಅಭಿವೃದ್ಧಿ",
                "faculty_review": "ಅಧ್ಯಾಪಕರ ಪರಿಶೀಲನೆ",
                "industry_validation": "ಉದ್ಯಮ ಮೌಲ್ಯೀಕರಣ",
                "inspection": "ಸ್ಥಳ ತಪಾಸಣೆ",
                "feedback_pending": "ಪ್ರತಿಕ್ರಿಯೆ ಬಾಕಿಯಿದೆ",
                "escalated": "ಮೇಲಧಿಕಾರಿಗೆ ರವಾನಿಸಲಾಗಿದೆ",
                "active": "ಸಕ್ರಿಯ",
                "inactive": "ನಿಷ್ಕ್ರಿಯ",
                "completed": "ಪೂರ್ಣಗೊಂಡಿದೆ",
                "approved": "ಅನುಮೋದಿಸಲಾಗಿದೆ",
                "declined": "ತಿರಸ್ಕರಿಸಲಾಗಿದೆ",
                "pending": "ಬಾಕಿ ಉಳಿದಿದೆ"
            },
            "priority": {
                "low": "ಕಡಿಮೆ ಆದ್ಯತೆ",
                "medium": "ಮಧ್ಯಮ ಆದ್ಯತೆ",
                "high": "ಹೆಚ್ಚಿನ ಆದ್ಯತೆ",
                "critical": "ನಿರ್ಣಾಯಕ ಆದ್ಯತೆ",
                "emergency": "ತುರ್ತು ಆದ್ಯತೆ",
                "urgent": "ಅತ್ಯಾವಶ್ಯಕ"
            },
            "departments": {
                "waterSupply": "ನೀರು ಸರಬರಾಜು ಮತ್ತು ಒಳಚರಂಡಿ",
                "roadsTransport": "ರಸ್ತೆಗಳು ಮತ್ತು ಸಾರಿಗೆ",
                "electricityPower": "ವಿದ್ಯುತ್ ಮತ್ತು ಪವರ್ ಗ್ರಿಡ್",
                "solidWaste": "ಘನತ್ಯಾಜ್ಯ ಮತ್ತು ನೈರ್ಮಲ್ಯ",
                "publicHealth": "ಸಾರ್ವಜನಿಕ ಆರೋಗ್ಯ ಮತ್ತು ಸುರಕ್ಷತೆ",
                "urbanPlanning": "ನಗರ ಯೋಜನೆ ಮತ್ತು ಮೂಲಸೌಕರ್ಯ",
                "education": "ಶಿಕ್ಷಣ ಮತ್ತು ಯುವಜನ ವ್ಯವಹಾರಗಳು",
                "environmentForest": "ಪರಿಸರ ಮತ್ತು ಅರಣ್ಯ ಇಲಾಖೆ",
                "policeSafety": "ಪೊಲೀಸ್ ಮತ್ತು ಸಾರ್ವಜನಿಕ ಸುರಕ್ಷತೆ",
                "disasterManagement": "ವಿಪತ್ತು ನಿರ್ವಹಣಾ ಪ್ರಾಧಿಕಾರ",
                "municipalAdmin": "ಪುರಸಭಾ ಆಡಳಿತ"
            },
            "categories": {
                "water": "ನೀರು ಸರಬರಾಜು ಮತ್ತು ಒಳಚರಂಡಿ",
                "roads": "ರಸ್ತೆಗಳು ಮತ್ತು ಸಾರಿಗೆ",
                "electricity": "ವಿದ್ಯುತ್ ಮತ್ತು ಪವರ್ ಗ್ರಿಡ್",
                "waste": "ಘನತ್ಯಾಜ್ಯ ಮತ್ತು ನೈರ್ಮಲ್ಯ",
                "health": "ಸಾರ್ವಜನಿಕ ಆರೋಗ್ಯ ಮತ್ತು ಸುರಕ್ಷತೆ",
                "sanitation": "ನೈರ್ಮಲ್ಯ ಮತ್ತು ಒಳಚರಂಡಿ",
                "infrastructure": "ಸಾರ್ವಜನಿಕ ಮೂಲಸೌಕರ್ಯ",
                "streetlights": "ಬೀದಿ ದೀಪಗಳು ಮತ್ತು ವಿದ್ಯುತ್",
                "drainage": "ಒಳಚರಂಡಿ ಮತ್ತು ಕಾಲುವೆಗಳು",
                "potholes": "ಗುಂಡಿಗಳು ಮತ್ತು ರಸ್ತೆ ದುರಸ್ತಿ",
                "traffic": "ಸಂಚಾರ ಮತ್ತು ರಸ್ತೆ ಸುರಕ್ಷತೆ",
                "pollution": "ಮಾಲಿನ್ಯ ಮತ್ತು ಪರಿಸರ ಅಪಾಯ"
            },
            "validation": {
                "requiredField": "ಈ ಕ್ಷೇತ್ರವು ಕಡ್ಡಾಯವಾಗಿದೆ",
                "titleRequired": "ಶೀರ್ಷಿಕೆ ಅಗತ್ಯವಿದೆ",
                "descriptionRequired": "ವಿವರಣೆ ಅಗತ್ಯವಿದೆ",
                "locationRequired": "ಘಟನೆಯ ಸ್ಥಳ ಅಗತ್ಯವಿದೆ",
                "invalidEmail": "ದಯವಿಟ್ಟು ಮಾನ್ಯವಾದ ಇಮೇಲ್ ವಿಳಾಸವನ್ನು ನಮೂದಿಸಿ",
                "invalidPassword": "ಪಾಸ್‌ವರ್ಡ್ ಕನಿಷ್ಠ 8 ಅಕ್ಷರಗಳನ್ನು ಹೊಂದಿರಬೇಕು",
                "passwordTooShort": "ಪಾಸ್‌ವರ್ಡ್ ತುಂಬಾ ಚಿಕ್ಕದಾಗಿದೆ (ಕನಿಷ್ಠ 8 ಅಕ್ಷರಗಳು)",
                "passwordMismatch": "ಪಾಸ್‌ವರ್ಡ್‌ಗಳು ಹೊಂದಿಕೆಯಾಗುತ್ತಿಲ್ಲ",
                "unsupportedFile": "ಬೆಂಬಲವಿಲ್ಲದ ಫೈಲ್ ಫಾರ್ಮ್ಯಾಟ್. ದಯವಿಟ್ಟು JPEG, PNG, MP4 ಅಥವಾ PDF ಅಪ್‌ಲೋಡ್ ಮಾಡಿ.",
                "maxFileSizeExceeded": "ಗರಿಷ್ಠ ಫೈಲ್ ಗಾತ್ರ ಮೀರಿದೆ (25MB ಮಿತಿ)",
                "micPermissionDenied": "ಮೈಕ್ರೊಫೋನ್ ಅನುಮತಿ ನಿರಾಕರಿಸಲಾಗಿದೆ. ದಯವಿಟ್ಟು ಅನುಮತಿಸಿ.",
                "cameraPermissionDenied": "ಕ್ಯಾಮೆರಾ ಅನುಮತಿ ನಿರಾಕರಿಸಲಾಗಿದೆ. ದಯವಿಟ್ಟು ಅನುಮತಿಸಿ.",
                "minLength": "ಇನ್‌ಪುಟ್ ಕನಿಷ್ಠ ಉದ್ದಕ್ಕಿಂತ ಕಡಿಮೆಯಿದೆ",
                "maxLength": "ಇನ್‌ಪುಟ್ ಗರಿಷ್ಠ ಉದ್ದವನ್ನು ಮೀರಿದೆ",
                "uploadFailed": "ಅಪ್‌ಲೋಡ್ ವಿಫಲವಾಗಿದೆ. ದಯವಿಟ್ಟು ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.",
                "uploadSuccessful": "ಫೈಲ್ ಯಶಸ್ವಿಯಾಗಿ ಅಪ್‌ಲೋಡ್ ಆಗಿದೆ.",
                "loginSuccessful": "ಯಶಸ್ವಿಯಾಗಿ ಸೈನ್ ಇನ್ ಮಾಡಲಾಗಿದೆ.",
                "registrationSuccessful": "ನೋಂದಣಿ ಯಶಸ್ವಿಯಾಗಿ ಪೂರ್ಣಗೊಂಡಿದೆ.",
                "fillRequiredFields": "ಸಲ್ಲಿಸುವ ಮೊದಲು ಎಲ್ಲಾ ಕಡ್ಡಾಯ ಕ್ಷೇತ್ರಗಳನ್ನು ಭರ್ತಿ ಮಾಡಿ."
            },
            "emptyStates": {
                "noData": "ಯಾವುದೇ ಡೇಟಾ ಲಭ್ಯವಿಲ್ಲ",
                "noResults": "ಹುಡುಕಾಟಕ್ಕೆ ಸರಿಹೊಂದುವ ಯಾವುದೇ ಫಲಿತಾಂಶಗಳು ಕಂಡುಬಂದಿಲ್ಲ",
                "noNotifications": "ಯಾವುದೇ ಹೊಸ ಅಧಿಸೂಚನೆಗಳಿಲ್ಲ",
                "noIssuesFound": "ಮಾನದಂಡಗಳಿಗೆ ಸರಿಹೊಂದುವ ಯಾವುದೇ ದೂರುಗಳು ಕಂಡುಬಂದಿಲ್ಲ",
                "noProjectsFound": "ಪ್ರಸ್ತುತ ಯಾವುದೇ ಸಕ್ರಿಯ ಯೋಜನೆಗಳು ಲಭ್ಯವಿಲ್ಲ",
                "noOfficersFound": "ಹುಡುಕಾಟಕ್ಕೆ ಸರಿಹೊಂದುವ ಯಾವುದೇ ಅಧಿಕಾರಿಗಳಿಲ್ಲ",
                "noActivitiesFound": "ಇನ್ನೂ ಯಾವುದೇ ಕ್ಷೇತ್ರ ಚಟುವಟಿಕೆಗಳು ದಾಖಲಾಗಿಲ್ಲ"
            },
            "loading": {
                "loading": "ಲೋಡ್ ಆಗುತ್ತಿದೆ...",
                "pleaseWait": "ದಯವಿಟ್ಟು ನಿರೀಕ್ಷಿಸಿ...",
                "fetchingData": "ಇತ್ತೀಚಿನ ಡೇಟಾವನ್ನು ಪಡೆಯಲಾಗುತ್ತಿದೆ...",
                "processing": "ನಿಮ್ಮ ವಿನಂತಿಯನ್ನು ಪ್ರಕ್ರಿಯೆಗೊಳಿಸಲಾಗುತ್ತಿದೆ...",
                "uploadingMedia": "ಮಾಧ್ಯಮವನ್ನು ಅಪ್‌ಲೋಡ್ ಮಾಡಲಾಗುತ್ತಿದೆ...",
                "analyzingAi": "AI ನೊಂದಿಗೆ ವಿಶ್ಲೇಷಿಸಲಾಗುತ್ತಿದೆ...",
                "savingChanges": "ಬದಲಾವಣೆಗಳನ್ನು ಉಳಿಸಲಾಗುತ್ತಿದೆ..."
            },
            "pagination": {
                "previous": "ಹಿಂದಿನ",
                "next": "ಮುಂದೆ",
                "page": "ಪುಟ",
                "of": "ರ",
                "rowsPerPage": "ಪ್ರತಿ ಪುಟಕ್ಕೆ ಸಾಲುಗಳು",
                "showing": "ತೋರಿಸಲಾಗುತ್ತಿದೆ",
                "entries": "ದಾಖಲೆಗಳು",
                "totalRecords": "ಒಟ್ಟು ದಾಖಲೆಗಳು"
            },
            "search": {
                "searchPlaceholder": "ದೂರುಗಳು, ಪ್ರಕರಣಗಳು, ಸ್ಥಳಗಳನ್ನು ಹುಡುಕಿ...",
                "searchGrievances": "ದೂರುಗಳನ್ನು ಹುಡುಕಿ...",
                "searchUsers": "ಬಳಕೆದಾರರನ್ನು ಹುಡುಕಿ...",
                "searchDepartments": "ಇಲಾಖೆಗಳನ್ನು ಹುಡುಕಿ...",
                "searchProjects": "ಯೋಜನೆಗಳನ್ನು ಹುಡುಕಿ...",
                "searchOfficers": "ಅಧಿಕಾರಿಗಳನ್ನು ಹುಡುಕಿ...",
                "quickNavigator": "ತ್ವರಿತ ನ್ಯಾವಿಗೇಟರ್...",
                "searchAll": "ಪ್ಲಾಟ್‌ಫಾರ್ಮ್‌ನಾದ್ಯಂತ ಹುಡುಕಿ..."
            }
        },
        "ai": {
            "processing": "AI ಪ್ರಕ್ರಿಯೆಗೊಳಿಸುವಿಕೆ",
            "ocrResult": "OCR ಪಠ್ಯವನ್ನು ಹೊರತೆಗೆಯಲಾಗಿದೆ",
            "speechResult": "ಸ್ಥಳೀಯ ಭಾಷಣದ ಪ್ರತಿಲೇಖನ",
            "speechTranscript": "ಭಾಷಣದ ಪ್ರತಿಲೇಖನ",
            "confidenceScore": "AI ವಿಶ್ವಾಸಾರ್ಹತೆಯ ಅಂಕ",
            "aiConfidence": "AI ವಿಶ್ವಾಸಾರ್ಹತೆ",
            "suggestedCategory": "ಸೂಚಿಸಲಾದ ವರ್ಗ",
            "suggestedDepartment": "ಸೂಚಿಸಲಾದ ಇಲಾಖೆ",
            "recommendedDepartment": "ಶಿಫಾರಸು ಮಾಡಿದ ಇಲಾಖೆ",
            "suggestedIndustry": "ಸೂಚಿಸಲಾದ ಉದ್ಯಮ ಪಾಲುದಾರ",
            "duplicateDetection": "ನಕಲಿ ದೂರುಗಳ ಪತ್ತೆ",
            "aiVerification": "ಮಲ್ಟಿಮೋಡಲ್ ದೃಷ್ಟಿ ಪರಿಶೀಲನೆ",
            "smartRouting": "ಬುದ್ಧಿವಂತ ಇಲಾಖಾ ರೂಟಿಂಗ್",
            "previewTitle": "AI ಹೊರತೆಗೆಯುವಿಕೆಯ ಮುನ್ನೋಟ",
            "previewSubtitle": "ಕಂಪ್ಯೂಟರ್ ದೃಷ್ಟಿ ಮತ್ತು ಭಾಷಣ ಪೈಪ್‌ಲೈನ್‌ಗಳು ಈ ಕೆಳಗಿನ ಡೇಟಾವನ್ನು ಹೊರತೆಗೆದಿವೆ. ಕಳುಹಿಸುವ ಮೊದಲು ಪರಿಶೀಲಿಸಿ.",
            "detectedHeadline": "ಪತ್ತೆಯಾದ ದೂರಿನ ಶೀರ್ಷಿಕೆ",
            "classifiedCategory": "AI ವರ್ಗೀಕರಿಸಿದ ವರ್ಗ",
            "dispatchedDept": "ನಿಯೋಜಿಸಲಾದ ಪುರಸಭೆ ಇಲಾಖೆ",
            "severityPriority": "ತೀವ್ರತೆ ಮತ್ತು ತುರ್ತು ಆದ್ಯತೆ",
            "mappedLocation": "ಮ್ಯಾಪ್ ಮಾಡಿದ ಘಟನೆಯ ಸ್ಥಳ",
            "confirmSubmit": "ದೃಢೀಕರಿಸಿ ಮತ್ತು ದೂರು ರವಾನಿಸಿ",
            "cancel": "ರದ್ದುಮಾಡಿ",
            "ocrBadge": "FastAPI OCR ಹೊರತೆಗೆದಿದೆ",
            "sttBadge": "ಸ್ಥಳೀಯ ಭಾಷಣ ಲಿಪ್ಯಂತರಿಸಲಾಗಿದೆ",
            "verificationStep": "ನಾಗರಿಕ ಪರಿಶೀಲನಾ ಹಂತ",
            "verificationStepHelp": "100% ನಿಖರತೆಯನ್ನು ಖಚಿತಪಡಿಸಿಕೊಳ್ಳಲು ನೀವು ಕೆಳಗಿನ ಯಾವುದೇ ಕ್ಷೇತ್ರವನ್ನು ನೇರವಾಗಿ ಸಂಪಾದಿಸಬಹುದು.",
            "ocrVision": "OCR ದೃಷ್ಟಿ ಹೊರತೆಗೆಯುವಿಕೆ",
            "noOcrText": "ಫಲಕಗಳಲ್ಲಿ ಯಾವುದೇ ಪಠ್ಯ ಪತ್ತೆಯಾಗಿಲ್ಲ",
            "noAudioMemo": "ಯಾವುದೇ ಆಡಿಯೋ ಮೆಮೊ ಲಗತ್ತಿಸಲಾಗಿಲ್ಲ",
            "priorityScore": "ಲೆಕ್ಕಹಾಕಿದ ಆದ್ಯತೆಯ ಅಂಕ",
            "estimatedCost": "ಅಂದಾಜು ಪುರಸಭೆಯ ವೆಚ್ಚ",
            "estimatedTime": "ಅಂದಾಜು ಪರಿಹಾರ ಸಮಯ",
            "recommendation": "AI ಆಡಳಿತ ಶಿಫಾರಸು",
            "confidenceHigh": "ಹೆಚ್ಚಿನ ವಿಶ್ವಾಸಾರ್ಹತೆ (>90%)",
            "confidenceMedium": "ಮಧ್ಯಮ ವಿಶ್ವಾಸಾರ್ಹತೆ (70-90%)",
            "confidenceLow": "ಕಡಿಮೆ ವಿಶ್ವಾಸಾರ್ಹತೆ (<70%)",
            "duplicateFound": "ಸಂಭಾವ್ಯ ನಕಲಿ ದೂರು ಪತ್ತೆಯಾಗಿದೆ",
            "duplicateScore": "ಹೋಲಿಕೆಯ ಅಂಕ"
        },
        "citizen": {
            "portalTitle": "ನಾಗರಿಕ ಪೋರ್ಟಲ್",
            "dashboard": {
                "welcomeBack": "ಮರಳಿ ಸುಸ್ವಾಗತ",
                "totalReported": "ಒಟ್ಟು ವರದಿ ಮಾಡಲಾದವು",
                "inProgress": "ಪ್ರಗತಿಯಲ್ಲಿದೆ",
                "resolved": "ಪರಿಹರಿಸಲಾಗಿದೆ",
                "needsVerification": "ಪರಿಶೀಲನೆ ಅಗತ್ಯವಿದೆ",
                "communityImpact": "ಸಮುದಾಯದ ಪ್ರಭಾವದ ಅಂಕ",
                "avgResolution": "ಸರಾಸರಿ ಪರಿಹಾರ ಸಮಯ",
                "recentGrievances": "ಇತ್ತೀಚಿನ ದೂರುಗಳು",
                "reportNewIssue": "ಹೊಸ ದೂರನ್ನು ವರದಿ ಮಾಡಿ",
                "myIssues": "ನನ್ನ ದೂರುಗಳು",
                "trackIssues": "ಪರಿಹಾರವನ್ನು ಟ್ರ್ಯಾಕ್ ಮಾಡಿ",
                "liveIncidents": "ಲೈವ್ ನಾಗರಿಕ ಘಟನೆಗಳು",
                "civicFeed": "ನಾಗರಿಕ ಫೀಡ್",
                "satisfactionScore": "ನಾಗರಿಕ ತೃಪ್ತಿ ರೇಟಿಂಗ್",
                "activeCases": "ಸಕ್ರಿಯ ದೂರುಗಳು",
                "resolvedCases": "ಪರಿಹರಿಸಲಾದ ದೂರುಗಳು"
            },
            "report": {
                "title": "ಸಾಮಾಜಿಕ ದೂರನ್ನು ವರದಿ ಮಾಡಿ",
                "subtitle": "ಫೋಟೋಗಳು, ವಿಡಿಯೋ, ಧ್ವನಿ ಟಿಪ್ಪಣಿಗಳು ಅಥವಾ ದಾಖಲೆಗಳನ್ನು ಸಲ್ಲಿಸಿ. ನಮ್ಮ AI ಇಂಜಿನ್ OCR ಮೂಲಕ ಫಲಕಗಳನ್ನು ಹೊರತೆಗೆದು ಮುನ್ನೋಟವನ್ನು ನೀಡುತ್ತದೆ.",
                "multimodalBadge": "ಮಲ್ಟಿಮೋಡಲ್ AI ಇಂಜೆಶನ್",
                "moduleBadge": "ಮಾಡ್ಯೂಲ್ 1",
                "uploadEvidence": "ಫೋಟೋಗ್ರಾಫಿಕ್ ಮತ್ತು ಸಾಕ್ಷ್ಯ ದಾಖಲೆಗಳು",
                "uploadSubtitle": "ದೋಷ, ಮುರಿದ ಬೋರ್ಡ್ ಅಥವಾ ಪುರಸಭೆಯ ದಾಖಲೆಯ ಚಿತ್ರವನ್ನು ಅಪ್‌ಲೋಡ್ ಮಾಡಿ",
                "dragDrop": "ಚಿತ್ರಗಳು, ವಿಡಿಯೋ ಕ್ಲಿಪ್‌ಗಳು ಅಥವಾ ದಾಖಲೆಗಳನ್ನು ಎಳೆದು ಬಿಡಿ",
                "supportedFormats": "JPEG, PNG, MP4 ಮತ್ತು PDF (ಗರಿಷ್ಠ 25MB) ಬೆಂಬಲಿಸುತ್ತದೆ.",
                "browseFiles": "ಫೈಲ್‌ಗಳನ್ನು ಬ್ರೌಸ್ ಮಾಡಿ",
                "openCamera": "ಕ್ಯಾಮೆರಾ ತೆರೆಯಿರಿ",
                "uploadingProgress": "AI ಮೂಲಕ ಮಾಧ್ಯಮವನ್ನು ಅಪ್‌ಲೋಡ್ ಮಾಡಿ ಪ್ರಕ್ರಿಯೆಗೊಳಿಸಲಾಗುತ್ತಿದೆ...",
                "attachedEvidence": "ಲಗತ್ತಿಸಲಾದ ಸಾಕ್ಷ್ಯಗಳು",
                "voiceGrievance": "ಧ್ವನಿ ಆಡಿಯೋ ದೂರು",
                "optional": "ಐಚ್ಛಿಕ",
                "voiceSubtitle": "ಮಾತನಾಡುವ ವಿವರಣೆಯನ್ನು ರೆಕಾರ್ಡ್ ಮಾಡಿ. ಸ್ವಯಂಚಾಲಿತವಾಗಿ ಲಿಪ್ಯಂತರಿಸಲಾಗುತ್ತದೆ.",
                "pressRecordHelp": "ಯಾವುದೇ ಭಾಷೆಯಲ್ಲಿ ನಿಮ್ಮ ಸಮಸ್ಯೆಯನ್ನು ವಿವರಿಸಲು ರೆಕಾರ್ಡ್ ಒತ್ತಿರಿ.",
                "startVoiceRecording": "ಧ್ವನಿ ರೆಕಾರ್ಡಿಂಗ್ ಪ್ರಾರಂಭಿಸಿ",
                "stopRecording": "ರೆಕಾರ್ಡಿಂಗ್ ನಿಲ್ಲಿಸಿ",
                "recording": "ರೆಕಾರ್ಡ್ ಆಗುತ್ತಿದೆ...",
                "speechProcessing": "ಧ್ವನಿ ಪ್ರಕ್ರಿಯೆಗೊಳಿಸಲಾಗುತ್ತಿದೆ...",
                "speechConverted": "ಧ್ವನಿ ಯಶಸ್ವಿಯಾಗಿ ಪರಿವರ್ತನೆಗೊಂಡಿದೆ",
                "incidentLocation": "ಘಟನೆಯ ಸ್ಥಳ",
                "locationSubtitle": "ಕ್ಷೇತ್ರ ಕಾರ್ಯಕರ್ತರನ್ನು ಕಳುಹಿಸಲು ನಿಖರವಾದ ನಿರ್ದೇಶಾಂಕಗಳನ್ನು ಗುರುತಿಸಿ",
                "useCurrentGps": "ಪ್ರಸ್ತುತ GPS ಬಳಸಿ",
                "streetAddress": "ರಸ್ತೆ ವಿಳಾಸ / ಗುರುತು",
                "addressPlaceholder": "ಉದಾ. 14ನೇ ಮುಖ್ಯ ರಸ್ತೆ, ಇಂದಿರಾ ಗಾಂಧಿ ವೃತ್ತದ ಹತ್ತಿರ",
                "mapTip": "ಸುಳಿವು: ನಿರ್ದೇಶಾಂಕಗಳನ್ನು ಹೊಂದಿಸಲು ನೀವು ನಕ್ಷೆಯಲ್ಲಿ ಎಲ್ಲಿ ಬೇಕಾದರೂ ಕ್ಲಿಕ್ ಮಾಡಬಹುದು.",
                "contextTitle": "ಸಮಸ್ಯೆಯ ವಿವರಣೆ",
                "contextSubtitle": "ಸಂಕ್ಷಿಪ್ತ ಸಂದರ್ಭವನ್ನು ಒದಗಿಸಿ (AI ಸ್ವಯಂಚಾಲಿತವಾಗಿ ವರ್ಗೀಕರಿಸುತ್ತದೆ)",
                "headlineLabel": "ಸಂಕ್ಷಿಪ್ತ ದೂರಿನ ಶೀರ್ಷಿಕೆ",
                "headlinePlaceholder": "ಉದಾ., ಭೂಗತ ನೀರಿನ ಪೈಪ್ ಒಡೆದು ರಸ್ತೆಯಲ್ಲಿ ನೀರು ನಿಂತಿರುವುದು",
                "detailsLabel": "ವಿವರವಾದ ವಿವರಣೆ",
                "detailsPlaceholder": "ಸಾಮಾಜಿಕ ಪರಿಣಾಮ, ಅವಧಿ ಮತ್ತು ಸುರಕ್ಷತಾ ಅಪಾಯಗಳನ್ನು ವಿವರಿಸಿ...",
                "categoryLabel": "ಪುರಸಭೆಯ ವರ್ಗ",
                "priorityLabel": "ತುರ್ತು ಆದ್ಯತೆ",
                "generateAiPreview": "AI ಮುನ್ನೋಟವನ್ನು ರಚಿಸಿ",
                "processingAi": "AI ಪ್ರಕ್ರಿಯೆ ನಡೆಯುತ್ತಿದೆ...",
                "audioMemo": "ಆಡಿಯೋ ದೂರು ಮೆಮೊ",
                "readyStt": "STT ಪಾರ್ಸಿಂಗ್‌ಗೆ ಸಿದ್ಧವಾಗಿದೆ",
                "incidentCoordinates": "ಘಟನೆಯ ನಿರ್ದೇಶಾಂಕಗಳು",
                "currentDetectedLocation": "ಪತ್ತೆಯಾದ ಪ್ರಸ್ತುತ ಸ್ಥಳ"
            },
            "track": {
                "title": "ದೂರು ಪರಿಹಾರವನ್ನು ಟ್ರ್ಯಾಕ್ ಮಾಡಿ",
                "subtitle": "ಸ್ಥಿತಿ ಪರಿವರ್ತನೆಗಳು, ನಿಯೋಜಿಸಲಾದ ಇಂಜಿನಿಯರ್‌ಗಳು ಮತ್ತು SLA ಟೈಮರ್‌ಗಳನ್ನು ಮೇಲ್ವಿಚಾರಣೆ ಮಾಡಿ.",
                "enterId": "ದೂರು ಟ್ರ್ಯಾಕಿಂಗ್ ID ನಮೂದಿಸಿ",
                "searchPlaceholder": "ಉದಾ. SOC-2026-8821",
                "currentStage": "ಪ್ರಸ್ತುತ ಹಂತ",
                "assignedTo": "ನಿಯೋಜಿಸಲಾದ ಇಲಾಖೆ",
                "officerInCharge": "ಪ್ರಭಾರ ಅಧಿಕಾರಿ",
                "slaTimer": "SLA ಪರಿಹಾರ ಕೌಂಟ್‌ಡೌನ್",
                "timeline": "ಆಡಿಟ್ ಕಾಲಮಿತಿ",
                "trackingDetails": "ಟ್ರ್ಯಾಕಿಂಗ್ ವಿವರಗಳು",
                "liveStatusTransitions": "ಲೈವ್ ಸ್ಥಿತಿ ಬದಲಾವಣೆಗಳು"
            },
            "profile": {
                "title": "ನಾಗರಿಕ ಪ್ರೊಫೈಲ್",
                "fullName": "ಪೂರ್ಣ ಹೆಸರು",
                "email": "ಇಮೇಲ್ ವಿಳಾಸ",
                "phone": "ದೂರವಾಣಿ ಸಂಖ್ಯೆ",
                "district": "ವಾಸಿಸುವ ಜಿಲ್ಲೆ",
                "address": "ಖಾಯಂ ವಿಳಾಸ",
                "saveProfile": "ಪ್ರೊಫೈಲ್ ಉಳಿಸಿ",
                "citizenBadge": "ಪರಿಶೀಲಿಸಿದ ನಾಗರಿಕ",
                "verificationStatus": "ಗುರುತು ಪರಿಶೀಲನಾ ಸ್ಥಿತಿ"
            },
            "settings": {
                "title": "ಆದ್ಯತೆಗಳು ಮತ್ತು ಸಂಯೋಜನೆಗಳು",
                "notifications": "ದೂರಿನ ಅಧಿಸೂಚನೆಗಳು",
                "emailAlerts": "ಇಮೇಲ್ ಎಚ್ಚರಿಕೆಗಳು",
                "smsAlerts": "SMS ಎಚ್ಚರಿಕೆಗಳು",
                "theme": "ಪ್ರದರ್ಶನ ಥೀಮ್",
                "language": "ಅಪ್ಲಿಕೇಶನ್ ಭಾಷೆ",
                "savePreferences": "ಆದ್ಯತೆಗಳನ್ನು ಉಳಿಸಿ"
            }
        },
        "government": {
            "portalTitle": "ಪುರಸಭೆಯ ಕಮಾಂಡ್ ಮತ್ತು ನಿಯಂತ್ರಣ",
            "dashboard": {
                "title": "ಸರ್ಕಾರಿ ಅಧಿಕೃತ ಪೋರ್ಟಲ್",
                "overview": "ಪುರಸಭೆಯ ಅವಲೋಕನ",
                "assignedCases": "ನಿಯೋಜಿಸಲಾದ ದೂರುಗಳು",
                "liveCases": "ಸಕ್ರಿಯ ಪ್ರಕರಣಗಳು",
                "slaBreachRisk": "SLA ಉಲ್ಲಂಘನೆಯ ಅಪಾಯ",
                "avgTurnaround": "ಸರಾಸರಿ ಪರಿಹಾರ ಸಮಯ",
                "citizenSatisfaction": "ನಾಗರಿಕ ತೃಪ್ತಿ",
                "urgentDocket": "ತುರ್ತು ರವಾನೆ ಪಟ್ಟಿ",
                "viewQueue": "ಸಂಪೂರ್ಣ ಸರದಿಯನ್ನು ವೀಕ್ಷಿಸಿ",
                "syncTelemetry": "ಟೆಲಿಮೆಟ್ರಿ ಸಿಂಕ್ ಮಾಡಿ",
                "telemetryActive": "ನೈಜ-ಸಮಯದ ನಾಗರಿಕ ಟೆಲಿಮೆಟ್ರಿ ಮತ್ತು ಸ್ವಯಂಚಾಲಿತ ರವಾನೆ ಸಕ್ರಿಯವಾಗಿದೆ.",
                "monthlyTrends": "ಮಾಸಿಕ ದೂರು ಪ್ರವೃತ್ತಿಗಳು",
                "resolutionBreakdown": "ಪರಿಹಾರದ ವಿವರಗಳು",
                "districtHeatmap": "ಜಿಲ್ಲಾ ಕಾರ್ಯಕ್ಷಮತೆಯ ನಕ್ಷೆ",
                "departmentEfficiency": "ಇಲಾಖಾ ದಕ್ಷತೆಯ ರೇಟಿಂಗ್‌ಗಳು",
                "docketOverview": "ಪ್ರಕರಣಗಳ ಅವಲೋಕನ",
                "statutoryTarget": "24 ಗಂಟೆಗಳ ಶಾಸನಬದ್ಧ ರಾಜ್ಯ ಗುರಿಯ ವಿರುದ್ಧ"
            },
            "officers": {
                "title": "ಅಧಿಕಾರಿಗಳ ಡೈರೆಕ್ಟರಿ",
                "directory": "ಕ್ಷೇತ್ರ ಮತ್ತು ನೋಡಲ್ ಅಧಿಕಾರಿಗಳು",
                "addOfficer": "ಅಧಿಕಾರಿಯನ್ನು ನೋಂದಾಯಿಸಿ",
                "officerName": "ಅಧಿಕಾರಿಯ ಹೆಸರು",
                "designation": "ಹುದ್ದೆ",
                "department": "ಇಲಾಖೆ",
                "contact": "ಸಂಪರ್ಕ",
                "assignedCount": "ನಿಯೋಜಿಸಲಾದ ಪ್ರಕರಣಗಳು",
                "resolutionRate": "ಪರಿಹಾರ ದರ",
                "status": "ಕರ್ತವ್ಯದ ಸ್ಥಿತಿ",
                "actions": "ಕ್ರಿಯೆಗಳು",
                "searchOfficers": "ಹೆಸರು, ಬ್ಯಾಡ್ಜ್ ಅಥವಾ ಇಲಾಖೆಯ ಮೂಲಕ ಹುಡುಕಿ..."
            },
            "departments": {
                "title": "ಪುರಸಭೆಯ ಇಲಾಖೆಗಳು",
                "municipalDepartments": "ನಗರ ಕಾರ್ಯಾಚರಣೆ ಇಲಾಖೆಗಳು",
                "addDepartment": "ಇಲಾಖೆಯನ್ನು ಸೇರಿಸಿ",
                "deptName": "ಇಲಾಖೆಯ ಹೆಸರು",
                "headOfDept": "ಇಲಾಖಾ ಮುಖ್ಯಸ್ಥರು",
                "activePersonnel": "ಸಕ್ರಿಯ ಸಿಬ್ಬಂದಿ",
                "budgetAllocated": "ಹಂಚಿಕೆಯಾದ ಬಜೆಟ್",
                "openGrievances": "ಬಾಕಿ ಉಳಿದಿರುವ ದೂರುಗಳು",
                "slaCompliance": "SLA ಅನುಸರಣೆ",
                "efficiencyRating": "ದಕ್ಷತೆಯ ರೇಟಿಂಗ್",
                "searchDepartments": "ಇಲಾಖೆಗಳನ್ನು ಹುಡುಕಿ..."
            },
            "assigned": {
                "title": "ನಿಯೋಜಿಸಲಾದ ದೂರುಗಳು",
                "caseId": "ಪ್ರಕರಣ ID",
                "citizenName": "ನಾಗರಿಕರ ಹೆಸರು",
                "category": "ವರ್ಗ",
                "priority": "ಆದ್ಯತೆ",
                "status": "ಸ್ಥಿತಿ",
                "dateReported": "ವರದಿ ಮಾಡಿದ ದಿನಾಂಕ",
                "targetResolution": "ಗುರಿಯ ಪರಿಹಾರ",
                "reassign": "ಅಧಿಕಾರಿಯನ್ನು ಮರುನಿಯೋಜಿಸಿ",
                "escalate": "ಮೇಲಧಿಕಾರಿಗೆ ಕಳುಹಿಸಿ",
                "resolveCase": "ಪರಿಹರಿಸಲಾಗಿದೆ ಎಂದು ಗುರುತಿಸಿ",
                "viewCase": "ಪ್ರಕರಣವನ್ನು ಪರಿಶೀಲಿಸಿ",
                "filterPriority": "ಆದ್ಯತೆಯ ಮೂಲಕ ಫಿಲ್ಟರ್ ಮಾಡಿ",
                "filterStatus": "ಸ್ಥಿತಿಯ ಮೂಲಕ ಫಿಲ್ಟರ್ ಮಾಡಿ",
                "allCases": "ಎಲ್ಲಾ ಪ್ರಕರಣಗಳು"
            },
            "tracking": {
                "title": "ದೂರು ಜಿಯೋ-ಟ್ರ್ಯಾಕಿಂಗ್",
                "subtitle": "ಅಧಿಕಾರಿಗಳ ಟೆಲಿಮೆಟ್ರಿಯೊಂದಿಗೆ ಸಮಸ್ಯೆಗಳನ್ನು ತೋರಿಸುವ ಸಂವಾದಾತ್ಮಕ ನಕ್ಷೆ.",
                "liveIncidentMap": "ಲೈವ್ ಘಟನೆಯ ನಕ್ಷೆ",
                "filterByWard": "ವಾರ್ಡ್ ಮೂಲಕ ಫಿಲ್ಟರ್ ಮಾಡಿ",
                "filterBySeverity": "ತೀವ್ರತೆಯ ಮೂಲಕ ಫಿಲ್ಟರ್ ಮಾಡಿ"
            },
            "aiSuggestions": {
                "title": "AI ಆಡಳಿತ ಒಳನೋಟಗಳು",
                "smartRoutingTitle": "ಸ್ವಯಂಚಾಲಿತ ರೂಟಿಂಗ್ ಶಿಫಾರಸುಗಳು",
                "recommendedActions": "ಶಿಫಾರಸು ಮಾಡಿದ ಕ್ರಮಗಳು",
                "anomalyDetection": "ಅಸಂಗತತೆ ಪತ್ತೆ",
                "duplicateClusters": "ಪತ್ತೆಯಾದ ನಕಲಿ ಕ್ಲಸ್ಟರ್‌ಗಳು",
                "autoTriage": "ಆಟೋ-ಟ್ರಯಾಜ್ ನಿಯಮಗಳ ಎಂಜಿನ್"
            },
            "reports": {
                "title": "ಆಡಳಿತ ವಿಶ್ಲೇಷಣೆ ಮತ್ತು ವರದಿಗಳು",
                "generateReport": "ವರದಿಯನ್ನು ರಚಿಸಿ",
                "downloadPdf": "PDF ಡೌನ್‌ಲೋಡ್ ಮಾಡಿ",
                "downloadCsv": "CSV ರಫ್ತು ಮಾಡಿ",
                "monthlyAudit": "ಮಾಸಿಕ ಪುರಸಭೆಯ ಲೆಕ್ಕಪರಿಶೋಧನೆ",
                "quarterlyPerformance": "ತ್ರೈಮಾಸಿಕ ಕಾರ್ಯಕ್ಷಮತೆ ಪರಿಶೀಲನೆ",
                "exportAnalytics": "ವಿಶ್ಲೇಷಣೆಯನ್ನು ರಫ್ತು ಮಾಡಿ"
            },
            "settings": {
                "title": "ಪೋರ್ಟಲ್ ಆಡಳಿತ ಸಂಯೋಜನೆಗಳು",
                "slaThresholds": "SLA ತುರ್ತು ಮಿತಿಗಳು",
                "notificationRules": "ಎಚ್ಚರಿಕೆ ಮತ್ತು ಅಧಿಸೂಚನೆ ನಿಯಮಗಳು",
                "escalationMatrix": "ರವಾನೆ ಮ್ಯಾಟ್ರಿಕ್ಸ್",
                "workingHours": "ಇಲಾಖೆಯ ಕೆಲಸದ ಸಮಯ"
            }
        },
        "industry": {
            "portalTitle": "ಉದ್ಯಮ ಮತ್ತು ಕಾರ್ಪೊರೇಟ್ CSR ಪೋರ್ಟಲ್",
            "dashboard": {
                "title": "ಉದ್ಯಮ CSR ಡ್ಯಾಶ್‌ಬೋರ್ಡ್",
                "overview": "CSR ಬಂಡವಾಳ ಮತ್ತು ಪ್ರಭಾವ",
                "csrFunding": "CSR ಬಂಡವಾಳ ಹಂಚಿಕೆ",
                "capitalAllocation": "ಬಂಡವಾಳ ಹಂಚಿಕೆ",
                "availableProjects": "ಪರಿಶೀಲಿಸಿದ ಯೋಜನೆಗಳು",
                "liveGrants": "ಸಕ್ರಿಯ ಅನುದಾನಗಳು",
                "partnershipPact": "PPP ಒಪ್ಪಂದಗಳು",
                "totalDisbursed": "ವಿತರಿಸಲಾದ ಒಟ್ಟು ನಿಧಿ",
                "activeProjects": "ಸಕ್ರಿಯ ಅನುದಾನಿತ ಯೋಜನೆಗಳು",
                "impactScore": "ಸಾಮಾಜಿಕ ಪ್ರಭಾವದ ಅಂಕ",
                "viewOpportunities": "ಅವಕಾಶಗಳನ್ನು ವೀಕ್ಷಿಸಿ",
                "availableCsr": "ಲಭ್ಯವಿರುವ CSR ಬಜೆಟ್",
                "corporatePartner": "ಕಾರ್ಪೊರೇಟ್ ಪಾಲುದಾರ",
                "verifiedEntity": "ಪರಿಶೀಲಿಸಿದ CSR ಸಂಸ್ಥೆ"
            },
            "projects": {
                "title": "ಲಭ್ಯವಿರುವ CSR ಯೋಜನೆಗಳು",
                "projectCatalog": "ಯೋಜನೆಗಳ ಕ್ಯಾಟಲಾಗ್",
                "fundingGoal": "ಗುರಿಯ ನಿಧಿ",
                "raisedAmount": "ಸಂಗ್ರಹಿಸಿದ ನಿಧಿ",
                "municipalSponsor": "ಪುರಸಭೆಯ ಪ್ರಾಯೋಜಕರು",
                "sdgImpact": "SDG ಪ್ರಭಾವದ ವರ್ಗ",
                "applyFunding": "CSR ನಿಧಿಯನ್ನು ಒದಗಿಸಿ",
                "exploreInitiatives": "ಉಪಕ್ರಮಗಳನ್ನು ಅನ್ವೇಷಿಸಿ",
                "searchProjects": "ಕೀವರ್ಡ್, SDG ಅಥವಾ ನಗರದ ಮೂಲಕ ಹುಡುಕಿ..."
            },
            "funding": {
                "title": "ನಿಧಿ ಮತ್ತು ಬಂಡವಾಳ ಹಂಚಿಕೆ",
                "grantApplication": "ಅನುದಾನ ಪ್ರಸ್ತಾಪ",
                "disbursementStatus": "ವಿತರಣಾ ಸ್ಥಿತಿ",
                "corporateDonation": "ಕಾರ್ಪೊರೇಟ್ ಕೊಡುಗೆ",
                "taxBenefit": "ಸೆಕ್ಷನ್ 80G / 135 ಪ್ರಯೋಜನ",
                "escrowStatus": "ಎಸ್ಕ್ರೋ ಖಾತೆಯ ಸ್ಥಿತಿ",
                "fundMilestone": "ಕಂತು ಬಿಡುಗಡೆ ಮಾಡಿ"
            },
            "csr": {
                "title": "CSR ಪ್ರಭಾವದ ವಿಶ್ಲೇಷಣೆ",
                "spendByCategory": "ವರ್ಗವಾರು ಖರ್ಚು",
                "geographicAllocation": "ಭೌಗೋಳಿಕ ಹಂಚಿಕೆ",
                "socialReturnOnInvestment": "ಸಾಮಾಜಿಕ ಲಾಭಾಂಶ (SROI)",
                "auditCompliance": "ಶಾಸನಬದ್ಧ ಲೆಕ್ಕಪರಿಶೋಧನಾ ಅನುಸರಣೆ",
                "csrDistribution": "CSR ವಿತರಣೆ"
            },
            "mentorship": {
                "title": "ಉದ್ಯಮ ಮಾರ್ಗದರ್ಶನ ಕಾರ್ಯಕ್ರಮ",
                "expertGuidance": "ತಜ್ಞರ ಮಾರ್ಗದರ್ಶನ ನೀಡಿ",
                "studentPrototypes": "ವಿದ್ಯಾರ್ಥಿ ಮಾದರಿಗಳು",
                "industryAdvisors": "ಕಾರ್ಪೊರೇಟ್ ಸಲಹೆಗಾರರು",
                "scheduleSession": "ಅಧಿವೇಶನವನ್ನು ನಿಗದಿಪಡಿಸಿ"
            },
            "collaboration": {
                "title": "ವಿಶ್ವವಿದ್ಯಾಲಯ ಸಹಯೋಗ ಕೇಂದ್ರ",
                "academicPacts": "ಶೈಕ್ಷಣಿಕ ಮೈತ್ರಿಗಳು",
                "joinConsortium": "ಒಕ್ಕೂಟಕ್ಕೆ ಸೇರಿ",
                "jointResearch": "ಜಂಟಿ ಸಂಶೋಧನೆಗಳು",
                "mouSigned": "ಸಹಿ ಮಾಡಿದ ಒಪ್ಪಂದಗಳು"
            },
            "prototypes": {
                "title": "ತಂತ್ರಜ್ಞಾನ ಮಾದರಿಗಳು",
                "technologyDemonstrators": "ನಾಗರಿಕ ಮಾದರಿಗಳು",
                "readyForDeployment": "ನಿಯೋಜನೆಗೆ ಸಿದ್ಧವಾಗಿದೆ",
                "pilotTested": "ಕ್ಷೇತ್ರದಲ್ಲಿ ಪರೀಕ್ಷಿಸಲಾಗಿದೆ",
                "commercialize": "ವಾಣಿಜ್ಯೀಕರಿಸಿ"
            },
            "tracking": {
                "title": "ನಿಧಿ ಮತ್ತು ಮೈಲಿಗಲ್ಲುಗಳ ಟ್ರ್ಯಾಕಿಂಗ್",
                "milestoneProgress": "ಮೈಲಿಗಲ್ಲು ಪೂರ್ಣಗೊಂಡಿದೆ",
                "verificationCheck": "ತೃತೀಯ ಪಕ್ಷದ ಪರಿಶೀಲನೆ",
                "fundRelease": "ಕಂತು ಬಿಡುಗಡೆ"
            },
            "profile": {
                "title": "ಸಂಸ್ಥೆಯ ಪ್ರೊಫೈಲ್",
                "companyName": "ಕಂಪನಿಯ ಹೆಸರು",
                "cinRegistration": "ಕಾರ್ಪೊರೇಟ್ ಗುರುತು (CIN)",
                "csrBudget": "ವಾರ್ಷಿಕ CSR ಬಜೆಟ್",
                "contactPerson": "CSR ಮುಖ್ಯಸ್ಥರು / ಸಂಪರ್ಕ",
                "panNumber": "ಕಾರ್ಪೊರೇಟ್ ಪ್ಯಾನ್"
            },
            "settings": {
                "title": "CSR ಸಂಯೋಜನೆಗಳು",
                "emailNotifications": "ಚಟುವಟಿಕೆ ಎಚ್ಚರಿಕೆಗಳು",
                "bankDetails": "ಬ್ಯಾಂಕಿಂಗ್ ವಿವರಗಳು",
                "complianceDocs": "ಅನುಸರಣಾ ದಾಖಲೆಗಳು"
            }
        },
        "ngo": {
            "portalTitle": "ನಾಗರಿಕ ಸಮಾಜ ಮತ್ತು ಸ್ವಯಂಸೇವಕ ಪೋರ್ಟಲ್",
            "dashboard": {
                "title": "ನಾಗರಿಕ ಸಮಾಜದ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್",
                "overview": "ಕ್ಷೇತ್ರ ಕಾರ್ಯಾಚರಣೆಗಳ ಅವಲೋಕನ",
                "groundSquads": "ಸಕ್ರಿಯ ಸ್ವಯಂಸೇವಕ ತಂಡಗಳು",
                "activeVolunteers": "ನೋಂದಾಯಿತ ಸ್ವಯಂಸೇವಕರು",
                "fieldInterventions": "ಕ್ಷೇತ್ರ ಮಧ್ಯಸ್ಥಿಕೆಗಳು",
                "reliefOperations": "ಪರಿಹಾರ ಕಾರ್ಯಾಚರಣೆಗಳು",
                "communityImpact": "ಪ್ರಭಾವಿತ ನಾಗರಿಕರು",
                "certsAwarded": "ನೀಡಲಾದ ಪ್ರಮಾಣಪತ್ರಗಳು",
                "urgentReliefCalls": "ತುರ್ತು ಪರಿಹಾರ ಕರೆಗಳು",
                "groundTelemetryLive": "ಲೈವ್ ಕ್ಷೇತ್ರ ಟೆಲಿಮೆಟ್ರಿ",
                "logFieldEvidence": "ಕ್ಷೇತ್ರ ಪುರಾವೆಯನ್ನು ದಾಖಲಿಸಿ"
            },
            "projects": {
                "title": "ಸಮುದಾಯ ಯೋಜನೆಗಳು",
                "localGrievances": "ನಾಗರಿಕ ಸಮಸ್ಯೆಗಳನ್ನು ಸ್ವೀಕರಿಸಿ",
                "adoptIssue": "ತಂಡವನ್ನು ಸಜ್ಜುಗೊಳಿಸಿ",
                "publicWorks": "ಸಮುದಾಯ ಕ್ರಿಯಾ ಅಭಿಯಾನಗಳು",
                "grassrootInterventions": "ತಳಮಟ್ಟದ ಮಧ್ಯಸ್ಥಿಕೆಗಳು"
            },
            "assignedProjects": {
                "title": "ನಿಯೋಜಿಸಲಾದ ಎನ್‌ಜಿಒ ಯೋಜನೆಗಳು",
                "operationalSquads": "ನಿಯೋಜಿತ ತಂಡಗಳು",
                "projectTimeline": "ಅನುಷ್ಠಾನದ ಕಾಲಮಿತಿ",
                "targetCompletion": "ಗುರಿಯ ಪೂರ್ಣಗೊಳಿಸುವ ದಿನಾಂಕ",
                "submitProgressReport": "ಪ್ರಗತಿ ವರದಿಯನ್ನು ಸಲ್ಲಿಸಿ"
            },
            "fieldActivities": {
                "title": "ಕ್ಷೇತ್ರ ಪುರಾವೆ ಲಾಗ್",
                "liveReliefLog": "ಲೈವ್ ಕ್ಷೇತ್ರ ಲಾಗ್‌ಗಳು",
                "geoTaggedPhotos": "ಜಿಯೋ-ಟ್ಯಾಗ್ ಮಾಡಿದ ಫೋಟೋಗಳು",
                "suppliesDistributed": "ವಿತರಿಸಲಾದ ನೆರವು",
                "citizensAssisted": "ಸಹಾಯ ಪಡೆದ ನಾಗರಿಕರು",
                "addLogEntry": "ಹೊಸ ಲಾಗ್ ಸಲ್ಲಿಸಿ"
            },
            "volunteers": {
                "title": "ಸ್ವಯಂಸೇವಕರ ನಿರ್ವಹಣೆ",
                "registerVolunteer": "ಹೊಸ ಸ್ವಯಂಸೇವಕರನ್ನು ಸೇರಿಸಿ",
                "skillsDirectory": "ಕೌಶಲ್ಯಗಳ ಡೈರೆಕ್ಟರಿ",
                "assignWard": "ವಾರ್ಡ್ ನಿಯೋಜಿಸಿ",
                "volunteerSquads": "ಕ್ಷೇತ್ರ ತಂಡಗಳು",
                "attendance": "ಹಾಜರಾತಿ"
            },
            "impact": {
                "title": "ಸಮುದಾಯ ಪ್ರಭಾವದ ವಿಶ್ಲೇಷಣೆ",
                "livesImpacted": "ಪ್ರಯೋಜನ ಪಡೆದ ನಾಗರಿಕರು",
                "wardsTransformed": "ಬದಲಾದ ಪುರಸಭೆಯ ವಾರ್ಡ್‌ಗಳು",
                "satisfactionIndex": "ತೃಪ್ತಿ ಸೂಚ್ಯಂಕ",
                "volunteerHours": "ಒಟ್ಟು ಸ್ವಯಂಸೇವಕ ಗಂಟೆಗಳು"
            },
            "collaborations": {
                "title": "ಪಾಲುದಾರಿಕೆಗಳು ಮತ್ತು ಮೈತ್ರಿಗಳು",
                "municipalMoU": "ಪುರಸಭೆಯ ಸಹಕಾರ ಒಪ್ಪಂದಗಳು",
                "corporateSponsors": "ಕಾರ್ಪೊರೇಟ್ CSR ಪಾಲುದಾರರು",
                "universityAlliances": "ವಿಶ್ವವಿದ್ಯಾಲಯದ ಮೈತ್ರಿಗಳು"
            },
            "certificates": {
                "title": "ಪ್ರಮಾಣಪತ್ರಗಳು ಮತ್ತು ಬ್ಯಾಡ್ಜ್‌ಗಳು",
                "awardCertificate": "ಪ್ರಶಂಸನಾ ಪತ್ರ ನೀಡಿ",
                "downloadBadge": "ಡಿಜಿಟಲ್ ಬ್ಯಾಡ್ಜ್ ಡೌನ್‌ಲೋಡ್ ಮಾಡಿ",
                "recognitionLetter": "ಪುರಸಭೆಯ ಪ್ರಶಂಸಾ ಪತ್ರ"
            },
            "reports": {
                "title": "ಕ್ಷೇತ್ರ ಲೆಕ್ಕಪರಿಶೋಧನೆ ಮತ್ತು ವರದಿಗಳು",
                "fieldAuditReports": "ಕ್ಷೇತ್ರ ಪರಿಶೀಲನಾ ವರದಿಗಳು",
                "monthlyActivitySummary": "ಮಾಸಿಕ ಚಟುವಟಿಕೆಗಳ ಸಾರಾಂಶ",
                "incidentLogSheet": "ಘಟನೆಗಳ ಪ್ರತಿಕ್ರಿಯೆ ಲಾಗ್",
                "submitToGovernment": "ಸರ್ಕಾರಕ್ಕೆ ವರದಿ ಸಲ್ಲಿಸಿ"
            },
            "settings": {
                "title": "ಎನ್‌ಜಿಒ ಪ್ರೊಫೈಲ್ ಮತ್ತು ಸಂಯೋಜನೆಗಳು",
                "registrationDetails": "ನೋಂದಣಿ ವಿವರಗಳು",
                "ngoDarpanId": "ನೀತಿ ಆಯೋಗ್ ದರ್ಪಣ್ ID",
                "focalPoints": "ಕ್ಷೇತ್ರ ಸಂಯೋಜಕರು"
            }
        },
        "university": {
            "portalTitle": "ವಿಶ್ವವಿದ್ಯಾಲಯ ಮತ್ತು ಶೈಕ್ಷಣಿಕ ಪೋರ್ಟಲ್",
            "student": {
                "dashboard": {
                    "title": "ವಿದ್ಯಾರ್ಥಿ ನಾವೀನ್ಯತೆ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್",
                    "academicCredits": "ಗಳಿಸಿದ ಶೈಕ್ಷಣಿಕ ಕ್ರೆಡಿಟ್‌ಗಳು",
                    "assignedTasks": "ನಿಯೋಜಿಸಲಾದ ಲ್ಯಾಬ್ ಕಾರ್ಯಗಳು",
                    "labProjects": "ಸಂಶೋಧನಾ ಯೋಜನೆಗಳು",
                    "prototypeChallenges": "ನಾವೀನ್ಯತೆ ಸವಾಲುಗಳು",
                    "submitMilestone": "ಮೈಲಿಗಲ್ಲನ್ನು ಸಲ್ಲಿಸಿ"
                },
                "tasks": {
                    "title": "ಲ್ಯಾಬ್ ಕಾರ್ಯಗಳು",
                    "pendingTasks": "ಬಾಕಿ ಇರುವ ಕಾರ್ಯಗಳು",
                    "taskDescription": "ಕಾರ್ಯ ಸೂಚನೆಗಳು",
                    "dueDate": "ಸಲ್ಲಿಕೆಯ ಅಂತಿಮ ದಿನಾಂಕ",
                    "submitDeliverable": "ಪರಿಹಾರವನ್ನು ಸಲ್ಲಿಸಿ",
                    "advisorNotes": "ಸಲಹೆಗಾರರ ಟಿಪ್ಪಣಿಗಳು",
                    "dueTasks": "ಶೀಘ್ರದಲ್ಲೇ ಮುಗಿಯಬೇಕಾದ ಕಾರ್ಯಗಳು"
                },
                "uploads": {
                    "title": "ಫಲಿತಾಂಶಗಳನ್ನು ಅಪ್‌ಲೋಡ್ ಮಾಡಿ",
                    "researchNotes": "ಸಂಶೋಧನಾ ಟಿಪ್ಪಣಿಗಳು ಮತ್ತು ವರದಿಗಳು",
                    "projectCode": "ಮೂಲ ಕೋಡ್ ಭಂಡಾರ",
                    "presentationSlides": "ಪ್ರಸ್ತುತಿ ಸ್ಲೈಡ್‌ಗಳು",
                    "submitForGrading": "ಪರಿಶೀಲನೆಗಾಗಿ ಸಲ್ಲಿಸಿ"
                },
                "timeline": {
                    "title": "ಮೈಲಿಗಲ್ಲು ಕಾಲಮಿತಿ",
                    "projectSchedule": "ಯೋಜನೆಯ ವೇಳಾಪಟ್ಟಿ",
                    "semesterDeadlines": "ಸೆಮಿಸ್ಟರ್ ಮೈಲಿಗಲ್ಲುಗಳು",
                    "facultyReviewDate": "ನಿಗದಿತ ಪರಿಶೀಲನೆ"
                },
                "messages": {
                    "title": "ಸಲಹೆಗಾರರ ಚರ್ಚೆ",
                    "chatWithMentor": "ಮಾರ್ಗದರ್ಶಕರೊಂದಿಗೆ ಚಾಟ್ ಮಾಡಿ",
                    "feedbackThread": "ಪ್ರತಿಕ್ರಿಯೆ ಮತ್ತು ತಿದ್ದುಪಡಿಗಳು",
                    "askQuestion": "ಪ್ರಶ್ನೆ ಕೇಳಿ"
                }
            },
            "faculty": {
                "dashboard": {
                    "title": "ಅಧ್ಯಾಪಕರ ಮಾರ್ಗದರ್ಶಿ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್",
                    "studentCohorts": "ವಿದ್ಯಾರ್ಥಿ ತಂಡಗಳು",
                    "mentoredProjects": "ಮಾರ್ಗದರ್ಶನ ನೀಡಿದ ಯೋಜನೆಗಳು",
                    "pendingApprovals": "ಬಾಕಿ ಇರುವ ಅನುಮೋದನೆಗಳು",
                    "researchPapers": "ಪ್ರಕಟಿತ ಸಂಶೋಧನಾ ಪ್ರಬಂಧಗಳು",
                    "innovationIndex": "ನಾವೀನ್ಯತೆ ಸೂಚ್ಯಂಕ"
                },
                "approvals": {
                    "title": "ಮೈಲಿಗಲ್ಲು ಅನುಮೋದನೆಗಳು",
                    "reviewSubmission": "ಸಲ್ಲಿಕೆಯನ್ನು ಪರಿಶೀಲಿಸಿ",
                    "approveMilestone": "ಮೈಲಿಗಲ್ಲನ್ನು ಅನುಮೋದಿಸಿ",
                    "rejectMilestone": "ತಿದ್ದುಪಡಿಗೆ ವಿನಂತಿಸಿ",
                    "provideFeedback": "ಪ್ರತಿಕ್ರಿಯೆ ಮತ್ತು ಮೌಲ್ಯಮಾಪನ",
                    "gradeAwarded": "ನೀಡಲಾದ ಕ್ರೆಡಿಟ್‌ಗಳು",
                    "pendingReviews": "ಬಾಕಿ ಇರುವ ಪರಿಶೀಲನೆಗಳು"
                },
                "proposals": {
                    "title": "ಪುರಸಭೆಯ ಸಂಶೋಧನಾ ಪ್ರಸ್ತಾಪಗಳು",
                    "civicResearchTopics": "ನಾಗರಿಕ ಸಮಸ್ಯೆಗಳ ಹೇಳಿಕೆಗಳು",
                    "grantProposals": "ಜಂಟಿ ಸಂಶೋಧನಾ ಅನುದಾನಗಳು",
                    "callForPapers": "ಪರಿಹಾರಗಳಿಗಾಗಿ ಆಹ್ವಾನ",
                    "openProposals": "ಮುಕ್ತ ಪ್ರಸ್ತಾಪಗಳು"
                },
                "teams": {
                    "title": "ವಿದ್ಯಾರ್ಥಿ ಸಂಶೋಧನಾ ತಂಡಗಳು",
                    "teamRoster": "ತಂಡದ ಸದಸ್ಯರು",
                    "assignLead": "ತಂಡದ ನಾಯಕರನ್ನು ನೇಮಿಸಿ",
                    "performanceReview": "ನಿಯತಕಾಲಿಕ ಮೌಲ್ಯಮಾಪನ",
                    "academicAdvising": "ಶೈಕ್ಷಣಿಕ ಸಲಹೆ"
                },
                "reports": {
                    "title": "ಶೈಕ್ಷಣಿಕ ವಿಶ್ಲೇಷಣೆ ಮತ್ತು ವರದಿಗಳು",
                    "cohortProgress": "ಪ್ರಗತಿ ಟ್ರ್ಯಾಕರ್",
                    "publicationOutput": "ಶೈಕ್ಷಣಿಕ ಔಟ್‌ಪುಟ್",
                    "creditDistribution": "ಕ್ರೆಡಿಟ್ ವಿತರಣೆ"
                }
            },
            "shared": {
                "projects": {
                    "title": "ಸಂಶೋಧನಾ ಯೋಜನೆಗಳು",
                    "studentResearch": "ವಿದ್ಯಾರ್ಥಿ ಸಂಶೋಧನಾ ಉಪಕ್ರಮಗಳು",
                    "capstoneProjects": "ಕ್ಯಾಪ್‌ಸ್ಟೋನ್ ಯೋಜನೆಗಳು",
                    "interdisciplinaryTeams": "ಅಂತರಶಿಸ್ತೀಯ ತಂಡಗಳು"
                },
                "research": {
                    "title": "ಸಂಶೋಧನಾ ಕೇಂದ್ರ",
                    "publications": "ಪ್ರಕಟಣೆಗಳು",
                    "datasets": "ಮುಕ್ತ ಡೇಟಾಸೆಟ್‌ಗಳು",
                    "patentFiling": "ಪೇಟೆಂಟ್ ಅರ್ಜಿಗಳು",
                    "peerReview": "ಪೀರ್ ವಿಮರ್ಶೆ ಡೈರೆಕ್ಟರಿ"
                },
                "innovation": {
                    "title": "ನಾವೀನ್ಯತೆ ಪ್ರಯೋಗಾಲಯ",
                    "innovationChallenges": "ಹ್ಯಾಕಥಾನ್‌ಗಳು ಮತ್ತು ಸವಾಲುಗಳು",
                    "hackathonDemos": "ಮಾದರಿ ಪ್ರದರ್ಶನ",
                    "incubatorReady": "ಇನ್‌ಕ್ಯುಬೇಶನ್ ಹಂತ",
                    "smartCityPrototypes": "ಸ್ಮಾರ್ಟ್ ಸಿಟಿ ಡೆಮೊಗಳು"
                },
                "credits": {
                    "title": "ಕ್ರೆಡಿಟ್‌ಗಳು ಮತ್ತು ಮನ್ನಣೆ",
                    "creditsEarned": "ಗಳಿಸಿದ ಕ್ರೆಡಿಟ್‌ಗಳು",
                    "skillBadges": "ಕೌಶಲ್ಯ ಬ್ಯಾಡ್ಜ್‌ಗಳು",
                    "hallOfFame": "ಹಾಲ್ ಆಫ್ ಫೇಮ್",
                    "transcriptVerification": "ಪರಿಶೀಲಿಸಿದ ಟ್ರಾನ್ಸ್‌ಕ್ರಿಪ್ಟ್"
                },
                "repository": {
                    "title": "ಶೈಕ್ಷಣಿಕ ಭಂಡಾರ",
                    "researchPapersArchive": "ಸಂಶೋಧನಾ ಪ್ರಬಂಧಗಳ ಆರ್ಕೈವ್",
                    "openDataVault": "ಮುಕ್ತ ಡೇಟಾ ವಾಲ್ಟ್",
                    "citationIndex": "ಸೈಟೇಶನ್ ಇಂಡೆಕ್ಸ್"
                },
                "settings": {
                    "title": "ವಿಶ್ವವಿದ್ಯಾಲಯದ ಸಂಯೋಜನೆಗಳು",
                    "facultyProfile": "ಸಾಂಸ್ಥಿಕ ಪ್ರೊಫೈಲ್",
                    "departmentAffiliation": "ಇಲಾಖಾ ಸಂಬಂಧ",
                    "orcidId": "ORCID / ಸಂಶೋಧಕರ ID"
                }
            }
        },
        "admin": {
            "portalTitle": "ಕೇಂದ್ರ ಕಮಾಂಡ್ ಮತ್ತು ಪ್ಲಾಟ್‌ಫಾರ್ಮ್ ಆಡಳಿತ",
            "dashboard": {
                "title": "ಪ್ಲಾಟ್‌ಫಾರ್ಮ್ ಆಡಳಿತ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್",
                "totalSystemUsers": "ಒಟ್ಟು ನೋಂದಾಯಿತ ಬಳಕೆದಾರರು",
                "activePortals": "ಸಕ್ರಿಯ ಪೋರ್ಟಲ್‌ಗಳು",
                "aiModelStatus": "AI ಮಾದರಿ ಆರೋಗ್ಯ",
                "databaseHealth": "ಡೇಟಾಬೇಸ್ ಸುಪ್ತತೆ",
                "unresolvedGrievances": "ಪರಿಹರಿಸದ ದೂರುಗಳು",
                "platformLoad": "ಸರ್ವರ್ ಲೋಡ್",
                "liveEventStream": "ಲೈವ್ ಆಡಿಟ್ ಸ್ಟ್ರೀಮ್",
                "rootConsole": "ರೂಟ್ ಕನ್ಸೋಲ್",
                "cpuUsage": "CPU ಬಳಕೆ",
                "dbLatency": "ಡೇಟಾಬೇಸ್ ಸುಪ್ತತೆ",
                "uptime": "ಸಿಸ್ಟಮ್ ಅಪ್‌ಟೈಮ್"
            },
            "users": {
                "title": "ಬಳಕೆದಾರ ಮತ್ತು ಪಾತ್ರ ನಿರ್ವಹಣೆ",
                "allUsers": "ಎಲ್ಲಾ ಬಳಕೆದಾರರು",
                "addUser": "ಬಳಕೆದಾರರನ್ನು ಸೇರಿಸಿ",
                "editRole": "ಪಾತ್ರವನ್ನು ಮಾರ್ಪಡಿಸಿ",
                "suspendUser": "ಖಾತೆಯನ್ನು ಅಮಾನತುಗೊಳಿಸಿ",
                "resetPassword": "ಪಾಸ್‌ವರ್ಡ್ ಮರುಹೊಂದಿಸಿ",
                "roleFilter": "ಪಾತ್ರದ ಮೂಲಕ ಫಿಲ್ಟರ್ ಮಾಡಿ",
                "searchUsers": "ಹೆಸರು, ಇಮೇಲ್ ಮೂಲಕ ಹುಡುಕಿ..."
            },
            "roles": {
                "title": "ಪಾತ್ರ ಮತ್ತು ಅನುಮತಿಗಳ ನಿರ್ವಹಣೆ",
                "permissionsMatrix": "ಪ್ರವೇಶ ನಿಯಂತ್ರಣ ಮ್ಯಾಟ್ರಿಕ್ಸ್",
                "accessControl": "ಭದ್ರತಾ ನೀತಿಗಳು",
                "createRole": "ಹೊಸ ಪಾತ್ರವನ್ನು ರಚಿಸಿ",
                "customRoles": "ಕಸ್ಟಮ್ ಪಾತ್ರಗಳು"
            },
            "government": {
                "title": "ಪುರಸಭಾ ಆಡಳಿತ ನಿಯಂತ್ರಣ",
                "municipalBOD": "ಪುರಸಭಾ ಸಂಸ್ಥೆಗಳು",
                "cityDistricts": "ಜಿಲ್ಲಾ ವ್ಯಾಪ್ತಿಗಳು",
                "assignWardEngineers": "ವಾರ್ಡ್ ಎಂಜಿನಿಯರ್‌ಗಳನ್ನು ನೇಮಿಸಿ"
            },
            "universities": {
                "title": "ವಿಶ್ವವಿದ್ಯಾಲಯ ಮಾನ್ಯತೆ ನಿರ್ವಹಣೆ",
                "registeredCampuses": "ಸಂಯೋಜಿತ ವಿಶ್ವವಿದ್ಯಾಲಯಗಳು",
                "accreditationVerify": "NAAC / UGC ಪರಿಶೀಲನೆ",
                "studentCap": "ದಾಖಲಾತಿ ಕೋಟಾ"
            },
            "industry": {
                "title": "ಉದ್ಯಮ ಪಾಲುದಾರರ ಮೇಲ್ವಿಚಾರಣೆ",
                "corporatePartners": "ನೋಂದಾಯಿತ CSR ಪಾಲುದಾರರು",
                "csrValidation": "ಸೆಕ್ಷನ್ 135 ಅರ್ಹತೆ ಪರಿಶೀಲನೆ",
                "escrowAudits": "ಎಸ್ಕ್ರೋ ಆಡಿಟ್ ಪರಿಶೀಲನೆ"
            },
            "ngos": {
                "title": "ಎನ್‌ಜಿಒ ಮೇಲ್ವಿಚಾರಣೆ",
                "verifiedNgos": "ಮಾನ್ಯತೆ ಪಡೆದ ಎನ್‌ಜಿಒಗಳು",
                "darpanCheck": "ಎನ್‌ಜಿಒ ದರ್ಪಣ್ ಪರಿಶೀಲನೆ",
                "groundClearance": "ಕ್ಷೇತ್ರ ಅನುಮತಿಗಳು"
            },
            "research": {
                "title": "ಸಂಶೋಧನಾ ಸಂಸ್ಥೆಗಳ ಮೇಲ್ವಿಚಾರಣೆ",
                "institutePartnerships": "ಸಂಶೋಧನಾ ಪಾಲುದಾರರು",
                "ethicsClearance": "ಎಥಿಕ್ಸ್ ರಿವ್ಯೂ ಬೋರ್ಡ್",
                "datasetAccess": "ಡೇಟಾ ಪ್ರವೇಶ ಅನುಮತಿಗಳು"
            },
            "departments": {
                "title": "ಇಲಾಖಾ ಮಾಸ್ಟರ್ ಸಂರಚನೆ",
                "routingRules": "ಸ್ವಯಂಚಾಲಿತ ರೂಟಿಂಗ್ ನಿಯಮಗಳು",
                "autoAssignmentEngine": "AI ರವಾನೆ ಎಂಜಿನ್",
                "fallbackQueues": "ಫಾಲ್‌ಬ್ಯಾಕ್ ಸರತಿಗಳು"
            },
            "issues": {
                "title": "ಪ್ಲಾಟ್‌ಫಾರ್ಮ್ ದೂರುಗಳ ನಿರ್ವಹಣೆ",
                "forceResolve": "ಆಡಳಿತಾತ್ಮಕ ಪರಿಹಾರ",
                "reassignCluster": "ಸಮಸ್ಯೆ ಕ್ಲಸ್ಟರ್ ಮರುನಿಯೋಜಿಸಿ",
                "auditLog": "ಕ್ರಿಯೆಗಳ ಲಾಗ್",
                "purgeTestData": "ಪರೀಕ್ಷಾ ಡೇಟಾ ತೆರವುಗೊಳಿಸಿ"
            },
            "aiMonitoring": {
                "title": "AI ದೃಷ್ಟಿ ಮತ್ತು ಟೆಲಿಮೆಟ್ರಿ ಮೇಲ್ವಿಚಾರಣೆ",
                "geminiVisionUptime": "ದೃಷ್ಟಿ ಮಾದರಿ ಅಪ್‌ಟೈಮ್",
                "fastApiOcrStatus": "FastAPI OCR ಪೈಪ್‌ಲೈನ್",
                "speechToTextLatency": "STT ಸುಪ್ತತೆ",
                "accuracyScore": "ನಿಖರತೆಯ ಅಂಕ",
                "confidenceDistribution": "ವಿಶ್ವಾಸಾರ್ಹತೆಯ ವಿತರಣೆ",
                "modelLogs": "ಸುಪ್ತತೆಯ ಲಾಗ್‌ಗಳು"
            },
            "workflowMonitoring": {
                "title": "ವರ್ಕ್‌ಫ್ಲೋ ಮತ್ತು ಸರತಿ ಟೆಲಿಮೆಟ್ರಿ",
                "stateMachineInspect": "ಸ್ಥಿತಿ ಬದಲಾವಣೆಗಳು",
                "queueDepth": "ಸಂದೇಶ ಸರದಿಯ ಆಳ",
                "deadLetterQueue": "ಡೆಡ್-ಲೆಟರ್ ಸರತಿ",
                "retryFailedTasks": "ವಿಫಲ ಕಾರ್ಯಗಳನ್ನು ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ"
            },
            "analytics": {
                "title": "ಪ್ಲಾಟ್‌ಫಾರ್ಮ್ ವಿಶ್ಲೇಷಣೆ",
                "crossPortalActivity": "ಬಳಕೆಯ ಮೆಟ್ರಿಕ್‌ಗಳು",
                "municipalPerformanceIndex": "ಪುರಸಭೆಯ ಕಾರ್ಯಕ್ಷಮತೆ ಸೂಚ್ಯಂಕ",
                "peakUsageHours": "ಗರಿಷ್ಠ ಬಳಕೆಯ ಸಮಯ"
            },
            "systemHealth": {
                "title": "ಮೂಲಸೌಕರ್ಯ ಮತ್ತು ಸಿಸ್ಟಮ್ ಆರೋಗ್ಯ",
                "databaseReplicas": "ಡೇಟಾಬೇಸ್ ಪ್ರತಿಗಳು",
                "redisCache": "ರೆಡಿಸ್ ಮೆಮೊರಿ ಸ್ಥಿತಿ",
                "storageUsage": "ಸಂಗ್ರಹಣಾ ಪ್ರಮಾಣ",
                "apiGateways": "ಮೈಕ್ರೋಸರ್ವಿಸ್ ಆರೋಗ್ಯ",
                "uptime99": "99.98% ಲಭ್ಯತೆ",
                "online": "ಆನ್‌ಲೈನ್",
                "maintenance": "ನಿರ್ವಹಣೆ"
            },
            "settings": {
                "title": "ಪ್ಲಾಟ್‌ಫಾರ್ಮ್ ಸಂಯೋಜನೆಗಳು",
                "maintenanceMode": "ನಿರ್ವಹಣಾ ಮೋಡ್",
                "apiRateLimits": "API ದರ ಮಿತಿಗಳು",
                "backupSchedules": "ಬ್ಯಾಕಪ್ ವೇಳಾಪಟ್ಟಿ",
                "smtpConfig": "SMTP ಮತ್ತು ಇಮೇಲ್ ಗೇಟ್‌ವೇಗಳು"
            }
        },
        "toast": {
            "issueSubmitted": "ದೂರನ್ನು ಯಶಸ್ವಿಯಾಗಿ ಸಲ್ಲಿಸಲಾಗಿದೆ! ಜವಾಬ್ದಾರಿಯುತ ಇಲಾಖೆಗೆ ರವಾನಿಸಲಾಗಿದೆ.",
            "gpsCaptured": "GPS ನಿರ್ದೇಶಾಂಕಗಳನ್ನು ಸೆರೆಹಿಡಿಯಲಾಗಿದೆ",
            "gpsCapturedDesc": "ನಿರ್ದೇಶಾಂಕಗಳನ್ನು ದೂರಿನ ವರದಿಯೊಂದಿಗೆ ಲಿಂಕ್ ಮಾಡಲಾಗಿದೆ.",
            "locationDenied": "ಸ್ಥಳದ ಅನುಮತಿ ನಿರಾಕರಿಸಲಾಗಿದೆ. ಡೀಫಾಲ್ಟ್ ಸ್ಥಳವನ್ನು ಬಳಸಲಾಗುತ್ತಿದೆ.",
            "fileSizeExceeded": "ಫೈಲ್ ಗಾತ್ರವು 25MB ಮಿತಿಯನ್ನು ಮೀರಿದೆ.",
            "audioNotSupported": "ಈ ಬ್ರೌಸರ್‌ನಲ್ಲಿ ಆಡಿಯೋ ರೆಕಾರ್ಡಿಂಗ್ ಬೆಂಬಲಿಸುವುದಿಲ್ಲ.",
            "micSimulation": "ಧ್ವನಿ ದೂರು ಡೆಮೊಗಾಗಿ ಮೈಕ್ರೊಫೋನ್ ಸಿಮ್ಯುಲೇಶನ್ ಸಕ್ರಿಯವಾಗಿದೆ.",
            "profileUpdated": "ಪ್ರೊಫೈಲ್ ಯಶಸ್ವಿಯಾಗಿ ನವೀಕರಿಸಲಾಗಿದೆ.",
            "settingsSaved": "ಆದ್ಯತೆಗಳನ್ನು ಯಶಸ್ವಿಯಾಗಿ ಉಳಿಸಲಾಗಿದೆ.",
            "deleteRequested": "ಖಾತೆ ಅಳಿಸುವಿಕೆಯ ವಿನಂತಿಯನ್ನು ಸಲ್ಲಿಸಲಾಗಿದೆ.",
            "languageChanged": "ಭಾಷೆಯನ್ನು ಯಶಸ್ವಿಯಾಗಿ ಬದಲಾಯಿಸಲಾಗಿದೆ.",
            "errorOccurred": "ದೋಷ ಸಂಭವಿಸಿದೆ. ದಯವಿಟ್ಟು ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.",
            "caseUpdated": "ಪ್ರಕರಣದ ವಿವರಗಳನ್ನು ನವೀಕರಿಸಲಾಗಿದೆ.",
            "caseReassigned": "ಪ್ರಕರಣವನ್ನು ನೋಡಲ್ ಅಧಿಕಾರಿಗೆ ಮರುನಿಯೋಜಿಸಲಾಗಿದೆ.",
            "caseResolved": "ದೂರನ್ನು ಪರಿಹರಿಸಲಾಗಿದೆ ಎಂದು ಗುರುತಿಸಲಾಗಿದೆ.",
            "volunteerAdded": "ಹೊಸ ಸ್ವಯಂಸೇವಕರನ್ನು ಯಶಸ್ವಿಯಾಗಿ ನೋಂದಾಯಿಸಲಾಗಿದೆ.",
            "grantApproved": "CSR ಅನುದಾನ ಹಂಚಿಕೆಯನ್ನು ಅನುಮೋದಿಸಲಾಗಿದೆ.",
            "milestoneApproved": "ಶೈಕ್ಷಣಿಕ ಮೈಲಿಗಲ್ಲನ್ನು ಅನುಮೋದಿಸಲಾಗಿದೆ.",
            "deliverableUploaded": "ಫಲಿತಾಂಶವನ್ನು ಪರಿಶೀಲನೆಗಾಗಿ ಅಪ್‌ಲೋಡ್ ಮಾಡಲಾಗಿದೆ.",
            "loginSuccess": "ಯಶಸ್ವಿಯಾಗಿ ಸೈನ್ ಇನ್ ಮಾಡಲಾಗಿದೆ. ಸುಸ್ವಾಗತ!",
            "logoutSuccess": "ಯಶಸ್ವಿಯಾಗಿ ಲಾಗ್ ಔಟ್ ಮಾಡಲಾಗಿದೆ.",
            "accessDenied": "ಪ್ರವೇಶ ನಿರ್ಬಂಧಿಸಲಾಗಿದೆ. ಸಾಕಷ್ಟು ಅನುಮತಿಗಳಿಲ್ಲ.",
            "changesSaved": "ಎಲ್ಲಾ ಬದಲಾವಣೆಗಳನ್ನು ಯಶಸ್ವಿಯಾಗಿ ಉಳಿಸಲಾಗಿದೆ.",
            "reportExported": "ವರದಿಯನ್ನು ರಚಿಸಲಾಗಿದೆ ಮತ್ತು ಡೌನ್‌ಲೋಡ್ ಮಾಡಲಾಗಿದೆ.",
            "dataRefreshed": "ಟೆಲಿಮೆಟ್ರಿ ಡೇಟಾ ರಿಫ್ರೆಶ್ ಆಗಿದೆ."
        },
        "language": "ಭಾಷೆ",
        "dashboard": "ಡ್ಯಾಶ್‌ಬೋರ್ಡ್",
        "report_issue": "ಸಮಸ್ಯೆಯನ್ನು ವರದಿ ಮಾಡಿ",
        "report_problem": "ಸಮಸ್ಯೆಯನ್ನು ವರದಿ ಮಾಡಿ",
        "my_issues": "ನನ್ನ ದೂರುಗಳು",
        "track_issues": "ಪರಿಹಾರವನ್ನು ಟ್ರ್ಯಾಕ್ ಮಾಡಿ",
        "notifications": "ಅಧಿಸೂಚನೆಗಳು",
        "profile": "ಪ್ರೊಫೈಲ್",
        "settings": "ಸಂಯೋಜನೆಗಳು",
        "help": "ಸಹಾಯ ಮತ್ತು ಬೆಂಬಲ",
        "logout": "ಲಾಗ್ ಔಟ್",
        "login": "ಲಾಗ್ ಇನ್",
        "recent_grievances": "ಇತ್ತೀಚಿನ ದೂರುಗಳು",
        "issue_id": "ದೂರು ID",
        "citizen_portal": "ನಾಗರಿಕ ಪೋರ್ಟಲ್",
        "government_portal": "ಸರ್ಕಾರಿ ಪೋರ್ಟಲ್",
        "university_portal": "ವಿಶ್ವವಿದ್ಯಾಲಯ ಪೋರ್ಟಲ್",
        "industry_portal": "ಉದ್ಯಮ ಪೋರ್ಟಲ್",
        "ngo_portal": "ಎನ್‌ಜಿಒ ಪೋರ್ಟಲ್",
        "admin_portal": "ಅಡ್ಮಿನ್ ಪೋರ್ಟಲ್",
        "ai_governance_insight": "AI ಆಡಳಿತ ಒಳನೋಟ",
        "resolution": "ಪರಿಹಾರ",
        "report": "ವರದಿಗಳು",
        "map": "ಘಟನೆಯ ನಕ್ಷೆ",
        "search": "ಹುಡುಕಿ",
        "search_placeholder": "ದೂರುಗಳು, ಪ್ರಕರಣಗಳು, ಸ್ಥಳಗಳನ್ನು ಹುಡುಕಿ...",
        "filter": "ಫಿಲ್ಟರ್",
        "save": "ಉಳಿಸಿ",
        "cancel": "ರದ್ದುಮಾಡಿ",
        "delete": "ಅಳಿಸಿ",
        "submit": "ಸಲ್ಲಿಸಿ",
        "upload": "ಅಪ್‌ಲೋಡ್ ಮಾಡಿ",
        "location": "ಸ್ಥಳ",
        "description": "ವಿವರಣೆ",
        "title": "ಶೀರ್ಷಿಕೆ",
        "category": "ವರ್ಗ",
        "department": "ಇಲಾಖೆ",
        "created_at": "ವರದಿ ಮಾಡಿದ ದಿನಾಂಕ",
        "action": "ಕ್ರಿಯೆ",
        "actions": "ಕ್ರಿಯೆಗಳು",
        "view": "ವೀಕ್ಷಿಸಿ",
        "edit": "ತಿದ್ದು",
        "loading": "ಲೋಡ್ ಆಗುತ್ತಿದೆ...",
        "success": "ಯಶಸ್ಸು",
        "error": "ದೋಷ ಸಂಭವಿಸಿದೆ",
        "welcome_back": "ಮರಳಿ ಸುಸ್ವಾಗತ",
        "total_issues": "ಒಟ್ಟು ದೂರುಗಳು",
        "resolved_issues": "ಪರಿಹರಿಸಲಾದ ದೂರುಗಳು",
        "in_progress_issues": "ಪ್ರಗತಿಯಲ್ಲಿರುವ ದೂರುಗಳು",
        "pending_issues": "ಬಾಕಿ ಉಳಿದಿರುವ ದೂರುಗಳು",
        "active_projects": "ಸಕ್ರಿಯ ಯೋಜನೆಗಳು",
        "ai_accuracy": "AI ರೂಟಿಂಗ್ ನಿಖರತೆ",
        "sla_compliance": "SLA ಅನುಸರಣೆ ದರ",
        "civic_engagement": "ನಾಗರಿಕ ತೊಡಗಿಸಿಕೊಳ್ಳುವಿಕೆ ಸೂಚ್ಯಂಕ",
        "recent_activity": "ಇತ್ತೀಚಿನ ಚಟುವಟಿಕೆ",
        "quick_actions": "ತ್ವರಿತ ಕ್ರಿಯೆಗಳು",
        "live_incidents": "ಲೈವ್ ನಾಗರಿಕ ಘಟನೆಗಳು",
        "all": "ಎಲ್ಲವೂ",
        "high": "ಹೆಚ್ಚಿನ ಆದ್ಯತೆ",
        "medium": "ಮಧ್ಯಮ ಆದ್ಯತೆ",
        "low": "ಕಡಿಮೆ ಆದ್ಯತೆ",
        "critical": "ನಿರ್ಣಾಯಕ ಆದ್ಯತೆ",
        "emergency": "ತುರ್ತು ಆದ್ಯತೆ",
        "pending": "ಬಾಕಿ ಉಳಿದಿದೆ",
        "in_progress": "ಪ್ರಗತಿಯಲ್ಲಿದೆ",
        "resolved": "ಪರಿಹರಿಸಲಾಗಿದೆ",
        "closed": "ಮುಚ್ಚಲಾಗಿದೆ",
        "rejected": "ತಿರಸ್ಕರಿಸಲಾಗಿದೆ",
        "approved": "ಅನುಮೋದಿಸಲಾಗಿದೆ",
        "declined": "ತಿರಸ್ಕರಿಸಲಾಗಿದೆ",
        "export": "ಡೇಟಾ ರಫ್ತು ಮಾಡಿ",
        "download": "ಡೌನ್‌ಲೋಡ್",
        "confirm": "ದೃಢೀಕರಿಸಿ",
        "close": "ಮುಚ್ಚಿ",
        "back": "ಹಿಂದಕ್ಕೆ",
        "next": "ಮುಂದೆ",
        "previous": "ಹಿಂದಿನ",
        "no_results": "ಯಾವುದೇ ಫಲಿತಾಂಶಗಳು ಕಂಡುಬಂದಿಲ್ಲ",
        "view_all": "ಎಲ್ಲವನ್ನೂ ವೀಕ್ಷಿಸಿ",
        "home": "ಮುಖಪುಟ",
        "feed": "ನಾಗರಿಕ ಫೀಡ್",
        "analytics": "AI ವಿಶ್ಲೇಷಣೆ",
        "optional": "ಐಚ್ಛಿಕ",
        "faculty": "ಅಧ್ಯಾಪಕರು",
        "student": "ವಿದ್ಯಾರ್ಥಿ",
        "projects": "ಯೋಜನೆಗಳು",
        "research": "ಸಂಶೋಧನಾ ಕೇಂದ್ರ",
        "innovation": "ನಾವೀನ್ಯತೆ ಸವಾಲುಗಳು",
        "teams": "ತಂಡಗಳು",
        "credits": "ಶೈಕ್ಷಣಿಕ ಕ್ರೆಡಿಟ್‌ಗಳು",
        "officers": "ಅಧಿಕಾರಿಗಳು",
        "assigned": "ನಿಯೋಜಿಸಲಾದವು",
        "under_review": "ಪರಿಶೀಲನೆಯಲ್ಲಿದೆ",
        "industry_assigned": "ಉದ್ಯಮಕ್ಕೆ ನಿಯೋಜಿಸಲಾಗಿದೆ",
        "industry_review": "ಉದ್ಯಮ ಪರಿಶೀಲನೆ",
        "univ_assigned": "ವಿಶ್ವವಿದ್ಯಾಲಯಕ್ಕೆ ನಿಯೋಜಿಸಲಾಗಿದೆ",
        "student_dev": "ವಿದ್ಯಾರ್ಥಿ ಅಭಿವೃದ್ಧಿ",
        "faculty_review": "ಅಧ್ಯಾಪಕರ ಪರಿಶೀಲನೆ",
        "industry_val": "ಉದ್ಯಮ ಮೌಲ್ಯೀಕರಣ",
        "inspection": "ಸ್ಥಳ ತಪಾಸಣೆ",
        "feedback": "ಪ್ರತಿಕ್ರಿಯೆ ಬಾಕಿಯಿದೆ"
    }
