# -*- coding: utf-8 -*-
"""Bengali (bn) translations dictionary for SOCIAL-X platform"""

def get_bn_dict():
    return {
    "nav": {
        "overview": "সংক্ষিপ্ত বিবরণ",
        "access_identity": "প্রবেশাধিকার এবং পরিচয়",
        "stakeholder_ecosystem": "অংশীদার ইকোসিস্টেম",
        "operations_ai": "অপারেশনস এবং এআই",
        "infra_observability": "অবকাঠামো ও পর্যবেক্ষণ",
        "field_activities": "মাঠপর্যায়ের কার্যক্রম ও ত্রাণ",
        "community_workforce": "সম্প্রদায় ও কর্মীবাহিনী",
        "governance_comms": "প্রশাসন ও যোগাযোগ",
        "csr_investment": "সিএসআর ও মূলধন বরাদ্দ",
        "collaboration_rd": "সহযোগিতা ও গবেষণা",
        "student_portal": "শিক্ষার্থী পোর্টাল",
        "faculty_portal": "অনুষদ পোর্টাল",
        "dashboard": "ড্যাশবোর্ড",
        "my_issues": "আমার অভিযোগসমূহ",
        "report_problem": "অভিযোগ দায়ের করুন",
        "track_issues": "সমাধান ট্র্যাক করুন",
        "notifications": "বিজ্ঞপ্তি",
        "profile": "প্রোফাইল",
        "settings": "সেটিংস",
        "help": "সাহায্য ও সমর্থন",
        "logout": "লগ আউট",
        "login": "লগ ইন",
        "analytics": "অ্যানালিটিক্স ও রিপোর্ট",
        "assigned_cases": "বরাদ্দকৃত মামলা",
        "departments": "বিভাগসমূহ",
        "officers": "কর্মকর্তা ডিরেক্টরি",
        "ai_suggestions": "এআই পরামর্শ",
        "reports": "রিপোর্ট ও অডিট",
        "projects": "উপলব্ধ প্রকল্প",
        "funding": "তহবিলের সুযোগ",
        "csr_analytics": "সিএসআর অ্যানালিটিক্স",
        "mentorship": "পরামর্শদান (মেন্টরশিপ)",
        "university_collaboration": "বিশ্ববিদ্যালয় সহযোগিতা",
        "research": "গবেষণা উদ্যোগ",
        "prototypes": "প্রোটোটাইপ ও ডেমো",
        "volunteers": "স্বেচ্ছাসেবক স্কোয়াড",
        "field_log": "মাঠপর্যায়ের প্রমাণ লগ",
        "impact": "সম্প্রদায় প্রভাব",
        "certificates": "শংসাপত্র ও ব্যাজ",
        "lab_tasks": "ল্যাব কার্যাবলী",
        "upload_deliverables": "ফলাফল আপলোড করুন",
        "milestone_timeline": "মাইলফলক টাইমলাইন",
        "advisor_discussion": "উপদেষ্টা আলোচনা",
        "milestone_approvals": "মাইলফলক অনুমোদন",
        "municipal_proposals": "পৌর প্রস্তাবনা",
        "teams": "দল ও রোস্টার",
        "credits": "অ্যাকাডেমিক ক্রেডিট",
        "user_management": "ব্যবহারকারী ব্যবস্থাপনা",
        "role_management": "ভূমিকা ব্যবস্থাপনা",
        "government_management": "সরকারি প্রশাসন ব্যবস্থাপনা",
        "university_management": "বিশ্ববিদ্যালয় ব্যবস্থাপনা",
        "industry_management": "শিল্প ব্যবস্থাপনা",
        "ngo_management": "এনজিও ব্যবস্থাপনা",
        "research_organizations": "গবেষণা সংস্থা",
        "issue_management": "অভিযোগ ব্যবস্থাপনা",
        "ai_monitoring": "এআই টেলিমেট্রি পর্যবেক্ষণ",
        "workflow_monitoring": "ওয়ার্কফ্লো পর্যবেক্ষণ",
        "audit_logs": "অপরিবর্তনীয় অডিট ট্রেইল",
        "system_health": "সিস্টেমের স্বাস্থ্য",
        "landing_features": "বৈশিষ্ট্যসমূহ",
        "landing_how_it_works": "এটি কীভাবে কাজ করে",
        "landing_about": "আমাদের সম্পর্কে",
        "landing_faq": "সাধারণ প্রশ্নোত্তর (FAQ)",
        "landing_contact": "যোগাযোগ",
        "role_login": "রোল ভিত্তিক লগইন",
        "citizen_sign_up": "নাগরিক নিবন্ধন"
    },
    "common": {
        "buttons": {
            "browseFiles": "ফাইল ব্রাউজ করুন",
            "openCamera": "ক্যামেরা খুলুন",
            "startRecording": "রেকর্ডিং শুরু করুন",
            "stopRecording": "রেকর্ডিং বন্ধ করুন",
            "submit": "জমা দিন",
            "cancel": "বাতিল করুন",
            "save": "সংরক্ষণ করুন",
            "delete": "মুছুন",
            "search": "অনুসন্ধান করুন",
            "filter": "ফিল্টার",
            "upload": "আপলোড করুন",
            "confirm": "নিশ্চিত করুন",
            "close": "বন্ধ করুন",
            "back": "পেছনে",
            "next": "পরবর্তী",
            "previous": "পূর্ববর্তী",
            "detectLocation": "বর্তমান অবস্থান সনাক্ত করুন",
            "useCurrentGps": "বর্তমান জিপিএস ব্যবহার করুন",
            "resetForm": "ফর্ম রিসেট করুন",
            "submitIssue": "অভিযোগ জমা দিন",
            "viewAll": "সব দেখুন",
            "export": "তথ্য রপ্তানি করুন",
            "download": "ডাউনলোড",
            "refresh": "রিফ্রেশ",
            "login": "লগ ইন",
            "logout": "লগ আউট",
            "modifyUploads": "আপলোড পরিবর্তন করুন",
            "removeFile": "ফাইল সরান",
            "removeVoiceMemo": "ভয়েস মেমো সরান",
            "edit": "সম্পাদনা করুন",
            "view": "বিবরণ দেখুন",
            "add": "নতুন যোগ করুন",
            "create": "তৈরি করুন",
            "update": "আপডেট করুন",
            "approve": "অনুমোদন করুন",
            "reject": "প্রত্যাখ্যান করুন",
            "reassign": "পুনরায় বরাদ্দ করুন",
            "escalate": "উচ্চপদস্থ কর্মকর্তার কাছে পাঠান",
            "resolve": "মামলা নিষ্পত্তি করুন",
            "assign": "বরাদ্দ করুন",
            "verify": "যাচাই করুন",
            "downloadReport": "রিপোর্ট ডাউনলোড করুন",
            "syncTelemetry": "টেলিমেট্রি সিঙ্ক করুন",
            "applyFilters": "ফিল্টার প্রয়োগ করুন",
            "clearFilters": "ফিল্টার সাফ করুন",
            "viewDetails": "বিস্তারিত দেখুন",
            "sendNotification": "বিজ্ঞপ্তি পাঠান",
            "inviteMember": "সদস্য আমন্ত্রণ জানান",
            "print": "প্রিন্ট করুন",
            "share": "শেয়ার করুন",
            "copyLink": "লিঙ্ক কপি করুন",
            "proceed": "এগিয়ে যান",
            "retry": "পুনরায় চেষ্টা করুন",
            "dismiss": "খারিজ করুন",
            "accept": "গ্রহণ করুন",
            "decline": "প্রত্যাখ্যান করুন"
        },
        "labels": {
            "dashboard": "ড্যাশবোর্ড",
            "profile": "প্রোফাইল",
            "settings": "সেটিংস",
            "notifications": "বিজ্ঞপ্তি",
            "help": "সাহায্য ও সমর্থন",
            "logout": "লগ আউট",
            "login": "লগ ইন",
            "status": "অবস্থা",
            "priority": "অগ্রাধিকার",
            "department": "বিভাগ",
            "category": "বিভাগ / বিভাগীয় শ্রেণী",
            "district": "জেলা",
            "ward": "ওয়ার্ড",
            "address": "ঠিকানা",
            "landmark": "ল্যান্ডমার্ক / দর্শনীয় স্থান",
            "title": "শিরোনাম",
            "description": "বর্ণনা",
            "location": "অবস্থান",
            "latitude": "অক্ষাংশ",
            "longitude": "দ্রাঘিমাংশ",
            "accuracy": "নির্ভুলতা",
            "date": "তারিখ",
            "action": "পদক্ষেপ",
            "actions": "পদক্ষেপসমূহ",
            "all": "সমস্ত",
            "high": "উচ্চ",
            "medium": "মাঝারি",
            "low": "কম",
            "critical": "সংকটাপন্ন",
            "emergency": "জরুরি",
            "pending": "বিচারাধীন",
            "inProgress": "চলমান",
            "resolved": "নিষ্পত্তি হয়েছে",
            "closed": "বন্ধ",
            "rejected": "প্রত্যাখ্যাত",
            "verified": "যাচাইকৃত",
            "assigned": "বরাদ্দকৃত",
            "recentActivity": "সাম্প্রতিক কার্যকলাপ",
            "quickActions": "দ্রুত পদক্ষেপ",
            "systemHealth": "সিস্টেম স্বাস্থ্য",
            "language": "ভাষা",
            "selectLanguage": "ভাষা নির্বাচন করুন",
            "searchLanguage": "ভাষা খুঁজুন...",
            "editable": "সম্পাদনাযোগ্য",
            "active": "সক্রিয়",
            "inactive": "নিষ্ক্রিয়",
            "completed": "সম্পন্ন",
            "failed": "ব্যর্থ",
            "total": "মোট",
            "count": "গণনা",
            "rate": "হার",
            "percentage": "শতকরা হার",
            "timeRemaining": "অবশিষ্ট সময়",
            "dueDate": "নির্দিষ্ট তারিখ",
            "submittedBy": "দাখিলকারী",
            "assignedTo": "বরাদ্দকৃত ব্যক্তি",
            "officerInCharge": "দায়িত্বপ্রাপ্ত কর্মকর্তা",
            "slaTimer": "এসএলএ টাইমার",
            "auditTimeline": "অডিট টাইমলাইন",
            "contactInfo": "যোগাযোগের তথ্য",
            "phoneNumber": "ফোন নম্বর",
            "emailAddress": "ইমেল ঠিকানা",
            "fullName": "সম্পূর্ণ নাম",
            "role": "ভূমিকা",
            "organization": "সংস্থা",
            "institution": "শিক্ষা প্রতিষ্ঠান",
            "createdAt": "তৈরির তারিখ",
            "updatedAt": "আপডেটের তারিখ"
        },
        "status": {
            "open": "উন্মুক্ত",
            "submitted": "দাখিল করা হয়েছে",
            "verified": "যাচাইকৃত",
            "assigned": "বরাদ্দকৃত",
            "in_progress": "চলমান",
            "inProgress": "চলমান",
            "resolved": "নিষ্পত্তি হয়েছে",
            "closed": "বন্ধ",
            "rejected": "প্রত্যাখ্যাত",
            "under_review": "পর্যালোচনাধীন",
            "under_government_review": "সরকারি পর্যালোচনাধীন",
            "assigned_to_government": "পৌরসভায় পাঠানো হয়েছে",
            "assigned_to_industry": "শিল্প অংশীদারের কাছে পাঠানো হয়েছে",
            "industry_review": "শিল্প পর্যালোচনা",
            "assigned_to_university": "বিশ্ববিদ্যালয়ে পাঠানো হয়েছে",
            "student_development": "শিক্ষার্থী উন্নয়ন কার্য",
            "faculty_review": "অনুষদ পর্যালোচনা",
            "industry_validation": "শিল্প বৈধকরণ",
            "inspection": "পরিদর্শন",
            "feedback_pending": "প্রতিক্রিয়া অপেক্ষমাণ",
            "escalated": "উচ্চস্তরে পাঠানো হয়েছে",
            "active": "সক্রিয়",
            "inactive": "নিষ্ক্রিয়",
            "completed": "সম্পন্ন",
            "approved": "অনুমোদিত",
            "declined": "প্রত্যাখ্যাত",
            "pending": "বিচারাধীন"
        },
        "priority": {
            "low": "কম অগ্রাধিকার",
            "medium": "মাঝারি অগ্রাধিকার",
            "high": "উচ্চ অগ্রাধিকার",
            "critical": "সংকটাপন্ন অগ্রাধিকার",
            "emergency": "জরুরি অগ্রাধিকার",
            "urgent": "অতীব জরুরি"
        },
        "departments": {
            "waterSupply": "পানি সরবরাহ ও পয়ঃনিষ্কাশন",
            "roadsTransport": "সড়ক ও পরিবহন ব্যবস্থাপনা",
            "electricityPower": "বিদ্যুৎ ও শক্তি গ্রিড",
            "solidWaste": "কঠিন বর্জ্য ব্যবস্থাপনা",
            "publicHealth": "জনস্বাস্থ্য ও পরিচ্ছন্নতা",
            "urbanPlanning": "নগর পরিকল্পনা ও উন্নয়ন",
            "education": "শিক্ষা ও দক্ষতা উন্নয়ন",
            "environmentForest": "পরিবেশ ও বন সংরক্ষণ",
            "policeSafety": "পুলিশ ও নাগরিক নিরাপত্তা",
            "disasterManagement": "দুর্যোগ ব্যবস্থাপনা ও অগ্নিনির্বাপণ",
            "municipalAdmin": "সাধারণ পৌর প্রশাসন"
        },
        "categories": {
            "water": "পানি সরবরাহ ও ফুটো",
            "roads": "রাস্তা ও গর্ত",
            "electricity": "বিদ্যুৎ ও সড়কবাতি",
            "waste": "বর্জ্য ও পরিচ্ছন্নতা",
            "health": "জনস্বাস্থ্য ও স্বাস্থ্যবিধি",
            "sanitation": "নর্দমা ও নিষ্কাশন",
            "infrastructure": "পৌর অবকাঠামো",
            "streetlights": "সড়কবাতি",
            "drainage": "নর্দমা",
            "potholes": "রাস্তার গর্ত",
            "traffic": "যানজট",
            "pollution": "দূষণ"
        },
        "validation": {
            "requiredField": "এই ক্ষেত্রটি পূরণ করা আবশ্যক",
            "titleRequired": "অভিযোগের শিরোনাম প্রয়োজন",
            "descriptionRequired": "বিস্তারিত বিবরণ প্রয়োজন",
            "locationRequired": "অবস্থানের স্থানাঙ্ক বা ঠিকানা প্রয়োজন",
            "invalidEmail": "অনুগ্রহ করে একটি বৈধ ইমেল ঠিকানা লিখুন",
            "invalidPassword": "পাসওয়ার্ড নির্দেশিকা পূরণ করতে হবে",
            "passwordTooShort": "পাসওয়ার্ড কমপক্ষে ৮ অক্ষরের হতে হবে",
            "passwordMismatch": "পাসওয়ার্ড দুটি মেলেনি",
            "unsupportedFile": "ফাইল ফরম্যাট সমর্থিত নয় (শুধুমাত্র JPG, PNG, PDF, MP4, MP3)",
            "maxFileSizeExceeded": "ফাইলের আকার ২৫ মেগাবাইটের বেশি হতে পারবে না",
            "micPermissionDenied": "মাইক্রোফোনের অনুমতি প্রত্যাখ্যাত হয়েছে",
            "cameraPermissionDenied": "ক্যামেরার অনুমতি প্রত্যাখ্যাত হয়েছে",
            "minLength": "ন্যূনতম অক্ষরের দৈর্ঘ্য পূরণ করুন",
            "maxLength": "সর্বোচ্চ অক্ষরের সীমা অতিক্রম করেছে",
            "uploadFailed": "ফাইল আপলোড ব্যর্থ হয়েছে",
            "uploadSuccessful": "ফাইল সফলভাবে আপলোড হয়েছে",
            "loginSuccessful": "সফলভাবে লগ ইন হয়েছে",
            "registrationSuccessful": "নিবন্ধন সফল হয়েছে",
            "fillRequiredFields": "অনুগ্রহ করে সমস্ত প্রয়োজনীয় ক্ষেত্র পূরণ করুন"
        },
        "emptyStates": {
            "noData": "কোনো তথ্য উপলব্ধ নেই",
            "noResults": "কোনো অনুসন্ধান ফলাফল পাওয়া যায়নি",
            "noNotifications": "কোনো নতুন বিজ্ঞপ্তি নেই",
            "noIssuesFound": "কোনো অভিযোগ পাওয়া যায়নি",
            "noProjectsFound": "কোনো প্রকল্প পাওয়া যায়নি",
            "noOfficersFound": "কোনো কর্মকর্তা পাওয়া যায়নি",
            "noActivitiesFound": "কোনো সাম্প্রতিক কার্যকলাপ পাওয়া যায়নি"
        },
        "loading": {
            "loading": "লোড হচ্ছে...",
            "pleaseWait": "অনুগ্রহ করে অপেক্ষা করুন...",
            "fetchingData": "সর্বশেষ তথ্য আনা হচ্ছে...",
            "processing": "প্রক্রিয়াকরণ চলছে...",
            "uploadingMedia": "মিডিয়া আপলোড হচ্ছে...",
            "analyzingAi": "এআই বিশ্লেষণ করছে...",
            "savingChanges": "পরিবর্তনগুলি সংরক্ষণ করা হচ্ছে..."
        },
        "pagination": {
            "previous": "পূর্ববর্তী",
            "next": "পরবর্তী",
            "page": "পৃষ্ঠা",
            "of": "এর",
            "rowsPerPage": "প্রতি পৃষ্ঠায় সারি",
            "showing": "প্রদর্শন করা হচ্ছে",
            "entries": "এন্ট্রি",
            "totalRecords": "মোট রেকর্ড"
        },
        "search": {
            "searchPlaceholder": "অভিযোগ, মামলা, অবস্থান খুঁজুন...",
            "searchGrievances": "অভিযোগ খুঁজুন...",
            "searchUsers": "ব্যবহারকারী খুঁজুন...",
            "searchDepartments": "বিভাগ খুঁজুন...",
            "searchProjects": "প্রকল্প খুঁজুন...",
            "searchOfficers": "কর্মকর্তা খুঁজুন...",
            "quickNavigator": "দ্রুত নেভিগেটর...",
            "searchAll": "প্ল্যাটফর্মে সবকিছু খুঁজুন..."
        }
    },
    "ai": {
        "processing": "এআই প্রক্রিয়াকরণ",
        "ocrResult": "ওসিআর পাঠ্য নিষ্কাশিত",
        "speechResult": "স্থানীয় কণ্ঠস্বরের প্রতিলিপি",
        "speechTranscript": "কণ্ঠস্বর প্রতিলিপি",
        "confidenceScore": "এআই আত্মবিশ্বাস স্কোর",
        "aiConfidence": "এআই আত্মবিশ্বাস",
        "suggestedCategory": "প্রস্তাবিত বিভাগ",
        "suggestedDepartment": "প্রস্তাবিত পৌর বিভাগ",
        "recommendedDepartment": "সুপারিশকৃত বিভাগ",
        "suggestedIndustry": "প্রস্তাবিত শিল্প অংশীদার",
        "duplicateDetection": "নকল অভিযোগ সনাক্তকরণ",
        "aiVerification": "মাল্টিমোডাল ভিশন যাচাইকরণ",
        "smartRouting": "বুদ্ধিমান বিভাগীয় রাউটিং",
        "previewTitle": "মাল্টিমোডাল এআই নিষ্কাশন পূর্বরূপ",
        "previewSubtitle": "আমাদের কম্পিউটার ভিশন ও স্পিচ পাইপলাইন নিচের তথ্য নিষ্কাশন করেছে। জমা দেওয়ার আগে যাচাই করুন।",
        "detectedHeadline": "সনাক্তকৃত অভিযোগ শিরোনাম",
        "classifiedCategory": "এআই শ্রেণীবদ্ধ বিভাগ",
        "dispatchedDept": "বরাদ্দকৃত পৌর বিভাগ",
        "severityPriority": "তীব্রতা ও অগ্রাধিকার",
        "mappedLocation": "মানচিত্রিত ঘটনার অবস্থান",
        "confirmSubmit": "নিশ্চিত করুন এবং অভিযোগ প্রেরণ করুন",
        "cancel": "বাতিল করুন",
        "ocrBadge": "FastAPI ওসিআর নিষ্কাশিত",
        "sttBadge": "কণ্ঠস্বর প্রতিলিপিকৃত",
        "verificationStep": "নাগরিক যাচাইকরণ ধাপ",
        "verificationStepHelp": "শতভাগ নির্ভুলতা নিশ্চিত করতে চূড়ান্ত প্রেরণের আগে আপনি যেকোনো ক্ষেত্র সরাসরি সম্পাদনা করতে পারেন।",
        "ocrVision": "ওসিআর ভিশন নিষ্কাশন",
        "noOcrText": "সাইন বোর্ডে কোনো পাঠ্য পাওয়া যায়নি",
        "noAudioMemo": "কোনো অডিও মেমো সংযুক্ত নেই",
        "priorityScore": "গণনাকৃত অগ্রাধিকার স্কোর",
        "estimatedCost": "আনুমানিক পৌর খরচ",
        "estimatedTime": "আনুমানিক সমাধানের সময়",
        "recommendation": "এআই প্রশাসনিক সুপারিশ",
        "confidenceHigh": "উচ্চ আত্মবিশ্বাস (>৯০%)",
        "confidenceMedium": "মাঝারি আত্মবিশ্বাস (৭০-৯০%)",
        "confidenceLow": "কম আত্মবিশ্বাস (<৭০%)",
        "duplicateFound": "সম্ভাব্য সদৃশ অভিযোগ সনাক্ত হয়েছে",
        "duplicateScore": "সাদৃশ্য স্কোর"
    },
    "citizen": {
        "portalTitle": "নাগরিক সেবা ও অভিযোগ পোর্টাল",
        "dashboard": {
            "welcomeBack": "স্বাগতম",
            "totalReported": "মোট দাখিলকৃত অভিযোগ",
            "inProgress": "চলমান অভিযোগ",
            "resolved": "নিষ্পত্তিকৃত অভিযোগ",
            "needsVerification": "যাচাইকরণ প্রয়োজন",
            "communityImpact": "সম্প্রদায় প্রভাব",
            "avgResolution": "গড় সমাধানের সময়",
            "recentGrievances": "আমার সাম্প্রতিক অভিযোগসমূহ",
            "reportNewIssue": "নতুন অভিযোগ দায়ের করুন",
            "myIssues": "আমার অভিযোগসমূহ",
            "trackIssues": "সমাধান ট্র্যাক করুন",
            "liveIncidents": "লাইভ পৌর ঘটনা",
            "civicFeed": "নাগরিক ফিড",
            "satisfactionScore": "নাগরিক সন্তুষ্টি স্কোর",
            "activeCases": "সক্রিয় মামলা",
            "resolvedCases": "নিষ্পত্তিকৃত মামলা"
        },
        "report": {
            "title": "নতুন নাগরিক অভিযোগ দায়ের করুন",
            "subtitle": "ছবি, অডিও এবং সঠিক জিপিএস সহ সমস্যা রিপোর্ট করুন। এআই তাৎক্ষণিকভাবে উপযুক্ত বিভাগে পাঠাবে।",
            "multimodalBadge": "মাল্টিমোডাল এআই বিশ্লেষণ সক্রিয়",
            "moduleBadge": "স্মার্ট নাগরিক অভিযোগ মডিউল",
            "uploadEvidence": "ছবি বা ভিডিও প্রমাণ আপলোড করুন",
            "uploadSubtitle": "স্পষ্ট ছবি দ্রুত সমস্যা সমাধানে সহায়তা করে",
            "dragDrop": "ফাইলটি এখানে টেনে আনুন বা",
            "supportedFormats": "PNG, JPG, MP4, MP3 (সর্বোচ্চ ২৫MB)",
            "browseFiles": "ফাইল ব্রাউজ করুন",
            "openCamera": "ক্যামেরা খুলুন",
            "uploadingProgress": "আপলোড হচ্ছে...",
            "attachedEvidence": "সংযুক্ত প্রমাণসমূহ",
            "voiceGrievance": "ভয়েস অভিযোগ রেকর্ড করুন",
            "optional": "ঐচ্ছিক",
            "voiceSubtitle": "আপনার সমস্যা স্থানীয় ভাষায় সরাসরি কথা বলে বলুন",
            "pressRecordHelp": "কথা বলা শুরু করতে মাইক্রোফোনে চাপ দিন",
            "startVoiceRecording": "ভয়েস মেমো শুরু করুন",
            "stopRecording": "রেকর্ডিং থামান",
            "recording": "রেকর্ড হচ্ছে...",
            "speechProcessing": "কণ্ঠস্বর পাঠ্যে রূপান্তরিত হচ্ছে...",
            "speechConverted": "কণ্ঠস্বর পাঠ্যে রূপান্তরিত হয়েছে",
            "incidentLocation": "ঘটনার সঠিক অবস্থান",
            "locationSubtitle": "মানচিত্রে অবস্থান চিহ্নিত করুন অথবা জিপিএস ব্যবহার করুন",
            "useCurrentGps": "আমার বর্তমান জিপিএস অবস্থান ব্যবহার করুন",
            "streetAddress": "রাস্তা বা এলাকা",
            "addressPlaceholder": "রাস্তার নাম, এলাকা, ওয়ার্ড নম্বর...",
            "mapTip": "সঠিক অবস্থানের জন্য মানচিত্রের পিনটি সরান",
            "contextTitle": "সমস্যার প্রেক্ষাপট ও বিবরণ",
            "contextSubtitle": "কর্মকর্তাদের বুঝতে সুবিধার্থে সঠিক তথ্য ও বিবরণ দিন",
            "headlineLabel": "অভিযোগের সংক্ষিপ্ত শিরোনাম",
            "headlinePlaceholder": "যেমন: প্রধান সড়কে বড় ও ঝুঁকিপূর্ণ গর্ত",
            "detailsLabel": "বিস্তারিত বিবরণ",
            "detailsPlaceholder": "সমস্যার ধরণ, যান চলাচলে বাধা এবং ঝুঁকি বিস্তারিত লিখুন...",
            "categoryLabel": "সমস্যার ধরণ / শ্রেণী",
            "priorityLabel": "জরুরি অগ্রাধিকার",
            "generateAiPreview": "এআই পূর্বরূপ তৈরি করুন",
            "processingAi": "এআই তথ্য যাচাই করছে...",
            "audioMemo": "অডিও মেমো সংযুক্ত হয়েছে",
            "readyStt": "প্রতিলিপি প্রস্তুত",
            "incidentCoordinates": "ঘটনার স্থানাঙ্ক",
            "currentDetectedLocation": "বর্তমানে সনাক্তকৃত অবস্থান"
        },
        "track": {
            "title": "অভিযোগ সমাধান ট্র্যাকার",
            "subtitle": "দাখিলকৃত অভিযোগের বর্তমান অবস্থা, দায়িত্বপ্রাপ্ত কর্মকর্তা ও পদক্ষেপসমূহ সরাসরি ট্র্যাক করুন।",
            "enterId": "অভিযোগ নম্বর (ID) লিখুন",
            "searchPlaceholder": "যেমন: GRV-2026-8942",
            "currentStage": "বর্তমান পর্যায়",
            "assignedTo": "বরাদ্দকৃত বিভাগ/কর্মকর্তা",
            "officerInCharge": "দায়িত্বপ্রাপ্ত কর্মকর্তা",
            "slaTimer": "এসএলএ সময়সীমা",
            "timeline": "সমাধানের সময়রেখা",
            "trackingDetails": "বিস্তারিত ট্র্যাকিং তথ্য",
            "liveStatusTransitions": "লাইভ স্ট্যাটাস ট্রানজিশন"
        },
        "profile": {
            "title": "নাগরিক প্রোফাইল ও পরিচয়",
            "fullName": "সম্পূর্ণ নাম",
            "email": "ইমেল ঠিকানা",
            "phone": "নিবন্ধিত মোবাইল নম্বর",
            "district": "জেলা",
            "address": "আবাসিক ঠিকানা",
            "saveProfile": "প্রোফাইল সংরক্ষণ করুন",
            "citizenBadge": "যাচাইকৃত নাগরিক ব্যাজ",
            "verificationStatus": "পরিচয় যাচাইকরণ অবস্থা"
        },
        "settings": {
            "title": "অ্যাকাউন্ট ও নিরাপত্তা সেটিংস",
            "notifications": "বিজ্ঞপ্তি সেটিংস",
            "emailAlerts": "ইমেল সতর্কতা",
            "smsAlerts": "এসএমএস সতর্কতা",
            "theme": "থিম (ডার্ক / লাইট মোড)",
            "language": "অ্যাপ্লিকেশনের ভাষা",
            "savePreferences": "পছন্দসমূহ সংরক্ষণ করুন"
        }
    },
    "government": {
        "portalTitle": "পৌর প্রশাসন ও কমান্ড সেন্টার",
        "dashboard": {
            "title": "প্রশাসনিক নিয়ন্ত্রণ কক্ষ",
            "overview": "সার্বিক পর্যালোচনা",
            "assignedCases": "বরাদ্দকৃত মামলা",
            "liveCases": "সক্রিয় লাইভ মামলা",
            "slaBreachRisk": "এসএলএ লঙ্ঘনের ঝুঁকি",
            "avgTurnaround": "গড় সমাধানের সময়",
            "citizenSatisfaction": "নাগরিক সন্তুষ্টি সূচক",
            "urgentDocket": "জরুরি ডকেটসমূহ",
            "viewQueue": "মামলার সারি দেখুন",
            "syncTelemetry": "টেলিমেট্রি সিঙ্ক করুন",
            "telemetryActive": "লাইভ টেলিমেট্রি সক্রিয়",
            "monthlyTrends": "মাসিক ট্রেন্ডস",
            "resolutionBreakdown": "নিষ্পত্তির বিভাজন",
            "districtHeatmap": "জেলা অভিযোগ হিটম্যাপ",
            "departmentEfficiency": "বিভাগীয় দক্ষতা সূচক",
            "docketOverview": "ডকেট পর্যালোচনা",
            "statutoryTarget": "সংবিধিবদ্ধ লক্ষ্যমাত্রা"
        },
        "officers": {
            "title": "মাঠপর্যায়ের কর্মকর্তা ডিরেক্টরি",
            "directory": "কর্মকর্তাদের তালিকা",
            "addOfficer": "নতুন কর্মকর্তা যোগ করুন",
            "officerName": "কর্মকর্তার নাম",
            "designation": "পদবী",
            "department": "বিভাগ",
            "contact": "যোগাযোগ নম্বর",
            "assignedCount": "বরাদ্দকৃত মামলা",
            "resolutionRate": "সমাধানের হার",
            "status": "অবস্থা",
            "actions": "পদক্ষেপসমূহ",
            "searchOfficers": "কর্মকর্তা খুঁজুন..."
        },
        "departments": {
            "title": "পৌর বিভাগীয় ব্যবস্থাপনা",
            "municipalDepartments": "পৌর বিভাগের তালিকা",
            "addDepartment": "নতুন বিভাগ যোগ করুন",
            "deptName": "বিভাগের নাম",
            "headOfDept": "বিভাগীয় প্রধান",
            "activePersonnel": "কর্মরত কর্মী সংখ্যা",
            "budgetAllocated": "বরাদ্দকৃত বাজেট",
            "openGrievances": "বিচারাধীন অভিযোগ",
            "slaCompliance": "এসএলএ অনুপালন হার",
            "efficiencyRating": "দক্ষতা রেটিং",
            "searchDepartments": "বিভাগ খুঁজুন..."
        },
        "assigned": {
            "title": "আমার বরাদ্দকৃত পৌর মামলা",
            "caseId": "ডকেট নম্বর",
            "citizenName": "নাগরিকের নাম",
            "category": "শ্রেণী",
            "priority": "অগ্রাধিকার",
            "status": "অবস্থা",
            "dateReported": "রিপোর্টের তারিখ",
            "targetResolution": "লক্ষ্যমাত্রা সমাধানের তারিখ",
            "reassign": "পুনরায় বরাদ্দ করুন",
            "escalate": "উচ্চস্তরে পাঠান",
            "resolveCase": "মামলা নিষ্পত্তি করুন",
            "viewCase": "মামলা দেখুন",
            "filterPriority": "অগ্রাধিকার অনুযায়ী ফিল্টার",
            "filterStatus": "অবস্থা অনুযায়ী ফিল্টার",
            "allCases": "সকল মামলা"
        },
        "tracking": {
            "title": "নগরব্যাপী মামলার লাইভ ট্র্যাকিং",
            "subtitle": "মানচিত্রে সমস্ত নাগরিক অভিযোগ ও ঘটনা সরাসরি ট্র্যাক করুন",
            "liveIncidentMap": "লাইভ ঘটনা মানচিত্র",
            "filterByWard": "ওয়ার্ড অনুযায়ী ফিল্টার",
            "filterBySeverity": "তীব্রতা অনুযায়ী ফিল্টার"
        },
        "aiSuggestions": {
            "title": "এআই উন্নত প্রশাসনিক বিশ্লেষণ ও পরামর্শ",
            "smartRoutingTitle": "স্মার্ট রাউটিং পরামর্শ",
            "recommendedActions": "সুপারিশকৃত পদক্ষেপ",
            "anomalyDetection": "অসঙ্গতি সনাক্তকরণ",
            "duplicateClusters": "সদৃশ অভিযোগের ক্লাস্টার",
            "autoTriage": "স্বয়ংক্রিয় ট্রায়াজ"
        },
        "reports": {
            "title": "অডিট ও কর্মক্ষমতা রিপোর্ট",
            "generateReport": "রিপোর্ট তৈরি করুন",
            "downloadPdf": "পিডিএফ ডাউনলোড করুন",
            "downloadCsv": "সিএসভি ডাউনলোড করুন",
            "monthlyAudit": "মাসিক অডিট রিপোর্ট",
            "quarterlyPerformance": "ত্রৈমাসিক কর্মক্ষমতা",
            "exportAnalytics": "অ্যানালিটিক্স রপ্তানি করুন"
        },
        "settings": {
            "title": "পৌর নিয়ন্ত্রণ কক্ষের সেটিংস",
            "slaThresholds": "এসএলএ সময়সীমা",
            "notificationRules": "বিজ্ঞপ্তির নিয়মাবলী",
            "escalationMatrix": "উচ্চস্তরে পাঠানোর ম্যাট্রিক্স",
            "workingHours": "কাজের সময়"
        }
    },
    "industry": {
        "portalTitle": "শিল্প ও কর্পোরেট সিএসআর পোর্টাল",
        "dashboard": {
            "title": "শিল্প সিএসআর ও উদ্ভাবন ড্যাশবোর্ড",
            "overview": "সিএসআর পর্যালোচনা",
            "csrFunding": "সিএসআর তহবিল",
            "capitalAllocation": "মূলধন বরাদ্দ",
            "availableProjects": "উপলব্ধ পৌর প্রকল্প",
            "liveGrants": "সক্রিয় অনুদান",
            "partnershipPact": "অংশীদারিত্ব চুক্তি",
            "totalDisbursed": "মোট বিতরণকৃত তহবিল",
            "activeProjects": "সক্রিয় প্রকল্প",
            "impactScore": "সামাজিক প্রভাব স্কোর",
            "viewOpportunities": "সুযোগসমূহ দেখুন",
            "availableCsr": "উপলব্ধ সিএসআর তহবিল",
            "corporatePartner": "কর্পোরেট অংশীদার",
            "verifiedEntity": "যাচাইকৃত প্রতিষ্ঠান"
        },
        "projects": {
            "title": "টেকসই পৌর প্রকল্পসমূহ",
            "projectCatalog": "প্রকল্প ক্যাটালগ",
            "fundingGoal": "তহবিলের লক্ষ্য",
            "raisedAmount": "সংগৃহীত অর্থ",
            "municipalSponsor": "পৌর পৃষ্ঠপোষক",
            "sdgImpact": "টেকসই উন্নয়ন লক্ষ্যমাত্রা (SDG)",
            "applyFunding": "অর্থায়নের জন্য আবেদন করুন",
            "exploreInitiatives": "উদ্যোগসমূহ অন্বেষণ করুন",
            "searchProjects": "প্রকল্প খুঁজুন..."
        },
        "funding": {
            "title": "সিএসআর অনুদান ও তহবিল ব্যবস্থাপনা",
            "grantApplication": "অনুদান আবেদন",
            "disbursementStatus": "বিতরণের অবস্থা",
            "corporateDonation": "কর্পোরেট অনুদান",
            "taxBenefit": "কর সুবিধা (80G)",
            "escrowStatus": "এসক্রো অ্যাকাউন্টের অবস্থা",
            "fundMilestone": "মাইলফলকে অর্থায়ন করুন"
        },
        "csr": {
            "title": "কর্পোরেট সিএসআর নীতি ও অনুপালন",
            "spendByCategory": "বিভাগভিত্তিক ব্যয়",
            "geographicAllocation": "ভৌগোলিক বরাদ্দ",
            "socialReturnOnInvestment": "সামাজিক বিনিয়োগের রিটার্ন (SROI)",
            "auditCompliance": "অডিট অনুপালন",
            "csrDistribution": "সিএসআর বিতরণ"
        },
        "mentorship": {
            "title": "শিল্প বিশেষজ্ঞ ও শিক্ষার্থী পরামর্শদান",
            "expertGuidance": "বিশেষজ্ঞ দিকনির্দেশনা",
            "studentPrototypes": "শিক্ষার্থীদের প্রোটোটাইপ",
            "industryAdvisors": "শিল্প উপদেষ্টা",
            "scheduleSession": "সেশন নির্ধারণ করুন"
        },
        "collaboration": {
            "title": "পৌর ও শিক্ষায়তনিক সহযোগিতা",
            "academicPacts": "শিক্ষায়তনিক চুক্তি",
            "joinConsortium": "কনসোর্টিয়ামে যোগ দিন",
            "jointResearch": "যৌথ গবেষণা",
            "mouSigned": "স্বাক্ষরিত সমঝোতা স্মারক (MoU)"
        },
        "prototypes": {
            "title": "শিক্ষার্থী প্রোটোটাইপ ও উদ্ভাবন",
            "technologyDemonstrators": "প্রযুক্তি ডেমোনস্ট্রেটর",
            "readyForDeployment": "প্রয়োগের জন্য প্রস্তুত",
            "pilotTested": "পাইলট পরীক্ষা সম্পন্ন",
            "commercialize": "বাণিজ্যিকীকরণ"
        },
        "tracking": {
            "title": "সিএসআর প্রভাবের লাইভ ট্র্যাকিং",
            "milestoneProgress": "মাইলফলকের অগ্রগতি",
            "verificationCheck": "যাচাইকরণ পরীক্ষা",
            "fundRelease": "তহবিল ছাড়করণ"
        },
        "profile": {
            "title": "কোম্পানি ও শিল্প প্রোফাইল",
            "companyName": "কোম্পানির নাম",
            "cinRegistration": "সিআইএন (CIN) নিবন্ধন",
            "csrBudget": "বার্ষিক সিএসআর বাজেট",
            "contactPerson": "যোগাযোগকারী ব্যক্তি",
            "panNumber": "প্যান (PAN) নম্বর"
        },
        "settings": {
            "title": "শিল্প পোর্টাল পছন্দসমূহ",
            "emailNotifications": "ইমেল বিজ্ঞপ্তি",
            "bankDetails": "ব্যাংক অ্যাকাউন্টের বিবরণ",
            "complianceDocs": "অনুপালন নথিপত্র"
        }
    },
    "ngo": {
        "portalTitle": "এনজিও ও নাগরিক অংশগ্রহণ পোর্টাল",
        "dashboard": {
            "title": "এনজিও কর্ম নিয়ন্ত্রণ কেন্দ্র",
            "overview": "কার্যক্রমের পর্যালোচনা",
            "groundSquads": "মাঠপর্যায়ের স্বেচ্ছাসেবক স্কোয়াড",
            "activeVolunteers": "সক্রিয় স্বেচ্ছাসেবক",
            "fieldInterventions": "মাঠপর্যায়ের পদক্ষেপ",
            "reliefOperations": "ত্রাণ কার্যক্রম",
            "communityImpact": "সম্প্রদায় প্রভাব",
            "certsAwarded": "প্রদত্ত শংসাপত্র",
            "urgentReliefCalls": "জরুরি ত্রাণ কল",
            "groundTelemetryLive": "লাইভ গ্রাউন্ড টেলিমেট্রি",
            "logFieldEvidence": "মাঠের প্রমাণ নথিবদ্ধ করুন"
        },
        "projects": {
            "title": "সম্প্রদায় উন্নয়ন প্রকল্প",
            "localGrievances": "স্থানীয় সমস্যাসমূহ",
            "adoptIssue": "সমস্যার দায়িত্ব নিন",
            "publicWorks": "জনকল্যাণমূলক কাজ",
            "grassrootInterventions": "তৃণমূল পর্যায়ের পদক্ষেপ"
        },
        "assignedProjects": {
            "title": "পৌর যৌথ প্রকল্পসমূহ",
            "operationalSquads": "কর্মরত দলসমূহ",
            "projectTimeline": "প্রকল্পের সময়রেখা",
            "targetCompletion": "সমাপ্তির লক্ষ্য",
            "submitProgressReport": "অগ্রগতি রিপোর্ট জমা দিন"
        },
        "fieldActivities": {
            "title": "মাঠপর্যায়ের কার্যক্রম ও প্রমাণ লগ",
            "liveReliefLog": "লাইভ ত্রাণ লগ",
            "geoTaggedPhotos": "জিও-ট্যাগযুক্ত ছবি",
            "suppliesDistributed": "বিতরণকৃত ত্রাণ সামগ্রী",
            "citizensAssisted": "সহায়তাপ্রাপ্ত নাগরিক সংখ্যা",
            "addLogEntry": "নতুন এন্ট্রি যোগ করুন"
        },
        "volunteers": {
            "title": "স্বেচ্ছাসেবক ব্যবস্থাপনা ও দল",
            "registerVolunteer": "নতুন স্বেচ্ছাসেবক নিবন্ধন",
            "skillsDirectory": "দক্ষতা ডিরেক্টরি",
            "assignWard": "ওয়ার্ড বরাদ্দ করুন",
            "volunteerSquads": "স্বেচ্ছাসেবক স্কোয়াড",
            "attendance": "উপস্থিতি ট্র্যাকার"
        },
        "impact": {
            "title": "সামাজিক প্রভাব ও ফলাফল মূল্যায়ন",
            "livesImpacted": "উপকৃত নাগরিক",
            "wardsTransformed": "উন্নত ওয়ার্ডসমূহ",
            "satisfactionIndex": "সন্তুষ্টি সূচক",
            "volunteerHours": "মোট স্বেচ্ছাসেবক সময়"
        },
        "collaborations": {
            "title": "শিল্প ও পৌর অংশীদারিত্ব",
            "municipalMoU": "পৌর সমঝোতা চুক্তি",
            "corporateSponsors": "কর্পোরেট স্পনসর",
            "universityAlliances": "বিশ্ববিদ্যালয় মৈত্রী"
        },
        "certificates": {
            "title": "শংসাপত্র ও স্বীকৃতি",
            "awardCertificate": "শংসাপত্র প্রদান করুন",
            "downloadBadge": "ব্যাজ ডাউনলোড করুন",
            "recognitionLetter": "প্রশংসাপত্র"
        },
        "reports": {
            "title": "মাঠপর্যায়ের কার্যক্রমের রিপোর্ট",
            "fieldAuditReports": "মাঠ অডিট রিপোর্ট",
            "monthlyActivitySummary": "মাসিক কার্যকলাপের সারাংশ",
            "incidentLogSheet": "ঘটনা লগ শিট",
            "submitToGovernment": "সরকারের কাছে জমা দিন"
        },
        "settings": {
            "title": "সংস্থার প্রোফাইল ও সেটিংস",
            "registrationDetails": "নিবন্ধনের বিবরণ",
            "ngoDarpanId": "এনজিও দর্পণ আইডি",
            "focalPoints": "যোগাযোগের কেন্দ্রবিন্দু"
        }
    },
    "university": {
        "portalTitle": "বিশ্ববিদ্যালয় ও শিক্ষায়তনিক উদ্ভাবন পোর্টাল",
        "student": {
            "dashboard": {
                "title": "শিক্ষার্থী ড্যাশবোর্ড",
                "academicCredits": "অ্যাকাডেমিক ক্রেডিট",
                "assignedTasks": "বরাদ্দকৃত কার্যাবলী",
                "labProjects": "ল্যাব প্রকল্পসমূহ",
                "prototypeChallenges": "প্রোটোটাইপ চ্যালেঞ্জ",
                "submitMilestone": "মাইলফলক জমা দিন"
            },
            "tasks": {
                "title": "ল্যাব কার্যাবলী",
                "pendingTasks": "বিচারাধীন কার্যাবলী",
                "taskDescription": "কাজের বিবরণ",
                "dueDate": "নির্দিষ্ট তারিখ",
                "submitDeliverable": "ফলাফল আপলোড করুন",
                "advisorNotes": "উপদেষ্টার নোট",
                "dueTasks": "বকেয়া কাজ"
            },
            "uploads": {
                "title": "ফলাফল আপলোড করুন",
                "researchNotes": "গবেষণা নোট",
                "projectCode": "প্রকল্প কোড / সংগ্রহস্থল",
                "presentationSlides": "উপস্থাপনা স্লাইড",
                "submitForGrading": "মূল্যায়নের জন্য জমা দিন"
            },
            "timeline": {
                "title": "প্রকল্পের সময়রেখা",
                "projectSchedule": "প্রকল্পের সময়সূচী",
                "semesterDeadlines": "সেমিস্টার সময়সীমা",
                "facultyReviewDate": "অনুষদ পর্যালোচনার তারিখ"
            },
            "messages": {
                "title": "পরামর্শদাতা যোগাযোগ",
                "chatWithMentor": "পরামর্শদাতার সাথে চ্যাট করুন",
                "feedbackThread": "প্রতিক্রিয়া থ্রেড",
                "askQuestion": "প্রশ্ন জিজ্ঞাসা করুন"
            }
        },
        "faculty": {
            "dashboard": {
                "title": "অনুষদ ড্যাশবোর্ড",
                "studentCohorts": "শিক্ষার্থী দল",
                "mentoredProjects": "পরামর্শকৃত প্রকল্প",
                "pendingApprovals": "বিচারাধীন অনুমোদন",
                "researchPapers": "গবেষণাপত্র",
                "innovationIndex": "উদ্ভাবন সূচক"
            },
            "approvals": {
                "title": "মাইলফলক অনুমোদন",
                "reviewSubmission": "জমা দেওয়া কাজ পর্যালোচনা করুন",
                "approveMilestone": "মাইলফলক অনুমোদন করুন",
                "rejectMilestone": "মাইলফলক প্রত্যাখ্যান করুন",
                "provideFeedback": "প্রতিক্রিয়া জানান",
                "gradeAwarded": "প্রদত্ত গ্রেড / নম্বর",
                "pendingReviews": "বিচারাধীন পর্যালোচনা"
            },
            "proposals": {
                "title": "পৌর প্রস্তাবনা",
                "civicResearchTopics": "পৌর গবেষণা বিষয়",
                "grantProposals": "অনুদান প্রস্তাবনা",
                "callForPapers": "গবেষণাপত্রের আহ্বান",
                "openProposals": "উন্মুক্ত প্রস্তাবনা"
            },
            "teams": {
                "title": "গবেষণা দল",
                "teamRoster": "দলের রোস্টার",
                "assignLead": "দলনেতা নির্ধারণ করুন",
                "performanceReview": "কর্মক্ষমতা পর্যালোচনা",
                "academicAdvising": "শিক্ষায়তনিক পরামর্শ"
            },
            "reports": {
                "title": "শিক্ষায়তনিক রিপোর্ট",
                "cohortProgress": "শিক্ষার্থী দলের অগ্রগতি রিপোর্ট",
                "publicationOutput": "প্রকাশনার ফলাফল",
                "creditDistribution": "ক্রেডিট বিতরণ রিপোর্ট"
            }
        },
        "shared": {
            "projects": {
                "title": "বিশ্ববিদ্যালয় প্রকল্পসমূহ",
                "studentResearch": "শিক্ষার্থী গবেষণা",
                "capstoneProjects": "ক্যাপস্টোন প্রকল্প",
                "interdisciplinaryTeams": "বহুবিষয়ক দল"
            },
            "research": {
                "title": "গবেষণা কেন্দ্র",
                "publications": "গবেষণা প্রকাশনা",
                "datasets": "পৌর তথ্যসম্ভার (ডেটাসেট)",
                "patentFiling": "পেটেন্ট ফাইলিং",
                "peerReview": "সহকর্মী পর্যালোচনা"
            },
            "innovation": {
                "title": "উদ্ভাবন চ্যালেঞ্জ",
                "innovationChallenges": "স্মার্ট সিটি চ্যালেঞ্জ",
                "hackathonDemos": "হ্যাকার্থন ডেমো",
                "incubatorReady": "ইনকিউবেশনের জন্য প্রস্তুত",
                "smartCityPrototypes": "স্মার্ট সিটি প্রোটোটাইপ"
            },
            "credits": {
                "title": "অ্যাকাডেমিক ক্রেডিট",
                "creditsEarned": "অর্জিত ক্রেডিট",
                "skillBadges": "দক্ষতা ব্যাজ",
                "hallOfFame": "সম্মাননা হল",
                "transcriptVerification": "ট্রান্সক্রিপ্ট যাচাইকরণ"
            },
            "repository": {
                "title": "জ্ঞান ভান্ডার",
                "researchPapersArchive": "গবেষণাপত্র আর্কাইভ",
                "openDataVault": "উন্মুক্ত তথ্য ভান্ডার",
                "citationIndex": "উদ্ধৃতি সূচক"
            },
            "settings": {
                "title": "শিক্ষায়তনিক প্রোফাইল সেটিংস",
                "facultyProfile": "অনুষদ প্রোফাইল",
                "departmentAffiliation": "বিভাগীয় সংযুক্তি",
                "orcidId": "ORCID আইডি"
            }
        }
    },
    "admin": {
        "portalTitle": "কেন্দ্রীয় কমান্ড ও প্ল্যাটফর্ম প্রশাসন",
        "dashboard": {
            "title": "কেন্দ্রীয় প্রশাসন ড্যাশবোর্ড",
            "totalSystemUsers": "মোট সিস্টেম ব্যবহারকারী",
            "activePortals": "সক্রিয় পোর্টাল",
            "aiModelStatus": "এআই মডেল অবস্থা",
            "databaseHealth": "ডাটাবেসের স্বাস্থ্য",
            "unresolvedGrievances": "অমীমাংসিত অভিযোগসমূহ",
            "platformLoad": "প্ল্যাটফর্ম লোড",
            "liveEventStream": "লাইভ ইভেন্ট স্ট্রিম",
            "rootConsole": "রুট কনসোল",
            "cpuUsage": "সিপিইউ ব্যবহার",
            "dbLatency": "ডাটাবেস বিলম্ব",
            "uptime": "সিস্টেম আপটাইম"
        },
        "users": {
            "title": "ব্যবহারকারী ব্যবস্থাপনা",
            "allUsers": "সকল ব্যবহারকারী",
            "addUser": "ব্যবহারকারী যোগ করুন",
            "editRole": "ভূমিকা সম্পাদনা করুন",
            "suspendUser": "ব্যবহারকারী স্থগিত করুন",
            "resetPassword": "পাসওয়ার্ড রিসেট করুন",
            "roleFilter": "ভূমিকা ফিল্টার",
            "searchUsers": "ব্যবহারকারী খুঁজুন..."
        },
        "roles": {
            "title": "ভূমিকা ও অধিকার ব্যবস্থাপনা (RBAC)",
            "permissionsMatrix": "অনুমতি ম্যাট্রিক্স",
            "accessControl": "প্রবেশাধিকার নিয়ন্ত্রণ",
            "createRole": "নতুন ভূমিকা তৈরি করুন",
            "customRoles": "কাস্টম ভূমিকা"
        },
        "government": {
            "title": "পৌর প্রশাসন ব্যবস্থাপনা",
            "municipalBOD": "পৌর পরিচালনা পর্ষদ",
            "cityDistricts": "শহরের জেলা ও জোন",
            "assignWardEngineers": "ওয়ার্ড প্রকৌশলী নিয়োগ করুন"
        },
        "universities": {
            "title": "বিশ্ববিদ্যালয় ও শিক্ষা প্রতিষ্ঠান",
            "registeredCampuses": "নিবন্ধিত বিশ্ববিদ্যালয়সমূহ",
            "accreditationVerify": "স্বীকৃতি যাচাইকরণ",
            "studentCap": "শিক্ষার্থী সীমা"
        },
        "industry": {
            "title": "শিল্প ও কর্পোরেট অংশীদার",
            "corporatePartners": "কর্পোরেট অংশীদার কোম্পানি",
            "csrValidation": "সিএসআর বৈধতা যাচাই",
            "escrowAudits": "এসক্রো অ্যাকাউন্ট অডিট"
        },
        "ngos": {
            "title": "স্বেচ্ছাসেবী সংস্থা ও ট্রাস্ট",
            "verifiedNgos": "স্বীকৃত এনজিও",
            "darpanCheck": "এনজিও দর্পণ যাচাইকরণ",
            "groundClearance": "মাঠপর্যায়ের কাজের অনুমতি"
        },
        "research": {
            "title": "গবেষণা প্রতিষ্ঠান ও ল্যাব",
            "institutePartnerships": "গবেষণা অংশীদার প্রতিষ্ঠান",
            "ethicsClearance": "নৈতিকতা কমিটির অনুমোদন",
            "datasetAccess": "পৌর ডেটাসেট অ্যাক্সেস"
        },
        "departments": {
            "title": "বিভাগ মাস্টার ও রাউটিং নিয়মাবলী",
            "routingRules": "স্বয়ংক্রিয় রাউটিং নিয়মাবলী",
            "autoAssignmentEngine": "এআই প্রেরণ ইঞ্জিন",
            "fallbackQueues": "ফলব্যাক সারি"
        },
        "issues": {
            "title": "প্ল্যাটফর্ম অভিযোগ মাস্টার",
            "forceResolve": "প্রশাসনিক নিষ্পত্তি",
            "reassignCluster": "অভিযোগ ক্লাস্টার পুনরায় বরাদ্দ করুন",
            "auditLog": "অপরিবর্তনীয় অ্যাকশন লগ",
            "purgeTestData": "পরীক্ষামূলক ডেটা মুছুন"
        },
        "aiMonitoring": {
            "title": "এআই ভিশন ও টেলিমেট্রি পর্যবেক্ষণ",
            "geminiVisionUptime": "ভিশন মডেল আপটাইম",
            "fastApiOcrStatus": "FastAPI ওসিআর পাইপলাইন",
            "speechToTextLatency": "ভয়েস রূপান্তর বিলম্ব",
            "accuracyScore": "শ্রেণীবদ্ধকরণ নির্ভুলতা স্কোর",
            "confidenceDistribution": "আত্মবিশ্বাস বন্টন",
            "modelLogs": "ইনফারেন্স লেটেন্সি লগ"
        },
        "workflowMonitoring": {
            "title": "ওয়ার্কফ্লো ইঞ্জিন ও কিউ টেলিমেট্রি",
            "stateMachineInspect": "স্টেট মেশিন রূপান্তর",
            "queueDepth": "মেসেজ কিউ গভীরতা",
            "deadLetterQueue": "ডেড-লেটার কিউ",
            "retryFailedTasks": "ব্যর্থ কাজ পুনরায় চেষ্টা করুন"
        },
        "analytics": {
            "title": "ক্রস-প্ল্যাটফর্ম ম্যাক্রো অ্যানালিটিক্স",
            "crossPortalActivity": "ক্রস-পোর্টাল ব্যবহারের মেট্রিক্স",
            "municipalPerformanceIndex": "পৌর কর্মক্ষমতা সূচক",
            "peakUsageHours": "সর্বোচ্চ ব্যবহারের সময়"
        },
        "systemHealth": {
            "title": "অবকাঠামো ও সিস্টেম স্বাস্থ্য",
            "databaseReplicas": "ডাটাবেস প্রতিলিপি",
            "redisCache": "রেডিস ইন-মেমরি স্থিতি",
            "storageUsage": "অবজেক্ট স্টোরেজ ব্যবহার",
            "apiGateways": "মাইক্রোসার্ভিস স্বাস্থ্য",
            "uptime99": "৯৯.৯৮% উচ্চ প্রাপ্যতা",
            "online": "অনলাইন",
            "maintenance": "রক্ষণাবেক্ষণ চলছে"
        },
        "settings": {
            "title": "প্ল্যাটফর্ম কনফিগারেশন সেটিংস",
            "maintenanceMode": "রক্ষণাবেক্ষণ মোড",
            "apiRateLimits": "এপিআই রেট লিমিট",
            "backupSchedules": "স্বয়ংক্রিয় ব্যাকআপ সময়সূচী",
            "smtpConfig": "ইমেল ও এসএমএস গেটওয়ে"
        }
    },
    "toast": {
        "issueSubmitted": "অভিযোগ সফলভাবে জমা দেওয়া হয়েছে! দায়িত্বপ্রাপ্ত বিভাগে প্রেরণ করা হয়েছে।",
        "gpsCaptured": "জিপিএস স্থানাঙ্ক সনাক্ত হয়েছে",
        "gpsCapturedDesc": "স্থানাঙ্ক অভিযোগ রিপোর্টের সাথে সংযুক্ত করা হয়েছে।",
        "locationDenied": "অবস্থানের অনুমতি প্রত্যাখ্যাত বা অনুপলব্ধ। ডিফল্ট অবস্থান ব্যবহৃত হচ্ছে।",
        "fileSizeExceeded": "ফাইলের আকার ২৫ মেগাবাইটের সীমা অতিক্রম করেছে।",
        "audioNotSupported": "এই ব্রাউজারে অডিও রেকর্ডিং সমর্থিত নয়।",
        "micSimulation": "ভয়েস অভিযোগ ডেমোর জন্য মাইক্রোফোন সিমুলেশন সক্রিয় রয়েছে।",
        "profileUpdated": "প্রোফাইল সফলভাবে আপডেট করা হয়েছে।",
        "settingsSaved": "পছন্দসমূহ সফলভাবে সংরক্ষিত হয়েছে।",
        "deleteRequested": "অ্যাকাউন্ট মুছে ফেলার অনুরোধ জমা দেওয়া হয়েছে।",
        "languageChanged": "ভাষা সফলভাবে পরিবর্তন করা হয়েছে।",
        "errorOccurred": "একটি ত্রুটি ঘটেছে। অনুগ্রহ করে আবার চেষ্টা করুন।",
        "caseUpdated": "কেস ডকেট সফলভাবে আপডেট করা হয়েছে।",
        "caseReassigned": "মামলাটি পুনরায় নোডাল অফিসারের কাছে পাঠানো হয়েছে।",
        "caseResolved": "অভিযোগ নিষ্পত্তি হিসেবে চিহ্নিত করা হয়েছে।",
        "volunteerAdded": "নতুন স্বেচ্ছাসেবক সফলভাবে নিবন্ধিত হয়েছে।",
        "grantApproved": "সিএসআর অনুদান বরাদ্দ অনুমোদিত হয়েছে।",
        "milestoneApproved": "শিক্ষায়তনিক মাইলফলক অনুমোদিত হয়েছে।",
        "deliverableUploaded": "মূল্যায়নের জন্য ফলাফল আপলোড করা হয়েছে।",
        "loginSuccess": "সফলভাবে সাইন ইন হয়েছে। স্বাগতম!",
        "logoutSuccess": "সফলভাবে লগ আউট হয়েছে।",
        "accessDenied": "প্রবেশাধিকার সীমাবদ্ধ। অপর্যাপ্ত অনুমতি।",
        "changesSaved": "সমস্ত পরিবর্তন সফলভাবে সংরক্ষণ করা হয়েছে।",
        "reportExported": "রিপোর্ট তৈরি ও ডাউনলোড করা হয়েছে।",
        "dataRefreshed": "টেলিমেট্রি তথ্য রিফ্রেশ করা হয়েছে।"
    },
    "language": "ভাষা",
    "dashboard": "ড্যাশবোর্ড",
    "report_issue": "অভিযোগ জানান",
    "report_problem": "অভিযোগ দায়ের করুন",
    "my_issues": "আমার অভিযোগসমূহ",
    "track_issues": "সমাধান ট্র্যাক করুন",
    "notifications": "বিজ্ঞপ্তি",
    "profile": "প্রোফাইল",
    "settings": "সেটিংস",
    "help": "সাহায্য ও সমর্থন",
    "logout": "লগ আউট",
    "login": "লগ ইন",
    "recent_grievances": "সাম্প্রতিক অভিযোগসমূহ",
    "issue_id": "অভিযোগ নম্বর (ID)",
    "citizen_portal": "নাগরিক পোর্টাল",
    "government_portal": "সরকারি পোর্টাল",
    "university_portal": "বিশ্ববিদ্যালয় পোর্টাল",
    "industry_portal": "শিল্প পোর্টাল",
    "ngo_portal": "এনজিও পোর্টাল",
    "admin_portal": "প্রশাসক পোর্টাল",
    "ai_governance_insight": "এআই প্রশাসনিক অন্তর্দৃষ্টি",
    "resolution": "সমাধান",
    "report": "রিপোর্ট",
    "map": "ঘটনার মানচিত্র",
    "search": "অনুসন্ধান করুন",
    "search_placeholder": "অভিযোগ, মামলা, অবস্থান খুঁজুন...",
    "filter": "ফিল্টার",
    "save": "সংরক্ষণ করুন",
    "cancel": "বাতিল করুন",
    "delete": "মুছুন",
    "submit": "জমা দিন",
    "upload": "আপলোড করুন",
    "location": "অবস্থান",
    "description": "বর্ণনা",
    "title": "শিরোনাম",
    "category": "শ্রেণী",
    "department": "বিভাগ",
    "created_at": "রিপোর্টের তারিখ",
    "action": "পদক্ষেপ",
    "actions": "পদক্ষেপসমূহ",
    "view": "দেখুন",
    "edit": "সম্পাদনা করুন",
    "loading": "লোড হচ্ছে...",
    "success": "সফল",
    "error": "একটি ত্রুটি ঘটেছে",
    "welcome_back": "স্বাগতম",
    "total_issues": "মোট অভিযোগ",
    "resolved_issues": "নিষ্পত্তিকৃত অভিযোগ",
    "in_progress_issues": "চলমান অভিযোগ",
    "pending_issues": "বিচারাধীন অভিযোগ",
    "active_projects": "সক্রিয় প্রকল্প",
    "ai_accuracy": "এআই রাউটিং নির্ভুলতা",
    "sla_compliance": "এসএলএ অনুপালন হার",
    "civic_engagement": "নাগরিক অংশগ্রহণ সূচক",
    "recent_activity": "সাম্প্রতিক কার্যকলাপ",
    "quick_actions": "দ্রুত পদক্ষেপ",
    "live_incidents": "লাইভ পৌর ঘটনা",
    "all": "সমস্ত",
    "high": "উচ্চ অগ্রাধিকার",
    "medium": "মাঝারি অগ্রাধিকার",
    "low": "কম অগ্রাধিকার",
    "critical": "সংকটাপন্ন অগ্রাধিকার",
    "emergency": "জরুরি অগ্রাধিকার",
    "pending": "বিচারাধীন",
    "in_progress": "চলমান",
    "resolved": "নিষ্পত্তি হয়েছে",
    "closed": "বন্ধ",
    "rejected": "প্রত্যাখ্যাত",
    "approved": "অনুমোদিত",
    "declined": "প্রত্যাখ্যাত",
    "export": "তথ্য রপ্তানি করুন",
    "download": "ডাউনলোড",
    "confirm": "নিশ্চিত করুন",
    "close": "বন্ধ করুন",
    "back": "পেছনে",
    "next": "পরবর্তী",
    "previous": "পূর্ববর্তী",
    "no_results": "কোনো ফলাফল পাওয়া যায়নি",
    "view_all": "সব দেখুন",
    "home": "হোম",
    "feed": "নাগরিক ফিড",
    "analytics": "এআই অ্যানালিটিক্স",
    "optional": "ঐচ্ছিক",
    "faculty": "অনুষদ পরামর্শদাতা",
    "student": "শিক্ষার্থী দল",
    "projects": "প্রকল্প",
    "research": "গবেষণা কেন্দ্র",
    "innovation": "উদ্ভাবন চ্যালেঞ্জ",
    "teams": "দলসমূহ",
    "credits": "অ্যাকাডেমিক ক্রেডিট",
    "officers": "কর্মকর্তা ডিরেক্টরি",
    "assigned": "বরাদ্দকৃত মামলা",
    "under_review": "পর্যালোচনাধীন",
    "industry_assigned": "শিল্প অংশীদারের কাছে পাঠানো হয়েছে",
    "industry_review": "শিল্প পর্যালোচনা",
    "univ_assigned": "বিশ্ববিদ্যালয়ে পাঠানো হয়েছে",
    "student_dev": "শিক্ষার্থী উন্নয়ন কার্য",
    "faculty_review": "অনুষদ পর্যালোচনা",
    "industry_val": "শিল্প বৈধকরণ",
    "inspection": "পরিদর্শন",
    "feedback": "প্রতিক্রিয়া অপেক্ষমাণ"
}
