# -*- coding: utf-8 -*-
"""
Generates data_or.py with 100% key parity with get_base_en()
"""

import sys, os, json
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from scripts.generate_all_translations import get_base_en

base = get_base_en()

# Odia translation dictionary
# Translating every section with authentic Odia administrative, civic & portal terms

OR_DICT = {
    "nav": {
        "overview": "ସମୀକ୍ଷା",
        "access_identity": "ପ୍ରବେଶ ଏବଂ ପରିଚୟ",
        "stakeholder_ecosystem": "ଅଂଶୀଦାର ଇକୋସିଷ୍ଟମ୍",
        "operations_ai": "ପରିଚାଳନା ଏବଂ AI",
        "infra_observability": "ଭିତ୍ତିଭୂମି ଓ ପର୍ଯ୍ୟବେକ୍ଷଣ",
        "field_activities": "କ୍ଷେତ୍ର କାର୍ଯ୍ୟକଳାପ ଓ ରିଲିଫ୍",
        "community_workforce": "ସମ୍ପ୍ରଦାୟ ଓ କର୍ମଚାରୀ",
        "governance_comms": "ପ୍ରଶାସନ ଓ ଯୋଗାଯୋଗ",
        "csr_investment": "CSR ଓ ପୁଞ୍ଜି ଆବଣ୍ଟନ",
        "collaboration_rd": "ସହଯୋଗ ଓ ଗବେଷଣା",
        "student_portal": "ଛାତ୍ର ପୋର୍ଟାଲ",
        "faculty_portal": "ଅଧ୍ୟାପକ ପୋର୍ଟାଲ",
        "dashboard": "ଡ୍ୟାସବୋର୍ଡ",
        "my_issues": "ମୋର ଅଭିଯୋଗ",
        "report_problem": "ଅଭିଯୋଗ ଦାଖଲ କରନ୍ତୁ",
        "track_issues": "ସମାଧାନ ଟ୍ରାକ୍ କରନ୍ତୁ",
        "notifications": "ବିଜ୍ଞପ୍ତି",
        "profile": "ପ୍ରୋଫାଇଲ୍",
        "settings": "ସେଟିଙ୍ଗ୍ସ",
        "help": "ସହାୟତା ଓ ସମର୍ଥନ",
        "logout": "ଲଗ୍ ଆଉଟ୍",
        "login": "ଲଗ୍ ଇନ୍",
        "analytics": "ବିଶ୍ଳେଷଣ ଓ ରିପୋର୍ଟ",
        "assigned_cases": "ନ୍ୟସ୍ତ ମାମଲା",
        "departments": "ବିଭାଗଗୁଡିକ",
        "officers": "ଅଧିକାରୀ ତାଲିକା",
        "ai_suggestions": "AI ପରାମର୍ଶ",
        "reports": "ରିପୋର୍ଟ ଓ ଅଡିଟ୍",
        "projects": "ଉପଲବ୍ଧ ପ୍ରକଳ୍ପ",
        "funding": "ପାଣ୍ଠି ସୁଯୋଗ",
        "csr_analytics": "CSR ବିଶ୍ଳେଷଣ",
        "mentorship": "ମାର୍ଗଦର୍ଶନ",
        "university_collaboration": "ବିଶ୍ୱବିଦ୍ୟାଳୟ ସହଯୋଗ",
        "research": "ଗବେଷଣା ପଦକ୍ଷେପ",
        "prototypes": "ପ୍ରୋଟୋଟାଇପ୍ ଓ ଡେମୋ",
        "volunteers": "ସ୍ୱେଚ୍ଛାସେବୀ ଦଳ",
        "field_log": "କ୍ଷେତ୍ର ପ୍ରମାଣ ଲଗ୍",
        "impact": "ସାମାଜିକ ପ୍ରଭାବ",
        "certificates": "ପ୍ରମାଣପତ୍ର ଓ ବ୍ୟାଜ୍",
        "lab_tasks": "ଲ୍ୟାବ୍ କାର୍ଯ୍ୟ",
        "upload_deliverables": "ପ୍ରକଳ୍ପ ଫଳାଫଳ ଅପଲୋଡ୍ କରନ୍ତୁ",
        "milestone_timeline": "ମାଇଲଷ୍ଟୋନ୍ ଟାଇମଲାଇନ୍",
        "advisor_discussion": "ଉପଦେଷ୍ଟା ଆଲୋଚନା",
        "milestone_approvals": "ମାଇଲଷ୍ଟୋନ୍ ଅନୁମୋଦନ",
        "municipal_proposals": "ପୌର ପ୍ରସ୍ତାବ",
        "teams": "ଦଳ ଓ ରୋଷ୍ଟର",
        "credits": "ଏକାଡେମିକ୍ କ୍ରେଡିଟ୍",
        "user_management": "ଉପଭୋକ୍ତା ପରିଚାଳନା",
        "role_management": "ଭୂମିକା ପରିଚାଳନା",
        "government_management": "ସରକାରୀ ପ୍ରଶାସନ ପରିଚାଳନା",
        "university_management": "ବିଶ୍ୱବିଦ୍ୟାଳୟ ପରିଚାଳନା",
        "industry_management": "ଶିଳ୍ପ ପରିଚାଳନା",
        "ngo_management": "NGO ପରିଚାଳନା",
        "research_organizations": "ଗବେଷଣା ସଂସ୍ଥା",
        "issue_management": "ଅଭିଯୋଗ ପରିଚାଳନା",
        "ai_monitoring": "AI ଟେଲିମେଟ୍ରି ନିରୀକ୍ଷଣ",
        "workflow_monitoring": "ୱାର୍କଫ୍ଲୋ ନିରୀକ୍ଷଣ",
        "audit_logs": "ଅପରିବର୍ତ୍ତନୀୟ ଅଡିଟ୍ ଲଗ୍",
        "system_health": "ସିଷ୍ଟମ୍ ସ୍ୱାସ୍ଥ୍ୟ",
        "landing_features": "ବୈଶିଷ୍ଟ୍ୟଗୁଡିକ",
        "landing_how_it_works": "ଏହା କିପରି କାମ କରେ",
        "landing_about": "ଆମ ବିଷୟରେ",
        "landing_faq": "ବାରମ୍ବାର ପଚରାଯାଉଥିବା ପ୍ରଶ୍ନ (FAQ)",
        "landing_contact": "ଯୋଗାଯୋଗ",
        "role_login": "ଭୂମିକା ଭିତ୍ତିକ ଲଗଇନ୍",
        "citizen_sign_up": "ନାଗରିକ ପଞ୍ଜୀକରଣ"
    },
    "common": {
        "buttons": {
            "browseFiles": "ଫାଇଲ୍ ବ୍ରାଉଜ୍ କରନ୍ତୁ",
            "openCamera": "କ୍ୟାମେରା ଖୋଲନ୍ତୁ",
            "startRecording": "ରେକର୍ଡିଂ ଆରମ୍ଭ କରନ୍ତୁ",
            "stopRecording": "ରେକର୍ଡିଂ ବନ୍ଦ କରନ୍ତୁ",
            "submit": "ଦାଖଲ କରନ୍ତୁ",
            "cancel": "ବାତିଲ କରନ୍ତୁ",
            "save": "ପରିବର୍ତ୍ତନ ସଂରକ୍ଷଣ କରନ୍ତୁ",
            "delete": "ଡିଲିଟ୍ କରନ୍ତୁ",
            "search": "ଖୋଜନ୍ତୁ",
            "filter": "ଫିଲ୍ଟର୍",
            "upload": "ଅପଲୋଡ୍ କରନ୍ତୁ",
            "confirm": "ନିଶ୍ଚିତ କରନ୍ତୁ",
            "close": "ବନ୍ଦ କରନ୍ତୁ",
            "back": "ପଛକୁ",
            "next": "ପରବର୍ତ୍ତୀ",
            "previous": "ପୂର୍ବବର୍ତ୍ତୀ",
            "detectLocation": "ବର୍ତ୍ତମାନର ସ୍ଥାନ ଚିହ୍ନଟ କରନ୍ତୁ",
            "useCurrentGps": "ବର୍ତ୍ତମାନର GPS ବ୍ୟବହାର କରନ୍ତୁ",
            "resetForm": "ଫର୍ମ ରିସେଟ୍ କରନ୍ତୁ",
            "submitIssue": "ଅଭିଯୋଗ ଦାଖଲ କରନ୍ତୁ",
            "viewAll": "ସମସ୍ତ ଦେଖନ୍ତୁ",
            "export": "ଡାଟା ରପ୍ତାନି କରନ୍ତୁ",
            "download": "ଡାଉନଲୋଡ୍",
            "refresh": "ରିଫ୍ରେଶ୍",
            "login": "ଲଗ୍ ଇନ୍",
            "logout": "ଲଗ୍ ଆଉଟ୍",
            "modifyUploads": "ଅପଲୋଡ୍ ପରିବର୍ତ୍ତନ କରନ୍ତୁ",
            "removeFile": "ଫାଇଲ୍ ହଟାନ୍ତୁ",
            "removeVoiceMemo": "ଭଏସ୍ ମେମୋ ହଟାନ୍ତୁ",
            "edit": "ସମ୍ପାଦନ କରନ୍ତୁ",
            "view": "ବିବରଣୀ ଦେଖନ୍ତୁ",
            "add": "ନୂତନ ଯୋଡ଼ନ୍ତୁ",
            "create": "ତିଆରି କରନ୍ତୁ",
            "update": "ଅପଡେଟ୍ କରନ୍ତୁ",
            "approve": "ଅନୁମୋଦନ କରନ୍ତୁ",
            "reject": "ପ୍ରତ୍ୟାଖ୍ୟାନ କରନ୍ତୁ",
            "reassign": "ପୁନଃ ନ୍ୟସ୍ତ କରନ୍ତୁ",
            "escalate": "ଉଚ୍ଚାଧିକାରୀଙ୍କୁ ପଠାନ୍ତୁ",
            "resolve": "ସମାଧାନ କରନ୍ତୁ",
            "assign": "ନ୍ୟସ୍ତ କରନ୍ତୁ",
            "verify": "ଯାଞ୍ଚ କରନ୍ତୁ",
            "downloadReport": "ରିପୋର୍ଟ ଡାଉନଲୋଡ୍ କରନ୍ତୁ",
            "syncTelemetry": "ଟେଲିମେଟ୍ରି ସିଙ୍କ୍ କରନ୍ତୁ",
            "applyFilters": "ଫିଲ୍ଟର୍ ଲାଗୁ କରନ୍ତୁ",
            "clearFilters": "ଫିଲ୍ଟର୍ ହଟାନ୍ତୁ",
            "viewDetails": "ବିବରଣୀ ଦେଖନ୍ତୁ",
            "sendNotification": "ବିଜ୍ଞପ୍ତି ପଠାନ୍ତୁ",
            "inviteMember": "ସଦସ୍ୟଙ୍କୁ ଆମନ୍ତ୍ରଣ କରନ୍ତୁ",
            "print": "ପ୍ରିଣ୍ଟ କରନ୍ତୁ",
            "share": "ସେୟାର କରନ୍ତୁ",
            "copyLink": "ଲିଙ୍କ୍ କପି କରନ୍ତୁ",
            "proceed": "ଆଗକୁ ବଢ଼ନ୍ତୁ",
            "retry": "ପୁନର୍ବାର ଚେଷ୍ଟା କରନ୍ତୁ",
            "dismiss": "ଖାରଜ କରନ୍ତୁ",
            "accept": "ଗ୍ରହଣ କରନ୍ତୁ",
            "decline": "ପ୍ରତ୍ୟାଖ୍ୟାନ କରନ୍ତୁ"
        },
        "labels": {
            "dashboard": "ଡ୍ୟାସବୋର୍ଡ",
            "profile": "ପ୍ରୋଫାଇଲ୍",
            "settings": "ସେଟିଙ୍ଗ୍ସ",
            "notifications": "ବିଜ୍ଞପ୍ତି",
            "help": "ସହାୟତା ଓ ସମର୍ଥନ",
            "logout": "ଲଗ୍ ଆଉଟ୍",
            "login": "ଲଗ୍ ଇନ୍",
            "status": "ସ୍ଥିତି",
            "priority": "ପ୍ରାଥମିକତା",
            "department": "ବିଭାଗ",
            "category": "ବର୍ଗ",
            "district": "ଜିଲ୍ଲା",
            "ward": "ୱାର୍ଡ",
            "address": "ଠିକଣା",
            "landmark": "ପ୍ରମୁଖ ସ୍ଥାନ / ଲ୍ୟାଣ୍ଡମାର୍କ",
            "title": "ଶୀର୍ଷକ",
            "description": "ବର୍ଣ୍ଣନା",
            "location": "ସ୍ଥାନ",
            "latitude": "ଅକ୍ଷାଂଶ",
            "longitude": "ଦ୍ରାଘିମା",
            "accuracy": "ସଠିକତା",
            "date": "ତାରିଖ",
            "action": "କାର୍ଯ୍ୟାନୁଷ୍ଠାନ",
            "actions": "କାର୍ଯ୍ୟାନୁଷ୍ଠାନଗୁଡିକ",
            "all": "ସମସ୍ତ",
            "high": "ଉଚ୍ଚ",
            "medium": "ମଧ୍ୟମ",
            "low": "କମ୍",
            "critical": "ସଙ୍କଟଜନକ",
            "emergency": "ଜରୁରୀକାଳୀନ",
            "pending": "ବିଚାରାଧୀନ",
            "inProgress": "ପ୍ରକ୍ରିୟାଧୀନ",
            "resolved": "ସମାଧାନ ହୋଇଛି",
            "closed": "ବନ୍ଦ ହୋଇଛି",
            "rejected": "ପ୍ରତ୍ୟାଖ୍ୟାତ",
            "verified": "ଯାଞ୍ଚ ହୋଇଛି",
            "assigned": "ନ୍ୟସ୍ତ ହୋଇଛି",
            "recentActivity": "ସାମ୍ପ୍ରତିକ କାର୍ଯ୍ୟକଳାପ",
            "quickActions": "ଦ୍ରୁତ କାର୍ଯ୍ୟାନୁଷ୍ଠାନ",
            "systemHealth": "ସିଷ୍ଟମ୍ ସ୍ୱାସ୍ଥ୍ୟ",
            "language": "ଭାଷା",
            "selectLanguage": "ଭାଷା ଚୟନ କରନ୍ତୁ",
            "searchLanguage": "ଭାଷା ଖୋଜନ୍ତୁ...",
            "editable": "ସମ୍ପାଦନଯୋଗ୍ୟ",
            "active": "ସକ୍ରିୟ",
            "inactive": "ନିଷ୍କ୍ରିୟ",
            "completed": "ସମ୍ପୂର୍ଣ୍ଣ ହୋଇଛି",
            "failed": "ବିଫଳ ହୋଇଛି",
            "total": "ମୋଟ",
            "count": "ଗଣନା",
            "rate": "ହାର",
            "percentage": "ପ୍ରତିଶତ",
            "timeRemaining": "ବାକି ଥିବା ସମୟ",
            "dueDate": "ଅନ୍ତିମ ତାରିଖ",
            "submittedBy": "ଦାଖଲକାରୀ",
            "assignedTo": "ନ୍ୟସ୍ତ ବ୍ୟକ୍ତି",
            "officerInCharge": "ଦାୟିତ୍ୱପ୍ରାପ୍ତ ଅଧିକାରୀ",
            "slaTimer": "SLA ଟାଇମର୍",
            "auditTimeline": "ଅଡିଟ୍ ଟାଇମଲାଇନ୍",
            "contactInfo": "ଯୋଗାଯୋଗ ତଥ୍ୟ",
            "phoneNumber": "ଫୋନ୍ ନମ୍ବର",
            "emailAddress": "ଇମେଲ୍ ଠିକଣା",
            "fullName": "ପୂରା ନାମ",
            "role": "ଭୂମିକା",
            "organization": "ସଂସ୍ଥା",
            "institution": "ଶିକ୍ଷାନୁଷ୍ଠାନ",
            "createdAt": "ସୃଷ୍ଟି ତାରିଖ",
            "updatedAt": "ଅଦ୍ୟତନ ତାରିଖ"
        },
        "status": {
            "open": "ଖୋଲା",
            "submitted": "ଦାଖଲ ହୋଇଛି",
            "verified": "ଯାଞ୍ଚ ହୋଇଛି",
            "assigned": "ନ୍ୟସ୍ତ ହୋଇଛି",
            "in_progress": "ପ୍ରକ୍ରିୟାଧୀନ",
            "inProgress": "ପ୍ରକ୍ରିୟାଧୀନ",
            "resolved": "ସମାଧାନ ହୋଇଛି",
            "closed": "ବନ୍ଦ ହୋଇଛି",
            "rejected": "ପ୍ରତ୍ୟାଖ୍ୟାତ",
            "under_review": "ସମୀକ୍ଷାଧୀନ",
            "under_government_review": "ସରକାରୀ ସମୀକ୍ଷାଧୀନ",
            "assigned_to_government": "ପୌରପାଳିକାକୁ ନ୍ୟସ୍ତ",
            "assigned_to_industry": "ଶିଳ୍ପ ସହଭାଗୀଙ୍କୁ ନ୍ୟସ୍ତ",
            "industry_review": "ଶିଳ୍ପ ସମୀକ୍ଷା",
            "assigned_to_university": "ବିଶ୍ୱବିଦ୍ୟାଳୟକୁ ନ୍ୟସ୍ତ",
            "student_development": "ଛାତ୍ର ବିକାଶ କାର୍ଯ୍ୟ",
            "faculty_review": "ଅଧ୍ୟାପକ ସମୀକ୍ଷା",
            "industry_validation": "ଶିଳ୍ପ ବୈଧିକରଣ",
            "inspection": "କ୍ଷେତ୍ର ପରିଦର୍ଶନ",
            "feedback_pending": "ମତାମତ ଅପେକ୍ଷିତ",
            "escalated": "ଉଚ୍ଚାଧିକାରୀଙ୍କୁ ପଠାଯାଇଛି",
            "active": "ସକ୍ରିୟ",
            "inactive": "ନିଷ୍କ୍ରିୟ",
            "completed": "ସମ୍ପୂର୍ଣ୍ଣ ହୋଇଛି",
            "approved": "ଅନୁମୋଦିତ",
            "declined": "ପ୍ରତ୍ୟାଖ୍ୟାତ",
            "pending": "ବିଚାରାଧୀନ"
        },
        "priority": {
            "low": "କମ୍ ପ୍ରାଥମିକତା",
            "medium": "ମଧ୍ୟମ ପ୍ରାଥମିକତା",
            "high": "ଉଚ୍ଚ ପ୍ରାଥମିକତା",
            "critical": "ସଙ୍କଟଜନକ ପ୍ରାଥମିକତା",
            "emergency": "ଜରୁରୀକାଳୀନ ପ୍ରାଥମିକତା",
            "urgent": "ଅତ୍ୟନ୍ତ ଜରୁରୀ"
        },
        "departments": {
            "waterSupply": "ଜଳ ଯୋଗାଣ ଓ ନିଷ୍କାସନ",
            "roadsTransport": "ରାସ୍ତାଘାଟ ଓ ପରିବହନ",
            "electricityPower": "ବିଦ୍ୟୁତ୍ ଓ ଶକ୍ତି ଗ୍ରିଡ୍",
            "solidWaste": "କଠିନ ବର୍ଜ୍ୟବସ୍ତୁ ପରିଚାଳନା",
            "publicHealth": "ଜନସ୍ୱାସ୍ଥ୍ୟ ଓ ପରିମଳ",
            "urbanPlanning": "ନଗର ଉନ୍ନୟନ ଓ ଯୋଜନା",
            "education": "ଶିକ୍ଷା ଓ ଦକ୍ଷତା ବିକାଶ",
            "environmentForest": "ପରିବେଶ ଓ ଜଙ୍ଗଲ ସଂରକ୍ଷଣ",
            "policeSafety": "ପୋଲିସ୍ ଓ ନାଗରିକ ସୁରକ୍ଷା",
            "disasterManagement": "ବିପର୍ଯ୍ୟୟ ପରିଚାଳନା ଓ ଅଗ୍ନିଶମ",
            "municipalAdmin": "ସାଧାରଣ ପୌର ପ୍ରଶାସନ"
        },
        "categories": {
            "water": "ପାନୀୟ ଜଳ ଯୋଗାଣ ଓ ଲିକ୍",
            "roads": "ରାସ୍ତା ଓ ଖାଲଖମା",
            "electricity": "ବିଦ୍ୟୁତ୍ ଓ ଷ୍ଟ୍ରିଟ୍ ଲାଇଟ୍",
            "waste": "ଆବର୍ଜନା ଓ ସଫେଇ",
            "health": "ଜନସ୍ୱାସ୍ଥ୍ୟ ଓ ସ୍ୱଚ୍ଛତା",
            "sanitation": "ଡ୍ରେନେଜ୍ ଓ ନର୍ଦ୍ଦମା",
            "infrastructure": "ସାଧାରଣ ଭିତ୍ତିଭୂମି",
            "streetlights": "ଷ୍ଟ୍ରିଟ୍ ଲାଇଟ୍",
            "drainage": "ନର୍ଦ୍ଦମା",
            "potholes": "ରାସ୍ତା ଖାଲଖମା",
            "traffic": "ଟ୍ରାଫିକ୍ ଜାମ୍",
            "pollution": "ପ୍ରଦୂଷଣ"
        },
        "validation": {
            "requiredField": "ଏହି ଫିଲ୍ଡଟି ଆବଶ୍ୟକ",
            "titleRequired": "ଅଭିଯୋଗର ଶୀର୍ଷକ ଆବଶ୍ୟକ",
            "descriptionRequired": "ବିସ୍ତୃତ ବର୍ଣ୍ଣନା ଆବଶ୍ୟକ",
            "locationRequired": "ସ୍ଥାନ ବା ଠିକଣା ଆବଶ୍ୟକ",
            "invalidEmail": "ଦୟାକରି ଏକ ବୈଧ ଇମେଲ୍ ଠିକଣା ଦିଅନ୍ତୁ",
            "invalidPassword": "ପାସୱାର୍ଡ ନିୟମାବଳୀ ଅନୁଯାୟୀ ହେବା ଆବଶ୍ୟକ",
            "passwordTooShort": "ପାସୱାର୍ଡ ଅତିକମରେ ୮ ଅକ୍ଷରର ହେବା ଆବଶ୍ୟକ",
            "passwordMismatch": "ପାସୱାର୍ଡ ମେଳ ଖାଉନାହିଁ",
            "unsupportedFile": "ଫାଇଲ୍ ଫର୍ମାଟ୍ ସମର୍ଥିତ ନୁହେଁ (କେବଳ JPG, PNG, PDF, MP4, MP3)",
            "maxFileSizeExceeded": "ଫାଇଲ୍ ଆକାର ୨୫MB ରୁ ଅଧିକ ହୋଇପାରିବ ନାହିଁ",
            "micPermissionDenied": "ମାଇକ୍ରୋଫୋନ୍ ଅନୁମତି ପ୍ରତ୍ୟାଖ୍ୟାତ ହୋଇଛି",
            "cameraPermissionDenied": "କ୍ୟାମେରା ଅନୁମତି ପ୍ରତ୍ୟାଖ୍ୟାତ ହୋଇଛି",
            "minLength": "ସର୍ବନିମ୍ନ ଅକ୍ଷର ସୀମା ପୂରଣ କରନ୍ତୁ",
            "maxLength": "ସର୍ବାଧିକ ଅକ୍ଷର ସୀମା ଅତିକ୍ରମ କରିଛି",
            "uploadFailed": "ଫାଇଲ୍ ଅପଲୋଡ୍ ବିଫଳ ହୋଇଛି",
            "uploadSuccessful": "ଫାଇଲ୍ ସଫଳତାର ସହ ଅପଲୋଡ୍ ହୋଇଛି",
            "loginSuccessful": "ସଫଳତାର ସହ ଲଗ୍ ଇନ୍ ହୋଇଛି",
            "registrationSuccessful": "ପଞ୍ଜୀକରଣ ସଫଳ ହୋଇଛି",
            "fillRequiredFields": "ଦୟାକରି ସମସ୍ତ ଆବଶ୍ୟକୀୟ ଫିଲ୍ଡ ପୂରଣ କରନ୍ତୁ"
        },
        "emptyStates": {
            "noData": "କୌଣସି ତଥ୍ୟ ଉପଲବ୍ଧ ନାହିଁ",
            "noResults": "କୌଣସି ସନ୍ଧାନ ଫଳାଫଳ ମିଳିଲା ନାହିଁ",
            "noNotifications": "କୌଣସି ନୂତନ ବିଜ୍ଞପ୍ତି ନାହିଁ",
            "noIssuesFound": "କୌଣସି ଅଭିଯୋଗ ମିଳିଲା ନାହିଁ",
            "noProjectsFound": "କୌଣସି ପ୍ରକଳ୍ପ ମିଳିଲା ନାହିଁ",
            "noOfficersFound": "କୌଣସି ଅଧିକାରୀ ମିଳିଲେ ନାହିଁ",
            "noActivitiesFound": "କୌଣସି ସାମ୍ପ୍ରତିକ କାର୍ଯ୍ୟକଳାପ ନାହିଁ"
        },
        "loading": {
            "loading": "ଲୋଡ୍ ହେଉଛି...",
            "pleaseWait": "ଦୟାକରି ଅପେକ୍ଷା କରନ୍ତୁ...",
            "fetchingData": "ନୂତନ ତଥ୍ୟ ଅଣାଯାଉଛି...",
            "processing": "ପ୍ରକ୍ରିୟାକରଣ ଚାଲିଛି...",
            "uploadingMedia": "ମିଡିଆ ଅପଲୋଡ୍ ହେଉଛି...",
            "analyzingAi": "AI ବିଶ୍ଳେଷଣ କରୁଛି...",
            "savingChanges": "ପରିବର୍ତ୍ତନ ସଂରକ୍ଷଣ ହେଉଛି..."
        },
        "pagination": {
            "previous": "ପୂର୍ବବର୍ତ୍ତୀ",
            "next": "ପରବର୍ତ୍ତୀ",
            "page": "ପୃଷ୍ଠା",
            "of": "ର",
            "rowsPerPage": "ପ୍ରତି ପୃଷ୍ଠାରେ ଧାଡ଼ି",
            "showing": "ଦେଖାଉଛି",
            "entries": "ଏଣ୍ଟ୍ରି",
            "totalRecords": "ମୋଟ ରେକର୍ଡ"
        },
        "search": {
            "searchPlaceholder": "ଅଭିଯୋଗ, ମାମଲା, ସ୍ଥାନ ଖୋଜନ୍ତୁ...",
            "searchGrievances": "ଅଭିଯୋଗ ଖୋଜନ୍ତୁ...",
            "searchUsers": "ଉପଭୋକ୍ତା ଖୋଜନ୍ତୁ...",
            "searchDepartments": "ବିଭାଗ ଖୋଜନ୍ତୁ...",
            "searchProjects": "ପ୍ରକଳ୍ପ ଖୋଜନ୍ତୁ...",
            "searchOfficers": "ଅଧିକାରୀ ଖୋଜନ୍ତୁ...",
            "quickNavigator": "ଦ୍ରୁତ ନେଭିଗେଟର୍...",
            "searchAll": "ପ୍ଲାଟଫର୍ମରେ ସମସ୍ତ ଖୋଜନ୍ତୁ..."
        }
    },
    "ai": {
        "processing": "AI ପ୍ରକ୍ରିୟାକରଣ ଚାଲିଛି",
        "ocrResult": "OCR ପାଠ୍ୟ ବାହାର କରାଯାଇଛି",
        "speechResult": "ସ୍ଥାନୀୟ ଭଏସ୍ ଟ୍ରାନ୍ସକ୍ରିପ୍ଟ",
        "speechTranscript": "ଭଏସ୍ ଟ୍ରାନ୍ସକ୍ରିପ୍ଟ",
        "confidenceScore": "AI ବିଶ୍ୱସନୀୟତା ସ୍କୋର",
        "aiConfidence": "AI ବିଶ୍ୱସନୀୟତା",
        "suggestedCategory": "ପ୍ରସ୍ତାବିତ ବର୍ଗ",
        "suggestedDepartment": "ପ୍ରସ୍ତାବିତ ପୌର ବିଭାଗ",
        "recommendedDepartment": "ସୁପାରିଶକୃତ ବିଭାଗ",
        "suggestedIndustry": "ପ୍ରସ୍ତାବିତ ଶିଳ୍ପ ସହଭାଗୀ",
        "duplicateDetection": "ସମାନ ଅଭିଯୋଗ ଚିହ୍ନଟ",
        "aiVerification": "ମଲ୍ଟିମୋଡାଲ୍ ଭିଜନ୍ ଯାଞ୍ଚ",
        "smartRouting": "ସ୍ମାର୍ଟ ବିଭାଗୀୟ ରାଉଟିଙ୍ଗ୍",
        "previewTitle": "ମଲ୍ଟିମୋଡାଲ୍ AI ତଥ୍ୟ ପୂର୍ବାବଲୋକନ",
        "previewSubtitle": "ଆମର କମ୍ପ୍ୟୁଟର ଭିଜନ୍ ଏବଂ ସ୍ପିଚ୍ ସିଷ୍ଟମ୍ ନିମ୍ନଲିଖିତ ତଥ୍ୟ ବାହାର କରିଛି। ଦାଖଲ କରିବା ପୂର୍ବରୁ ଯାଞ୍ଚ କରନ୍ତୁ।",
        "detectedHeadline": "ଚିହ୍ନଟ ହୋଇଥିବା ଅଭିଯୋଗ ଶୀର୍ଷକ",
        "classifiedCategory": "AI ବର୍ଗୀକୃତ ବର୍ଗ",
        "dispatchedDept": "ନ୍ୟସ୍ତ ପୌର ବିଭାଗ",
        "severityPriority": "ତୀବ୍ରତା ଓ ପ୍ରାଥମିକତା",
        "mappedLocation": "ମ୍ୟାପ୍ କରାଯାଇଥିବା ସ୍ଥାନ",
        "confirmSubmit": "ନିଶ୍ଚିତ କରନ୍ତୁ ଏବଂ ଅଭିଯୋଗ ପଠାନ୍ତୁ",
        "cancel": "ବାତିଲ କରନ୍ତୁ",
        "ocrBadge": "FastAPI OCR ନିଷ୍କାସିତ",
        "sttBadge": "ଭଏସ୍ ରୂପାନ୍ତରିତ",
        "verificationStep": "ନାଗରିକ ଯାଞ୍ଚ ପଦକ୍ଷେପ",
        "verificationStepHelp": "୧୦୦% ସଠିକତା ନିଶ୍ଚିତ କରିବାକୁ ଅନ୍ତିମ ଦାଖଲ ପୂର୍ବରୁ ଆପଣ ଯେକୌଣସି ଫିଲ୍ଡ ସମ୍ପାଦନ କରିପାରିବେ।",
        "ocrVision": "OCR ଭିଜନ୍ ନିଷ୍କାସନ",
        "noOcrText": "ସାଇନବୋର୍ଡରେ କୌଣସି ଲେଖା ମିଳିଲା ନାହିଁ",
        "noAudioMemo": "କୌଣସି ଅଡିଓ ମେମୋ ଯୋଡ଼ା ଯାଇନାହିଁ",
        "priorityScore": "ଗଣନା କରାଯାଇଥିବା ପ୍ରାଥମିକତା ସ୍କୋର",
        "estimatedCost": "ଆନୁମାନିକ ପୌର ଖର୍ଚ୍ଚ",
        "estimatedTime": "ଆନୁମାନିକ ସମାଧାନ ସମୟ",
        "recommendation": "AI ପ୍ରଶାସନିକ ସୁପାରିଶ",
        "confidenceHigh": "ଉଚ୍ଚ ବିଶ୍ୱସନୀୟତା (>୯୦%)",
        "confidenceMedium": "ମଧ୍ୟମ ବିଶ୍ୱସନୀୟତା (୭୦-୯୦%)",
        "confidenceLow": "କମ୍ ବିଶ୍ୱସନୀୟତା (<୭୦%)",
        "duplicateFound": "ସମ୍ଭାବ୍ୟ ସମାନ ଅଭିଯୋଗ ମିଳିଛି",
        "duplicateScore": "ସାଦୃଶ୍ୟ ସ୍କୋର"
    },
    "citizen": {
        "portalTitle": "ନାଗରିକ ସେବା ଓ ଅଭିଯୋଗ ପୋର୍ଟାଲ",
        "dashboard": {
            "welcomeBack": "ସ୍ୱାଗତମ୍",
            "totalReported": "ମୋଟ ଦାଖଲ ହୋଇଥିବା ଅଭିଯୋଗ",
            "inProgress": "ପ୍ରକ୍ରିୟାଧୀନ ଅଭିଯୋଗ",
            "resolved": "ସମାଧାନ ହୋଇଥିବା ଅଭିଯୋଗ",
            "needsVerification": "ଯାଞ୍ଚ ଆବଶ୍ୟକ",
            "communityImpact": "ସାମାଜିକ ପ୍ରଭାବ",
            "avgResolution": "ହାରାହାରି ସମାଧାନ ସମୟ",
            "recentGrievances": "ମୋର ସାମ୍ପ୍ରତିକ ଅଭିଯୋଗ",
            "reportNewIssue": "ନୂତନ ଅଭିଯୋଗ ଦାଖଲ କରନ୍ତୁ",
            "myIssues": "ମୋର ଅଭିଯୋଗଗୁଡିକ",
            "trackIssues": "ସମାଧାନ ଟ୍ରାକ୍ କରନ୍ତୁ",
            "liveIncidents": "ଲାଇଭ୍ ପୌର ଘଟଣା",
            "civicFeed": "ନାଗରିକ ଫିଡ୍",
            "satisfactionScore": "ସନ୍ତୁଷ୍ଟି ସୂଚକାଙ୍କ",
            "activeCases": "ସକ୍ରିୟ ମାମଲା",
            "resolvedCases": "ସମାଧାନ ହୋଇଥିବା ମାମଲା"
        },
        "report": {
            "title": "ନୂତନ ନାଗରିକ ଅଭିଯୋଗ ଦାଖଲ କରନ୍ତୁ",
            "subtitle": "ଫଟୋ, ଅଡିଓ ଏବଂ ସଠିକ୍ GPS ସହିତ ସମସ୍ୟା ରିପୋର୍ଟ କରନ୍ତୁ। AI ସିଷ୍ଟମ୍ ତୁରନ୍ତ ସମ୍ପୃକ୍ତ ବିଭାଗକୁ ପଠାଇବ।",
            "multimodalBadge": "ମଲ୍ଟିମୋଡାଲ୍ AI ବିଶ୍ଳେଷଣ ସକ୍ରିୟ",
            "moduleBadge": "ସ୍ମାର୍ଟ ନାଗରିକ ଅଭିଯୋଗ ମଡ୍ୟୁଲ୍",
            "uploadEvidence": "ଫଟୋ କିମ୍ବା ଭିଡିଓ ପ୍ରମାଣ ଅପଲୋଡ୍ କରନ୍ତୁ",
            "uploadSubtitle": "ସ୍ପଷ୍ଟ ଫଟୋ ଶୀଘ୍ର ସମାଧାନରେ ସାହାଯ୍ୟ କରେ",
            "dragDrop": "ଫାଇଲ୍ ଏଠାରେ ଡ୍ରାଗ୍ କରନ୍ତୁ କିମ୍ବା",
            "supportedFormats": "PNG, JPG, MP4, MP3 (ସର୍ବାଧିକ ୨୫MB)",
            "browseFiles": "ଫାଇଲ୍ ବ୍ରାଉଜ୍ କରନ୍ତୁ",
            "openCamera": "କ୍ୟାମେରା ଖୋଲନ୍ତୁ",
            "uploadingProgress": "ଅପଲୋଡ୍ ହେଉଛି...",
            "attachedEvidence": "ସଂଲଗ୍ନ ପ୍ରମାଣ",
            "voiceGrievance": "ଭଏସ୍ ଅଭିଯୋଗ ରେକର୍ଡ କରନ୍ତୁ",
            "optional": "ଇଚ୍ଛାଧୀନ",
            "voiceSubtitle": "ନିଜ ଭାଷାରେ ସିଧାସଳଖ କହି ସମସ୍ୟା ରେକର୍ଡ କରନ୍ତୁ",
            "pressRecordHelp": "କହିବା ଆରମ୍ଭ କରିବା ପାଇଁ ମାଇକ୍ରୋଫୋନ୍ ଦବାନ୍ତୁ",
            "startVoiceRecording": "ଭଏସ୍ ରେକର୍ଡିଂ ଆରମ୍ଭ କରନ୍ତୁ",
            "stopRecording": "ରେକର୍ଡିଂ ବନ୍ଦ କରନ୍ତୁ",
            "recording": "ରେକର୍ଡ ହେଉଛି...",
            "speechProcessing": "ଭଏସ୍ ଟେକ୍ସଟ୍‌ରେ ରୂପାନ୍ତରିତ ହେଉଛି...",
            "speechConverted": "ଭଏସ୍ ଟେକ୍ସଟ୍‌ରେ ରୂପାନ୍ତରିତ ହୋଇଛି",
            "incidentLocation": "ଘଟଣାର ସଠିକ୍ ସ୍ଥାନ",
            "locationSubtitle": "ମ୍ୟାପ୍‌ରେ ସ୍ଥାନ ଚିହ୍ନଟ କରନ୍ତୁ କିମ୍ବା GPS ବ୍ୟବହାର କରନ୍ତୁ",
            "useCurrentGps": "ମୋର ବର୍ତ୍ତମାନର GPS ସ୍ଥାନ ବ୍ୟବହାର କରନ୍ତୁ",
            "streetAddress": "ରାସ୍ତା କିମ୍ବା ଠିକଣା",
            "addressPlaceholder": "ରାସ୍ତା ନାମ, ଅଞ୍ଚଳ, ୱାର୍ଡ ନମ୍ବର...",
            "mapTip": "ସଠିକ୍ ସ୍ଥାନ ପାଇଁ ମ୍ୟାପ୍‌ର ପିନ୍ ଘୁଞ୍ଚାନ୍ତୁ",
            "contextTitle": "ସମସ୍ୟାର ପ୍ରସଙ୍ଗ ଓ ବିବରଣୀ",
            "contextSubtitle": "ଅଧିକାରୀମାନେ ବୁଝିବା ପାଇଁ ସଠିକ୍ ବିବରଣୀ ଦିଅନ୍ତୁ",
            "headlineLabel": "ଅଭିଯୋଗର ସଂକ୍ଷିପ୍ତ ଶୀର୍ଷକ",
            "headlinePlaceholder": "ଯଥା: ମୁଖ୍ୟ ରାସ୍ତାରେ ବଡ଼ ବିପଦଜନକ ଖାଲ",
            "detailsLabel": "ବିସ୍ତୃତ ବିବରଣୀ",
            "detailsPlaceholder": "ସମସ୍ୟାର ସ୍ୱରୂପ, ଯାତାୟାତରେ ବାଧା ଓ ବିପଦ ସମ୍ପର୍କରେ ଲେଖନ୍ତୁ...",
            "categoryLabel": "ସମସ୍ୟାର ବର୍ଗ",
            "priorityLabel": "ଜରୁରୀକାଳୀନ ପ୍ରାଥମିକତା",
            "generateAiPreview": "AI ପୂର୍ବାବଲୋକନ ପ୍ରସ୍ତୁତ କରନ୍ତୁ",
            "processingAi": "AI ତଥ୍ୟ ଯାଞ୍ଚ କରୁଛି...",
            "audioMemo": "ଅଡିଓ ମେମୋ ଯୋଡ଼ା ଯାଇଛି",
            "readyStt": "ଟ୍ରାନ୍ସକ୍ରିପ୍ଟ ପ୍ରସ୍ତୁତ",
            "incidentCoordinates": "ଘଟଣା ସ୍ଥଳ ସ୍ଥାନାଙ୍କ",
            "currentDetectedLocation": "ଚିହ୍ନଟ ହୋଇଥିବା ବର୍ତ୍ତମାନର ସ୍ଥାନ"
        },
        "track": {
            "title": "ଅଭିଯୋଗ ସମାଧାନ ଟ୍ରାକର୍",
            "subtitle": "ଦାଖଲ ହୋଇଥିବା ଅଭିଯୋଗର ବର୍ତ୍ତମାନର ସ୍ଥିତି ଓ ଅଧିକାରୀଙ୍କ କାର୍ଯ୍ୟାନୁଷ୍ଠାନ ଲାଇଭ୍ ଟ୍ରାକ୍ କରନ୍ତୁ।",
            "enterId": "ଅଭିଯୋଗ ନମ୍ବର (ID) ପ୍ରବେଶ କରନ୍ତୁ",
            "searchPlaceholder": "ଯଥା: GRV-2026-8942",
            "currentStage": "ବର୍ତ୍ତମାନର ପର୍ଯ୍ୟାୟ",
            "assignedTo": "ନ୍ୟସ୍ତ ବିଭାଗ / ଅଧିକାରୀ",
            "officerInCharge": "ନୋଡାଲ୍ ଅଫିସର୍",
            "slaTimer": "SLA ସମୟସୀମା",
            "timeline": "ସମାଧାନ ଟାଇମଲାଇନ୍",
            "trackingDetails": "ବିସ୍ତୃତ ଟ୍ରାକିଂ ତଥ୍ୟ",
            "liveStatusTransitions": "ଲାଇଭ୍ ସ୍ଥିତି ପରିବର୍ତ୍ତନ"
        },
        "profile": {
            "title": "ନାଗରିକ ପ୍ରୋଫାଇଲ୍ ଓ ପରିଚୟ",
            "fullName": "ପୂରା ନାମ",
            "email": "ଇମେଲ୍ ଠିକଣା",
            "phone": "ପଞ୍ଜୀକୃତ ମୋବାଇଲ୍ ନମ୍ବର",
            "district": "ଜିଲ୍ଲା",
            "address": "ବାସସ୍ଥାନ ଠିକଣା",
            "saveProfile": "ପ୍ରୋଫାଇଲ୍ ସଂରକ୍ଷଣ କରନ୍ତୁ",
            "citizenBadge": "ଯାଞ୍ଚ ହୋଇଥିବା ନାଗରିକ ବ୍ୟାଜ୍",
            "verificationStatus": "ପରିଚୟ ଯାଞ୍ଚ ସ୍ଥିତି"
        },
        "settings": {
            "title": "ଆକାଉଣ୍ଟ ଓ ସୁରକ୍ଷା ସେଟିଙ୍ଗ୍ସ",
            "notifications": "ବିଜ୍ଞପ୍ତି ସେଟିଙ୍ଗ୍ସ",
            "emailAlerts": "ଇମେଲ୍ ସତର୍କତା",
            "smsAlerts": "SMS ସତର୍କତା",
            "theme": "ଥିମ୍ (ଡାର୍କ / ଲାଇଟ୍ ମୋଡ୍)",
            "language": "ଆପ୍ ଭାଷା",
            "savePreferences": "ପସନ୍ଦ ସଂରକ୍ଷଣ କରନ୍ତୁ"
        }
    },
    "government": {
        "portalTitle": "ପୌର ପ୍ରଶାସନ ଓ ନିୟନ୍ତ୍ରଣ କେନ୍ଦ୍ର",
        "dashboard": {
            "title": "ପ୍ରଶାସନିକ ନିୟନ୍ତ୍ରଣ କକ୍ଷ",
            "overview": "ସାମଗ୍ରିକ ସମୀକ୍ଷା",
            "assignedCases": "ନ୍ୟସ୍ତ ମାମଲା",
            "liveCases": "ସକ୍ରିୟ ଲାଇଭ୍ ମାମଲା",
            "slaBreachRisk": "SLA ଉଲ୍ଲଂଘନ ବିପଦ",
            "avgTurnaround": "ହାରାହାରି ସମାଧାନ ସମୟ",
            "citizenSatisfaction": "ନାଗରିକ ସନ୍ତୁଷ୍ଟି ସୂଚକାଙ୍କ",
            "urgentDocket": "ଜରୁରୀ ଡକେଟ୍",
            "viewQueue": "ମାମଲା ଧାଡ଼ି ଦେଖନ୍ତୁ",
            "syncTelemetry": "ଟେଲିମେଟ୍ରି ସିଙ୍କ୍ କରନ୍ତୁ",
            "telemetryActive": "ଲାଇଭ୍ ଟେଲିମେଟ୍ରି ସକ୍ରିୟ",
            "monthlyTrends": "ମାସିକ ଟ୍ରେଣ୍ଡ୍",
            "resolutionBreakdown": "ସମାଧାନ ବର୍ଗୀକରଣ",
            "districtHeatmap": "ଜିଲ୍ଲା ଅଭିଯୋଗ ହିଟମ୍ୟାପ୍",
            "departmentEfficiency": "ବିଭାଗୀୟ ଦକ୍ଷତା ସୂଚକାଙ୍କ",
            "docketOverview": "ଡକେଟ୍ ସମୀକ୍ଷା",
            "statutoryTarget": "ବିଧିବଦ୍ଧ ଲକ୍ଷ୍ୟ"
        },
        "officers": {
            "title": "କ୍ଷେତ୍ର ଅଧିକାରୀ ତାଲିକା",
            "directory": "ଅଧିକାରୀ ତାଲିକା",
            "addOfficer": "ନୂତନ ଅଧିକାରୀ ଯୋଡ଼ନ୍ତୁ",
            "officerName": "ଅଧିକାରୀଙ୍କ ନାମ",
            "designation": "ପଦବୀ",
            "department": "ବିଭାଗ",
            "contact": "ଯୋଗାଯୋଗ ନମ୍ବର",
            "assignedCount": "ନ୍ୟସ୍ତ ମାମଲା",
            "resolutionRate": "ସମାଧାନ ହାର",
            "status": "ଉପଲବ୍ଧତା ସ୍ଥିତି",
            "actions": "କାର୍ଯ୍ୟାନୁଷ୍ଠାନ",
            "searchOfficers": "ଅଧିକାରୀ ଖୋଜନ୍ତୁ..."
        },
        "departments": {
            "title": "ପୌର ବିଭାଗ ପରିଚାଳନା",
            "municipalDepartments": "ସମସ୍ତ ପୌର ବିଭାଗ",
            "addDepartment": "ନୂତନ ବିଭାଗ ଯୋଡ଼ନ୍ତୁ",
            "deptName": "ବିଭାଗର ନାମ",
            "headOfDept": "ବିଭାଗୀୟ ମୁଖ୍ୟ",
            "activePersonnel": "କାର୍ଯ୍ୟରତ କର୍ମଚାରୀ ସଂଖ୍ୟା",
            "budgetAllocated": "ବାର୍ଷିକ ବଜେଟ୍ ଆବଣ୍ଟନ",
            "openGrievances": "ବିଚାରାଧୀନ ଅଭିଯୋଗ",
            "slaCompliance": "SLA ଅନୁପାଳନ ହାର",
            "efficiencyRating": "ଦକ୍ଷତା ରେଟିଂ",
            "searchDepartments": "ବିଭାଗ ଖୋଜନ୍ତୁ..."
        },
        "assigned": {
            "title": "ମୋତେ ନ୍ୟସ୍ତ ପୌର ମାମଲା",
            "caseId": "ଡକେଟ୍ ନମ୍ବର",
            "citizenName": "ନାଗରିକଙ୍କ ନାମ",
            "category": "ବର୍ଗ",
            "priority": "ପ୍ରାଥମିକତା",
            "status": "ସ୍ଥିତି",
            "dateReported": "ରିପୋର୍ଟ ତାରିଖ",
            "targetResolution": "ଲକ୍ଷ୍ୟ ସମାଧାନ ତାରିଖ",
            "reassign": "ପୁନଃ ନ୍ୟସ୍ତ କରନ୍ତୁ",
            "escalate": "ଉଚ୍ଚାଧିକାରୀଙ୍କୁ ପଠାନ୍ତୁ",
            "resolveCase": "ମାମଲା ସମାଧାନ କରନ୍ତୁ",
            "viewCase": "ବିବରଣୀ ଦେଖନ୍ତୁ",
            "filterPriority": "ପ୍ରାଥମିକତା ଅନୁଯାୟୀ ଫିଲ୍ଟର୍",
            "filterStatus": "ସ୍ଥିତି ଅନୁଯାୟୀ ଫିଲ୍ଟର୍",
            "allCases": "ସମସ୍ତ ମାମଲା"
        },
        "tracking": {
            "title": "ସହରବ୍ୟାପୀ ମାମଲା ଲାଇଭ୍ ଟ୍ରାକିଂ",
            "subtitle": "ମ୍ୟାପ୍‌ରେ ସମସ୍ତ ନାଗରିକ ଅଭିଯୋଗ ଓ ଘଟଣା ଲାଇଭ୍ ଟ୍ରାକ୍ କରନ୍ତୁ",
            "liveIncidentMap": "ଲାଇଭ୍ ଘଟଣା ମ୍ୟାପ୍",
            "filterByWard": "ୱାର୍ଡ ଅନୁଯାୟୀ ଫିଲ୍ଟର୍",
            "filterBySeverity": "ତୀବ୍ରତା ଅନୁଯାୟୀ ଫିଲ୍ଟର୍"
        },
        "aiSuggestions": {
            "title": "AI ପ୍ରଶାସନିକ ବିଶ୍ଳେଷଣ ଓ ପରାମର୍ଶ",
            "smartRoutingTitle": "ସ୍ମାର୍ଟ ରାଉଟିଙ୍ଗ୍ ପରାମର୍ଶ",
            "recommendedActions": "ସୁପାରିଶକୃତ ପଦକ୍ଷେପ",
            "anomalyDetection": "ବିସଙ୍ଗତି ଚିହ୍ନଟ",
            "duplicateClusters": "ସମାନ ଅଭିଯୋଗର କ୍ଲଷ୍ଟର୍",
            "autoTriage": "ସ୍ୱୟଂଚାଳିତ ଟ୍ରାୟାଜ୍"
        },
        "reports": {
            "title": "ଅଡିଟ୍ ଓ କାର୍ଯ୍ୟଦକ୍ଷତା ରିପୋର୍ଟ",
            "generateReport": "ରିପୋର୍ଟ ପ୍ରସ୍ତୁତ କରନ୍ତୁ",
            "downloadPdf": "PDF ଡାଉନଲୋଡ୍ କରନ୍ତୁ",
            "downloadCsv": "CSV ଡାଉନଲୋଡ୍ କରନ୍ତୁ",
            "monthlyAudit": "ମାସିକ ଅଡିଟ୍ ରିପୋର୍ଟ",
            "quarterlyPerformance": "ତ୍ରୈମାସିକ କାର୍ଯ୍ୟଦକ୍ଷତା",
            "exportAnalytics": "ବିଶ୍ଳେଷଣ ରପ୍ତାନି କରନ୍ତୁ"
        },
        "settings": {
            "title": "ପୌର ନିୟନ୍ତ୍ରଣ କକ୍ଷ ସେଟିଙ୍ଗ୍ସ",
            "slaThresholds": "SLA ସମୟସୀମା",
            "notificationRules": "ବିଜ୍ଞପ୍ତି ନିୟମାବଳୀ",
            "escalationMatrix": "ଏସ୍କାଲେସନ୍ ମ୍ୟାଟ୍ରିକ୍ସ",
            "workingHours": "କାର୍ଯ୍ୟ ସମୟ"
        }
    },
    "industry": {
        "portalTitle": "ଶିଳ୍ପ ଓ କର୍ପୋରେଟ୍ CSR ପୋର୍ଟାଲ",
        "dashboard": {
            "title": "ଶିଳ୍ପ CSR ଓ ଉଦ୍ଭାବନ ଡ୍ୟାସବୋର୍ଡ",
            "overview": "CSR ସମୀକ୍ଷା",
            "csrFunding": "CSR ପାଣ୍ଠି",
            "capitalAllocation": "ପୁଞ୍ଜି ଆବଣ୍ଟନ",
            "availableProjects": "ଉପଲବ୍ଧ ପୌର ପ୍ରକଳ୍ପ",
            "liveGrants": "ସକ୍ରିୟ ଅନୁଦାନ",
            "partnershipPact": "ସହଭାଗୀତା ଚୁକ୍ତି",
            "totalDisbursed": "ମୋଟ ପ୍ରଦତ୍ତ ପାଣ୍ଠି",
            "activeProjects": "ସକ୍ରିୟ ପ୍ରକଳ୍ପ",
            "impactScore": "ସାମାଜିକ ପ୍ରଭାବ ସ୍କୋର",
            "viewOpportunities": "ସୁଯୋଗ ଦେଖନ୍ତୁ",
            "availableCsr": "ଉପଲବ୍ଧ CSR ପାଣ୍ଠି",
            "corporatePartner": "କର୍ପୋରେଟ୍ ସହଭାଗୀ",
            "verifiedEntity": "ଯାଞ୍ଚ ହୋଇଥିବା ସଂସ୍ଥା"
        },
        "projects": {
            "title": "ସ୍ଥାୟୀ ପୌର ପ୍ରକଳ୍ପ",
            "projectCatalog": "ପ୍ରକଳ୍ପ କାଟାଲଗ୍",
            "fundingGoal": "ପାଣ୍ଠି ଲକ୍ଷ୍ୟ",
            "raisedAmount": "ସଂଗୃହିତ ରାଶି",
            "municipalSponsor": "ପୌର ପ୍ରାୟୋଜକ",
            "sdgImpact": "ସ୍ଥାୟୀ ବିକାଶ ଲକ୍ଷ୍ୟ (SDG)",
            "applyFunding": "ପାଣ୍ଠି ପାଇଁ ଆବେଦନ କରନ୍ତୁ",
            "exploreInitiatives": "ପଦକ୍ଷେପ ଅନୁସନ୍ଧାନ କରନ୍ତୁ",
            "searchProjects": "ପ୍ରକଳ୍ପ ଖୋଜନ୍ତୁ..."
        },
        "funding": {
            "title": "CSR ଅନୁଦାନ ଓ ପାଣ୍ଠି ପରିଚାଳନା",
            "grantApplication": "ଅନୁଦାନ ଆବେଦନ",
            "disbursementStatus": "ବଣ୍ଟନ ସ୍ଥିତି",
            "corporateDonation": "କର୍ପୋରେଟ୍ ଦାନ",
            "taxBenefit": "ଟ୍ୟାକ୍ସ ରିହାତି (80G)",
            "escrowStatus": "ଏସ୍କ୍ରୋ ଆକାଉଣ୍ଟ ସ୍ଥିତି",
            "fundMilestone": "ମାଇଲଷ୍ଟୋନ୍ ପାଇଁ ପାଣ୍ଠି ଦିଅନ୍ତୁ"
        },
        "csr": {
            "title": "କମ୍ପାନୀ CSR ନୀତି ଓ ଅନୁପାଳନ",
            "spendByCategory": "ବର୍ଗ ଅନୁଯାୟୀ ଖର୍ଚ୍ଚ",
            "geographicAllocation": "ଭୌଗୋଳିକ ଆବଣ୍ଟନ",
            "socialReturnOnInvestment": "ସାମାଜିକ ବିନିଯୋଗ ରିଟର୍ଣ୍ଣ (SROI)",
            "auditCompliance": "ଅଡିଟ୍ ଅନୁପାଳନ",
            "csrDistribution": "CSR ବଣ୍ଟନ"
        },
        "mentorship": {
            "title": "ଶିଳ୍ପ ବିଶେଷଜ୍ଞ ଓ ଛାତ୍ର ମାର୍ଗଦର୍ଶନ",
            "expertGuidance": "ବିଶେଷଜ୍ଞ ମାର୍ଗଦର୍ଶନ",
            "studentPrototypes": "ଛାତ୍ର ପ୍ରୋଟୋଟାଇପ୍",
            "industryAdvisors": "ଶିଳ୍ପ ଉପଦେଷ୍ଟା",
            "scheduleSession": "ସେସନ୍ ନିର୍ଦ୍ଧାରଣ କରନ୍ତୁ"
        },
        "collaboration": {
            "title": "ପୌର ଓ ଏକାଡେମିକ୍ ସହଯୋଗ",
            "academicPacts": "ଏକାଡେମିକ୍ ଚୁକ୍ତି",
            "joinConsortium": "କନସୋର୍ଟିୟମରେ ଯୋଗ ଦିଅନ୍ତୁ",
            "jointResearch": "ମିଳିତ ଗବେଷଣା",
            "mouSigned": "ସ୍ୱାକ୍ଷରିତ ବୁଝାମଣା ପତ୍ର (MoU)"
        },
        "prototypes": {
            "title": "ଛାତ୍ର ପ୍ରୋଟୋଟାଇପ୍ ଓ ଉଦ୍ଭାବନ",
            "technologyDemonstrators": "ପ୍ରଯୁକ୍ତି ଡେମୋନଷ୍ଟ୍ରେଟର୍",
            "readyForDeployment": "ନିୟୋଜନ ପାଇଁ ପ୍ରସ୍ତୁତ",
            "pilotTested": "ପାଇଲଟ୍ ପରୀକ୍ଷଣ ସମ୍ପୂର୍ଣ୍ଣ",
            "commercialize": "ବାଣିଜ୍ୟିକରଣ କରନ୍ତୁ"
        },
        "tracking": {
            "title": "CSR ପ୍ରଭାବର ଲାଇଭ୍ ଟ୍ରାକିଂ",
            "milestoneProgress": "ମାଇଲଷ୍ଟୋନ୍ ପ୍ରଗତି",
            "verificationCheck": "ଯାଞ୍ଚ ପରୀକ୍ଷା",
            "fundRelease": "ପାଣ୍ଠି ପ୍ରଦାନ"
        },
        "profile": {
            "title": "କମ୍ପାନୀ ଓ ଶିଳ୍ପ ପ୍ରୋଫାଇଲ୍",
            "companyName": "କମ୍ପାନୀର ନାମ",
            "cinRegistration": "CIN ପଞ୍ଜୀକରଣ ନମ୍ବର",
            "csrBudget": "ବାର୍ଷିକ CSR ବଜେଟ୍",
            "contactPerson": "ଯୋଗାଯୋଗ ବ୍ୟକ୍ତି",
            "panNumber": "PAN ନମ୍ବର"
        },
        "settings": {
            "title": "ଶିଳ୍ପ ପୋର୍ଟାଲ ପସନ୍ଦ",
            "emailNotifications": "ଇମେଲ୍ ବିଜ୍ଞପ୍ତି",
            "bankDetails": "ବ୍ୟାଙ୍କ ଆକାଉଣ୍ଟ ବିବରଣୀ",
            "complianceDocs": "ଅନୁପାଳନ ଦସ୍ତାବିଜ"
        }
    },
    "ngo": {
        "portalTitle": "ସ୍ୱେଚ୍ଛାସେବୀ ସଂଗଠନ ଓ ନାଗରିକ ସହଭାଗୀତା ପୋର୍ଟାଲ",
        "dashboard": {
            "title": "NGO କାର୍ଯ୍ୟ ନିୟନ୍ତ୍ରଣ କେନ୍ଦ୍ର",
            "overview": "କାର୍ଯ୍ୟ ସମୀକ୍ଷା",
            "groundSquads": "କ୍ଷେତ୍ର ସ୍ୱେଚ୍ଛାସେବୀ ଦଳ",
            "activeVolunteers": "ସକ୍ରିୟ ସ୍ୱେଚ୍ଛାସେବୀ",
            "fieldInterventions": "କ୍ଷେତ୍ର ପଦକ୍ଷେପ",
            "reliefOperations": "ରିଲିଫ୍ କାର୍ଯ୍ୟ",
            "communityImpact": "ସାମାଜିକ ପ୍ରଭାବ",
            "certsAwarded": "ପ୍ରଦତ୍ତ ପ୍ରମାଣପତ୍ର",
            "urgentReliefCalls": "ଜରୁରୀ ରିଲିଫ୍ କଲ୍",
            "groundTelemetryLive": "ଲାଇଭ୍ ଫିଲ୍ଡ ଟେଲିମେଟ୍ରି",
            "logFieldEvidence": "କ୍ଷେତ୍ର ପ୍ରମାଣ ଲଗ୍ କରନ୍ତୁ"
        },
        "projects": {
            "title": "ସମ୍ପ୍ରଦାୟ ବିକାଶ ପ୍ରକଳ୍ପ",
            "localGrievances": "ସ୍ଥାନୀୟ ସମସ୍ୟା",
            "adoptIssue": "ସମସ୍ୟାର ଦାୟିତ୍ୱ ନିଅନ୍ତୁ",
            "publicWorks": "ଜନକଲ୍ୟାଣ କାର୍ଯ୍ୟ",
            "grassrootInterventions": "ତୃଣମୂଳ ସ୍ତରର ପଦକ୍ଷେପ"
        },
        "assignedProjects": {
            "title": "ପୌର ମିଳିତ ପ୍ରକଳ୍ପ",
            "operationalSquads": "କାର୍ଯ୍ୟରତ ଦଳ",
            "projectTimeline": "ପ୍ରକଳ୍ପ ଟାଇମଲାଇନ୍",
            "targetCompletion": "ସମ୍ପୂର୍ଣ୍ଣ କରିବା ଲକ୍ଷ୍ୟ",
            "submitProgressReport": "ପ୍ରଗତି ରିପୋର୍ଟ ଦାଖଲ କରନ୍ତୁ"
        },
        "fieldActivities": {
            "title": "କ୍ଷେତ୍ର କାର୍ଯ୍ୟକଳାପ ଓ ପ୍ରମାଣ ଲଗ୍",
            "liveReliefLog": "ଲାଇଭ୍ ରିଲିଫ୍ ଲଗ୍",
            "geoTaggedPhotos": "ଜିଓ-ଟ୍ୟାଗ୍ ହୋଇଥିବା ଫଟୋ",
            "suppliesDistributed": "ବଣ୍ଟନ ହୋଇଥିବା ସାମଗ୍ରୀ",
            "citizensAssisted": "ସହାୟତା ପ୍ରାପ୍ତ ନାଗରିକ",
            "addLogEntry": "ନୂତନ ଏଣ୍ଟ୍ରି ଯୋଡ଼ନ୍ତୁ"
        },
        "volunteers": {
            "title": "ସ୍ୱେଚ୍ଛାସେବୀ ପରିଚାଳନା ଓ ଦଳ",
            "registerVolunteer": "ନୂତନ ସ୍ୱେଚ୍ଛାସେବୀ ପଞ୍ଜୀକରଣ",
            "skillsDirectory": "ଦକ୍ଷତା ତାଲିକା",
            "assignWard": "ୱାର୍ଡ ନ୍ୟସ୍ତ କରନ୍ତୁ",
            "volunteerSquads": "ସ୍ୱେଚ୍ଛାସେବୀ ସ୍କ୍ୱାଡ୍",
            "attendance": "ଉପସ୍ଥିତି ଟ୍ରାକର୍"
        },
        "impact": {
            "title": "ସାମାଜିକ ପ୍ରଭାବ ମୂଲ୍ୟାଙ୍କନ",
            "livesImpacted": "ଉପକୃତ ନାଗରିକ",
            "wardsTransformed": "ଉନ୍ନତ ୱାର୍ଡ",
            "satisfactionIndex": "ସନ୍ତୁଷ୍ଟି ସୂଚକାଙ୍କ",
            "volunteerHours": "ମୋଟ ସ୍ୱେଚ୍ଛାସେବା ଘଣ୍ଟା"
        },
        "collaborations": {
            "title": "ଶିଳ୍ପ ଓ ପୌର ସହଯୋଗ",
            "municipalMoU": "ପୌର ବୁଝାମଣା ପତ୍ର",
            "corporateSponsors": "କର୍ପୋରେଟ୍ ପ୍ରାୟୋଜକ",
            "universityAlliances": "ବିଶ୍ୱବିଦ୍ୟାଳୟ ମେଣ୍ଟ"
        },
        "certificates": {
            "title": "ପ୍ରମାଣପତ୍ର ଓ ସ୍ୱୀକୃତି",
            "awardCertificate": "ପ୍ରମାଣପତ୍ର ପ୍ରଦାନ କରନ୍ତୁ",
            "downloadBadge": "ବ୍ୟାଜ୍ ଡାଉନଲୋଡ୍ କରନ୍ତୁ",
            "recognitionLetter": "ପ୍ରଶଂସା ପତ୍ର"
        },
        "reports": {
            "title": "ମାସିକ କ୍ଷେତ୍ର କାର୍ଯ୍ୟ ରିପୋର୍ଟ",
            "fieldAuditReports": "କ୍ଷେତ୍ର ଅଡିଟ୍ ରିପୋର୍ଟ",
            "monthlyActivitySummary": "ମାସିକ କାର୍ଯ୍ୟକଳାପ ସାରାଂଶ",
            "incidentLogSheet": "ଘଟଣା ଲଗ୍ ସିଟ୍",
            "submitToGovernment": "ସରକାରଙ୍କୁ ଦାଖଲ କରନ୍ତୁ"
        },
        "settings": {
            "title": "ସଂସ୍ଥା ପ୍ରୋଫାଇଲ୍ ସେଟିଙ୍ଗ୍ସ",
            "registrationDetails": "ପଞ୍ଜୀକରଣ ବିବରଣୀ",
            "ngoDarpanId": "NGO ଦର୍ପଣ ID",
            "focalPoints": "ପ୍ରମୁଖ ଯୋଗାଯୋଗ କେନ୍ଦ୍ର"
        }
    },
    "university": {
        "portalTitle": "ବିଶ୍ୱବିଦ୍ୟାଳୟ ଓ ଏକାଡେମିକ୍ ଉଦ୍ଭାବନ ପୋର୍ଟାଲ",
        "student": {
            "dashboard": {
                "title": "ଛାତ୍ର ଡ୍ୟାସବୋର୍ଡ",
                "academicCredits": "ଏକାଡେମିକ୍ କ୍ରେଡିଟ୍",
                "assignedTasks": "ନ୍ୟସ୍ତ କାର୍ଯ୍ୟ",
                "labProjects": "ଲ୍ୟାବ୍ ପ୍ରକଳ୍ପ",
                "prototypeChallenges": "ପ୍ରୋଟୋଟାଇପ୍ ଚ୍ୟାଲେଞ୍ଜ",
                "submitMilestone": "ମାଇଲଷ୍ଟୋନ୍ ଦାଖଲ କରନ୍ତୁ"
            },
            "tasks": {
                "title": "ଲ୍ୟାବ୍ କାର୍ଯ୍ୟ",
                "pendingTasks": "ବିଚାରାଧୀନ କାର୍ଯ୍ୟ",
                "taskDescription": "କାର୍ଯ୍ୟ ବିବରଣୀ",
                "dueDate": "ଅନ୍ତିମ ତାରିଖ",
                "submitDeliverable": "ଫଳାଫଳ ଅପଲୋଡ୍ କରନ୍ତୁ",
                "advisorNotes": "ଉପଦେଷ୍ଟାଙ୍କ ନୋଟ୍",
                "dueTasks": "ବାକି ଥିବା କାର୍ଯ୍ୟ"
            },
            "uploads": {
                "title": "ଫଳାଫଳ ଅପଲୋଡ୍ କରନ୍ତୁ",
                "researchNotes": "ଗବେଷଣା ନୋଟ୍",
                "projectCode": "ପ୍ରକଳ୍ପ କୋଡ୍",
                "presentationSlides": "ଉପସ୍ଥାପନା ସ୍ଲାଇଡ୍",
                "submitForGrading": "ମୂଲ୍ୟାଙ୍କନ ପାଇଁ ଦାଖଲ କରନ୍ତୁ"
            },
            "timeline": {
                "title": "ପ୍ରକଳ୍ପ ଟାଇମଲାଇନ୍",
                "projectSchedule": "ପ୍ରକଳ୍ପ ସମୟସାରଣୀ",
                "semesterDeadlines": "ସେମିଷ୍ଟାର୍ ସମୟସୀମା",
                "facultyReviewDate": "ଅଧ୍ୟାପକ ସମୀକ୍ଷା ତାରିଖ"
            },
            "messages": {
                "title": "ଉପଦେଷ୍ଟା ଆଲୋଚନା",
                "chatWithMentor": "ମେଣ୍ଟରଙ୍କ ସହ କଥାବାର୍ତ୍ତା କରନ୍ତୁ",
                "feedbackThread": "ମତାମତ ଥ୍ରେଡ୍",
                "askQuestion": "ପ୍ରଶ୍ନ ପଚାରନ୍ତୁ"
            }
        },
        "faculty": {
            "dashboard": {
                "title": "ଅଧ୍ୟାପକ ଡ୍ୟାସବୋର୍ଡ",
                "studentCohorts": "ଛାତ୍ର ଦଳ",
                "mentoredProjects": "ମାର୍ଗଦର୍ଶିତ ପ୍ରକଳ୍ପ",
                "pendingApprovals": "ବିଚାରାଧୀନ ଅନୁମୋଦନ",
                "researchPapers": "ଗବେଷଣା ପତ୍ର",
                "innovationIndex": "ଉଦ୍ଭାବନ ସୂଚକାଙ୍କ"
            },
            "approvals": {
                "title": "ମାଇଲଷ୍ଟୋନ୍ ଅନୁମୋଦନ",
                "reviewSubmission": "ଦାଖଲ କାର୍ଯ୍ୟ ସମୀକ୍ଷା କରନ୍ତୁ",
                "approveMilestone": "ମାଇଲଷ୍ଟୋନ୍ ଅନୁମୋଦନ କରନ୍ତୁ",
                "rejectMilestone": "ମାଇଲଷ୍ଟୋନ୍ ପ୍ରତ୍ୟାଖ୍ୟାନ କରନ୍ତୁ",
                "provideFeedback": "ମତାମତ ପ୍ରଦାନ କରନ୍ତୁ",
                "gradeAwarded": "ପ୍ରଦତ୍ତ ଗ୍ରେଡ୍",
                "pendingReviews": "ବିଚାରାଧୀନ ସମୀକ୍ଷା"
            },
            "proposals": {
                "title": "ପୌର ପ୍ରସ୍ତାବ",
                "civicResearchTopics": "ପୌର ଗବେଷଣା ବିଷୟ",
                "grantProposals": "ଅନୁଦାନ ପ୍ରସ୍ତାବ",
                "callForPapers": "ପ୍ରବନ୍ଧ ଆହ୍ୱାନ",
                "openProposals": "ଉନ୍ମୁକ୍ତ ପ୍ରସ୍ତାବ"
            },
            "teams": {
                "title": "ଗବେଷଣା ଦଳ",
                "teamRoster": "ଦଳ ତାଲିକା",
                "assignLead": "ଦଳ ନେତା ନିଯୁକ୍ତ କରନ୍ତୁ",
                "performanceReview": "କାର୍ଯ୍ୟଦକ୍ଷତା ସମୀକ୍ଷା",
                "academicAdvising": "ଏକାଡେମିକ୍ ପରାମର୍ଶ"
            },
            "reports": {
                "title": "ଏକାଡେମିକ୍ ରିପୋର୍ଟ",
                "cohortProgress": "ଦଳ ପ୍ରଗତି ରିପୋର୍ଟ",
                "publicationOutput": "ପ୍ରକାଶନ ଆଉଟପୁଟ୍",
                "creditDistribution": "କ୍ରେଡିଟ୍ ବଣ୍ଟନ"
            }
        },
        "shared": {
            "projects": {
                "title": "ବିଶ୍ୱବିଦ୍ୟାଳୟ ପ୍ରକଳ୍ପ",
                "studentResearch": "ଛାତ୍ର ଗବେଷଣା",
                "capstoneProjects": "କ୍ୟାପଷ୍ଟୋନ୍ ପ୍ରକଳ୍ପ",
                "interdisciplinaryTeams": "ବିଭିନ୍ନ ବିଷୟର ମିଳିତ ଦଳ"
            },
            "research": {
                "title": "ଗବେଷଣା କେନ୍ଦ୍ର",
                "publications": "ଗବେଷଣା ପ୍ରକାଶନ",
                "datasets": "ପୌର ତଥ୍ୟସମ୍ଭାର (ଡାଟାସେଟ୍)",
                "patentFiling": "ପେଟେଣ୍ଟ ଦାଖଲ",
                "peerReview": "ପିଅର୍ ସମୀକ୍ଷା"
            },
            "innovation": {
                "title": "ଉଦ୍ଭାବନ ଚ୍ୟାଲେଞ୍ଜ",
                "innovationChallenges": "ସ୍ମାର୍ଟ ସିଟି ଚ୍ୟାଲେଞ୍ଜ",
                "hackathonDemos": "ହ୍ୟାକାଥନ୍ ଡେମୋ",
                "incubatorReady": "ଇନକ୍ୟୁବେସନ୍ ପାଇଁ ପ୍ରସ୍ତୁତ",
                "smartCityPrototypes": "ସ୍ମାର୍ଟ ସିଟି ପ୍ରୋଟୋଟାଇପ୍"
            },
            "credits": {
                "title": "ଏକାଡେମିକ୍ କ୍ରେଡିଟ୍",
                "creditsEarned": "ଅର୍ଜିତ କ୍ରେଡିଟ୍",
                "skillBadges": "ଦକ୍ଷତା ବ୍ୟାଜ୍",
                "hallOfFame": "ସମ୍ମାନ ହଲ୍",
                "transcriptVerification": "ମାର୍କସିଟ୍ ଯାଞ୍ଚ"
            },
            "repository": {
                "title": "ଜ୍ଞାନ ଭଣ୍ଡାର",
                "researchPapersArchive": "ଗବେଷଣା ପତ୍ର ଆର୍କାଇଭ୍",
                "openDataVault": "ମୁକ୍ତ ତଥ୍ୟ ଭଣ୍ଡାର",
                "citationIndex": "ସାଇଟେସନ୍ ସୂଚକାଙ୍କ"
            },
            "settings": {
                "title": "ଏକାଡେମିକ୍ ପ୍ରୋଫାଇଲ୍ ସେଟିଙ୍ଗ୍ସ",
                "facultyProfile": "ଅଧ୍ୟାପକ ପ୍ରୋଫାଇଲ୍",
                "departmentAffiliation": "ବିଭାଗୀୟ ସମ୍ପୃକ୍ତି",
                "orcidId": "ORCID ID"
            }
        }
    },
    "admin": {
        "portalTitle": "କେନ୍ଦ୍ରୀୟ ପ୍ରଶାସନ ଓ ନିୟନ୍ତ୍ରଣ କେନ୍ଦ୍ର",
        "dashboard": {
            "title": "କେନ୍ଦ୍ରୀୟ ପ୍ରଶାସନ ଡ୍ୟାସବୋର୍ଡ",
            "totalSystemUsers": "ମୋଟ ସିଷ୍ଟମ୍ ଉପଭୋକ୍ତା",
            "activePortals": "ସକ୍ରିୟ ପୋର୍ଟାଲ",
            "aiModelStatus": "AI ମଡେଲ୍ ସ୍ଥିତି",
            "databaseHealth": "ଡାଟାବେସ୍ ସ୍ୱାସ୍ଥ୍ୟ",
            "unresolvedGrievances": "ଅସମାହିତ ଅଭିଯୋଗ",
            "platformLoad": "ପ୍ଲାଟଫର୍ମ ଲୋଡ୍",
            "liveEventStream": "ଲାଇଭ୍ ଇଭେଣ୍ଟ ଷ୍ଟ୍ରିମ୍",
            "rootConsole": "ରୁଟ୍ କନସୋଲ୍",
            "cpuUsage": "CPU ବ୍ୟବହାର",
            "dbLatency": "ଡାଟାବେସ୍ ଲେଟେନ୍ସି",
            "uptime": "ସିଷ୍ଟମ୍ କାର୍ଯ୍ୟ ସମୟ"
        },
        "users": {
            "title": "ଉପଭୋକ୍ତା ପରିଚାଳନା",
            "allUsers": "ସମସ୍ତ ଉପଭୋକ୍ତା",
            "addUser": "ଉପଭୋକ୍ତା ଯୋଡ଼ନ୍ତୁ",
            "editRole": "ଭୂମିକା ସମ୍ପାଦନ କରନ୍ତୁ",
            "suspendUser": "ଉପଭୋକ୍ତାଙ୍କୁ ନିଲମ୍ବିତ କରନ୍ତୁ",
            "resetPassword": "ପାସୱାର୍ଡ ରିସେଟ୍ କରନ୍ତୁ",
            "roleFilter": "ଭୂମିକା ଫିଲ୍ଟର୍",
            "searchUsers": "ଉପଭୋକ୍ତା ଖୋଜନ୍ତୁ..."
        },
        "roles": {
            "title": "ଭୂମିକା ଓ ଅଧିକାର ପରିଚାଳନା (RBAC)",
            "permissionsMatrix": "ଅନୁମତି ମ୍ୟାଟ୍ରିକ୍ସ",
            "accessControl": "ପ୍ରବେଶ ନିୟନ୍ତ୍ରଣ",
            "createRole": "ନୂତନ ଭୂମିକା ତିଆରି କରନ୍ତୁ",
            "customRoles": "କଷ୍ଟମ୍ ଭୂମିକା"
        },
        "government": {
            "title": "ପୌର ପ୍ରଶାସନ ପରିଚାଳନା",
            "municipalBOD": "ପୌର ପରିଚାଳନା ବୋର୍ଡ",
            "cityDistricts": "ସହର ଜିଲ୍ଲା ଓ ଜୋନ୍",
            "assignWardEngineers": "ୱାର୍ଡ ଇଞ୍ଜିନିୟର୍ ନିଯୁକ୍ତ କରନ୍ତୁ"
        },
        "universities": {
            "title": "ବିଶ୍ୱବିଦ୍ୟାଳୟ ଓ ଶିକ୍ଷାନୁଷ୍ଠାନ",
            "registeredCampuses": "ପଞ୍ଜୀକୃତ ବିଶ୍ୱବିଦ୍ୟାଳୟ",
            "accreditationVerify": "ସ୍ୱୀକୃତି ଯାଞ୍ଚ",
            "studentCap": "ଛାତ୍ର ସୀମା"
        },
        "industry": {
            "title": "ଶିଳ୍ପ ଓ କର୍ପୋରେଟ୍ ସହଭାଗୀ",
            "corporatePartners": "କର୍ପୋରେଟ୍ ସହଭାଗୀ କମ୍ପାନୀ",
            "csrValidation": "CSR ବୈଧତା ଯାଞ୍ଚ",
            "escrowAudits": "ଏସ୍କ୍ରୋ ଅଡିଟ୍"
        },
        "ngos": {
            "title": "ସ୍ୱେଚ୍ଛାସେବୀ ସଂଗଠନ ଓ ଟ୍ରଷ୍ଟ",
            "verifiedNgos": "ସ୍ୱୀକୃତିପ୍ରାପ୍ତ NGO",
            "darpanCheck": "NGO ଦର୍ପଣ ଯାଞ୍ଚ",
            "groundClearance": "କ୍ଷେତ୍ର କାର୍ଯ୍ୟ ଅନୁମତି"
        },
        "research": {
            "title": "ଗବେଷଣା ସଂସ୍ଥା ଓ ଲ୍ୟାବ୍",
            "institutePartnerships": "ସହଭାଗୀ ଗବେଷଣା ସଂସ୍ଥା",
            "ethicsClearance": "ନୈତିକତା କମିଟି ଅନୁମୋଦନ",
            "datasetAccess": "ପୌର ତଥ୍ୟ ପ୍ରବେଶ ଅନୁମତି"
        },
        "departments": {
            "title": "ବିଭାଗ ମାଷ୍ଟର ଓ ରାଉଟିଙ୍ଗ୍ ନିୟମ",
            "routingRules": "ସ୍ୱୟଂଚାଳିତ ରାଉଟିଙ୍ଗ୍ ନିୟମ",
            "autoAssignmentEngine": "AI ପ୍ରେରଣ ଇଞ୍ଜିନ୍",
            "fallbackQueues": "ଫଲବ୍ୟାକ୍ ଧାଡ଼ି"
        },
        "issues": {
            "title": "ପ୍ଲାଟଫର୍ମ ଅଭିଯୋଗ ମାଷ୍ଟର",
            "forceResolve": "ପ୍ରଶାସନିକ ସମାଧାନ",
            "reassignCluster": "ଅଭିଯୋଗ କ୍ଲଷ୍ଟର୍ ପୁନଃ ନ୍ୟସ୍ତ କରନ୍ତୁ",
            "auditLog": "ଅପରିବର୍ତ୍ତନୀୟ କାର୍ଯ୍ୟାନୁଷ୍ଠାନ ଲଗ୍",
            "purgeTestData": "ପରୀକ୍ଷଣ ତଥ୍ୟ ହଟାନ୍ତୁ"
        },
        "aiMonitoring": {
            "title": "AI ଭିଜନ୍ ଓ ଟେଲିମେଟ୍ରି ନିରୀକ୍ଷଣ",
            "geminiVisionUptime": "ଭିଜନ୍ ମଡେଲ୍ କାର୍ଯ୍ୟକ୍ଷମ ସମୟ",
            "fastApiOcrStatus": "FastAPI OCR ପାଇପଲାଇନ୍",
            "speechToTextLatency": "ଭଏସ୍ ରୂପାନ୍ତର ବିଳମ୍ବ",
            "accuracyScore": "ବର୍ଗୀକରଣ ସଠିକତା ସ୍କୋର",
            "confidenceDistribution": "ବିଶ୍ୱସନୀୟତା ବଣ୍ଟନ",
            "modelLogs": "ଇନଫରେନ୍ସ ଲେଟେନ୍ସି ଲଗ୍"
        },
        "workflowMonitoring": {
            "title": "ୱାର୍କଫ୍ଲୋ ଇଞ୍ଜିନ୍ ଓ କ୍ୟୁ ଟେଲିମେଟ୍ରି",
            "stateMachineInspect": "ଷ୍ଟେଟ୍ ମେସିନ୍ ରୂପାନ୍ତରଣ",
            "queueDepth": "ବାର୍ତ୍ତା ଧାଡ଼ି ଗଭୀରତା",
            "deadLetterQueue": "ଡେଡ୍-ଲେଟର୍ ଧାଡ଼ି",
            "retryFailedTasks": "ବିଫଳ କାର୍ଯ୍ୟ ପୁନର୍ବାର ଚେଷ୍ଟା କରନ୍ତୁ"
        },
        "analytics": {
            "title": "କ୍ରସ୍-ପ୍ଲାଟଫର୍ମ ମ୍ୟାକ୍ରୋ ବିଶ୍ଳେଷଣ",
            "crossPortalActivity": "କ୍ରସ୍-ପୋର୍ଟାଲ ବ୍ୟବହାର ମେଟ୍ରିକ୍ସ",
            "municipalPerformanceIndex": "ପୌର କାର୍ଯ୍ୟଦକ୍ଷତା ସୂଚକାଙ୍କ",
            "peakUsageHours": "ସର୍ବାଧିକ ବ୍ୟବହାର ସମୟ"
        },
        "systemHealth": {
            "title": "ଭିତ୍ତିଭୂମି ଓ ସିଷ୍ଟମ୍ ସ୍ୱାସ୍ଥ୍ୟ",
            "databaseReplicas": "ଡାଟାବେସ୍ ପ୍ରତିରୂପ",
            "redisCache": "ରେଡିସ୍ ଇନ୍-ମେମୋରୀ ସ୍ଥିତି",
            "storageUsage": "ଷ୍ଟୋରେଜ୍ ବ୍ୟବହାର",
            "apiGateways": "ମାଇକ୍ରୋସର୍ଭିସ୍ ସ୍ୱାସ୍ଥ୍ୟ",
            "uptime99": "୯୯.୯୮% ଉଚ୍ଚ ଉପଲବ୍ଧତା",
            "online": "ଅନଲାଇନ୍",
            "maintenance": "ରକ୍ଷଣାବେକ୍ଷଣ ଚାଲିଛି"
        },
        "settings": {
            "title": "ପ୍ଲାଟଫର୍ମ କନଫିଗୁରେସନ୍ ସେଟିଙ୍ଗ୍ସ",
            "maintenanceMode": "ରକ୍ଷଣାବେକ୍ଷଣ ମୋଡ୍",
            "apiRateLimits": "API ସୀମା",
            "backupSchedules": "ସ୍ୱୟଂଚାଳିତ ବ୍ୟାକଅପ୍ ସମୟସାରଣୀ",
            "smtpConfig": "ଇମେଲ୍ ଓ SMS ଗେଟୱେ"
        }
    },
    "toast": {
        "issueSubmitted": "ଅଭିଯୋଗ ସଫଳତାର ସହ ଦାଖଲ ହୋଇଛି! ଦାୟିତ୍ୱପ୍ରାପ୍ତ ବିଭାଗକୁ ପଠାଯାଇଛି।",
        "gpsCaptured": "GPS ସ୍ଥାନାଙ୍କ ଚିହ୍ନଟ ହୋଇଛି",
        "gpsCapturedDesc": "ସ୍ଥାନାଙ୍କ ଅଭିଯୋଗ ରିପୋର୍ଟ ସହିତ ସଂଲଗ୍ନ ହୋଇଛି।",
        "locationDenied": "ସ୍ଥାନ ଅନୁମତି ପ୍ରତ୍ୟାଖ୍ୟାତ ବା ଅନୁପଲବ୍ଧ। ଡିଫଲ୍ଟ ସ୍ଥାନ ବ୍ୟବହୃତ ହେଉଛି।",
        "fileSizeExceeded": "ଫାଇଲ୍ ଆକାର ୨୫MB ସୀମା ଅତିକ୍ରମ କରିଛି।",
        "audioNotSupported": "ଏହି ବ୍ରାଉଜରରେ ଅଡିଓ ରେକର୍ଡିଂ ସମର୍ଥିତ ନୁହେଁ।",
        "micSimulation": "ଭଏସ୍ ଅଭିଯୋଗ ଡେମୋ ପାଇଁ ମାଇକ୍ରୋଫୋନ୍ ସିମୁଲେସନ୍ ସକ୍ରିୟ ଅଛି।",
        "profileUpdated": "ପ୍ରୋଫାଇଲ୍ ସଫଳତାର ସହ ଅପଡେଟ୍ ହୋଇଛି।",
        "settingsSaved": "ପସନ୍ଦ ସଫଳତାର ସହ ସଂରକ୍ଷିତ ହୋଇଛି।",
        "deleteRequested": "ଆକାଉଣ୍ଟ ବିଲୋପ ଅନୁରୋଧ ଦାଖଲ ହୋଇଛି।",
        "languageChanged": "ଭାଷା ସଫଳତାର ସହ ପରିବର୍ତ୍ତିତ ହୋଇଛି।",
        "errorOccurred": "ଏକ ତ୍ରୁଟି ଘଟିଲା। ଦୟାକରି ପୁନର୍ବାର ଚେଷ୍ଟା କରନ୍ତୁ।",
        "caseUpdated": "କେସ୍ ଡକେଟ୍ ସଫଳତାର ସହ ଅପଡେଟ୍ ହୋଇଛି।",
        "caseReassigned": "ମାମଲା ନୋଡାଲ୍ ଅଫିସରଙ୍କୁ ପୁନଃ ନ୍ୟସ୍ତ କରାଯାଇଛି।",
        "caseResolved": "ଅଭିଯୋଗ ସମାଧାନ ହୋଇଥିବା ଭାବେ ଚିହ୍ନିତ ହୋଇଛି।",
        "volunteerAdded": "ନୂତନ ସ୍ୱେଚ୍ଛାସେବୀ ସଫଳତାର ସହ ପଞ୍ଜୀକୃତ ହୋଇଛନ୍ତି।",
        "grantApproved": "CSR ଅନୁଦାନ ଆବଣ୍ଟନ ଅନୁମୋଦିତ ହୋଇଛି।",
        "milestoneApproved": "ଏକାଡେମିକ୍ ମାଇଲଷ୍ଟୋନ୍ ଅନୁମୋଦିତ ହୋଇଛି।",
        "deliverableUploaded": "ସମୀକ୍ଷା ପାଇଁ ଫଳାଫଳ ଅପଲୋଡ୍ କରାଯାଇଛି।",
        "loginSuccess": "ସଫଳତାର ସହ ସାଇନ୍ ଇନ୍ ହୋଇଛି। ସ୍ୱାଗତମ୍!",
        "logoutSuccess": "ସଫଳତାର ସହ ଲଗ୍ ଆଉଟ୍ ହୋଇଛି।",
        "accessDenied": "ପ୍ରବେଶ ଅଧିକାର ସୀମିତ। ଅପର୍ଯ୍ୟାପ୍ତ ଅନୁମତି।",
        "changesSaved": "ସମସ୍ତ ପରିବର୍ତ୍ତନ ସଫଳତାର ସହ ସଂରକ୍ଷିତ ହୋଇଛି।",
        "reportExported": "ରିପୋର୍ଟ ପ୍ରସ୍ତୁତ ଓ ଡାଉନଲୋଡ୍ ହୋଇଛି।",
        "dataRefreshed": "ଟେଲିମେଟ୍ରି ତଥ୍ୟ ରିଫ୍ରେଶ୍ ହୋଇଛି।"
    },
    "language": "ଭାଷା",
    "dashboard": "ଡ୍ୟାସବୋର୍ଡ",
    "report_issue": "ଅଭିଯୋଗ ଦାଖଲ କରନ୍ତୁ",
    "report_problem": "ଅଭିଯୋଗ ଦାଖଲ କରନ୍ତୁ",
    "my_issues": "ମୋର ଅଭିଯୋଗଗୁଡିକ",
    "track_issues": "ସମାଧାନ ଟ୍ରାକ୍ କରନ୍ତୁ",
    "notifications": "ବିଜ୍ଞପ୍ତି",
    "profile": "ପ୍ରୋଫାଇଲ୍",
    "settings": "ସେଟିଙ୍ଗ୍ସ",
    "help": "ସହାୟତା ଓ ସମର୍ଥନ",
    "logout": "ଲଗ୍ ଆଉଟ୍",
    "login": "ଲଗ୍ ଇନ୍",
    "recent_grievances": "ସାମ୍ପ୍ରତିକ ଅଭିଯୋଗ",
    "issue_id": "ଅଭିଯୋଗ ନମ୍ବର (ID)",
    "citizen_portal": "ନାଗରିକ ପୋର୍ଟାଲ",
    "government_portal": "ସରକାରୀ ପୋର୍ଟାଲ",
    "university_portal": "ବିଶ୍ୱବିଦ୍ୟାଳୟ ପୋର୍ଟାଲ",
    "industry_portal": "ଶିଳ୍ପ ପୋର୍ଟାଲ",
    "ngo_portal": "NGO ପୋର୍ଟାଲ",
    "admin_portal": "ପ୍ରଶାସକ ପୋର୍ଟାଲ",
    "ai_governance_insight": "AI ପ୍ରଶାସନିକ ଅନ୍ତର୍ଦୃଷ୍ଟି",
    "resolution": "ସମାଧାନ",
    "report": "ରିପୋର୍ଟ",
    "map": "ଘଟଣା ମ୍ୟାପ୍",
    "search": "ଖୋଜନ୍ତୁ",
    "search_placeholder": "ଅଭିଯୋଗ, ମାମଲା, ସ୍ଥାନ ଖୋଜନ୍ତୁ...",
    "filter": "ଫିଲ୍ଟର୍",
    "save": "ପରିବର୍ତ୍ତନ ସଂରକ୍ଷଣ କରନ୍ତୁ",
    "cancel": "ବାତିଲ କରନ୍ତୁ",
    "delete": "ଡିଲିଟ୍ କରନ୍ତୁ",
    "submit": "ଦାଖଲ କରନ୍ତୁ",
    "upload": "ଅପଲୋଡ୍ କରନ୍ତୁ",
    "location": "ସ୍ଥାନ",
    "description": "ବର୍ଣ୍ଣନା",
    "title": "ଶୀର୍ଷକ",
    "category": "ବର୍ଗ",
    "department": "ବିଭାଗ",
    "created_at": "ରିପୋର୍ଟ ତାରିଖ",
    "action": "କାର୍ଯ୍ୟାନୁଷ୍ଠାନ",
    "actions": "କାର୍ଯ୍ୟାନୁଷ୍ଠାନଗୁଡିକ",
    "view": "ଦେଖନ୍ତୁ",
    "edit": "ସମ୍ପାଦନ କରନ୍ତୁ",
    "loading": "ଲୋଡ୍ ହେଉଛି...",
    "success": "ସଫଳ",
    "error": "ଏକ ତ୍ରୁଟି ଘଟିଲା",
    "welcome_back": "ସ୍ୱାଗତମ୍",
    "total_issues": "ମୋଟ ଅଭିଯୋଗ",
    "resolved_issues": "ସମାଧାନ ହୋଇଥିବା ଅଭିଯୋଗ",
    "in_progress_issues": "ପ୍ରକ୍ରିୟାଧୀନ ଅଭିଯୋଗ",
    "pending_issues": "ବିଚାରାଧୀନ ଅଭିଯୋଗ",
    "active_projects": "ସକ୍ରିୟ ପ୍ରକଳ୍ପ",
    "ai_accuracy": "AI ରାଉଟିଙ୍ଗ୍ ସଠିକତା",
    "sla_compliance": "SLA ଅନୁପାଳନ ହାର",
    "civic_engagement": "ନାଗରିକ ସହଭାଗୀତା ସୂଚକାଙ୍କ",
    "recent_activity": "ସାମ୍ପ୍ରତିକ କାର୍ଯ୍ୟକଳାପ",
    "quick_actions": "ଦ୍ରୁତ କାର୍ଯ୍ୟାନୁଷ୍ଠାନ",
    "live_incidents": "ଲାଇଭ୍ ପୌର ଘଟଣା",
    "all": "ସମସ୍ତ",
    "high": "ଉଚ୍ଚ ପ୍ରାଥମିକତା",
    "medium": "ମଧ୍ୟମ ପ୍ରାଥମିକତା",
    "low": "କମ୍ ପ୍ରାଥମିକତା",
    "critical": "ସଙ୍କଟଜନକ ପ୍ରାଥମିକତା",
    "emergency": "ଜରୁରୀକାଳୀନ ପ୍ରାଥମିକତା",
    "pending": "ବିଚାରାଧୀନ",
    "in_progress": "ପ୍ରକ୍ରିୟାଧୀନ",
    "resolved": "ସମାଧାନ ହୋଇଛି",
    "closed": "ବନ୍ଦ ହୋଇଛି",
    "rejected": "ପ୍ରତ୍ୟାଖ୍ୟାତ",
    "approved": "ଅନୁମୋଦିତ",
    "declined": "ପ୍ରତ୍ୟାଖ୍ୟାତ",
    "export": "ତଥ୍ୟ ରପ୍ତାନି କରନ୍ତୁ",
    "download": "ଡାଉନଲୋଡ୍",
    "confirm": "ନିଶ୍ଚିତ କରନ୍ତୁ",
    "close": "ବନ୍ଦ କରନ୍ତୁ",
    "back": "ପଛକୁ",
    "next": "ପରବର୍ତ୍ତୀ",
    "previous": "ପୂର୍ବବର୍ତ୍ତୀ",
    "no_results": "କୌଣସି ଫଳାଫଳ ମିଳିଲା ନାହିଁ",
    "view_all": "ସମସ୍ତ ଦେଖନ୍ତୁ",
    "home": "ହୋମ୍",
    "feed": "ନାଗରିକ ଫିଡ୍",
    "analytics": "AI ବିଶ୍ଳେଷଣ",
    "optional": "ଇଚ୍ଛାଧୀନ",
    "faculty": "ଅଧ୍ୟାପକ ମାର୍ଗଦର୍ଶକ",
    "student": "ଛାତ୍ର ଦଳ",
    "projects": "ପ୍ରକଳ୍ପ",
    "research": "ଗବେଷଣା କେନ୍ଦ୍ର",
    "innovation": "ଉଦ୍ଭାବନ ଚ୍ୟାଲେଞ୍ଜ",
    "teams": "ଦଳଗୁଡିକ",
    "credits": "ଏକାଡେମିକ୍ କ୍ରେଡିଟ୍",
    "officers": "ଅଧିକାରୀ ତାଲିକା",
    "assigned": "ନ୍ୟସ୍ତ ମାମଲା",
    "under_review": "ସମୀକ୍ଷାଧୀନ",
    "industry_assigned": "ଶିଳ୍ପ ସହଭାଗୀଙ୍କୁ ନ୍ୟସ୍ତ",
    "industry_review": "ଶିଳ୍ପ ସମୀକ୍ଷା",
    "univ_assigned": "ବିଶ୍ୱବିଦ୍ୟାଳୟକୁ ନ୍ୟସ୍ତ",
    "student_dev": "ଛାତ୍ର ବିକାଶ କାର୍ଯ୍ୟ",
    "faculty_review": "ଅଧ୍ୟାପକ ସମୀକ୍ଷା",
    "industry_val": "ଶିଳ୍ପ ବୈଧିକରଣ",
    "inspection": "କ୍ଷେତ୍ର ପରିଦର୍ଶନ",
    "feedback": "ମତାମତ ଅପେକ୍ଷିତ"
}

def get_keys(d, p=""):
    r = []
    for k, v in d.items():
        c = f"{p}.{k}" if p else k
        if isinstance(v, dict):
            r.extend(get_keys(v, c))
        else:
            r.append(c)
    return set(r)

base_keys = get_keys(base)
or_keys = get_keys(OR_DICT)
diff = base_keys.symmetric_difference(or_keys)

if diff:
    print(f"Key mismatch in OR! Diff count: {len(diff)}")
    print("Diff items:", diff)
    sys.exit(1)

print(f"OR 100% matched! Total keys: {len(or_keys)}. Writing scripts/data_or.py...")

out_path = os.path.join(os.path.dirname(os.path.abspath(__file__)), "data_or.py")
with open(out_path, "w", encoding="utf-8") as f:
    f.write("# -*- coding: utf-8 -*-\n")
    f.write('"""Odia (or) translations dictionary for SOCIAL-X platform"""\n\n')
    f.write("def get_or_dict():\n")
    f.write("    return " + json.dumps(OR_DICT, ensure_ascii=False, indent=4) + "\n")

print(f"Successfully generated {out_path}!")
