# -*- coding: utf-8 -*-
"""
Generates data_mr.py with 100% key parity with get_base_en()
"""

import sys, os, json
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from scripts.generate_all_translations import get_base_en

base = get_base_en()

# Marathi translation dictionary
# Translating every section with authentic Marathi administrative, civic & portal terms

MR_DICT = {
    "nav": {
        "overview": "आढावा",
        "access_identity": "प्रवेश आणि ओळख",
        "stakeholder_ecosystem": "भागधारक परिसंस्था",
        "operations_ai": "ऑपरेशन्स आणि एआय",
        "infra_observability": "पायाभूत सुविधा आणि वेधशाळा",
        "field_activities": "फील्ड उपक्रम आणि मदत",
        "community_workforce": "समुदाय आणि कार्यबल",
        "governance_comms": "प्रशासन आणि संप्रेषण",
        "csr_investment": "सीएसआर आणि भांडवल वाटप",
        "collaboration_rd": "सहकार्य आणि संशोधन",
        "student_portal": "विद्यार्थी पोर्टल",
        "faculty_portal": "प्राध्यापक पोर्टल",
        "dashboard": "डॅशबोर्ड",
        "my_issues": "माझ्या तक्रारी",
        "report_problem": "तक्रार नोंदवा",
        "track_issues": "निकालाचा मागोवा घ्या",
        "notifications": "सूचना",
        "profile": "प्रोफाइल",
        "settings": "सेटिंग्ज",
        "help": "मदत आणि सहाय्य",
        "logout": "लॉग आउट",
        "login": "लॉग इन",
        "analytics": "विश्लेषण आणि अहवाल",
        "assigned_cases": "सोपवलेली प्रकरणे",
        "departments": "विभाग",
        "officers": "अधिकारी निर्देशिका",
        "ai_suggestions": "एआय सूचना",
        "reports": "अहवाल आणि लेखापरीक्षण",
        "projects": "उपलब्ध प्रकल्प",
        "funding": "निधीच्या संधी",
        "csr_analytics": "सीएसआर विश्लेषण",
        "mentorship": "मार्गदर्शन",
        "university_collaboration": "विद्यापीठ सहकार्य",
        "research": "संशोधन उपक्रम",
        "prototypes": "प्रोटोटाइप आणि प्रात्यक्षिके",
        "volunteers": "स्वयंसेवक पथके",
        "field_log": "फील्ड पुरावा नोंद",
        "impact": "सामुदायिक प्रभाव",
        "certificates": "प्रमाणपत्रे आणि बॅज",
        "lab_tasks": "लॅब कार्ये",
        "upload_deliverables": "सादरणीय घटक अपलोड करा",
        "milestone_timeline": "टप्पा टाइमलाइन",
        "advisor_discussion": "सल्लागार चर्चा",
        "milestone_approvals": "टप्पा मंजुरी",
        "municipal_proposals": "महानगरपालिका प्रस्ताव",
        "teams": "संघ आणि रोस्टर",
        "credits": "शैक्षणिक क्रेडिट्स",
        "user_management": "वापरकर्ता व्यवस्थापन",
        "role_management": "भूमिका व्यवस्थापन",
        "government_management": "सरकारी व्यवस्थापन",
        "university_management": "विद्यापीठ व्यवस्थापन",
        "industry_management": "उद्योग व्यवस्थापन",
        "ngo_management": "एनजीओ व्यवस्थापन",
        "research_organizations": "संशोधन संस्था",
        "issue_management": "तक्रार व्यवस्थापन",
        "ai_monitoring": "एआय टेलिमेट्री देखरेख",
        "workflow_monitoring": "कार्यप्रवाह देखरेख",
        "audit_logs": "अपरिवर्तनीय ऑडिट ट्रेल",
        "system_health": "प्रणाली आरोग्य",
        "landing_features": "वैशिष्ट्ये",
        "landing_how_it_works": "हे कसे कार्य करते",
        "landing_about": "आमच्याबद्दल",
        "landing_faq": "नेहमी विचारले जाणारे प्रश्न",
        "landing_contact": "संपर्क",
        "role_login": "भूमिका लॉगिन",
        "citizen_sign_up": "नागरिक नोंदणी"
    },
    "common": {
        "buttons": {
            "browseFiles": "फायली ब्राउझ करा",
            "openCamera": "कॅमेरा उघडा",
            "startRecording": "रेकॉर्डिंग सुरू करा",
            "stopRecording": "रेकॉर्डिंग थांबवा",
            "submit": "सबमिट करा",
            "cancel": "रद्द करा",
            "save": "बदल जतन करा",
            "delete": "हटवा",
            "search": "शोधा",
            "filter": "फिल्टर",
            "upload": "अपलोड करा",
            "confirm": "पुष्टी करा",
            "close": "बंद करा",
            "back": "मागे",
            "next": "पुढे",
            "previous": "मागील",
            "detectLocation": "वर्तमान स्थान शोधा",
            "useCurrentGps": "वर्तमान GPS वापरा",
            "resetForm": "फॉर्म रीसेट करा",
            "submitIssue": "तक्रार नोंदवा",
            "viewAll": "सर्व पहा",
            "export": "डेटा निर्यात करा",
            "download": "डाउनलोड",
            "refresh": "रिफ्रेश करा",
            "login": "लॉग इन",
            "logout": "लॉग आउट",
            "modifyUploads": "अपलोड सुधारित करा",
            "removeFile": "फाइल काढा",
            "removeVoiceMemo": "व्हॉइस मेमो काढा",
            "edit": "संपादित करा",
            "view": "तपशील पहा",
            "add": "नवीन जोडा",
            "create": "तयार करा",
            "update": "अपडेट करा",
            "approve": "मंजूर करा",
            "reject": "नाकारा",
            "reassign": "पुन्हा सोपवा",
            "escalate": "प्रकरण वाढवा",
            "resolve": "प्रकरण सोडवा",
            "assign": "सोपवा",
            "verify": "पडताळणी करा",
            "downloadReport": "अहवाल डाउनलोड करा",
            "syncTelemetry": "टेलिमेट्री सिंक करा",
            "applyFilters": "फिल्टर लागू करा",
            "clearFilters": "फिल्टर साफ करा",
            "viewDetails": "तपशील पहा",
            "sendNotification": "सूचना पाठवा",
            "inviteMember": "सदस्याला आमंत्रित करा",
            "print": "प्रिंट करा",
            "share": "शेअर करा",
            "copyLink": "लिंक कॉपी करा",
            "proceed": "पुढे जा",
            "retry": "पुन्हा प्रयत्न करा",
            "dismiss": "काढून टाका",
            "accept": "स्वीकारा",
            "decline": "नाकारा"
        },
        "labels": {
            "dashboard": "डॅशबोर्ड",
            "profile": "प्रोफाइल",
            "settings": "सेटिंग्ज",
            "notifications": "सूचना",
            "help": "मदत आणि सहाय्य",
            "logout": "लॉग आउट",
            "login": "लॉग इन",
            "status": "स्थिती",
            "priority": "प्राधान्य",
            "department": "विभाग",
            "category": "वर्गवारी",
            "district": "जिल्हा",
            "ward": "प्रभाग",
            "address": "पत्ता",
            "landmark": "महत्त्वाचे ठिकाण",
            "title": "शीर्षक",
            "description": "वर्णन",
            "location": "स्थान",
            "latitude": "अक्षांश",
            "longitude": "रेखांश",
            "accuracy": "अचूकता",
            "date": "दिनांक",
            "action": "कृती",
            "actions": "कृती",
            "all": "सर्व",
            "high": "उच्च",
            "medium": "मध्यम",
            "low": "कमी",
            "critical": "गंभीर",
            "emergency": "तातडीचे",
            "pending": "प्रलंबित",
            "inProgress": "प्रगतीपथावर",
            "resolved": "निराकरण झाले",
            "closed": "बंद केले",
            "rejected": "नाकारले",
            "verified": "पडताळणी झाली",
            "assigned": "सोपवले",
            "recentActivity": "अलीकडील हालचाली",
            "quickActions": "त्वरित कृती",
            "systemHealth": "प्रणाली आरोग्य",
            "language": "भाषा",
            "selectLanguage": "भाषा निवडा",
            "searchLanguage": "भाषा शोधा...",
            "editable": "संपादनक्षम",
            "active": "सक्रिय",
            "inactive": "निष्क्रिय",
            "completed": "पूर्ण झाले",
            "failed": "अयशस्वी",
            "total": "एकूण",
            "count": "संख्या",
            "rate": "दर",
            "percentage": "टक्केवारी",
            "timeRemaining": "उर्वरित वेळ",
            "dueDate": "अंतिम तारीख",
            "submittedBy": "सादरकर्ता",
            "assignedTo": "सोपवले गेलेले",
            "officerInCharge": "प्रभारी अधिकारी",
            "slaTimer": "SLA टाइमर",
            "auditTimeline": "ऑडिट टाइमलाइन",
            "contactInfo": "संपर्क माहिती",
            "phoneNumber": "फोन नंबर",
            "emailAddress": "ईमेल पत्ता",
            "fullName": "पूर्ण नाव",
            "role": "भूमिका",
            "organization": "संस्था",
            "institution": "शैक्षणिक संस्था",
            "createdAt": "नोंदणी तारीख",
            "updatedAt": "अद्यतन तारीख"
        },
        "status": {
            "open": "उघडे",
            "submitted": "नोंदणी झाली",
            "verified": "पडताळणी झाली",
            "assigned": "सोपवले",
            "in_progress": "प्रगतीपथावर",
            "inProgress": "प्रगतीपथावर",
            "resolved": "निराकरण झाले",
            "closed": "बंद केले",
            "rejected": "नाकारले",
            "under_review": "पुनरावलोकन सुरू",
            "under_government_review": "शासकीय पुनरावलोकन सुरू",
            "assigned_to_government": "महानगरपालिकेकडे सोपवले",
            "assigned_to_industry": "उद्योग भागीदाराकडे सोपवले",
            "industry_review": "उद्योग पुनरावलोकन",
            "assigned_to_university": "विद्यापीठाकडे सोपवले",
            "student_development": "विद्यार्थी विकास कार्य",
            "faculty_review": "प्राध्यापक पुनरावलोकन",
            "industry_validation": "उद्योग प्रमाणीकरण",
            "inspection": "स्थळ पाहणी",
            "feedback_pending": "अभिप्राय प्रलंबित",
            "escalated": "वरिष्ठांकडे पाठवले",
            "active": "सक्रिय",
            "inactive": "निष्क्रिय",
            "completed": "पूर्ण झाले",
            "approved": "मंजूर केले",
            "declined": "नाकारले",
            "pending": "प्रलंबित"
        },
        "priority": {
            "low": "कमी प्राधान्य",
            "medium": "मध्यम प्राधान्य",
            "high": "उच्च प्राधान्य",
            "critical": "गंभीर प्राधान्य",
            "emergency": "तातडीचे / आणीबाणी",
            "urgent": "अत्यंत तातडीचे"
        },
        "departments": {
            "waterSupply": "पाणी पुरवठा आणि जलनिस्सारण",
            "roadsTransport": "रस्ते आणि वाहतूक व्यवस्थापन",
            "electricityPower": "विद्युत आणि ऊर्जा ग्रीड",
            "solidWaste": "घनकचरा व्यवस्थापन",
            "publicHealth": "सार्वजनिक आरोग्य आणि स्वच्छता",
            "urbanPlanning": "नगर रचना आणि विकास",
            "education": "शिक्षण आणि कौशल्य विकास",
            "environmentForest": "पर्यावरण आणि वन संरक्षण",
            "policeSafety": "पोलीस आणि नागरी सुरक्षा",
            "disasterManagement": "आपत्ती व्यवस्थापन आणि अग्निशामक",
            "municipalAdmin": "सामान्य महानगरपालिका प्रशासन"
        },
        "categories": {
            "water": "पाणी पुरवठा आणि गळती",
            "roads": "रस्ते आणि खड्डे",
            "electricity": "वीज आणि पथदिवे",
            "waste": "कचरा आणि स्वच्छता",
            "health": "सार्वजनिक आरोग्य आणि स्वच्छता",
            "sanitation": "सांडपाणी आणि गटारे",
            "infrastructure": "सार्वजनिक पायाभूत सुविधा",
            "streetlights": "पथदिवे",
            "drainage": "तुंबलेली गटारे",
            "potholes": "खड्डे",
            "traffic": "वाहतूक कोंडी",
            "pollution": "प्रदूषण"
        },
        "validation": {
            "requiredField": "हे फील्ड आवश्यक आहे",
            "titleRequired": "तक्रारीचे शीर्षक आवश्यक आहे",
            "descriptionRequired": "समस्येचे सविस्तर वर्णन आवश्यक आहे",
            "locationRequired": "स्थान निर्देशांक किंवा पत्ता आवश्यक आहे",
            "invalidEmail": "कृपया वैध ईमेल पत्ता प्रविष्ट करा",
            "invalidPassword": "पासवर्ड नियमांनुसार असणे आवश्यक आहे",
            "passwordTooShort": "पासवर्ड किमान ८ अक्षरांचा असावा",
            "passwordMismatch": "पासवर्ड जुळत नाहीत",
            "unsupportedFile": "फाइल फॉरमॅट समर्थित नाही (केवळ JPG, PNG, PDF, MP4, MP3)",
            "maxFileSizeExceeded": "फाइलचा आकार २५MB पेक्षा जास्त असू नये",
            "micPermissionDenied": "मायक्रोफोन परवानगी नाकारली गेली",
            "cameraPermissionDenied": "कॅमेरा परवानगी नाकारली गेली",
            "minLength": "किमान आवश्यक लांबी पूर्ण करा",
            "maxLength": "कमाल अक्षरांची मर्यादा ओलांडली",
            "uploadFailed": "फाइल अपलोड अयशस्वी",
            "uploadSuccessful": "फाइल यशस्वीरित्या अपलोड केली",
            "loginSuccessful": "लॉग इन यशस्वी झाले",
            "registrationSuccessful": "नोंदणी यशस्वी झाली",
            "fillRequiredFields": "कृपया सर्व आवश्यक फील्ड्स भरा"
        },
        "emptyStates": {
            "noData": "कोणताही डेटा उपलब्ध नाही",
            "noResults": "शोध परिणामांमध्ये काहीही आढळले नाही",
            "noNotifications": "कोणतीही नवीन सूचना नाही",
            "noIssuesFound": "कोणतीही तक्रार आढळली नाही",
            "noProjectsFound": "कोणतेही प्रकल्प आढळले नाहीत",
            "noOfficersFound": "कोणतेही अधिकारी आढळले नाहीत",
            "noActivitiesFound": "कोणतीही अलीकडील हालचाल नाही"
        },
        "loading": {
            "loading": "लोड होत आहे...",
            "pleaseWait": "कृपया प्रतीक्षा करा...",
            "fetchingData": "नवीनतम माहिती मिळवत आहे...",
            "processing": "प्रक्रिया सुरू आहे...",
            "uploadingMedia": "मीडिया फाइल्स अपलोड होत आहेत...",
            "analyzingAi": "एआय प्रणालीद्वारे विश्लेषण सुरू आहे...",
            "savingChanges": "बदल जतन केले जात आहेत..."
        },
        "pagination": {
            "previous": "मागील",
            "next": "पुढील",
            "page": "पृष्ठ",
            "of": "पैकी",
            "rowsPerPage": "पंक्ती प्रति पृष्ठ",
            "showing": "दर्शवित आहे",
            "entries": "प्रविष्ट्या",
            "totalRecords": "एकूण नोंदी"
        },
        "search": {
            "searchPlaceholder": "तक्रारी, प्रकरणे, स्थान शोधा...",
            "searchGrievances": "तक्रारी शोधा...",
            "searchUsers": "वापरकर्ते शोधा...",
            "searchDepartments": "विभाग शोधा...",
            "searchProjects": "प्रकल्प शोधा...",
            "searchOfficers": "अधिकारी शोधा...",
            "quickNavigator": "त्वरित नेव्हिगेटर...",
            "searchAll": "सर्व शोधा..."
        }
    },
    "ai": {
        "processing": "एआय प्रक्रिया सुरू आहे",
        "ocrResult": "ओसीआर द्वारे काढलेला मजकूर",
        "speechResult": "स्थानिक व्हॉइस ट्रान्सक्रिप्ट",
        "speechTranscript": "ध्वनी ट्रान्सक्रिप्ट",
        "confidenceScore": "एआय विश्वासार्हता निर्देशांक",
        "aiConfidence": "एआय विश्वासार्हता",
        "suggestedCategory": "सुचवलेली वर्गवारी",
        "suggestedDepartment": "सुचवलेला विभाग",
        "recommendedDepartment": "शिफारस केलेला विभाग",
        "suggestedIndustry": "सुचवलेला उद्योग भागीदार",
        "duplicateDetection": "समान तक्रार तपासणी",
        "aiVerification": "मल्टीमॉडल व्हिजन पडताळणी",
        "smartRouting": "स्मार्ट विभागीय रूटिंग",
        "previewTitle": "मल्टीमॉडल एआय माहिती पूर्वावलोकन",
        "previewSubtitle": "संगणक दृष्टी आणि ध्वनी प्रणालीने खालील माहिती काढली आहे. सबमिट करण्यापूर्वी तपासा.",
        "detectedHeadline": "ओळखलेले तक्रार शीर्षक",
        "classifiedCategory": "एआय वर्गीकृत वर्गवारी",
        "dispatchedDept": "वाटप केलेला महानगरपालिका विभाग",
        "severityPriority": "तीव्रता आणि प्राधान्यक्रम",
        "mappedLocation": "नकाशावरील अचूक स्थान",
        "confirmSubmit": "तपासणी पुष्टी करा आणि तक्रार पाठवा",
        "cancel": "रद्द करा",
        "ocrBadge": "FastAPI ओसीआर निष्कर्ष",
        "sttBadge": "व्हॉइस ट्रान्सक्रिप्ट तयार",
        "verificationStep": "नागरिक पडताळणी टप्पा",
        "verificationStepHelp": "१००% अचूकतेसाठी आपण सबमिट करण्यापूर्वी खालील फील्ड्स संपादित करू शकता.",
        "ocrVision": "ओसीआर व्हिजन निष्कर्ष",
        "noOcrText": "पाटीवर कोणताही मजकूर आढळला नाही",
        "noAudioMemo": "कोणताही ऑडिओ मेमो जोडलेला नाही",
        "priorityScore": "गणित केलेले प्राधान्य गुण",
        "estimatedCost": "अंदाजे दुरुस्ती खर्च",
        "estimatedTime": "अंदाजे निराकरण वेळ",
        "recommendation": "एआय प्रशासन शिफारस",
        "confidenceHigh": "उच्च विश्वासार्हता (>९०%)",
        "confidenceMedium": "मध्यम विश्वासार्हता (७०-९०%)",
        "confidenceLow": "कमी विश्वासार्हता (<७०%)",
        "duplicateFound": "संभाव्य समान तक्रार आढळली",
        "duplicateScore": "समानता गुण"
    },
    "citizen": {
        "portalTitle": "नागरिक सेवा आणि तक्रार पोर्टल",
        "dashboard": {
            "welcomeBack": "पुन्हा स्वागत आहे",
            "totalReported": "एकूण नोंदवलेल्या तक्रारी",
            "inProgress": "प्रगतीपथावर",
            "resolved": "निराकरण झालेले",
            "needsVerification": "पडताळणी आवश्यक",
            "communityImpact": "सामुदायिक प्रभाव",
            "avgResolution": "सरासरी निराकरण वेळ",
            "recentGrievances": "माझ्या अलीकडील तक्रारी",
            "reportNewIssue": "नवीन तक्रार नोंदवा",
            "myIssues": "माझ्या तक्रारी",
            "trackIssues": "निकालाचा मागोवा घ्या",
            "liveIncidents": "थेट नागरी घटना",
            "civicFeed": "नागरी फीड",
            "satisfactionScore": "समाधान निर्देशांक",
            "activeCases": "सक्रिय प्रकरणे",
            "resolvedCases": "सोडवलेली प्रकरणे"
        },
        "report": {
            "title": "नवीन नागरी तक्रार नोंदवा",
            "subtitle": "फोटो, ऑडिओ आणि अचूक GPS सह समस्या नोंदवा. एआय प्रणाली तात्काळ योग्य विभागाकडे पाठवेल.",
            "multimodalBadge": "मल्टीमॉडल एआय विश्लेषण सक्रिय",
            "moduleBadge": "स्मार्ट नागरिक तक्रार मॉड्यूल",
            "uploadEvidence": "फोटो किंवा व्हिडिओ पुरावा अपलोड करा",
            "uploadSubtitle": "स्पष्ट छायाचित्रे समस्येचे जलद निराकरण करण्यास मदत करतात",
            "dragDrop": "फाइल येथे ड्रॅग आणि ड्रॉप करा किंवा",
            "supportedFormats": "PNG, JPG, MP4, MP3 (कमाल २५MB)",
            "browseFiles": "फायली ब्राउझ करा",
            "openCamera": "कॅमेरा उघडा",
            "uploadingProgress": "अपलोड होत आहे...",
            "attachedEvidence": "जोडलेला पुरावा",
            "voiceGrievance": "व्हॉइस तक्रार रेकॉर्ड करा",
            "optional": "पर्यायी",
            "voiceSubtitle": "आपली समस्या स्थानिक भाषेत थेट बोलून सांगा",
            "pressRecordHelp": "बोलणे सुरू करण्यासाठी मायक्रोफोन दाबा",
            "startVoiceRecording": "व्हॉइस मेमो सुरू करा",
            "stopRecording": "रेकॉर्डिंग थांबवा",
            "recording": "रेकॉर्ड होत आहे...",
            "speechProcessing": "स्थानिक भाषेचे मजकुरात रूपांतर होत आहे...",
            "speechConverted": "भाषण मजकुरात रूपांतरित झाले",
            "incidentLocation": "समस्येचे अचूक स्थान",
            "locationSubtitle": "नकाशावर अचूक जागा दर्शवा किंवा GPS वापरा",
            "useCurrentGps": "माझे चालू GPS स्थान वापरा",
            "streetAddress": "रस्ता किंवा पत्ता",
            "addressPlaceholder": "रस्त्याचे नाव, वॉर्ड क्रमांक...",
            "mapTip": "अचूक स्थानासाठी नकाशावरील पिन हलवा",
            "contextTitle": "समस्येचा संदर्भ आणि तपशील",
            "contextSubtitle": "अधिकाऱ्यांना समजण्यासाठी योग्य वर्गवारी व माहिती द्या",
            "headlineLabel": "तक्रारीचे संक्षिप्त शीर्षक",
            "headlinePlaceholder": "उदा. मुख्य रस्त्यावर पडलेला मोठा धोकादायक खड्डा",
            "detailsLabel": "सविस्तर वर्णन",
            "detailsPlaceholder": "समस्येचे अचूक स्वरूप, वाहतुकीस होणारा अडथळा व धोके विशद करा...",
            "categoryLabel": "समस्येची वर्गवारी",
            "priorityLabel": "तातडीचे प्राधान्य",
            "generateAiPreview": "एआय पूर्वावलोकन व्युत्पन्न करा",
            "processingAi": "एआय प्रणाली माहिती तपासत आहे...",
            "audioMemo": "ऑडिओ मेमो जोडला गेला",
            "readyStt": "ट्रान्सक्रिप्ट तयार आहे",
            "incidentCoordinates": "घटना निर्देशांक",
            "currentDetectedLocation": "सध्या शोधलेले स्थान"
        },
        "track": {
            "title": "तक्रार निवारण ट्रॅकर",
            "subtitle": "नोंदवलेल्या तक्रारीची सद्यस्थिती, नियुक्त अधिकारी आणि कारवाईचा थेट मागोवा घ्या.",
            "enterId": "तक्रार क्रमांक (ID) प्रविष्ट करा",
            "searchPlaceholder": "उदा. GRV-2026-8942",
            "currentStage": "सद्यस्थिती टप्पा",
            "assignedTo": "सोपवले गेलेले",
            "officerInCharge": "नोडल अधिकारी",
            "slaTimer": "SLA मर्यादा",
            "timeline": "निराकरण टाइमलाइन",
            "trackingDetails": "तपशीलवार मागोवा",
            "liveStatusTransitions": "थेट स्थिती संक्रमण"
        },
        "profile": {
            "title": "नागरिक प्रोफाइल आणि ओळख",
            "fullName": "पूर्ण नाव",
            "email": "ईमेल पत्ता",
            "phone": "नोंदणीकृत मोबाइल क्रमांक",
            "district": "जिल्हा",
            "address": "निवासी पत्ता",
            "saveProfile": "प्रोफाइल जतन करा",
            "citizenBadge": "सत्यापित नागरिक बॅज",
            "verificationStatus": "ओळख पडताळणी स्थिती"
        },
        "settings": {
            "title": "खाते आणि सुरक्षा सेटिंग्ज",
            "notifications": "सूचना प्राधान्ये",
            "emailAlerts": "ईमेल सूचना",
            "smsAlerts": "एसएमएस सूचना",
            "theme": "थीम (डार्क / लाइट मोड)",
            "language": "अनुप्रयोग भाषा",
            "savePreferences": "प्राधान्ये जतन करा"
        }
    },
    "government": {
        "portalTitle": "महानगरपालिका प्रशासन आणि नियंत्रण केंद्र",
        "dashboard": {
            "title": "प्रशासकीय नियंत्रण कक्ष",
            "overview": "एकूण विहंगावलोकन",
            "assignedCases": "सोपवलेली प्रकरणे",
            "liveCases": "थेट सक्रिय प्रकरणे",
            "slaBreachRisk": "SLA उल्लंघनाचा धोका",
            "avgTurnaround": "सरासरी निराकरण कालावधी",
            "citizenSatisfaction": "नागरिक समाधान निर्देशांक",
            "urgentDocket": "तातडीचे डॉकेट्स",
            "viewQueue": "तक्रार रांग पहा",
            "syncTelemetry": "टेलिमेट्री सिंक करा",
            "telemetryActive": "थेट टेलिमेट्री सक्रिय",
            "monthlyTrends": "मासिक ट्रेंड्स",
            "resolutionBreakdown": "निराकरण वर्गीकरण",
            "districtHeatmap": "जिल्हा तक्रार घनता नकाशा",
            "departmentEfficiency": "विभागीय कार्यक्षमता",
            "docketOverview": "डॉकेट विहंगावलोकन",
            "statutoryTarget": "वैधानिक उद्दिष्ट"
        },
        "officers": {
            "title": "क्षेत्रीय अधिकारी निर्देशिका",
            "directory": "अधिकारी यादी",
            "addOfficer": "नवीन अधिकारी जोडा",
            "officerName": "अधिकाऱ्याचे नाव",
            "designation": "पदनाम",
            "department": "विभाग",
            "contact": "संपर्क क्रमांक",
            "assignedCount": "सोपवलेली प्रकरणे",
            "resolutionRate": "निराकरण दर",
            "status": "स्थिती",
            "actions": "कृती",
            "searchOfficers": "अधिकारी शोधा..."
        },
        "departments": {
            "title": "महानगरपालिका विभाग व्यवस्थापन",
            "municipalDepartments": "सर्व महानगरपालिका विभाग",
            "addDepartment": "नवीन विभाग जोडा",
            "deptName": "विभागाचे नाव",
            "headOfDept": "विभागीय प्रमुख",
            "activePersonnel": "कार्यरत कर्मचारी",
            "budgetAllocated": "मंजूर वार्षिक तरतूद",
            "openGrievances": "प्रलंबित तक्रारी",
            "slaCompliance": "SLA अनुपालन दर",
            "efficiencyRating": "कार्यक्षमता रेटिंग",
            "searchDepartments": "विभाग शोधा..."
        },
        "assigned": {
            "title": "मला सोपवलेली नागरी प्रकरणे",
            "caseId": "डॉकेट क्रमांक",
            "citizenName": "नागरिकाचे नाव",
            "category": "वर्गवारी",
            "priority": "प्राधान्य",
            "status": "स्थिती",
            "dateReported": "नोंदणी तारीख",
            "targetResolution": "लक्ष्यित निराकरण तारीख",
            "reassign": "पुन्हा सोपवा",
            "escalate": "प्रकरण वाढवा",
            "resolveCase": "प्रकरण सोडवा",
            "viewCase": "तपशील पहा",
            "filterPriority": "प्राधान्यानुसार फिल्टर",
            "filterStatus": "स्थितीनुसार फिल्टर",
            "allCases": "सर्व प्रकरणे"
        },
        "tracking": {
            "title": "शहरव्यापी प्रकरणांचा थेट मागोवा",
            "subtitle": "नकाशावर सर्व नागरी घटना आणि तक्रारींचा थेट मागोवा घ्या",
            "liveIncidentMap": "थेट घटना नकाशा",
            "filterByWard": "प्रभागानुसार फिल्टर",
            "filterBySeverity": "तीव्रतेनुसार फिल्टर"
        },
        "aiSuggestions": {
            "title": "एआय प्रगत प्रशासकीय विश्लेषण आणि सूचना",
            "smartRoutingTitle": "बुद्धिमान रूटिंग सूचना",
            "recommendedActions": "शिफारस केलेल्या कृती",
            "anomalyDetection": "असंगती शोध",
            "duplicateClusters": "समान तक्रारींचे गट",
            "autoTriage": "स्वयंचलित ट्रायज"
        },
        "reports": {
            "title": "ऑडिट आणि कामगिरी अहवाल",
            "generateReport": "अहवाल तयार करा",
            "downloadPdf": "PDF डाउनलोड करा",
            "downloadCsv": "CSV डाउनलोड करा",
            "monthlyAudit": "मासिक ऑडिट अहवाल",
            "quarterlyPerformance": "त्रैमासिक कामगिरी",
            "exportAnalytics": "विश्लेषण निर्यात करा"
        },
        "settings": {
            "title": "विभागीय नियंत्रण कक्ष सेटिंग्ज",
            "slaThresholds": "SLA मर्यादा",
            "notificationRules": "सूचना नियम",
            "escalationMatrix": "वाढवण्याचा पदानुक्रम",
            "workingHours": "कामाचे तास"
        }
    },
    "industry": {
        "portalTitle": "उद्योग आणि कॉर्पोरेट सीएसआर पोर्टल",
        "dashboard": {
            "title": "उद्योग सीएसआर आणि नवोन्मेष डॅशबोर्ड",
            "overview": "सीएसआर विहंगावलोकन",
            "csrFunding": "सीएसआर निधी",
            "capitalAllocation": "भांडवल वाटप",
            "availableProjects": "उपलब्ध नागरी प्रकल्प",
            "liveGrants": "सक्रिय अनुदान",
            "partnershipPact": "भागीदारी करार",
            "totalDisbursed": "एकूण वितरित निधी",
            "activeProjects": "सक्रिय प्रकल्प",
            "impactScore": "सामाजिक प्रभाव गुण",
            "viewOpportunities": "संधी पहा",
            "availableCsr": "उपलब्ध सीएसआर निधी",
            "corporatePartner": "कॉर्पोरेट भागीदार",
            "verifiedEntity": "प्रमाणित संस्था"
        },
        "projects": {
            "title": "शाश्वत नागरी प्रकल्प",
            "projectCatalog": "प्रकल्प सूची",
            "fundingGoal": "निधी उद्दिष्ट",
            "raisedAmount": "उभारलेला निधी",
            "municipalSponsor": "महानगरपालिका प्रायोजक",
            "sdgImpact": "शाश्वत विकास उद्दिष्टे (SDG)",
            "applyFunding": "निधीसाठी अर्ज करा",
            "exploreInitiatives": "उपक्रम एक्सप्लोर करा",
            "searchProjects": "प्रकल्प शोधा..."
        },
        "funding": {
            "title": "सीएसआर अनुदान आणि वाटप व्यवस्थापन",
            "grantApplication": "अनुदान अर्ज",
            "disbursementStatus": "वितरण स्थिती",
            "corporateDonation": "कॉर्पोरेट देणगी",
            "taxBenefit": "कर सवलत (80G)",
            "escrowStatus": "एस्क्रो खाते स्थिती",
            "fundMilestone": "टप्प्याला निधी द्या"
        },
        "csr": {
            "title": "कंपनी सीएसआर धोरण आणि अनुपालन",
            "spendByCategory": "वर्गवारीनुसार खर्च",
            "geographicAllocation": "भौगोलिक वाटप",
            "socialReturnOnInvestment": "सामाजिक परतावा निर्देशांक (SROI)",
            "auditCompliance": "ऑडिट अनुपालन",
            "csrDistribution": "सीएसआर वितरण"
        },
        "mentorship": {
            "title": "उद्योग तज्ज्ञ आणि विद्यार्थी मार्गदर्शन",
            "expertGuidance": "तज्ज्ञ मार्गदर्शन",
            "studentPrototypes": "विद्यार्थी प्रोटोटाइप",
            "industryAdvisors": "उद्योग सल्लागार",
            "scheduleSession": "सत्र शेड्यूल करा"
        },
        "collaboration": {
            "title": "महानगरपालिका आणि शैक्षणिक सहकार्य",
            "academicPacts": "शैक्षणिक करार",
            "joinConsortium": "कन्सोर्टियममध्ये सामील व्हा",
            "jointResearch": "संयुक्त संशोधन",
            "mouSigned": "स्वाक्षरी केलेले सामंजस्य करार"
        },
        "prototypes": {
            "title": "विद्यार्थी प्रोटोटाइप आणि प्रात्यक्षिके",
            "technologyDemonstrators": "तंत्रज्ञान प्रात्यक्षिके",
            "readyForDeployment": "तैनातीसाठी तयार",
            "pilotTested": "प्रत्यक्ष चाचणी पूर्ण",
            "commercialize": "व्यावसायिकीकरण"
        },
        "tracking": {
            "title": "सीएसआर प्रभाव थेट ट्रॅकिंग",
            "milestoneProgress": "टप्पा प्रगती",
            "verificationCheck": "पडताळणी तपासणी",
            "fundRelease": "निधी वितरण"
        },
        "profile": {
            "title": "कंपनी आणि उद्योग प्रोफाइल",
            "companyName": "कंपनीचे नाव",
            "cinRegistration": "सीआयएन (CIN) नोंदणी",
            "csrBudget": "वार्षिक सीएसआर बजेट",
            "contactPerson": "संपर्क व्यक्ती",
            "panNumber": "पॅन (PAN) नंबर"
        },
        "settings": {
            "title": "उद्योग पोर्टल प्राधान्ये",
            "emailNotifications": "ईमेल सूचना",
            "bankDetails": "बँक खाते तपशील",
            "complianceDocs": "अनुपालन कागदपत्रे"
        }
    },
    "ngo": {
        "portalTitle": "स्वयंसेवी संस्था आणि नागरिक सहभाग पोर्टल",
        "dashboard": {
            "title": "स्वयंसेवी संस्था कार्य नियंत्रण केंद्र",
            "overview": "कार्य विहंगावलोकन",
            "groundSquads": "क्षेत्रीय स्वयंसेवक पथके",
            "activeVolunteers": "सक्रिय स्वयंसेवक",
            "fieldInterventions": "क्षेत्रीय हस्तक्षेप",
            "reliefOperations": "मदत मोहिमा",
            "communityImpact": "सामुदायिक प्रभाव",
            "certsAwarded": "दिलेली प्रमाणपत्रे",
            "urgentReliefCalls": "तातडीच्या मदत कॉल्स",
            "groundTelemetryLive": "थेट क्षेत्रीय टेलिमेट्री",
            "logFieldEvidence": "क्षेत्रीय पुरावा नोंदवा"
        },
        "projects": {
            "title": "समुदाय सुधारणा प्रकल्प",
            "localGrievances": "स्थानिक तक्रारी",
            "adoptIssue": "समस्या दत्तक घ्या",
            "publicWorks": "सार्वजनिक कार्ये",
            "grassrootInterventions": "तळागाळातील उपक्रम"
        },
        "assignedProjects": {
            "title": "महानगरपालिकेने दिलेले संयुक्त प्रकल्प",
            "operationalSquads": "कार्यरत पथके",
            "projectTimeline": "प्रकल्प टाइमलाइन",
            "targetCompletion": "पूर्णत्वाचे उद्दिष्ट",
            "submitProgressReport": "प्रगती अहवाल सादर करा"
        },
        "fieldActivities": {
            "title": "क्षेत्रीय उपक्रम आणि पुरावा नोंद",
            "liveReliefLog": "थेट मदत नोंद",
            "geoTaggedPhotos": "जिओ-टॅग केलेले फोटो",
            "suppliesDistributed": "वाटप केलेले साहित्य",
            "citizensAssisted": "मदत मिळालेले नागरिक",
            "addLogEntry": "नवीन नोंद जोडा"
        },
        "volunteers": {
            "title": "स्वयंसेवक व्यवस्थापन आणि संघ",
            "registerVolunteer": "नवीन स्वयंसेवक नोंदणी",
            "skillsDirectory": "कौशल्य निर्देशिका",
            "assignWard": "प्रभाग सोपवा",
            "volunteerSquads": "स्वयंसेवक पथके",
            "attendance": "उपस्थिती ट्रॅकर"
        },
        "impact": {
            "title": "नागरी प्रभाव आणि परिणाम मूल्यांकन",
            "livesImpacted": "लाभार्थी नागरिक",
            "wardsTransformed": "सुधारलेले प्रभाग",
            "satisfactionIndex": "समाधान निर्देशांक",
            "volunteerHours": "एकूण स्वयंसेवक तास"
        },
        "collaborations": {
            "title": "उद्योग आणि महानगरपालिका सहकार्य",
            "municipalMoU": "महानगरपालिका सामंजस्य करार",
            "corporateSponsors": "कॉर्पोरेट प्रायोजक",
            "universityAlliances": "विद्यापीठ युती"
        },
        "certificates": {
            "title": "प्रमाणपत्रे आणि स्वयंसेवक गौरव",
            "awardCertificate": "प्रमाणपत्र प्रदान करा",
            "downloadBadge": "बॅज डाउनलोड करा",
            "recognitionLetter": "प्रशंसापत्र"
        },
        "reports": {
            "title": "मासिक क्षेत्रीय कार्य अहवाल",
            "fieldAuditReports": "क्षेत्रीय ऑडिट अहवाल",
            "monthlyActivitySummary": "मासिक क्रियाकलाप सारांश",
            "incidentLogSheet": "घटना नोंद पत्रक",
            "submitToGovernment": "शासनाकडे सादर करा"
        },
        "settings": {
            "title": "संस्था प्रोफाइल आणि सेटिंग्ज",
            "registrationDetails": "नोंदणी तपशील",
            "ngoDarpanId": "एनजीओ दर्पण आयडी",
            "focalPoints": "संपर्क बिंदू"
        }
    },
    "university": {
        "portalTitle": "विद्यापीठ आणि शैक्षणिक नवोन्मेष पोर्टल",
        "student": {
            "dashboard": {
                "title": "विद्यार्थी डॅशबोर्ड",
                "academicCredits": "शैक्षणिक क्रेडिट्स",
                "assignedTasks": "सोपवलेली कार्ये",
                "labProjects": "प्रयोगशाळा प्रकल्प",
                "prototypeChallenges": "प्रोटोटाइप आव्हाने",
                "submitMilestone": "टप्पा सादर करा"
            },
            "tasks": {
                "title": "प्रयोगशाळा कार्ये",
                "pendingTasks": "प्रलंबित कार्ये",
                "taskDescription": "कार्याचे वर्णन",
                "dueDate": "अंतिम तारीख",
                "submitDeliverable": "सादरणीय घटक अपलोड करा",
                "advisorNotes": "मार्गदर्शकाच्या सूचना",
                "dueTasks": "देय कार्ये"
            },
            "uploads": {
                "title": "सादरणीय घटक अपलोड करा",
                "researchNotes": "संशोधन नोंदी",
                "projectCode": "प्रकल्प कोड / रिपॉझिटरी",
                "presentationSlides": "सादरीकरण स्लाइड्स",
                "submitForGrading": "मूल्यमापनासाठी सबमिट करा"
            },
            "timeline": {
                "title": "प्रकल्प टाइमलाइन",
                "projectSchedule": "प्रकल्प वेळापत्रक",
                "semesterDeadlines": "सत्र मुदत",
                "facultyReviewDate": "प्राध्यापक पुनरावलोकन तारीख"
            },
            "messages": {
                "title": "मार्गदर्शक संवाद",
                "chatWithMentor": "मार्गदर्शकाशी चर्चा",
                "feedbackThread": "अभिप्राय थ्रेड",
                "askQuestion": "प्रश्न विचारा"
            }
        },
        "faculty": {
            "dashboard": {
                "title": "प्राध्यापक डॅशबोर्ड",
                "studentCohorts": "विद्यार्थी गट",
                "mentoredProjects": "मार्गदर्शित प्रकल्प",
                "pendingApprovals": "प्रलंबित मंजुरी",
                "researchPapers": "संशोधन निबंध",
                "innovationIndex": "नवोन्मेष निर्देशांक"
            },
            "approvals": {
                "title": "टप्पा मंजुरी",
                "reviewSubmission": "सादरीकरण तपासा",
                "approveMilestone": "टप्पा मंजूर करा",
                "rejectMilestone": "टप्पा नाकारा",
                "provideFeedback": "अभिप्राय नोंदवा",
                "gradeAwarded": "दिलेली श्रेणी / ग्रेड",
                "pendingReviews": "प्रलंबित पुनरावलोकने"
            },
            "proposals": {
                "title": "महानगरपालिका प्रस्ताव",
                "civicResearchTopics": "नागरी संशोधन विषय",
                "grantProposals": "अनुदान प्रस्ताव",
                "callForPapers": "शोधनिबंधांचे आमंत्रण",
                "openProposals": "खुल्या निविदा / प्रस्ताव"
            },
            "teams": {
                "title": "संशोधन पथके",
                "teamRoster": "पथक रोस्टर",
                "assignLead": "पथक प्रमुख नियुक्त करा",
                "performanceReview": "कामगिरी पुनरावलोकन",
                "academicAdvising": "शैक्षणिक सल्ला"
            },
            "reports": {
                "title": "शैक्षणिक अहवाल",
                "cohortProgress": "गट प्रगती अहवाल",
                "publicationOutput": "प्रकाशने आउटपुट",
                "creditDistribution": "क्रेडिट वाटप अहवाल"
            }
        },
        "shared": {
            "projects": {
                "title": "विद्यापीठ प्रकल्प",
                "studentResearch": "विद्यार्थी संशोधन",
                "capstoneProjects": "कॅपस्टोन प्रकल्प",
                "interdisciplinaryTeams": "आंतरशाखीय पथके"
            },
            "research": {
                "title": "संशोधन केंद्र",
                "publications": "संशोधन प्रकाशने",
                "datasets": "नागरी डेटासेट्स",
                "patentFiling": "पेटंट दाखल करणे",
                "peerReview": "तज्ज्ञ पुनरावलोकन"
            },
            "innovation": {
                "title": "नवोन्मेष आव्हाने",
                "innovationChallenges": "स्मार्ट सिटी आव्हाने",
                "hackathonDemos": "हॅकाथॉन प्रात्यक्षिके",
                "incubatorReady": "इनक्यूबेशनसाठी सज्ज",
                "smartCityPrototypes": "स्मार्ट सिटी प्रोटोटाइप"
            },
            "credits": {
                "title": "शैक्षणिक क्रेडिट्स",
                "creditsEarned": "मिळवलेले क्रेडिट्स",
                "skillBadges": "कौशल्य बॅज",
                "hallOfFame": "सन्मान दालन",
                "transcriptVerification": "गुणपत्रिका पडताळणी"
            },
            "repository": {
                "title": "ज्ञान भांडार",
                "researchPapersArchive": "शोधनिबंध संग्रह",
                "openDataVault": "खुला डेटा संग्रह",
                "citationIndex": "उद्धरण निर्देशांक"
            },
            "settings": {
                "title": "शैक्षणिक प्रोफाइल सेटिंग्ज",
                "facultyProfile": "प्राध्यापक प्रोफाइल",
                "departmentAffiliation": "विभागीय संलग्नता",
                "orcidId": "ORCID ओळख क्रमांक"
            }
        }
    },
    "admin": {
        "portalTitle": "मध्यवर्ती प्रणाली प्रशासन आणि नियंत्रण",
        "dashboard": {
            "title": "मध्यवर्ती प्रशासन डॅशबोर्ड",
            "totalSystemUsers": "एकूण प्रणाली वापरकर्ते",
            "activePortals": "सक्रिय पोर्टल्स",
            "aiModelStatus": "एआय मॉडेल स्थिती",
            "databaseHealth": "डेटाबेस आरोग्य",
            "unresolvedGrievances": "असमाधानकारक तक्रारी",
            "platformLoad": "प्लॅटफॉर्म लोड",
            "liveEventStream": "थेट इव्हेंट प्रवाह",
            "rootConsole": "रूट कन्सोल",
            "cpuUsage": "CPU वापर",
            "dbLatency": "डेटाबेस विलंब",
            "uptime": "प्रणाली अपटाइम"
        },
        "users": {
            "title": "वापरकर्ता व्यवस्थापन",
            "allUsers": "सर्व वापरकर्ते",
            "addUser": "वापरकर्ता जोडा",
            "editRole": "भूमिका संपादित करा",
            "suspendUser": "वापरकर्ता निलंबित करा",
            "resetPassword": "पासवर्ड रीसेट करा",
            "roleFilter": "भूमिका फिल्टर",
            "searchUsers": "वापरकर्ते शोधा..."
        },
        "roles": {
            "title": "भूमिका व्यवस्थापन",
            "permissionsMatrix": "परवानग्या मॅट्रिक्स",
            "accessControl": "प्रवेश नियंत्रण",
            "createRole": "नवीन भूमिका तयार करा",
            "customRoles": "सानुकूल भूमिका"
        },
        "government": {
            "title": "महानगरपालिका प्रशासन व्यवस्थापन",
            "municipalBOD": "महानगरपालिका संचालक मंडळ",
            "cityDistricts": "शहर जिल्हे आणि झोन",
            "assignWardEngineers": "प्रभाग अभियंते नियुक्त करा"
        },
        "universities": {
            "title": "विद्यापीठ आणि शैक्षणिक संस्था",
            "registeredCampuses": "नोंदणीकृत विद्यापीठे",
            "accreditationVerify": "मान्यता पडताळणी",
            "studentCap": "विद्यार्थी मर्यादा"
        },
        "industry": {
            "title": "उद्योग आणि कॉर्पोरेट भागीदार",
            "corporatePartners": "कॉर्पोरेट भागीदार कंपन्या",
            "csrValidation": "सीएसआर वैधता तपासणी",
            "escrowAudits": "एस्क्रो खाते ऑडिट"
        },
        "ngos": {
            "title": "स्वयंसेवी संस्था आणि ट्रस्ट",
            "verifiedNgos": "मान्यताप्राप्त स्वयंसेवी संस्था",
            "darpanCheck": "एनजीओ दर्पण पडताळणी",
            "groundClearance": "क्षेत्रीय कार्य परवानगी"
        },
        "research": {
            "title": "संशोधन संस्था आणि प्रयोगशाळा",
            "institutePartnerships": "संशोधन भागीदार संस्था",
            "ethicsClearance": "नैतिकता समिती मान्यता",
            "datasetAccess": "नागरी डेटा ॲक्सेस परवानग्या"
        },
        "departments": {
            "title": "विभाग मास्टर आणि रूटिंग नियम",
            "routingRules": "स्वयंचलित रूटिंग नियम",
            "autoAssignmentEngine": "एआय प्रेषण इंजिन",
            "fallbackQueues": "पर्यायी कतार"
        },
        "issues": {
            "title": "प्लॅटफॉर्म तक्रार मास्टर",
            "forceResolve": "प्रशासकीय निराकरण",
            "reassignCluster": "तक्रार गट पुन्हा सोपवा",
            "auditLog": "अपरिवर्तनीय कृती लॉग",
            "purgeTestData": "चाचणी डेटा काढून टाका"
        },
        "aiMonitoring": {
            "title": "एआय व्हिजन आणि टेलिमेट्री देखरेख",
            "geminiVisionUptime": "व्हिजन मॉडेल अपटाइम",
            "fastApiOcrStatus": "FastAPI ओसीआर पाइपलाइन",
            "speechToTextLatency": "ध्वनी ट्रान्सक्रिप्शन विलंबता",
            "accuracyScore": "वर्गीकरण अचूकता गुण",
            "confidenceDistribution": "विश्वासार्हता वितरण",
            "modelLogs": "अनुमान विलंबता लॉग"
        },
        "workflowMonitoring": {
            "title": "कार्यप्रवाह इंजिन आणि कतार टेलिमेट्री",
            "stateMachineInspect": "स्टेट मशीन संक्रमण",
            "queueDepth": "संदेश कतार खोली",
            "deadLetterQueue": "डेड-लेटर कतार",
            "retryFailedTasks": "अयशस्वी कार्ये पुन्हा सुरू करा"
        },
        "analytics": {
            "title": "क्रॉस-प्लॅटफॉर्म मॅक्रो विश्लेषण",
            "crossPortalActivity": "क्रॉस-पोर्टल वापर मेट्रिक्स",
            "municipalPerformanceIndex": "महानगरपालिका कामगिरी निर्देशांक",
            "peakUsageHours": "सर्वोच्च वापराचे तास"
        },
        "systemHealth": {
            "title": "पायाभूत सुविधा आणि प्रणाली आरोग्य",
            "databaseReplicas": "डेटाबेस प्रतिकृती",
            "redisCache": "रेडिस इन-मेमरी स्थिती",
            "storageUsage": "ऑब्जेक्ट स्टोरेज वापर",
            "apiGateways": "मायक्रोसर्व्हिस आरोग्य",
            "uptime99": "९९.९८% उच्च उपलब्धता",
            "online": "ऑनलाइन",
            "maintenance": "देखभाल सुरू"
        },
        "settings": {
            "title": "प्लॅटफॉर्म कॉन्फिगरेशन सेटिंग्ज",
            "maintenanceMode": "देखभाल मोड",
            "apiRateLimits": "एपीआई मर्यादा",
            "backupSchedules": "स्वयंचलित बॅकअप वेळापत्रक",
            "smtpConfig": "ईमेल आणि एसएमएस गेटवे"
        }
    },
    "toast": {
        "issueSubmitted": "तक्रार यशस्वीरित्या नोंदवली गेली! संबंधित विभागाकडे पाठवली आहे.",
        "gpsCaptured": "जीपीएस निर्देशांक मिळवले गेले",
        "gpsCapturedDesc": "निर्देशांक तक्रार अहवालाशी जोडले गेले.",
        "locationDenied": "स्थान परवानगी नाकारली किंवा अनुपलब्ध. डीफॉल्ट पिन वापरला जात आहे.",
        "fileSizeExceeded": "फाइलचा आकार २५MB पेक्षा जास्त आहे.",
        "audioNotSupported": "या ब्राउझरमध्ये ऑडिओ रेकॉर्डिंग समर्थित नाही.",
        "micSimulation": "व्हॉइस तक्रार डेमोसाठी मायक्रोफोन सिम्युलेशन सक्रिय आहे.",
        "profileUpdated": "प्रोफाइल यशस्वीरित्या अद्ययावत केली.",
        "settingsSaved": "प्राधान्ये यशस्वीरित्या जतन केली.",
        "deleteRequested": "खाते हटवण्याची विनंती सादर केली गेली.",
        "languageChanged": "भाषा यशस्वीरित्या बदलली गेली.",
        "errorOccurred": "एक त्रुटी आली. कृपया पुन्हा प्रयत्न करा.",
        "caseUpdated": "केस डॉकेट यशस्वीरित्या अद्ययावत केले.",
        "caseReassigned": "प्रकरण नोडल अधिकाऱ्याकडे पुन्हा सोपवले.",
        "caseResolved": "तक्रार सोडवली गेली म्हणून नोंदवली.",
        "volunteerAdded": "नवीन स्वयंसेवक यशस्वीरित्या नोंदवला गेला.",
        "grantApproved": "सीएसआर अनुदान वाटप मंजूर झाले.",
        "milestoneApproved": "शैक्षणिक टप्पा मंजूर केला.",
        "deliverableUploaded": "सादरीकरण तपासणीसाठी अपलोड केले.",
        "loginSuccess": "यशस्वीरित्या साइन इन झाले. आपले स्वागत आहे!",
        "logoutSuccess": "यशस्वीरित्या लॉग आउट झाले.",
        "accessDenied": "प्रवेश प्रतिबंधित. अपुरे अधिकार.",
        "changesSaved": "सर्व बदल यशस्वीरित्या जतन केले.",
        "reportExported": "अहवाल तयार केला आणि डाउनलोड झाला.",
        "dataRefreshed": "टेलिमेट्री डेटा रिफ्रेश केला."
    },
    "language": "भाषा",
    "dashboard": "डॅशबोर्ड",
    "report_issue": "तक्रार नोंदवा",
    "report_problem": "तक्रार नोंदवा",
    "my_issues": "माझ्या तक्रारी",
    "track_issues": "निकालाचा मागोवा घ्या",
    "notifications": "सूचना",
    "profile": "प्रोफाइल",
    "settings": "सेटिंग्ज",
    "help": "मदत आणि सहाय्य",
    "logout": "लॉग आउट",
    "login": "लॉग इन",
    "recent_grievances": "अलीकडील तक्रारी",
    "issue_id": "तक्रार क्रमांक (ID)",
    "citizen_portal": "नागरिक पोर्टल",
    "government_portal": "सरकारी पोर्टल",
    "university_portal": "विद्यापीठ पोर्टल",
    "industry_portal": "उद्योग पोर्टल",
    "ngo_portal": "स्वयंसेवी संस्था पोर्टल",
    "admin_portal": "प्रशासक पोर्टल",
    "ai_governance_insight": "एआय प्रशासन अंतर्दृष्टी",
    "resolution": "निराकरण",
    "report": "अहवाल",
    "map": "घटना नकाशा",
    "search": "शोधा",
    "search_placeholder": "तक्रारी, प्रकरणे, स्थान शोधा...",
    "filter": "फिल्टर",
    "save": "बदल जतन करा",
    "cancel": "रद्द करा",
    "delete": "हटवा",
    "submit": "सबमिट करा",
    "upload": "अपलोड करा",
    "location": "स्थान",
    "description": "वर्णन",
    "title": "शीर्षक",
    "category": "वर्गवारी",
    "department": "विभाग",
    "created_at": "नोंदणी दिनांक",
    "action": "कृती",
    "actions": "कृती",
    "view": "पहा",
    "edit": "संपादित करा",
    "loading": "लोड होत आहे...",
    "success": "यशस्वी",
    "error": "एक त्रुटी आली",
    "welcome_back": "पुन्हा स्वागत आहे",
    "total_issues": "एकूण तक्रारी",
    "resolved_issues": "सोडवलेल्या तक्रारी",
    "in_progress_issues": "प्रगतीपथावरील तक्रारी",
    "pending_issues": "प्रलंबित तक्रारी",
    "active_projects": "सक्रिय प्रकल्प",
    "ai_accuracy": "एआय रूटिंग अचूकता",
    "sla_compliance": "SLA अनुपालन दर",
    "civic_engagement": "नागरी सहभाग निर्देशांक",
    "recent_activity": "अलीकडील हालचाली",
    "quick_actions": "त्वरित कृती",
    "live_incidents": "थेट नागरी घटना",
    "all": "सर्व",
    "high": "उच्च प्राधान्य",
    "medium": "मध्यम प्राधान्य",
    "low": "कमी प्राधान्य",
    "critical": "गंभीर प्राधान्य",
    "emergency": "तातडीचे प्राधान्य",
    "pending": "प्रलंबित",
    "in_progress": "प्रगतीपथावर",
    "resolved": "निराकरण झाले",
    "closed": "बंद केले",
    "rejected": "नाकारले",
    "approved": "मंजूर केले",
    "declined": "नाकारले",
    "export": "डेटा निर्यात करा",
    "download": "डाउनलोड",
    "confirm": "पुष्टी करा",
    "close": "बंद करा",
    "back": "मागे",
    "next": "पुढे",
    "previous": "मागील",
    "no_results": "कोणतेही परिणाम आढळले नाहीत",
    "view_all": "सर्व पहा",
    "home": "मुख्यपृष्ठ",
    "feed": "नागरी फीड",
    "analytics": "एआय विश्लेषण",
    "optional": "पर्यायी",
    "faculty": "प्राध्यापक मार्गदर्शक",
    "student": "विद्यार्थी गट",
    "projects": "प्रकल्प",
    "research": "संशोधन केंद्र",
    "innovation": "नवोन्मेष आव्हाने",
    "teams": "पथके",
    "credits": "शैक्षणिक क्रेडिट्स",
    "officers": "अधिकारी निर्देशिका",
    "assigned": "सोपवलेली प्रकरणे",
    "under_review": "पुनरावलोकन सुरू",
    "industry_assigned": "उद्योगाला सोपवले",
    "industry_review": "उद्योग पुनरावलोकन",
    "univ_assigned": "विद्यापीठाला सोपवले",
    "student_dev": "विद्यार्थी विकास कार्य",
    "faculty_review": "प्राध्यापक पुनरावलोकन",
    "industry_val": "उद्योग प्रमाणीकरण",
    "inspection": "स्थळ पाहणी",
    "feedback": "अभिप्राय प्रलंबित"
}

def get_keys(d, p=""):
    r = []
    for k, v in d.items():
        c = f"{p}.{k}" if p else k
        if isinstance(v, dict):
            r.extend(get_keys(v, c))
        else:
            r.append(c)
    return set(r)

base_keys = get_keys(base)
mr_keys = get_keys(MR_DICT)
diff = base_keys.symmetric_difference(mr_keys)

if diff:
    print(f"Key mismatch in MR! Diff count: {len(diff)}")
    print("Diff items:", diff)
    sys.exit(1)

print(f"MR 100% matched! Total keys: {len(mr_keys)}. Writing scripts/data_mr.py...")

out_path = os.path.join(os.path.dirname(os.path.abspath(__file__)), "data_mr.py")
with open(out_path, "w", encoding="utf-8") as f:
    f.write("# -*- coding: utf-8 -*-\n")
    f.write('"""Marathi (mr) translations dictionary for SOCIAL-X platform"""\n\n')
    f.write("def get_mr_dict():\n")
    f.write("    return " + json.dumps(MR_DICT, ensure_ascii=False, indent=4) + "\n")

print(f"Successfully generated {out_path}!")
